### ISSUE TITLE
victorialogs panic

### ISSUE THREAD

**Issue by kk-kwok** [VictoriaMetrics/VictoriaMetrics#6425] opened 2024-06-06 03:24 UTC
### Describe the bug

Panic occurs after running for a period of time.

### To Reproduce

Even if there is no access operation in the middle of the night, panic will occur.

### Version

victorialogs version from v0.11.0 to v0.17.0

### Logs

```
{"ts":"2024-06-05T20:40:17.034Z","level":"info","caller":"VictoriaMetrics/lib/logstorage/datadb.go:599","msg":"merged (12 parts, 40671346 rows, 15787 blocks, 2384297208 bytes) into (1 part, 40671346 rows, 14815 blocks, 2380922535 bytes) in 104.231 seconds at 390203 rows/sec to \"/storage/partitions/20240605/datadb/17D62E170E935969\""}
SIGSEGV: segmentation violation
PC=0x415ef7 m=33 sigcode=1 addr=0x20

goroutine 0 gp=0xc00e0748c0 m=33 mp=0xc001fe6808 [idle]:
runtime.(*mspan).typePointersOfUnchecked(0xc030dcc000?, 0x7f039f82f948?)
	runtime/mbitmap_allocheaders.go:202 +0x37 fp=0x7f039f82f8f8 sp=0x7f039f82f8d8 pc=0x415ef7
runtime.scanobject(0xc000052668?, 0xc000052668)
	runtime/mgcmark.go:1446 +0xb5 fp=0x7f039f82f988 sp=0x7f039f82f8f8 pc=0x421dd5
runtime.gcDrain(0xc000052668, 0x7)
	runtime/mgcmark.go:1242 +0x1f4 fp=0x7f039f82f9f0 sp=0x7f039f82f988 pc=0x421734
runtime.gcDrainMarkWorkerIdle(...)
	runtime/mgcmark.go:1114
runtime.gcBgMarkWorker.func2()
	runtime/mgc.go:1406 +0x6f fp=0x7f039f82fa40 sp=0x7f039f82f9f0 pc=0x41dd6f
runtime.systemstack(0x20000)
	runtime/asm_amd64.s:509 +0x4a fp=0x7f039f82fa50 sp=0x7f039f82fa40 pc=0x472aca

goroutine 36 gp=0xc00029c380 m=33 mp=0xc001fe6808 [GC worker (active)]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:474 +0x8 fp=0xc0002a2f50 sp=0xc0002a2f40 pc=0x472a68
runtime.gcBgMarkWorker()
	runtime/mgc.go:1370 +0x1f2 fp=0xc0002a2fe0 sp=0xc0002a2f50 pc=0x41da32
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc0002a2fe8 sp=0xc0002a2fe0 pc=0x474a81
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1234 +0x1c

goroutine 1 gp=0xc0000061c0 m=nil [chan receive, 156 minutes]:
runtime.gopark(0x84ebc5?, 0x94d160?, 0x1?, 0x3?, 0xc00052bdc0?)
	runtime/proc.go:402 +0xce fp=0xc000285d30 sp=0xc000285d10 pc=0x43d4ae
runtime.chanrecv(0xc000d10240, 0xc00052be08, 0x1)
	runtime/chan.go:583 +0x3bf fp=0xc000285da8 sp=0xc000285d30 pc=0x40759f
runtime.chanrecv1(0xc000d10240?, 0xc00052be18?)
	runtime/chan.go:442 +0x12 fp=0xc000285dd0 sp=0xc000285da8 pc=0x4071b2
github.com/VictoriaMetrics/VictoriaMetrics/lib/procutil.WaitForSigterm()
	github.com/VictoriaMetrics/VictoriaMetrics/lib/procutil/signal.go:23 +0xa5 fp=0xc000285e58 sp=0xc000285dd0 pc=0x84f4c5
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-logs/main.go:53 +0x317 fp=0xc000285f50 sp=0xc000285e58 pc=0x84fd17
runtime.main()
	runtime/proc.go:271 +0x29d fp=0xc000285fe0 sp=0xc000285f50 pc=0x43d05d
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000285fe8 sp=0xc000285fe0 pc=0x474a81

goroutine 2 gp=0xc000006c40 m=nil [force gc (idle), 156 minutes]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:402 +0xce fp=0xc000068fa8 sp=0xc000068f88 pc=0x43d4ae
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.forcegchelper()
	runtime/proc.go:326 +0xb3 fp=0xc000068fe0 sp=0xc000068fa8 pc=0x43d313
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x474a81
created by runtime.init.6 in goroutine 1
	runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000007180 m=nil [GC sweep wait]:
runtime.gopark(0x1083a01?, 0x1083a60?, 0xc?, 0x9?, 0x1?)
	runtime/proc.go:402 +0xce fp=0xc000069780 sp=0xc000069760 pc=0x43d4ae
runtime.goparkunlock(...)
	runtime/proc.go:408
runtime.bgsweep(0xc000092000)
	runtime/mgcsweep.go:318 +0xdf fp=0xc0000697c8 sp=0xc000069780 pc=0x426fdf
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x25 fp=0xc0000697e0 sp=0xc0000697c8 pc=0x41b845
```

**Comment by valyala** [comment] 2024-06-08 13:49
@kk-kwok , thanks for filing the bug report! It looks similar to https://github.com/golang/go/issues/66383 and https://github.com/golang/go/issues/67255 .

@kk-kwok , if you run VictoriaLogs on arm64, then it would be great if you could help Go core team narrowing down the issue at https://github.com/golang/go/issues/66383

**Comment by valyala** [comment] 2024-06-08 13:53
Also, try using [VictoriaLogs v0.18.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.18.0-victorialogs). It is built with Go1.22.4, which may contain the fix for this issue. See [the list of fixes in Go1.22.4](https://github.com/golang/go/issues?q=milestone%3AGo1.22.4+label%3ACherryPickApproved)

**Comment by kk-kwok** [comment] 2024-06-08 14:08
> Also, try using [VictoriaLogs v0.18.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.18.0-victorialogs). It is built with Go1.22.4, which may contain the fix for this issue. See [the list of fixes in Go1.22.4](https://github.com/golang/go/issues?q=milestone%3AGo1.22.4+label%3ACherryPickApproved)


Yesterday, it was updated to v0.18.0, and panic often occurred.

**Comment by kk-kwok** [comment] 2024-06-08 14:09
> @kk-kwok , thanks for filing the bug report! It looks similar to [golang/go#66383](https://github.com/golang/go/issues/66383) and [golang/go#67255](https://github.com/golang/go/issues/67255) .
> 
> @kk-kwok , if you run VictoriaLogs on arm64, then it would be great if you could help Go core team narrowing down the issue at [golang/go#66383](https://github.com/golang/go/issues/66383)

Sorry, I don't have an arm64 environment

**Comment by valyala** [comment] 2024-06-09 17:01
> Yesterday, it was updated to v0.18.0, and panic often occurred.

Does the stack trace for the panic look the same every time? Does it contain `SIGSEGV: segmentation violation` and `runtime.(*mspan).typePointersOfUnchecked` every time?

If not, then it would be great to see other examples of the panic.

Also, could you build VictoriaLogs from the [v0.18.0-victorialogs release tag](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/v0.18.0-victorialogs) with the `make victoria-logs-race` command? This command builds VictoriaLogs executable with the built-in [data race detector](https://go.dev/doc/articles/race_detector) and put the built binary in `bin` directory. The binary name should be `bin/victoria-logs-race`. Then run this binary and see whether it logs additional errors (data race errors) before and during the panic.

**Comment by kk-kwok** [comment] 2024-06-10 03:59
> > Yesterday, it was updated to v0.18.0, and panic often occurred.
> 
> Does the stack trace for the panic look the same every time? Does it contain `SIGSEGV: segmentation violation` and `runtime.(*mspan).typePointersOfUnchecked` every time?
> 
> If not, then it would be great to see other examples of the panic.
> 
> Also, could you build VictoriaLogs from the [v0.18.0-victorialogs release tag](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/v0.18.0-victorialogs) with the `make victoria-logs-race` command? This command builds VictoriaLogs executable with the built-in [data race detector](https://go.dev/doc/articles/race_detector) and put the built binary in `bin` directory. The binary name should be `bin/victoria-logs-race`. Then run this binary and see whether it logs additional errors (data race errors) before and during the panic.


Yes, the stack trace of Panic is the same every time.

**Comment by kk-kwok** [comment] 2024-06-10 04:16
> make victoria-logs-race

standard_init_linux.go:219: exec user process caused: no such file or directory

**Comment by valyala** [comment] 2024-06-10 17:10
@kk-kwok , I prepared Go1.21.11 builds of VictoriaLogs from the branch [victorialogs-go1.21-issue-6425](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425). There is a Docker image `docker.io/victoriametrics/victoria-logs:heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615` at DockerHub and the amd64-linux binary attached [here](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz). Could you try these builds and verify whether they are free from the panic? If yes, then the issue is definitely in Go1.22, and in this case we need to help Go core developers narrowing down the issue at https://github.com/golang/go/issues/66383 , so they could fix it quickly.

[victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz)

**Comment by valyala** [comment] 2024-06-14 02:25
@kk-kwok , are there any updates regarding the build with Go1.21? Feel free asking additional assistance if it is needed from our side.

**Comment by kk-kwok** [comment] 2024-06-15 08:22
> @kk-kwok , are there any updates regarding the build with Go1.21? Feel free asking additional assistance if it is needed from our side.

I'm sorry that I only saw this reply now. I'm now trying to use the image produced by go1.21.11.
Thank you

**Comment by kk-kwok** [comment] 2024-06-15 08:27
@valyala Another question, a colleague reported that the json size of several log records exceeds 25KB, but it is not found in victorylogs. What is the limit on the size of a single log?

**Comment by kk-kwok** [comment] 2024-06-15 08:31
> @kk-kwok , I prepared [Go1.21.11](https://go.dev/doc/devel/release#go1.21.0) builds of VictoriaLogs from the branch [victorialogs-go1.21-issue-6425](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425). There is a Docker image `docker.io/victoriametrics/victoria-logs:heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615` at DockerHub and the amd64-linux binary attached [here](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz). Could you try these builds and verify whether they are free from the panic? If yes, then the issue is definitely in Go1.22, and in this case we need to help Go core developers narrowing down the issue at [golang/go#66383](https://github.com/golang/go/issues/66383) , so they could fix it quickly.
> 
> [victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz)

Now that the new image compiled with go1.21.11 is used to run, I will observe whether panic occurs in the next day. Previous versions including v0.19.0 will panic after running for a few hours.

**Comment by kk-kwok** [comment] 2024-06-16 09:55
> > @kk-kwok , I prepared [Go1.21.11](https://go.dev/doc/devel/release#go1.21.0) builds of VictoriaLogs from the branch [victorialogs-go1.21-issue-6425](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425). There is a Docker image `docker.io/victoriametrics/victoria-logs:heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615` at DockerHub and the amd64-linux binary attached [here](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz). Could you try these builds and verify whether they are free from the panic? If yes, then the issue is definitely in Go1.22, and in this case we need to help Go core developers narrowing down the issue at [golang/go#66383](https://github.com/golang/go/issues/66383) , so they could fix it quickly.
> > [victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz)
> 
> Now that the new image compiled with go1.21.11 is used to run, I will observe whether panic occurs in the next day. Previous versions including v0.19.0 will panic after running for a few hours.

@valyala LGTM!
I have been running the image compiled by go1.21.11 for 25 hours now, and it has been running normally without panic.

**Comment by kk-kwok** [comment] 2024-06-20 06:48
> > > @kk-kwok , I prepared [Go1.21.11](https://go.dev/doc/devel/release#go1.21.0) builds of VictoriaLogs from the branch [victorialogs-go1.21-issue-6425](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425). There is a Docker image `docker.io/victoriametrics/victoria-logs:heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615` at DockerHub and the amd64-linux binary attached [here](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz). Could you try these builds and verify whether they are free from the panic? If yes, then the issue is definitely in Go1.22, and in this case we need to help Go core developers narrowing down the issue at [golang/go#66383](https://github.com/golang/go/issues/66383) , so they could fix it quickly.
> > > [victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz](https://github.com/user-attachments/files/15776746/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gbeee1cc615.tar.gz)
> > 
> > 
> > Now that the new image compiled with go1.21.11 is used to run, I will observe whether panic occurs in the next day. Previous versions including v0.19.0 will panic after running for a few hours.
> 
> @valyala LGTM! I have been running the image compiled by go1.21.11 for 25 hours now, and it has been running normally without panic.

@valyala   It has been running normally for 5 days  without panic.

**Comment by valyala** [comment] 2024-06-20 08:47
@kk-kwok , thanks for the feedback! Then it is definitely the issue in Go1.22 , which isn't limited to arm64 platform, but also is reproducible at amd64 platform. Now we need to help Go core developers narrowing down and fixing this issue. As a temporary workaround VictoriaLogsust be built with Go1.21 until the issue in Go1.22 is fixed.

**Comment by valyala** [comment] 2024-06-21 11:09
> Another question, a colleague reported that the json size of several log records exceeds 25KB, but it is not found in victorylogs. What is the limit on the size of a single log?

The maximum size of a single log line is 256KB. It can be adjusted via `-insert.maxLineSizeBytes` command-line flag. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/b201d1722d468a35edf91b98597e9c54bbee0af0/app/vlinsert/insertutils/flags.go#L11

**Comment by valyala** [comment] 2024-06-24 22:42
@kk-kwok , could you try running VictoriaLogs Docker image `heads-victorialogs-go1.21-issue-6425-0-gaadb73740f`? This image is built with [go1.23rc1](https://go.dev/dl/#go1.23rc1) according to the suggestion from @mknyszek at https://github.com/golang/go/issues/66383#issuecomment-2121729492 . This will help determining whether the issue is fixed in the upcoming Go1.23 release.

If you prefer running executable instead of Docker image, then please download and run the following executable - 
[victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gaadb73740f.tar.gz](https://github.com/user-attachments/files/15961982/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gaadb73740f.tar.gz).

Note that the name of the docker image and the executable contains go1.21, while in reality they are built with Go1.23rc1 - the `go1.21` is inherited from the branch name - https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425 , which was used for building these binaries. You can build VictoriaLogs binaries from this branch on yourself according to [these docs](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code).

If the panic is still present in these binaries built with Go1.23rc1, then could you run them with `GODEBUG=asyncpreemptoff=1` environment variable as suggested at https://github.com/golang/go/issues/66383#issuecomment-2121729492 and verify whether this helps avoiding the panic?

**Comment by kk-kwok** [comment] 2024-06-25 07:22
> > Another question, a colleague reported that the json size of several log records exceeds 25KB, but it is not found in victorylogs. What is the limit on the size of a single log?
> 
> The maximum size of a single log line is 256KB. It can be adjusted via `-insert.maxLineSizeBytes` command-line flag. See
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/b201d1722d468a35edf91b98597e9c54bbee0af0/app/vlinsert/insertutils/flags.go#L11
> 
> It isn't recommended increasing the `-insert.maxLineSizeBytes` too much, since VictoriaLogs isn't optimized for too long log lines.

Ok, thanks.

**Comment by kk-kwok** [comment] 2024-06-25 07:27
> @kk-kwok , could you try running VictoriaLogs Docker image `heads-victorialogs-go1.21-issue-6425-0-gaadb73740f`? This image is built with [go1.23rc1](https://go.dev/dl/#go1.23rc1) according to the suggestion from @mknyszek at [golang/go#66383 (comment)](https://github.com/golang/go/issues/66383#issuecomment-2121729492) . This will help determining whether the issue is fixed in the upcoming Go1.23 release.
> 
> If you prefer running executable instead of Docker image, then please download and run the following executable - [victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gaadb73740f.tar.gz](https://github.com/user-attachments/files/15961982/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gaadb73740f.tar.gz).
> 
> Note that the name of the docker image and the executable contains go1.21, while in reality they are built with Go1.23rc1 - the `go1.21` is inherited from the branch name - https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425 , which was used for building these binaries. You can build VictoriaLogs binaries from this branch on yourself according to [these docs](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code).
> 
> If the panic is still present in these binaries built with Go1.23rc1, then could you run them with `GODEBUG=asyncpreemptoff=1` environment variable as suggested at [golang/go#66383 (comment)](https://github.com/golang/go/issues/66383#issuecomment-2121729492) and verify whether this helps avoiding the panic?

Ok, I will try it.

**Comment by kk-kwok** [comment] 2024-06-26 02:24
> @kk-kwok , could you try running VictoriaLogs Docker image `heads-victorialogs-go1.21-issue-6425-0-gaadb73740f`? This image is built with [go1.23rc1](https://go.dev/dl/#go1.23rc1) according to the suggestion from @mknyszek at [golang/go#66383 (comment)](https://github.com/golang/go/issues/66383#issuecomment-2121729492) . This will help determining whether the issue is fixed in the upcoming Go1.23 release.
> 
> If you prefer running executable instead of Docker image, then please download and run the following executable - [victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gaadb73740f.tar.gz](https://github.com/user-attachments/files/15961982/victoria-logs-linux-amd64-heads-victorialogs-go1.21-issue-6425-0-gaadb73740f.tar.gz).
> 
> Note that the name of the docker image and the executable contains go1.21, while in reality they are built with Go1.23rc1 - the `go1.21` is inherited from the branch name - https://github.com/VictoriaMetrics/VictoriaMetrics/tree/victorialogs-go1.21-issue-6425 , which was used for building these binaries. You can build VictoriaLogs binaries from this branch on yourself according to [these docs](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code).
> 
> If the panic is still present in these binaries built with Go1.23rc1, then could you run them with `GODEBUG=asyncpreemptoff=1` environment variable as suggested at [golang/go#66383 (comment)](https://github.com/golang/go/issues/66383#issuecomment-2121729492) and verify whether this helps avoiding the panic?

@valyala It has been running normally for 20 hours without panic.

**Comment by valyala** [comment] 2024-06-26 17:15
@kk-kwok , thanks! This means that the issue has been fixed in Go1.23rc1!

**Comment by svanharmelen** [comment] 2024-07-01 09:01
Just a small FYI, we see the same error in the [operator](https://github.com/VictoriaMetrics/operator) using the official docker container version v.0.45.0. Is it save to assume this is related and will be fixed once a new release is build and pushed?

**Comment by valyala** [comment] 2024-07-10 01:38
> Just a small FYI, we see the same error in the [operator](https://github.com/VictoriaMetrics/operator) using the "official" docker container version v.0.45.0.

@f41gh7 , @Haleygo , could you look into this and verify whether using Go1.23rc1 helps resolving this issue in [VictoriaMetrics operator](https://github.com/VictoriaMetrics/operator)?

> Is it safe to assume this is related and will be fixed once a new release is build and pushed?

If the assumption about the bug in Go1.22 will be confirmed for VictoriaMetrics operator, then the next release will be built either with Go1.21 or with Go1.23 (it is going to be released soon).

**Comment by Haleygo** [comment] 2024-07-11 10:50
Hi @svanharmelen ,
>Just a small FYI, we see the same error in the [operator](https://github.com/VictoriaMetrics/operator) using the "official" docker container version v.0.45.0

Acctually, operator [v0.45.0](https://github.com/VictoriaMetrics/operator/actions/runs/9448297058/job/26021993426) is built on Go1.21 and we upgraded to Go1.22 when built v0.46.x.
Does this error also occur for operator [v0.46.4](https://github.com/VictoriaMetrics/operator/releases/tag/v0.46.4)?

**Comment by svanharmelen** [comment] 2024-07-11 12:49
Thanks for the info @Haleygo! I just tried and can no longer reproduce the problem. We changed more things so not entirely sure what caused it or what solved it, but the operator runs fine again now. Thanks 👍🏻

**Comment by valyala** [comment] 2024-07-25 22:31
@kk-kwok , could you verify whether the panic is still present in [VictoriaLogs v0.28.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.28.0-victorialogs)?

**Comment by kk-kwok** [comment] 2024-07-26 03:09
> @kk-kwok , could you verify whether the panic is still present in [VictoriaLogs v0.28.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.28.0-victorialogs)?

No, because I saw that v0.28.0 is still compiled with golang 1.22

**Comment by kk-kwok** [comment] 2024-08-14 03:50
@valyala Hello, Golang v1.23.0 has been released. Please use Golang v1.23.0 to compile a new version of VictoriaLogs v0.28.1. I will try to see if the panic issue still occurs.

**Comment by hagen1778** [comment] 2024-09-02 08:03
@kk-kwok kindly pinging for update

**Comment by valyala** [comment] 2024-09-08 10:31
Closing the issue because of inactivity.

@kk-kwok , feel free re-opening it if the panic still exists in [the latest VictoriaLogs release](https://docs.victoriametrics.com/victorialogs/changelog/)

**Closed by valyala** 2024-09-08 10:31 UTC
Labels: bug, need more info, victorialogs

**Comment by valyala** [comment] 2024-09-08 20:26
@kk-kwok , could you check whether the panic exists in [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/)? This release has been built with [Go1.23.1](https://go.dev/doc/devel/release#go1.23.minor), so, hopefully, the panic shouldn't be reproduced there.

**Comment by kk-kwok** [comment] 2024-09-09 08:13
> @kk-kwok , could you check whether the panic exists in [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/)? This release has been built with [Go1.23.1](https://go.dev/doc/devel/release#go1.23.minor), so, hopefully, the panic shouldn't be reproduced there.

I just updated to the latest version 0.29.0 two hours ago. Everything is working fine now. Thank you very much!

**Comment by kk-kwok** [comment] 2024-09-09 08:21
> Hey @kk-kwok! Could you try the following image https://hub.docker.com/layers/victoriametrics/victoria-logs/heads-vlogs-go-1.23-0-g566c437b0e/images/sha256-42c22e99fa42a1a5459a84ff2e7f14987770447e2a383aee85a8fc1057d4f1db?context=explore ? It is built with Go v1.23.0.

I'm very sorry for the late reply, because we modified [maxColumnsPerBlock](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/logstorage/consts.go#L17) to 100000 and then recompiled the image, so we waited until the new version v0.29.0 came out before updating the production environment version. Now everything is normal.

**Comment by valyala** [comment] 2024-09-24 16:55
@kk-kwok, thanks for the update!

BTW, increasing [maxColumnsPerBlock](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f86e093b20d416b1fd9e5834bde4d250cc51aca6/lib/logstorage/consts.go#L17) to too big values isn't recommended, since this may lead to too big memory usage during data ingestion. This also may result in significant query execution slowdown. See cf2e7d0d92f43ef42ccfbadfeb05ab5fcd0efa45 .

Why do you need increasing this constant from the the default 1_000 value to 100_000?

**Comment by kk-kwok** [comment] 2024-09-28 02:32
> @kk-kwok, thanks for the update!
> 
> BTW, increasing [maxColumnsPerBlock](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f86e093b20d416b1fd9e5834bde4d250cc51aca6/lib/logstorage/consts.go#L17) to too big values isn't recommended, since this may lead to too big memory usage during data ingestion. This also may result in significant query execution slowdown. See [cf2e7d0](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/cf2e7d0d92f43ef42ccfbadfeb05ab5fcd0efa45) .
> 
> Why do you need increasing this constant from the the default 1_000 value to 100_000?

Because using the default parameters will panic shortly after starting the program, I tried changing the value to 100000 according to the error message and it disappeared.

**Comment by kk-kwok** [comment] 2024-10-17 02:01
> @kk-kwok, thanks for the update!
> 
> BTW, increasing [maxColumnsPerBlock](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f86e093b20d416b1fd9e5834bde4d250cc51aca6/lib/logstorage/consts.go#L17) to too big values isn't recommended, since this may lead to too big memory usage during data ingestion. This also may result in significant query execution slowdown. See [cf2e7d0](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/cf2e7d0d92f43ef42ccfbadfeb05ab5fcd0efa45) .
> 
> Why do you need increasing this constant from the the default 1_000 value to 100_000?

When I start it directly using the official Docker image, the Pod will panic shortly after. The log is as follows：
```json
{"ts":"2024-10-16T17:58:14.078-0800","level":"panic","caller":"VictoriaMetrics/lib/logstorage/block_data.go:154","msg":"FATAL: /storage/partitions/20241017/datadb/17FF1463B37459F8/columns_header.bin: cannot unmarshal columnsHeader: too many column headers: 1392; mustn't exceed 1000"}
```

**Comment by valyala** [comment] 2024-11-01 16:16
@kk-kwok , it looks like the `too many column headers` panic could be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4762 . This panic should be fixed starting from `v0.4.0-victorialogs` release, but it may remain when querying logs ingested before this release. This panic may remain also if logs were ingested into VictoriaLogs built with manually increased `maxColumnsPerBlock` const value. This constant has been increased from 1000 to 2000 in the commit 9ba6be417997265bcd0f4ad5699a8b127eb60fd7 , so, if your logs contain less than 2000 fields, then you'll be able running the next VictoriaLogs release (`v0.41.0-victorialogs`) without the need to increase `maxColumnsPerBlock` constant.

Note also that the limit on the number of fields per block can be exceeded even if you do not have logs with more than `maxColumnsPerBlock` fields. This is possible if you ingest logs with distinct sets of fields into the same [log stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields). VictoriaLogs packs logs for the same log stream into a single block with columns, which cover all the unique field names across all the logs in the block. Suppose you store logs from two distinct sources into the same log stream:

- source1 generates logs with 500 fields.
- source2 generates logs with another set of 700 fields, which doesn't intersect with the fields from the source1.

Then VictoriaLogs puts theses logs into the same block, which should contain 500+700=1200 unique field names. This exceeds the limit on the number of fields per block.

The solution for this issue is to put logs from distinct sources into distinct log streams. Canonical definition of log stream is logs generated by a **single instance** of some application, so the best case is to put logs from every application instance into a separate log stream. This is usually achieved by putting `instance`, `host` or `address` field into log stream, so it uniquely identifies a **single instance** of some application. See more details [here](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields).

**Comment by kk-kwok** [comment] 2024-11-04 03:04
> @kk-kwok , it looks like the `too many column headers` panic could be related to #4762 . This panic should be fixed starting from `v0.4.0-victorialogs` release, but it may remain when querying logs ingested before this release. This panic may remain also if logs were ingested into VictoriaLogs built with manually increased `maxColumnsPerBlock` const value. This constant has been increased from 1000 to 2000 in the commit [9ba6be4](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/9ba6be417997265bcd0f4ad5699a8b127eb60fd7) , so, if your logs contain less than 2000 fields, then you'll be able running the next VictoriaLogs release (`v0.41.0-victorialogs`) without the need to increase `maxColumnsPerBlock` constant.
> 
> Note also that the limit on the number of fields per block can be exceeded even if you do not have logs with more than `maxColumnsPerBlock` fields. This is possible if you ingest logs with distinct sets of fields into the same [log stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields). VictoriaLogs packs logs for the same log stream into a single block with columns, which cover all the unique field names across all the logs in the block. Suppose you store logs from two distinct sources into the same log stream:
> 
> * source1 generates logs with 500 fields.
> * source2 generates logs with another set of 700 fields, which doesn't intersect with the fields from the source1.
> 
> Then VictoriaLogs puts theses logs into the same block, which should contain 500+700=1200 unique field names (aka columns). This exceeds the limit on the number of columns per block.
> 
> The solution for this issue is to put logs from distinct sources into distinct log streams. Canonical definition of log stream is logs generated by a **single instance** of some application, so the best case is to put logs from every application instance into a separate log stream. This is usually achieved by putting `instance`, `host` or `address` field into log stream, so it uniquely identifies a **single instance** of some application. See more details [here](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields).

@valyala 
First of all, thank you very much for your detailed explanation and help.
Our log streams are allocated according to the namespace and service in k8s, which means that the logs in the same log stream are logs output by the same k8s application service. In addition to application logs, there may also be logs from some third-party components.
Secondly, we initially installed VictoriaLogs starting from version v0.4.2, and did not use version v0.4.0.
Finally, we will test with the latest version first. If we encounter panic again, we will increase the maxColumnsPerBlock value and recompile.
Thank you very much.

**Comment by kk-kwok** [comment] 2024-11-04 03:45
```json
{"ts":"2024-11-03T19:22:26.612-0800","level":"panic","caller":"VictoriaMetrics/lib/logstorage/block_data.go:150","msg":"FATAL: /storage/partitions/20241104/datadb/18049AD5E15A35AA/columns_header.bin: cannot unmarshal columnsHeader: too many column headers: 2089; mustn't exceed 2000"}
```
Are there any related metrics to query column headers?

**Comment by valyala** [comment] 2025-01-15 22:34
> Are there any related metrics to query column headers?

You can query the information about columns with the following [pipes](https://docs.victoriametrics.com/victorialogs/logsql/#pipes):

- [`field_names`](https://docs.victoriametrics.com/victorialogs/logsql/#field_names-pipe)
- [`block_stats`](https://docs.victoriametrics.com/victorialogs/logsql/#block_stats-pipe).

For example, the following query returns field names across all the logs for the last 5 minutes:

```logsql
_time:5m | field_names
```

The following query returns the number of unique fields during the last 5 minutes:

```logsql
_time:5m | field_names | count()
```
