### ISSUE TITLE
Victoriametrics: the last error: cannot read stream body in 0 seconds: context deadline exceeded

### ISSUE THREAD

**Issue by MongoOverflow** [VictoriaMetrics/VictoriaMetrics#6630] opened 2024-07-11 05:20 UTC
### Describe the bug

Greetings. Haven't found it in changelog, so it might be a new one, although #5292  seem to be slightly related. 
During scraping of 'heavy' series, VM might apparently throw 'context deadline exceeded' while scraping the target on the same machine. It means, that network bottlenecks are not the issue here, while perhaps hdd is the one to blame. 

My concern is what can I possibly fine-tune in terms of timeouts until I substituted the hdd with the faster one? It would be also great to see some tips by what range of vars might be checked to fix problem before filing it here (just an odd suggestion)

### To Reproduce

Add a target on the same machine with Victoriametrics, populate around 29K series at once and see the logs.

### Version

`victoria-metrics-20231002-214434-tags-v1.94.0-0-gf13a96f42`

### Logs

`Jul 11 04:39:06 inst-2 victoria-metrics[1376015]: 2024-07-11T04:39:06.328Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 51 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:13:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:13:36.246Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 2 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:12:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:12:36.358Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 2 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:11:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:11:36.402Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 2 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:10:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:10:36.327Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 2 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:09:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:09:36.328Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 2 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:08:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:08:36.384Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 2 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:07:36 inst-2 victoria-metrics[1376015]: 2024-07-11T04:07:36.336Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 3 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 04:06:06 inst-2 victoria-metrics[1376015]: 2024-07-11T04:06:06.305Z        warn        VictoriaMetrics/lib/promscrape/scrapework.go:387        cannot scrape target "http://127.0.0.1:7555/metrics" ({capacity_group="cp",instance="127.0.0.1:7555",job="active_cams_exporter"}) 1 out of 40 times during -promscrape.suppressScrapeErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: context deadline exceeded
Jul 11 03:52:54 inst-2 victoria-metrics[1376015]: 2024-07-11T03:52:54.447Z        info        VictoriaMetrics/lib/storage/partition.go:1326        merged (15 parts, 604845637 rows, 61334438 blocks, 817459927 bytes) into (1 part, 604845637 rows, 8909488 blocks, 150899895 bytes) in 30.479 seconds at 19844440 rows/sec to "/opt/victoria-metrics/victoriametrics-data/data/small/2024_07/17DE230F34152586"`

### Used command-line flags

```
PROMETHEUS_SCRAPE_CONFIG_STRICT_PARSE="false"
PROMETHEUS_SCRAPE_MAX_SCRAPE_SIZE="2GB"
VICTORIAMETRICS_SEARCH_MAX_SERIES="30000000"
```

### Additional information

VM settings:
`global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s
`

**Comment by jiekun** [comment] 2024-07-11 06:11
Hi thanks you for dropping question here.

I assume you are talking about the scrape timeout of **vmagent**. It's necessary to locate the root cause before seeking for solution.

> populate around 29K series at once and see the logs.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/36814af5-6b2f-47b8-8277-347688df0f3f)

I simulate your scrape target with 400k+ series (20 MiB+ per response) on my local PC, it takes less than 2 seconds to scrape it. Since you are using `scrape_timeout: 10s`, it should be fine.

I suggest you to **query the scrape target manually (`curl`/`wget`/...)**, And **see how long does it take**. If it takes longer than 10s to response, you may need to figure it out **on your scrape target side**.

And if your scrape target can response quickly, it's time to check the `vmagent`. I recommand setting up a [grafana dashboard](https://grafana.com/grafana/dashboards/12683-victoriametrics-vmagent/) for it. Please consider sharing panel like this so that I could have more info of your use case.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/c0cb0e07-0382-46f0-90de-c6e4ced3c5cb)

**Comment by MongoOverflow** [comment] 2024-07-12 13:46
@jiekun thanks for rapid response. I was able to measure it scrape time and it may fall down from 6 while also skyrocketing up to 12 seconds, which is what I was afraid of. Even though I was able to temporary fix that by increasing scrape timeout, guess you were able to achieve the same under 2 seconds due to different disks and overall iops saturation. Anyway, I'll be looking forward to replace the disk and give it a shot again. Cheers

**Comment by jiekun** [comment] 2024-07-12 13:55
Hi @MongoOverflow,

I appreciate your response and test. However, it's worth to mention that the scrape time (displayed on the web UI of victoriametrics/vmagent) should not related to disk speed and IO. It mainly depends on the network, and the data will be temporarily stored in memory before being presistent to the disk.

So, if you observe a high scrape time, I still recommend investigating both side, start by examining the target side manually and then move on to the vm side.

I would like to close this issue as completed for now, but if you have any new info, feel free to reopen it, and we can continue the discussion.

**Closed by jiekun** 2024-07-12 13:55 UTC
Labels: question, vmagent
