### ISSUE TITLE
vmauth: `src_paths` without `/` results to the "missing route" error

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/VictoriaMetrics#4868] opened 2023-08-22 14:07 UTC
### Describe the bug

When accessing a URI **without** `/` at the end in the VMAuth's `src_paths` config, during redirects the `/` is added, resulting to the "**requestURI: /alertmanager/; missing route for "/alertmanager/"**" error.

### To Reproduce

Deploy victoria-metrics-auth Helm-chart v ~0.3.3.

Add a user with a `src_paths`:
```
    users:
    - username: vmadmin
      password: {{ .Values.vmauth_password }}
      url_map:
      - src_paths:
        - /alertmanager
        url_prefix: http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093
```
Configure Alertmanager with the `routePrefix: /alertmanager`.

Open https://vmauth.dev.example.co/alertmanager:

```
$ curl -vL --user vmadmin:PASS https://vmauth.dev.example.co/alertmanager
...
> GET /alertmanager HTTP/2
> Host: vmauth.dev.example.co
> Authorization: Basic dm1hZG1pbjpBd29oeDZvb21lcm8=
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/2 301 
< date: Tue, 22 Aug 2023 13:56:53 GMT
< content-type: text/html; charset=utf-8
< content-length: 49
< location: /alertmanager/
< vary: Accept-Encoding
< x-server-hostname: atlas-victoriametrics-victoria-metrics-auth-69dc9b4995-bdwdp
< 
* Ignoring the response-body
* Connection #0 to host vmauth.dev.example.co left intact
* Issue another request to this URL: 'https://vmadmin:PASS@vmauth.dev.example.co/alertmanager/'
...
remoteAddr: "10.0.0.74:20292, X-Forwarded-For: 217.***.***.253"; requestURI: /alertmanager/; missing route for "/alertmanager/"
```

In the 301 redirect, the ` location: /alertmanager/` now with the `/` added.

The workaround is to use regex `.*` in the user's config:

```
    users:
    - username: vmadmin
      password: {{ .Values.vmauth_password }}
      url_map:
      - src_paths:
        - /alertmanager.*
        url_prefix: http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093
```

But the [docs](https://docs.victoriametrics.com/vmauth.html#auth-config) say it must be without any regexes, and without slash.

### Version

```
image: victoriametrics/vmauth:v1.93.0
```

### Logs

```
{"ts":"2023-08-22T13:56:50.043Z","level":"info","caller":"VictoriaMetrics/app/vmauth/auth_config.go:329","msg":"SIGHUP received; loading -auth.config=\"/config/auth.yml\""}
{"ts":"2023-08-22T13:56:50.044Z","level":"info","caller":"VictoriaMetrics/app/vmauth/auth_config.go:354","msg":"loaded information about 1 users from -auth.config=\"/config/auth.yml\""}
{"ts":"2023-08-22T13:56:53.866Z","level":"warn","caller":"VictoriaMetrics/app/vmauth/main.go:159","msg":"remoteAddr: \"10.0.0.74:20292, X-Forwarded-For: 217.***.******.253\"; requestURI: /alertmanager/; missing route for \"/alertmanager/\""}
```

### Additional information

It also works, if set `/alertmanager/"` in both Alertmanager, and VMAuth user's config, and the request is `https://vmauth.dev.example.co/alertmanager/`, but obviously breaks if the request is `https://vmauth.dev.example.co/alertmanager` 

_No response_

**Comment by hagen1778** [comment] 2023-08-24 11:43
> But the [docs](https://docs.victoriametrics.com/vmauth.html#auth-config) say it must be without any regexes, and without slash.

The doc is right. The reason why you observe this behavior is that vmauth doesn't follow redirects. From the provided log:
```
< HTTP/2 301 
< date: Tue, 22 Aug 2023 13:56:53 GMT
< content-type: text/html; charset=utf-8
< content-length: 49
< location: /alertmanager/
< vary: Accept-Encoding
< x-server-hostname: atlas-victoriametrics-victoria-metrics-auth-69dc9b4995-bdwdp
```
this part is generated by `url_prefix: http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093`. The sequence of actions is the following:
1. curl inits the first request to /alertmanager
2. the request hits vmauth and matches the route
3. vmauth performs an HTTP request to http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093 but gets 301 in response
4. vmauth copies the response back to the caller, curl
5. curl observes 301 and follows the suggested redirect to `location: /alertmanager/`. Please note, the redirect path is set by http://vmalertmanager-vm-k8s-stack.dev-monitoring-ns.svc:9093
6. curl sends new HTTP request with /alertmanager/ path to vmauth - it doesn't match the route.
7. vmauth responds with error

If we set src_path to `/alertmanager.*` then both requests will match vmauth path: before and after redirect.
This is not a bug, vmauth did nothing wrong here and behaved like a default HTTP reverse proxy.

It could have done better though, if it would support following redirects feature. This is why I'm changing the label from Bug to Enhancement.

**Comment by hagen1778** [comment] 2023-08-25 08:26
@arseny-zinchenko I mentioned that vmauth doesn't follow redirects here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/4d316a23aec64055d577478ef57b46ed9e7f312c

It is unlikely we'll add option to follow redirects to vmauth. I am closing this issue as done.

**Closed by hagen1778** 2023-08-25 08:26 UTC
Labels: question, vmauth
