### ISSUE TITLE
vmagent lost some metrics during shutdown/recovery

### ISSUE THREAD

**Issue by berghauz** [VictoriaMetrics/VictoriaMetrics#1065] opened 2021-02-10 10:20 UTC
**Describe the bug**
Looks like vmagent drops some (not all pended) metrics in case of graceful shutdown and vminsert unavialability.

**To Reproduce**
1. Stop vminsert/vmstorage or victoriametrics all-in-one app. 
2. Push a few batch of metrics in vmagent, in my case it was 10 batches, 17k metrics each. One minute step between.
3. Stop vmagent to flush pending metrics to persistent storage.
4. Run vminsert/vmstorage or victoriametrics all-in-one app.
5. Run vmagent.

**Expected behavior**
All metrics from 10 batches should be readed from persisted storage and pushed by vmagent to storage backend and after vmselect cache drops it should be appared in grafana graphs but instead only first batch and 4 to 5 last batches appeared with gap in between. After some runs of this scenario looks like this batches wasn't offloaded in persistent storage, but it's just my assumption.

**Version**
All the same behaviour with
vmagent-20210203-211447-tags-v1.53.1-0-g19986da16
vmagent-20210113-110050-tags-v1.52.0-0-g7ce87ebcb

**Used command-line flags**
all defaults, except
`-remoteWrite.tmpDataPath=/var/data/vmagent-remotewrite-data -httpListenAddr=:8429 -remoteWrite.url=http://10.7.8.138:8480/insert/0/prometheus/api/v1/write"`
`

**Additional context**
No errors in vmagent logs was discovered but 503 errors towards vminsert, that's was expected.
Also, this behaviour only appear if vmagent was restarted (with sigterm), in case vmisert is appeared online without vmagent restart all batches reached db backend successfully without any gaps or losts.

**Comment by valyala** [comment] 2021-02-17 00:56
@f41gh7 , could you look into this issue?

**Comment by f41gh7** [comment] 2021-02-17 05:59
Confirmed, vmagent drops first data blocks from fast queue according to number of remote write queues.

**Comment by valyala** [comment] 2021-02-17 19:54
@berghauz , could you build `vmagent` from the commit edcdc39eb3813a274e0ae65dda717d6e0c1f4c1f and verify whether the issue is fixed there? See [build instructions for vmagent](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment] 2021-02-18 14:11
The bugfix has been included in [v1.54.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@berghauz , feel free re-opening the issue if `vmagent` still drops data in the case described here.

**Comment by berghauz** [comment] 2021-02-18 17:17
@valyala thanks, looks like this issue fixed, but there is another one appeared. vmagent doesn't respond on sigterm in case of gracefull stop and empty queue (and vminsert alive), it become killed by systemd in the end. But, if queue not empty (and vminsert instance is down) sigterm works instantly. 
If this issue is not fix related, i will open a new one, just let me know.
`Feb 18 20:02:48 AP-PC systemd[1]: vmagent.service: State 'stop-sigterm' timed out. Killing.
Feb 18 20:02:48 AP-PC systemd[1]: vmagent.service: Killing process 14081 (vmagent-prod) with signal SIGKILL.
Feb 18 20:02:48 AP-PC systemd[1]: vmagent.service: Main process exited, code=killed, status=9/KILL
Feb 18 20:02:48 AP-PC systemd[1]: vmagent.service: Failed with result 'timeout'.
Feb 18 20:02:48 AP-PC systemd[1]: Stopped Victoria Metrics Agent.
`

**Comment by berghauz** [comment] 2021-02-18 17:32
It is easy to reproduce, just start all cluster services (vmagent, vminsert, vmstorage) and just stop vmagent - it will lockup.

**Comment by valyala** [comment] 2021-02-18 22:49
@berghauz , the issue with graceful shutdown must be fixed in the commit c2678754e46880645f7f48ac1f5df1b3d5429750 . But it is better to build vmagent from the commit 2cfb376945ddd166814503d501fb543c86cd6942 , which fixes yet another issue in vmagent.

**Comment by valyala** [comment] 2021-03-02 21:21
The graceful shutdown bugfix has been included in `vmagent` [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Closed by valyala** 2021-03-02 21:21 UTC
Labels: bug, vmagent
