### ISSUE TITLE
vmui does not work properly through vmauth

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#3162] opened 2022-09-26 09:19 UTC
**Describe the bug**
vmui does not work properly through vmauth, where vmauth redirect all request to the wrong path

```
curl -Is -u vmsingleuser:123456 "http://127.0.0.1:8427/vmui"
HTTP/1.1 301 Moved Permanently
Date: Mon, 26 Sep 2022 08:39:05 GMT
Location: vmui/?
```
![2022-09-26_11-32](https://user-images.githubusercontent.com/5650611/192233297-1fd9cabd-27e3-4722-8a45-44f5e557cc47.png)

**To Reproduce**

Run **victoria-metrics** with the following flags:
```console
./victoria-metrics -storageDataPath=$PWD/vm-data -retentionPeriod=12 -httpListenAddr=:8428 -graphiteListenAddr=:2003 -opentsdbListenAddr=:4242 -influxListenAddr=:8089"
```

Run **vmauth** with the following flags:
```console 
./vmauth -auth.config=config.yml
```
vmauth **config.yml**:
```yaml
users:
- username: "vmsingleuser"
  password: "123456"
  url_prefix: "http://127.0.0.1:8428"
```

Run curl query:
```console
curl -Is -u vmsingleuser:123456 "http://127.0.0.1:8427/vmui"
```
or open http://127.0.0.1:8427/vmui in browser

**Expected behavior**
vmui works via vmauth without issues

**Comment by v98765** [comment] 2022-09-27 06:26
#1752 1752

**Comment by valyala** [comment] 2022-09-30 09:04
@v98765 , thanks for pointing to the duplicate issue!

Closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1752

**Closed by valyala** 2022-09-30 09:04 UTC
Labels: bug, vmui
