### ISSUE TITLE
Spaces in tags will broke graphite reciever

### ISSUE THREAD

**Issue by ctrlok** [VictoriaMetrics/VictoriaMetrics#99] opened 2019-07-15 14:38 UTC
I have VM cluster setup. I'm trying to send metrics in Graphite format. 
And I found that if the tag value contains a space, that next uniq metrics with same first tag will be broken. 

It's hard to explain, let me show you a code:
```shell
>>> echo 'metric;tag1=aaa1;tag2=bbb2;tag3=ccc3 2' | nc 127.0.0.1 2003
>>> curl 'http://localhost:8481/select/0/prometheus/api/v1/export?match[]=metric'

{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[2,2],"timestamps":[1563200403000,1563200407000]}
```
Everething is fine. 

Then I send metric with a space symbol in tags (tag2 and tag3) 
```
>>> echo 'metric;tag1=aaa1;tag2=bb b2;tag3=cc c3 2' | nc 127.0.0.1 2003
>>> curl 'http://localhost:8481/select/0/prometheus/api/v1/export?match[]=metric'

{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bb"},"values":[0],"timestamps":[1563200424000]}
{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[2,2],"timestamps":[1563200403000,1563200407000]}
```
I recieved the second metric poorly parsed. It's bad, but not the main issue. 

If I trying to send the next metrics with different and correct tag2 and tag3 I didn't receive anything 

```
>>> echo 'metric;tag1=aaa1;tag2=bb_b2;tag3=ccc3 2' | nc 127.0.0.1 2003
>>> curl 'http://localhost:8481/select/0/prometheus/api/v1/export?match[]=metric'

{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bb"},"values":[0],"timestamps":[1563200424000]}
{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[2,2],"timestamps":[1563200403000,1563200407000]}
```

And if I change metrics next to tag1 to any others VM still refuse to save them. It works only if I change tag1 value to any other
```
>>> echo 'metric;tag1=aa_a1;tag2=bb_b2;tag3=ccc3 2' | nc 127.0.0.1 2003
>>> curl 'http://localhost:8481/select/0/prometheus/api/v1/export?match[]=metric'

{"metric":{"__name__":"metric","tag1":"aa_a1","tag2":"bb_b2","tag3":"ccc3"},"values":[2],"timestamps":[1563200569000]}
{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bb"},"values":[0],"timestamps":[1563200424000]}
{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[2,2],"timestamps":[1563200403000,1563200407000]}


# As you can see if I add tag4 and tag5 instead of tag2 and tag3 it didn't change anything
>>> echo 'metric;tag1=aaa1;tag4=bbb2;tag5=ccc3 2' | nc 127.0.0.1 2003
>>> curl 'http://localhost:8481/select/0/prometheus/api/v1/export?match[]=metric'

{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bb"},"values":[0],"timestamps":[1563200424000]}
{"metric":{"__name__":"metric","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[2,2,2],"timestamps":[1563200403000,1563200407000,1563201198000]}
{"metric":{"__name__":"metric","tag1":"aa_a1","tag2":"bb_b2","tag3":"ccc3"},"values":[2],"timestamps":[1563200569000]}
```

It's a very interesting mistake how the single broken metric can affect other didn't broken metrics.

**Comment by valyala** [comment] 2019-07-15 19:30
@ctrlok , could you verify whether other Graphite implementations support metrics ingestion with white spaces inside tags?
Whitespace inside tags could be difficult to parse properly. For instance, how to parse the following line:
```
metric;tag=foo 123 456
```
Should it be parsed to:
```
{"__name__":"metric","tag":"foo 123"} with value 456 and the current timestamp
```
or to
```
{"__name__":"metric","tag":"foo""} with value 123 and timestamp 456
```
?

As for the missing rows after invalid line, I cannot reproduce the issue:
```
$ cat | nc -N 127.0.0.1 2003
m;tag1=aaa1;tag2=bbb2;tag3=ccc3 1
m;tag1=aaa1;tag2=bb b2;tag3=ccc3 2
m;tag1=aaa1;tag2=bbb3 3
m;tag1=aa_aa1;tag2=bb2 4
m;tag1=aaa;tag3=bbb;tag4=ccc 5
^D

$ curl 'http://localhost:8428/api/v1/export?match[]=m'
{"metric":{"__name__":"m","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[1],"timestamps":[1563218771000]}
{"metric":{"__name__":"m","tag1":"aaa1","tag2":"bbb3"},"values":[3],"timestamps":[1563218771000]}
{"metric":{"__name__":"m","tag1":"aa_aa1","tag2":"bb2"},"values":[4],"timestamps":[1563218771000]}
{"metric":{"__name__":"m","tag1":"aaa","tag3":"bbb","tag4":"ccc"},"values":[5],"timestamps":[1563218771000]}
```
As you can see, all the rows except the second one with whitespace in the tag are properly added into the db.

**Comment by ctrlok** [comment] 2019-07-15 20:03
>As for the missing rows after invalid line, I cannot reproduce the issue:
I didn't know how, but I reproduced it twice. 

> Whitespace inside tags could be difficult to parse properly. 
Yes, that is not a problem, but I'm sure that if this is an error you should show error message in console and didn't write metric with value 0 

```bash-3.2$ echo "s;tag1=aaa1;tag2=bbb2;tag3=ccc3 1" | nc 127.0.0.1 2003
bash-3.2$ echo "s;tag1=aaa1;tag2=bb b2;tag3=ccc3 1" | nc 127.0.0.1 2003
bash-3.2$ curl 'http://localhost:8481/select/0/prometheus/api/v1/export?match[]=s'
{"metric":{"__name__":"s","tag1":"aaa1","tag2":"bbb2","tag3":"ccc3"},"values":[1],"timestamps":[1563220576000]}
{"metric":{"__name__":"s","tag1":"aaa1","tag2":"bb"},"values":[0],"timestamps":[1563220592000]}```

**Comment by valyala** [comment] 2019-07-15 20:55
> if this is an error you should show error message in console and didn't write metric with value 0

Agreed. Will think how to implement this properly.

**Comment by valyala** [comment] 2020-09-16 15:24
FYI, this issue should be fixed after the commit 9bc8484ab67accf3e480ab9f251f42f2314c0f99 . It will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment] 2020-09-23 09:15
VictoriaMetrics should properly emit errors when it cannot parse timestamps and/or values in Graphite line starting from [v1.41.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed.

**Closed by valyala** 2020-09-23 09:15 UTC
Labels: bug, enhancement

**Comment by valyala** [comment] 2022-09-26 12:31
FYI, VictoriaMetrics should accept whitespace in metric names, tag names and tag values after the commit 41f8c2987ddc04bf1bf619937c72ac9dd7af68a9, which will be included in the next release. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3102 for more details.
