### ISSUE TITLE
tls configuration keys in command line

### ISSUE THREAD

**Issue by Ubusubus** [VictoriaMetrics/VictoriaMetrics#242] opened 2019-11-26 14:25 UTC
**Describe the bug**
If you launch VM with command line parameters order _-tls true -tlsCertFile x -tlsCertKey x_ it doesn't get cert and key values and falls with an error.
But if you launch VM with this order: _-tlsCertFile x -tlsCertKey x -tls true_ it gets cert and key values ok.

**To Reproduce**
Launch it with docker:
```
docker run -it victoriametrics/victoria-metrics:latest -tls true -tlsCertFile tls_cert_file -tlsKeyFile tls_key_file
```
cannot load TLS cert from tlsCertFile="", tlsKeyFile="": open : no such file or directory
and:
```
docker run -it victoriametrics/victoria-metrics:latest -tlsCertFile tls_cert_file -tlsKeyFile tls_key_file -tls true
```
cannot load TLS cert from tlsCertFile="tls_cert_file", tlsKeyFile="tls_key_file": open tls_cert_file: no such file or directory

**Expected behavior**
With the same parameters but different order in command line VM should behave the same, and load same values.

**Logs**
[vm1.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3892248/vm1.txt)
[vm2.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3892249/vm2.txt)

**Version**
```
docker run -it victoriametrics/victoria-metrics:latest -version
victoria-metrics-20191121-210951-tags-v1.29.5-0-g3e9b7add
```

**Comment by valyala** [comment] 2019-11-26 16:01
Thanks for the bug report, @Ubusubus ! The bug has been confirmed and will be fixed in the next release.

**Comment by valyala** [comment] 2019-11-26 16:05
FYI, this is related to the following issue in Go - https://github.com/golang/go/issues/22961 . I.e. `-tls true` doesn't work, but `-tls=true` and `-tls` works. Weird :) Will thinks about how to fix this

**Comment by valyala** [comment] 2019-11-26 21:27
Unfortunately there is no easy fix for the issue if continue using standard [flag](https://golang.org/pkg/flag/) package for Go. The workaround is to pass just `-tls` or `-tls=true` instead of `-tls true` to command-line flags.

**Comment by valyala** [comment] 2019-11-28 20:29
FYI, release [v1.30.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) contains improved docs for `-tls*` command-line flags. This should reduce the probability to trigger this issue.

**Comment by valyala** [comment] 2022-12-16 04:47
Closing this issue, since it has a workaround - just pass `-tls=true` instead of `-tls true` to VictoriaMetrics.

**Closed by valyala** 2022-12-16 04:47 UTC
Labels: bug
