### ISSUE TITLE
why data backfilling will effect the vmselect result

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#404] opened 2020-04-07 02:55 UTC
**Describe the bug**
when search.disableCache=false and data backfilling, I found the result is different when query every times.

why data backfilling will effect the vmselect result ? is it a bug？

```
$ ./victoria-metrics-prod --version
victoria-metrics-cluster-1.31.5
```

**Comment by valyala** [comment] 2020-04-07 09:47
`vmselect` caches query responses on the requested time range, so they could be merged with new data on subsequent queries. This helps reducing load on `vmstorage` for repeatedly executed queries for recent data (for instance, when auto-refresh is enabled in Grafana dashboard). `vmselect` in this case requests only new data from `vmstorage` and then merges it with the cached data from previous requests.

`vmselect` assumes that all the new data is added with timestamps closer than 5 minutes to the current time, so it caches responses on time ranges ending at 5 minutes till now. This time can be adjusted with `-search.cacheTimestampOffset` command-line flag (it has been added in `v1.34.0` and all the [newer releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)). If historical data with old timestamps is written into VictoriaMetrics, this data may be invisible in responses if they were already cached during previous queries. So it is recommended either disabling the response cache on `vmselect` with `-search.disableCache` command-line flag when you frequently backfill data or resetting the response cache with `/internal/resetRollupResultCache` after data backfilling is complete.

See more details at [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling).

**Comment by davidsome** [comment] 2020-04-11 14:09
@valyala thanks! do you guys have more detail and technical articles about vmstorage design？I want to learn more。

**Comment by hagen1778** [comment] 2020-04-11 19:47
All existing articles are published here https://medium.com/@valyala
But we plan to have a separate VictoriaMetrics tech blog.

**Comment by valyala** [comment] 2020-04-15 13:18
> do you guys have more detail and technical articles about vmstorage design？

I think the following articles would be interesting to you:

* [Why VictoriaMetrics doesn't use WAL](https://medium.com/@valyala/wal-usage-looks-broken-in-modern-time-series-databases-b62a627ab704)
* [How VictoriaMetrics compresses time series data](https://medium.com/@valyala/victoriametrics-achieving-better-compression-for-time-series-data-than-gorilla-317bc1f95932)
* [How VictoriaMetrics creates instant snapshots](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282)

**Comment by davidsome** [comment] 2020-05-14 15:07
@valyala I have a question. When I use different versions of vmselect and vmstorage in cluster mode. (such as vmselect(1.31.5) && vmstorage(1.28.0)) Does it effect the query_range result  comparing to (such as vmselect(1.31.5) && vmstorage(1.31.5))

**Comment by valyala** [comment] 2020-05-19 22:44
> When I use different versions of vmselect and vmstorage in cluster mode. (such as vmselect(1.31.5) && vmstorage(1.28.0)) Does it effect the query_range result comparing to (such as vmselect(1.31.5) && vmstorage(1.31.5)) ?

This depends on whether there were changes in `vmselect`<->`vmstorage` communication protocol. between the given releases. Sometimes this will work without issues, but sometimes it may lead to incorrect responses or even communication protocol errors. In general it is recommended to keep in sync versions for cluster components.

**Comment by denisgolius** [comment] 2022-07-19 08:34
Closing the issue due to inactivity. @davidsome  , feel free re-opening it or creating new one with additional details if you feel that the issue isn't resolved yet.

**Closed by denisgolius** 2022-07-19 08:34 UTC
Labels: question
