### ISSUE TITLE
Histogram buckets are updated partially for recently written samples

### ISSUE THREAD

**Issue by victoramsantos** [VictoriaMetrics/VictoriaMetrics#6424] opened 2024-06-05 21:44 UTC
### Describe the bug

Instante query from vm-select returning broken buckets. 
On Query 1 I have:
```
histogram_quantile(
  0.99,
  sum(
    rate(
      services_http_request_latency_seconds_bucket{
        path="/api/Y",
        method="get"
      }[1m]
    )
  ) by(le)
)
```
On Query 2:
```
sum(
  services_http_request_latency_seconds_bucket{
    path="/api/Y",
    method="get",
    kubernetes_pod_name="pod-XXX"
  }
) by(le)
```
I'm querying a specific pod against the `histogram_quantile` to identify that always that Query 1 report something strange (the correct should be something between 0.04 and 0.05) I have broken buckets. By broken buckets I mean buckets where `le`'s don't respect the histogram rules of one be grater than the previous, as we can see in this screenshot:
![Screenshot 2024-06-05 at 17 49 00](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/a6d0524f-4949-4792-9cc8-2d374f1346fc)

However when I do query_range I can not see any thing wrong with my data (I'm running only Query 1 on query_range):
![Screenshot 2024-06-05 at 17 57 26](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/fa15f9d8-904a-43b2-baec-370efba416b8)

Under my investigation I had the hypothesis that for some unknown reason vm-storage was reporting, during a non deterministic period, wrong values for my buckets. That said what I tested to prove it:

- **Verify that the problem wasn't with vm-select cache**
I ran this script which queries vm-select during some minutes but querying the same instant with `nocache=1` (I also tested without this flag and the result was the same).
```
#!/bin/sh

minutes=${MINUTES:-10}
start_time=$(date +"%s")
now=$start_time
end_time=$((start_time+60*$minutes))
url="https://my-url"
query="my-histogram-query"

echo "running from $(date -r $start_time) until $(date -r $end_time)"
while [ $now -le $end_time ]; do	
	res=$(curl --silent \
		 -m 5 \
		 -X GET "$url/select/0/prometheus/api/v1/query?query=$query&time=$start_time&nocache=1") 
	echo $(date) : $(date -r $(echo $res | jq ".data.result[0].value[0]")) : $(echo $res | jq ".isPartial") : $(echo $res | jq ".data.result[0].value[1]")
	now=$(date +"%s")
	sleep 1
done;
echo "end finished at $(date)"
``` 
And the result was:
```
...
Mon Jun 3 18:09:34 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "0.04911208112260571"
Mon Jun 3 18:09:36 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "0.0491120811226057"
...
Mon Jun 3 18:10:31 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "90"
...
Mon Jun 3 18:15:55 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "90"
Mon Jun 3 18:15:56 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "0.049000000000000016"
Mon Jun 3 18:15:57 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "0.048999999999999995"
Mon Jun 3 18:15:58 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "0.049000000000000016"
Mon Jun 3 18:15:59 -03 2024 : Mon Jun 3 18:09:20 -03 2024 : false : "0.049000000000000016"
...
```
_Description: time that I queried : instante queried (fixed) : isPartial response? : response value_

As you can see after some seconds running, I started to see the value as 90 and after about 5min the value was fixed and returned the value between 0.04 and 0.05.

- **Check if it's related to deduplication**

To validate if can be related to deduplication I created the script below which query for the same time two prometheus replicas, which queries have the same data that comes to VM. 
```
#!/bin/sh

minutes=${MINUTES:-10}
start_time=$(date +"%s")
now=$start_time
end_time=$((start_time+60*$minutes))
vm_url="vm-select-url"
prom_url_0="prometheus-0-url"
prom_url_1="prometheus-1-url"
query="my-query-that-return-only-buckets-of-a-specific-pod"

echo "running from $(date -r $start_time) until $(date -r $end_time)"
while [ $now -le $end_time ]; do	
	vm_raw_res=$(curl --silent \
		 -m 5 \
		 -X GET "$vm_url/api/v1/query?query=$query&time=$now") 
	echo $vm_raw_res | jq '[.data.result | group_by(.metric.kubernetes_pod_name) | map({(.[0].metric.kubernetes_pod_name): map({le: .metric.le, value: .value[1]})| sort_by(.le | tonumber)})]' > /tmp/vm_res.json

	prom_0_raw_res=$(curl --silent \
		 -m 5 \
		 -X GET "$prom_url_0/api/v1/query?query=$query&time=$now") 
	echo $prom_0_raw_res | jq '[.data.result | group_by(.metric.kubernetes_pod_name) | map({(.[0].metric.kubernetes_pod_name): map({le: .metric.le, value: .value[1]})| sort_by(.le | tonumber)})]' > /tmp/prom_res_0.json

	prom_1_raw_res=$(curl --silent \
		 -m 5 \
		 -X GET "$prom_url_1/api/v1/query?query=$query&time=$now") 
	echo $prom_1_raw_res | jq '[.data.result | group_by(.metric.kubernetes_pod_name) | map({(.[0].metric.kubernetes_pod_name): map({le: .metric.le, value: .value[1]})| sort_by(.le | tonumber)})]' > /tmp/prom_res_1.json
	
	diff -C 1 /tmp/prom_res_0.json /tmp/prom_res_1.json >> /tmp/proms.out
	echo "\n----------------------------------\n" >> /tmp/proms.out

	diff -C 1 /tmp/prom_res_0.json /tmp/vm_res.json >> /tmp/prom_0_x_vm.out
	echo "\n----------------------------------\n" >> /tmp/prom_0_x_vm.out

	diff -C 1 /tmp/prom_res_1.json /tmp/vm_res.json >> /tmp/prom_1_x_vm.out
	echo "\n----------------------------------\n" >> /tmp/prom_1_x_vm.out

	now=$(date +"%s")
	sleep 1
done;
echo "end at $(date)"
```
 As result of this script I found that there is some differences between both prometheus, which is normal since they scrapes the pods at different times, but none of the differences breaks any histogram rules. In other words, for every difference in a bucket Bn all the buckets Bn+1 have a value grater than Bn-1. However when comparing with vm-select I found this case:
```
***************
*** 38,40 ****
            "le": "0.625",
!           "value": "2530"
          },
--- 38,40 ----
            "le": "0.625",
!           "value": "2529"
          },
***************
*** 42,44 ****
            "le": "0.75",
!           "value": "2530"
          },
--- 42,44 ----
            "le": "0.75",
!           "value": "2527" <- HERE
          },
***************
*** 46,48 ****
            "le": "1.0",
!           "value": "2530"
          },
--- 46,48 ----
            "le": "1.0",
!           "value": "2529"
          },
***************
```
Which is a scenario where we are breaking the histogram rule.
My suspicious is that vm-storage is receiving both data, from rep-0 and rep-1 of prometheus and some times is persisting in-memory the grater value as described [here](https://docs.victoriametrics.com/#deduplication) of a given bucket from rep-0 but also the values for the other buckets coming from rep-1 and that's why we are facing this distinction. 
I also think that the data is "fixed" during some merge step after.

### To Reproduce

Let suppose that two replicas of prometheus remote write the data below:
rep-0
```
http_request_latency_bucket{pod="pod-xxx", le="0.1", method="get", path="/api/y"} 11
http_request_latency_bucket{pod="pod-xxx", le="0.2", method="get", path="/api/y"} 12
http_request_latency_bucket{pod="pod-xxx", le="0.3", method="get", path="/api/y"} 25
http_request_latency_bucket{pod="pod-xxx", le="0.4", method="get", path="/api/y"} 26
```
rep-1
```
http_request_latency_bucket{pod="pod-xxx", le="0.1", method="get", path="/api/y"} 15
http_request_latency_bucket{pod="pod-xxx", le="0.2", method="get", path="/api/y"} 15
http_request_latency_bucket{pod="pod-xxx", le="0.3", method="get", path="/api/y"} 28
http_request_latency_bucket{pod="pod-xxx", le="0.4", method="get", path="/api/y"} 28
```
In this case if rep-0 sends the data first than rep-1 we must end up with data from rep-1 entirely, but for some unknown reason, vm is returning data like:
```
http_request_latency_bucket{pod="pod-xxx", le="0.1", method="get", path="/api/y"} 15
http_request_latency_bucket{pod="pod-xxx", le="0.2", method="get", path="/api/y"} 12 <- Data from rep-0
http_request_latency_bucket{pod="pod-xxx", le="0.3", method="get", path="/api/y"} 28
http_request_latency_bucket{pod="pod-xxx", le="0.4", method="get", path="/api/y"} 28
```

### Version

- vmstorage-20231116-195550-tags-v1.95.1-cluster-0-g1a15b0f57
- vmselect-20231116-195457-tags-v1.95.1-cluster-0-g1a15b0f57

### Used command-line flags

These are all the flags that I run vm-storage, vm-select and vm-inserts
```
/vmselect-prod
	 --vmalert.proxyURL=http://yyy:8880
	 --http.connTimeout=130s
	 --http.idleConnTimeout=80s
	 --http.maxGracefulShutdownDuration=40s
	 --search.maxUniqueTimeseries=300000
	 --search.maxQueryDuration=35s
	 --search.minStalenessInterval=5m
	 --search.maxQueryLen=48KB
	 --search.maxConcurrentRequests=38
	 --search.maxMemoryPerQuery=500000000
	 --dedup.minScrapeInterval=30s
	 --loggerFormat=json
	 --replicationFactor=2
	 --search.logQueryMemoryUsage=450MB
	 --storageNode=XXX

/vminsert-prod
	 --disableRerouting=false
	 --dropSamplesOnOverload=false
	 --maxLabelsPerTimeseries=50
	 --replicationFactor=2
	 --loggerFormat=json
	 --loggerFormat=json
	 --disableRerouting=false
	 --dropSamplesOnOverload=false
	 --maxLabelsPerTimeseries=55
	 --replicationFactor=2
	 --vmstorageDialTimeout=2s
	 --vmstorageUserTimeout=2s
	 --maxConcurrentInserts=10
	 --storageNode=XXX

/vmstorage-prod
	 --storageDataPath=/storage
	 --retentionPeriod=8d
	 --search.maxUniqueTimeseries=300000
	 --dedup.minScrapeInterval=30s
	 --loggerFormat=json
	 --storage.vminsertConnsShutdownDuration=210s
	 --cacheExpireDuration=30m0s
	 --internStringCacheExpireDuration=6m0s
	 --memory.allowedPercent=60
	 --prevCacheRemovalPercent=0.1
	 --storage.minFreeDiskSpaceBytes=40GB
	 --precisionBits=64
```

**Comment by AndrewChubatiuk** [comment] 2024-06-10 09:27
Hey @victoramsantos 
this is a known issue as in cluster mode vminsert shards metric among multiple storage nodes, which impacts histogram metrics, that consist from count, sum and multiple buckets metrics. added PR to exclude `le` and `vmrange` labels from vminsert sharding to put all bucket metrics into a single storage. will let you know in case of any updates

**Comment by hagen1778** [comment] 2024-06-10 20:59
@victoramsantos do you execute your instant queries via vmalert? If yes, could you try setting `eval_delay` param (or -rule.evalDelay cmd line flag) to `1m`? This would make vmalert queries to shift the `time` param on query time by 1m in past and will increase chances for getting complete data.

Why data can be incomplete? The histogram, as was described above, is represented by a bunch of time series. All those time series need to be updated atomically for histogram_quantile to be correct. And this, indeed, works in Prometheus for pull model as it persists results of a scrape atomically. But with switch to push model (as in our case) and to the distributed system especially the promise of atomicity is very hard to make. So it could happen that data from Prom1 was already persisted to database, while data from Prom2 was still "in progress" because of network, or flush interval, etc. And then, on query time, expression evaluation happens on partially updated metric and produces these artifacts.

What can be done? First, add this artificial delay to vmalert (or what you use) to reduce chances of incomplete recently written data. 

Another thing is what @AndrewChubatiuk is trying to do in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442. The point here is that vminsert shards data across vmstorages, and sharding function is a hash from time series labels. Since histogram is represented by a set of time series, these series will end up on different vmstorage nodes. These vmstorage nodes are independent and may keep the received data up to 1s in the memory, before they get searchable. Andrew wants to make all series of one hisgoram to end up on the same vmstorage node, so all samples become searchable in the same moment of time.

**Comment by victoramsantos** [comment] 2024-06-11 12:40
Hi @hagen1778 I've got what you said however, I performed some tests by our side that lead me to think it won't work. 
I created an app that query vm-select with a custom interval time to simulate the _evaluationInterval_ of vm-alert. This service was performing a query using `histogram_quantile` like the one of the example above. To test it I performed the follow scenarios:

- **_Query with the current time_**

The service was querying vm-select with the query at the current time _t_ so every query was the last available data and I could see the problem happening (like the example above).

- **_Query with _lookbackTime__**  (I think this is what do you want with `eval_delay` of vm-alert, am I right?)

I did the same test above however changing the `time` _t_ to _currentTime_-_lookbackTime_. So I was querying now but with a fixed previous time. I tested it in all of our clusters with values from 10s up to 120s. So in the worst case I was querying now a data from 2 minutes ago and the problem still happening.


I also tested with the script above in these scenarios:

- **_Querying the past data_**

With the script above I fixed the `time` param to a fixed value (the timestamp that the script started) and then execute it. So when the time was passing I was querying a fixed past time.  

- **_Querying the past data without vm-select cache_**

The same test above but with `nocache=1`

--- 

Just to put it clear the problem is not constantly. So even when testing with _lookbackTime_ there was a period that everything was working and then started to fail again, example:

![Screenshot 2024-06-11 at 09 27 44](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/9c51099f-f22c-47b0-b5a2-c1acafb5ea61)

I checked all dashboards of prometheus-agent, vm-select, vm-insert and vm-storage and there is nothing that I could related to the same time that the problem starts (what was making me crazy XD).

I believe the PR can help to answer the question of why the hot data (the last datapoints) are being reported wrongly sometimes which will help us a lot, however I didn't understand why checking the past data I was receiving wrong data, sometimes after 5 minutes that the data was already stored :/ 

I'll try to test you suggestion on staging environment and come back with more information soon.

But anyway, thank's a lot for the help.

**Comment by hagen1778** [comment] 2024-06-11 12:45
@victoramsantos, could you try setting ` -search.latencyOffset` to value > `--dedup.minScrapeInterval`. For example, to `45s`. 

> I checked all dashboards of prometheus-agent

Does prometheus-agent maintain some kind of queue? Just in case data was actually delayed by the collector. JFYI, prometheus-agent shard time series it needs to send by the number of opened remote-write connections. So a buckets of one histogram could be send via multiple concurrent connections. If the number of connections is too high, or if prometheus-agent puts data in the queue - recently written data into remote storage could be partial.

**Comment by victoramsantos** [comment] 2024-06-11 12:56
> And if, by chance, you could try ruling out the problem by using vmagent - that would be great. I am suggesting this because I don't remember similar cases before, and most VM users are using vmagent as metrics collector.

hum, I know. It's just that isn't easy to change my stack like this, so I was trying to solve it using our current stack first.
Just to put it clear, there was no other issue related to this kind of problem?

**Comment by hagen1778** [comment] 2024-06-11 13:16
> hum, I know. It's just that isn't easy to change my stack like this, so I was trying to solve it using our current stack first.

That's understandable. This is why I suggest trying vmagent as last option.

> Just to put it clear, there was no other issue related to this kind of problem?

I can't remember cases like this. There was similar case related to the delayed data though https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4768

**Comment by victoramsantos** [comment] 2024-06-11 19:45
Just coming back with the results. I added the `search.latencyOffset` of 45s in some clusters but the result was the same:

![Screenshot 2024-06-11 at 16 42 25](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/fecfa1fc-cc49-4506-8777-0fcde96a33d5)

In this screenshot I'm doing the same query at Prometheus and VM on one of our clusters and it's possible to see the hug difference between them.

**Comment by victoramsantos** [comment] 2024-06-11 19:47
I'll test the version with the PR from Andrew (when it is merged) and will try to test vmagent on staging in next days.

**Comment by hagen1778** [comment] 2024-06-12 14:06
Thanks for update!

> In this case if rep-0 sends the data first than rep-1 we must end up with data from rep-1 entirely, but for some unknown reason, vm is returning data like

This will be true if rep-1 will send data with timestamp > than timestamps from rep-0. I've tried to setup two replicas of Prometheus agent and they seem to align their scrape time for the same target:
```
Rep-0
scrape timestamp 1718200465193 actual scrape time: 2024-06-12 15:54:25.313844 +0200 CEST m=+3197.447753751
scrape timestamp 1718200495195 actual scrape time: 2024-06-12 15:54:55.308871 +0200 CEST m=+3227.440187251

Rep-1
scrape timestamp 1718200465193; actual scrape time: 2024-06-12 15:54:25.313874 +0200 CEST m=+3195.588858126
scrape timestamp 1718200495195; actual scrape time: 2024-06-12 15:54:55.306038 +0200 CEST m=+3225.578429584
```

From example above we see that Rep-0 and Rep-1 scrape at different times (so they can get different values) but persist data with the same timestamp. The [deduplication](https://docs.victoriametrics.com/#deduplication) logic in VictoriaMetrics selects sample with the biggest timestamp on the interval. Or if timestamps are equal, it selects the biggest value. 

For example, if we have the following data sent to VM:
```
Rep-0
http_request_latency_bucket{pod="pod-xxx", le="0.2", method="get", path="/api/y"} 12 1718200465193

Rep-1
http_request_latency_bucket{pod="pod-xxx", le="0.2", method="get", path="/api/y"} 15 1718200465193
```
Then after deduplication we'll get `http_request_latency_bucket{pod="pod-xxx", le="0.2", method="get", path="/api/y"} 15 1718200465193` in response.

This problem should be fixed by adding a scrape jitter to one of prometheus agent. If one agent is always behind or ahead by 1ms at least, then data will be deduplicated deterministically. This jitter is already supported by VictoriaMetrics vmagent - see https://docs.victoriametrics.com/vmagent/#high-availability:
> It is also recommended passing different values to -promscrape.cluster.name command-line flag per each vmagent instance or per each vmagent cluster in HA setup. This is needed for proper data de-duplication. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2679) for details.

I didn't find anything similar in prometheus agent, except adding an external label - see https://github.com/prometheus/prometheus/blob/64a9abb8be73a25e486382e7160773697b7182d8/scrape/manager.go#L195-L207. So probably you can add an external label on the agents and then drop it via relabeling at vminsert, because VM expects time series to have identical labels for proper deduplication.

> I'll test the version with the PR from Andrew (when it is merged) and will try to test vmagent on staging in next days.

I don't think it will be merged without proving it is helpful. And I don't see it being helpful in this case, so far. If you'd like I can build and publish an image from this PR for you to test.

**Comment by victoramsantos** [comment] 2024-06-12 18:46
I've got it. Can you publish this image please? I would give it a try.

**Comment by victoramsantos** [comment] 2024-06-12 18:52
>  So probably you can add an external label to the prometheus agents and then drop it via relabeling at vminsert, because VM expects time series to have identical labels for proper deduplication.

So your suggestion is to send some identifier through prometheus (such as pod_name) as an external label and then drop it with vm-insert? 
I didn't find any way to do it through vm-inserts flags :/

**Comment by hagen1778** [comment] 2024-06-13 05:44
> So your suggestion is to send some identifier through prometheus (such as pod_name) as an external label and then drop it with vm-insert?

Not just send a label, set it to external_labels in prometheus config, because it uses those labels when calculating scrape offset. 
You can drop the label via relabeling on vminsert. Relabeling config can be specified via flag:
>   -relabelConfig string
     Optional path to a file with relabeling rules, which are applied to all the ingested metrics. The path can point either to local file or to http url. See https://docs.victoriametrics.com/#relabeling for details. The config is reloaded on SIGHUP signal

See how to drop a label here https://docs.victoriametrics.com/relabeling/#how-to-remove-labels-from-scraped-metrics. See how you can test it [here](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/relabeling?config=-+action%3A+labeldrop%0A++regex%3A+%22replica%22&labels=foo%7Binstance%3D%22bar%22%2C+replica%3D%22r1%22%7D).

**Comment by hagen1778** [comment] 2024-06-13 07:02
@victoramsantos please see [this image](https://hub.docker.com/layers/victoriametrics/vmagent/heads-exclude-le-vmrange-labels-from-sharding-0-gb9027fb3fb/images/sha256-4dd2626e5859fc6298663d69d81104e45374725e6c096aee90be7b15216c3411?context=explore).

**Comment by hagen1778** [comment] 2024-06-19 08:38
Hey @victoramsantos! Do you have any updates on the issue?

**Comment by juliocleal14** [comment] 2024-08-10 14:02
Hi @hagen1778 , I'm on the same team as @victoramsantos .
Thank you so much for your help!
We tested the VMAgent for the couple weeks and using the VMAgent in fact the problem does not occour.
However, I am trying understand the difference between the vmagent and the Prometheus in this specific situation.
Why with the VMAgent this did not occour?
There are some aggregation or the VMAgent send the timeseries with some hash, or something like this that for the VMInsert add the timeseries always in the same VMStorage?
What could be the difference between the timeseries sent by prometheus and VMAgent?

I am asking this because we tested the VMAgent without any aggregation configured, any deduplication configured (the VMAgent has some aggregation or deduplication configured as default?)

**Comment by hagen1778** [comment] 2024-08-13 12:37
Hey @juliocleal14!

>We tested the VMAgent for the couple weeks and using the VMAgent in fact the problem does not occour.

Have you tested it with vmagent in HA mode configured as suggested in docs https://docs.victoriametrics.com/vmagent/#high-availability ? If yes, then logic is explained in this [comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6424#issuecomment-2163104729). vmagents configured in HA mode intentiinally introduce a small jitter to the scrape time. Effectively this means that in HA pair of 2 vmagents their scrape time will be always different in a few milliseconds. This resolves the conflict between identical timestamps during [deduplication](https://docs.victoriametrics.com/#deduplication).

**Comment by juliocleal14** [comment] 2024-09-27 22:07
Hello everyone, I hope you’re doing well.

I would greatly appreciate any guidance on migrating from Prometheus-Agent to VMAgent.

We’ve been using Prometheus-Agent since migrating from Thanos to VictoriaMetrics two years ago. 

We initially chose this approach because we have a large Prometheus configuration file and wanted to avoid spending time revising it.

Recently, we reached out for assistance here regarding some unusual spikes in our histogram metrics. This issue was raised, and @hagen1778  recommended migrating to VMAgent as a solution.

We are currently working on it and encountering several challenges during the migration process.

Our scenario is:

* We are running VictoriaMetrics in cluster mode, deployed on Kubernetes.

* We’re implementing the [high availability approach](https://docs.victoriametrics.com/vmagent/#high-availability) for VMAgent by deploying 2 pods to scrape all targets. Deduplication is applied before forwarding the time series data to VMInsert/VMStorage.

* We are running the VMAgent on version `v1.103.0`, while the others VictoriaMetrics components are on version `v1.95.1`.

Below how we are running each component:

### VMAgent

```
/vmagent-prod \
        --promscrape.suppressScrapeErrors=true \
        --promscrape.suppressDuplicateScrapeTargetErrors=true \
        --promscrape.maxScrapeSize=400MB \
        --promscrape.streamParse=true \
        --promscrape.cluster.membersCount=6 \
        --promscrape.cluster.replicationFactor=2 \
        --promscrape.cluster.memberNum=$(POD_NAME) \
        --promscrape.config=/vmagent.yml \
        --remoteWrite.maxDiskUsagePerURL=95GiB \
        --remoteWrite.queues=32 \
        --remoteWrite.maxBlockSize=50MiB \
        --remoteWrite.maxRowsPerBlock=10000 \
        --loggerFormat=json \
        --remoteWrite.showURL=true \
        --remoteWrite.url=http://vminsert_address:8480/insert/0/prometheus/api/v1/write \
        --remoteWrite.tmpDataPath=/vmagent/data \
        --promscrape.cluster.name=$(POD_NAME) \
        --remoteWrite.streamAggr.dedupInterval=30s \
        --streamAggr.dropInputLabels=replica \
        --http.maxGracefulShutdownDuration=60s 
```

### VMStorage

```
/vmstorage-prod \
        --storageDataPath=/storage \
        --retentionPeriod=4d \
        --search.maxUniqueTimeseries=300000 \
        --dedup.minScrapeInterval=30s \
        --loggerFormat=json \
        --storage.vminsertConnsShutdownDuration=210s \
        --cacheExpireDuration=30m0s \
        --internStringCacheExpireDuration=6m0s \
        --memory.allowedPercent=60 \
        --prevCacheRemovalPercent=0.1 \
        --storage.minFreeDiskSpaceBytes=20GB \
        --precisionBits=64
```

### VMInsert

```
/vminsert-prod \
        --disableRerouting=false \
        --dropSamplesOnOverload=false \
        --maxLabelsPerTimeseries=60 \
        --replicationFactor=2 \
        --loggerFormat=json \
        --loggerFormat=json \
        --disableRerouting=false \
        --dropSamplesOnOverload=false \
        --maxLabelsPerTimeseries=60 \
        --replicationFactor=2 \
        --vmstorageDialTimeout=2s \
        --vmstorageUserTimeout=2s \
        --maxConcurrentInserts=15 \
        --storageNode=vmstorage-0:8400 \
        --storageNode=vmstorage-1:8400 \
        --storageNode=vmstorage-2:8400 \
        --storageNode=vmstorage-3:8400 \
        --storageNode=vmstorage-4:8400 \
        --storageNode=vmstorage-5:8400
```

So, we are trying understand some things:







1. I understand that a direct comparison may not be possible, but with Prometheus-Agent, we were using 13 vCPUs, whereas with VMAgent, we’ve configured 35 vCPUs, and it still hasn’t been sufficient.

## VMAGent vCPU

![image](https://github.com/user-attachments/assets/05463fbe-4e1b-42bf-9196-abf97ba69574)

## Prometheus agent vCPU

![image](https://github.com/user-attachments/assets/ecdb986a-3c9c-4060-8f6e-f38d266e24a3)


I came across a related [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5898) concerning a similar problem with aggregation enabled, although the user had a different configuration. I only require aggregation for deduplication purposes, nothing else.

I’ve adjusted the values for `remoteWrite.queues`, `remoteWrite.maxBlockSize`, and `remoteWrite.maxRowsPerBlock` in an attempt to decrease resource usage, but haven’t achieved the desired results. 

After several attempts, I believe I’ve identified a relationship between the configuration parameters and the scraped data points.

As shown in the Scrape Datapoints graph, we have around 500k datapoints scraped per second. If I configure `remoteWrite.maxRowsPerBlock` to 500k and set `remoteWrite.queue` to 60, I would expect the queues to fill in 60 seconds, correct? With this setup, I would just need to ensure that the datapoints are sent within that 60-second window to avoid storing them in the persistent queue, right?

![image](https://github.com/user-attachments/assets/473c3a63-ea7e-4282-b337-e7bdf8515c49)

So, I configured the VMAgent with the following values:

```
--remoteWrite.queues=64 \
--remoteWrite.maxBlockSize=400MiB \
--remoteWrite.maxRowsPerBlock=500000 \
```

With this configuration, I was able to get VMAgent working—at least it started sending metrics to the remote storage.

However, we began to notice some unusual values in various graphs. Take a look at these examples:

![image](https://github.com/user-attachments/assets/ddca7df5-d68c-4b92-b69b-d312cb752b29)

Explaing better the graphs: The graphs come from our ‘Monitoring of Monitoring’ setup, which is a Prometheus instance running with a few days’ retention, specifically scraping metrics from our monitoring tools.

The first two graphs show CPU and memory usage of VMAgent, using Prometheus as the data source. The last two graphs display the same CPU and memory usage, but with VictoriaMetrics as the data source, using metrics sent by VMAgent

As you can see, the graphs are significantly different. The graphs using metrics sent by VMAgent have fewer datapoints, and the values seem slightly off compared to those collected by Prometheus.

*My question is: Could this behavior be caused by a configuration issue on my end? I’m unsure why this is happening.*

Another observation is that with this configuration, we see a substantial increase in VMInsert and VMStorage resource usage, and, the resource usage of the VMAgent continue high. Take a look at the following data:

## VMInsert

![image](https://github.com/user-attachments/assets/48979879-2e6d-4049-8389-516b2bfd573f)

## VMStorage

![image](https://github.com/user-attachments/assets/62093762-51d0-4671-9fb9-f8d1e06694b2)

## VMAgent

![image](https://github.com/user-attachments/assets/305a8a04-8d25-4347-999f-815017fd1da3)

I understand that we need to make some adjustments to resource usage, but it seems to me that everything is worse when using VMAgent.









2. During the restart of VMAgent, we observe spikes in the Grafana graphs. It appears that this may be due to buffered time series being added out of order, with all of them being stored with the same timestamp?

This first image shows when I restarted the VMAGent

![image](https://github.com/user-attachments/assets/350ebb74-dcd7-4bf6-aea4-153fe43265c1)

The second metric represents HTTP request latency, which shows significant behavior changes during the VMAgent restart. This could be problematic, as it may lead to false alerts or misleading information in the graphs.

![image](https://github.com/user-attachments/assets/2c2217ae-d891-4746-b7ba-32ba185187cd)

I saw this flag: 

`streamAggr.ignoreFirstIntervals`: 

> Number of aggregation intervals to skip after the start for aggregator. Increase this value if you observe incorrect aggregation results after vmagent restarts. It could be caused by receiving unordered delayed data from clients pushing data into the vmagent. See https://docs.victoriametrics.com/stream-aggregation/#ignore-aggregation-intervals-on-start

Could this flag resolve the issue? If so, what is the rationale for selecting the optimal value?







3. I’ve noticed an unusual relationship between the rows inserted by VMInsert and disk utilization in VMStorage. My understanding is that fewer rows being inserted would require less disk space in VMStorage to store the metrics, however, it seems that this is not the case, look the graphs:

Please split the graphs into three sections:

a. Before 9/24, noting a brief gap around 18:00 separating.

b. The time between letter A and 9/25 around 18:00 (noting an another bried gap to separate)

c. After 9/25 at 18:00, highlighting the subsequent changes.

The letters A and C we were using Prometheus-agent and the letter b we were using VMAgent

We can observe a growth in the disk space utilization while we were using VMAgent.

![image](https://github.com/user-attachments/assets/486cba73-6434-432e-ba3a-740f0fe5def0)

But the stranger thing is: When we observe the rows inserted in the same interval we can see a significant difference between usage.

![image](https://github.com/user-attachments/assets/23b48387-1048-4f7c-8bef-1967aad47227)

Is this correct? 





4. The streamParse could cause a delay in the metrics send to remote storage? (I ask this because the VMAgent will process the responses in chunks async, right?)






**To summarize, I understand that migrating to VMAgent could help reduce the spikes in the histogram graphs. However, I believe VMAgent may not be well-suited for our scenario. I’m currently testing it in a small staging environment, while our main production environment is at least five times larger.

Do you have any advice for us to make VMAgent functional? We need to consider the financial implications of this decision. Preliminary calculations suggest that we would need to triple our current monitoring costs to support the migration, and ultimately, this may not be the best choice for us.

If we decide not to use VMAgent, do you have any suggestions for addressing these spikes? I noticed that [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6442), which aimed to ensure that timeseries from the same histogram metrics are routed to the same VMStorage by VMInsert, has been closed. Could this have been a viable solution? Alternatively, is there a newer version of VictoriaMetrics that resolves this issue in another way?

Thank you very much in advance. I realize I’ve provided a lot of information, so please feel free to ask for any additional details or to separate the problems into different parts.**

**Comment by hagen1778** [comment] 2024-09-30 07:15
Hi @juliocleal14 ! 
Thanks for detailed question! It contains many points, but I'd like to start from the very first ones. When they're clear, we can move to other questions.

```
/vmagent-prod \
        --promscrape.cluster.membersCount=6 \
        --promscrape.cluster.replicationFactor=2 \
        --promscrape.cluster.memberNum=$(POD_NAME) \
        --promscrape.config=/vmagent.yml \
        --remoteWrite.url=http://vminsert_address:8480/insert/0/prometheus/api/v1/write \
        --promscrape.cluster.name=$(POD_NAME) \
        --remoteWrite.streamAggr.dedupInterval=30s \
        --streamAggr.dropInputLabels=replica
```

In this vmagent setup, you have a cluster of 6 vmagents scraping the list of targets with RF=2 (which means each target is scraped at least twice). It is unclear for my why you have the following settings:
```
        --remoteWrite.streamAggr.dedupInterval=30s \
        --streamAggr.dropInputLabels=replica
```
These settings are needed if:
1. You have scrape_interval:15s and want to make it 30s via deduplication
2. Or you have other clients pushing metrics to these vmagents, and these metrics contain duplicates
3. You have label `replica` on the metrics these clients push, because vmagent by default doesn't add this label.

If none of this is true, just remove stream aggregation completely from this setup. Deduplication would make sense only if vmagent actually gets duplicates. In cluster mode with `--promscrape.cluster.replicationFactor=2 ` each distinct vmagent doesn't get any duplicates.

**Comment by hagen1778** [comment] 2024-09-30 09:30
> About reclassification, if you prefer I can start a new issue only about these topics

Yes, I think it would make it easier for other readers.

> I ask because, according to the documentation, it says that to use it in HA, I need to enable deduplication

Could you please point me to the specific doc?

**Comment by juliocleal14** [comment] 2024-09-30 12:57
> Yes, I think it would make it easier for other readers.

I will do that. Thank you! In the new issue I add the doc link

**Comment by juliocleal14** [comment] 2024-09-30 14:13
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7144

**Comment by hagen1778** [comment] 2024-10-01 09:43
@victoramsantos I'm closing this issue as it has had no updates for a long time since https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6424#issuecomment-2178098694.
Concerns raised by @juliocleal14 were moved to a separate issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7144.

**Closed by hagen1778** 2024-10-01 09:43 UTC
Labels: bug, need more info
