### ISSUE TITLE
histogram_quantile sometimes shows max value for inexistent data

### ISSUE THREAD

**Issue by jeromegn** [VictoriaMetrics/VictoriaMetrics#136] opened 2019-07-29 20:25 UTC
![image](https://user-images.githubusercontent.com/43325/62079525-e8701a00-b21c-11e9-8c5f-0c5268569875.png)
![image (1)](https://user-images.githubusercontent.com/43325/62079539-edcd6480-b21c-11e9-9898-254020d35e06.png)

Top is Prometheus, bottom is VictoriaMetrics.

Query looks like:

```
histogram_quantile(0.99, sum(rate(connect_time_histogram_seconds_bucket[30s])) by (le, service))
```

but repeated for 0.95 and 0.50 percentiles too.

Any ideas?

**Comment by valyala** [comment] 2019-07-29 22:27
This looks like edge case issue in VictoriaMetrics.

@jeromegn , could you provide graphs from Prometheus and VictoriaMetrics on the same time range for the following query:
```
sum(rate(connect_time_histogram_seconds_bucket[30s])) by (le)
```

**Comment by jeromegn** [comment] 2019-07-29 23:46
![image](https://user-images.githubusercontent.com/43325/62090086-8eca1880-b239-11e9-8348-f32df3b8d1d7.png)

![image](https://user-images.githubusercontent.com/43325/62090079-87a30a80-b239-11e9-8b92-ebc4c85cbd36.png)

As far as I can tell, the 2 are identical with that query (top prom, bottom victoria)

**Comment by valyala** [comment] 2019-07-30 10:13
Thanks!
Then could you provide graphs for the following query:
```
sum(rate(connect_time_histogram_seconds_bucket{service="app-2048"}[30s])) by (le)
```

**Comment by jeromegn** [comment] 2019-07-30 13:06
Prom
![image](https://user-images.githubusercontent.com/43325/62131304-efdd0500-b2a8-11e9-8493-22ab90400fe7.png)
VM
![image](https://user-images.githubusercontent.com/43325/62131289-e784ca00-b2a8-11e9-84e6-7acd1ed8be5f.png)

The main difference I notice is this bit:
Prom
![image](https://user-images.githubusercontent.com/43325/62131407-23b82a80-b2a9-11e9-93d4-207a426e8eae.png)

VM
![image](https://user-images.githubusercontent.com/43325/62131372-113df100-b2a9-11e9-8051-6cf47d530ecf.png)

**Comment by valyala** [comment] 2019-07-30 19:09
@jeromegn , try building VictoriaMetrics from 10f5a26bece6239c5a5865e7f2bfcfcb7990b4a5 (single-node version) or from c901a6472f82c8d4dd1ab4821bcb7418a6050f85 (cluster version) and verify whether the bug is fixed there. Build instructions are [here for single-node version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources) and [here for cluster version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#building-from-sources).

**Comment by valyala** [comment] 2019-07-31 13:37
@jeromegn , could you verify the issue is fixed in [v1.23.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by jeromegn** [comment] 2019-07-31 14:54
Ah, I'm sorry, it looks like this might be a promxy issue after all. If I hit either of our Victoria Metrics directly, it appears to have good data (slightly different than prometheus, but that's expected).

Very sorry about this wild goose chase.

**Comment by valyala** [comment] 2019-07-31 17:04
There is a fix for `histogram_quantile` issue similar to this one in recently published [v1.23.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), so probably the issue was real.

Anyway, thanks for the bug report :)

**Comment by username1366** [comment] 2020-10-16 15:51
Looks like I have the same issue:
<img width="1228" alt="Screenshot 2020-10-16 at 18 47 37" src="https://user-images.githubusercontent.com/8265171/96280108-43d42680-0fe0-11eb-831f-df2fbf701253.png">
<img width="1267" alt="Screenshot 2020-10-16 at 18 47 25" src="https://user-images.githubusercontent.com/8265171/96280131-4a629e00-0fe0-11eb-9530-d2fb16e10dca.png">

Query: histogram_quantile(0.99, avg(rate(istio_request_duration_milliseconds_bucket{app=~"$app",destination_app="$app"}[5m])) by (k8s_cluster,le))
VictoriaMetrics cluster v1.43.0-cluster

**Comment by valyala** [comment] 2020-10-16 17:51
@username1366 , could you provide graphs for VictoriaMetrics and Prometheus for the inner query inside histogram_query? I.e. `avg(rate(...))`

**Comment by username1366** [comment] 2020-10-16 20:56
<img width="1659" alt="Screenshot 2020-10-16 at 23 54 49" src="https://user-images.githubusercontent.com/8265171/96307930-0fc22b00-100b-11eb-91fb-e6ca6788cc68.png">
<img width="1644" alt="Screenshot 2020-10-16 at 23 56 14" src="https://user-images.githubusercontent.com/8265171/96308004-3a13e880-100b-11eb-84bd-01b29f954b01.png">

**Comment by username1366** [comment] 2020-10-16 23:25
I see that Prometheus metrics have more labels than VM's one
<img width="1619" alt="Screenshot 2020-10-17 at 02 21 11" src="https://user-images.githubusercontent.com/8265171/96321849-8f59f500-101f-11eb-999d-6e1298f98744.png">
<img width="1619" alt="Screenshot 2020-10-17 at 02 20 54" src="https://user-images.githubusercontent.com/8265171/96321856-95e86c80-101f-11eb-9314-3abdf2e3310c.png">

**Comment by valyala** [comment] 2020-10-17 06:47
VictoriaMetrics limits the number of metrics per time series with `-maxLabelsPerTimeseries` command-line flag. By default this limit is set to 30. It looks like your workload needs bigger limit. If you use [cluster version of VictoriaMetrics](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html), then the limit must be set at `vminsert` nodes. VictoriaMetrics exposes `vm_metrics_with_dropped_labels_total` counter at `/metrics` page, which shows the number of label drops. This metric can be [monitored](https://victoriametrics.github.io/#monitoring).

**Comment by username1366** [comment] 2020-10-19 08:02
I already set maxLabelsPerTimeseries to 200 but It didn't help
```
kubectl logs -f victoria-metrics-cluster-vminsert-7bbb9fb979-bfs42 -n monitoring
{"ts":"2020-10-16T10:07:45.180Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"maxLabelsPerTimeseries\" = \"200\""}
```
<img width="1611" alt="Screenshot 2020-10-19 at 11 01 17" src="https://user-images.githubusercontent.com/8265171/96417793-79ecf280-11fa-11eb-93fc-a15e8fcaf15d.png">

**Comment by hagen1778** [comment] 2023-04-27 07:27
Hi @username1366! Is the issue still relevant for you? Do you have a data set where problem can be reproduced?

**Comment by valyala** [comment] 2024-02-07 21:04
Closing the issue because of inactivity.

@username1366 , please open a new issue and post a link to this one if you still experience it in the [latest VictoriaMetrics releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest).

**Closed by valyala** 2024-02-07 21:04 UTC
Labels: bug
