### ISSUE TITLE
vmagent: missing some scrape_configs options

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#503] opened 2020-05-19 11:59 UTC
I tried to replace prometheus by vmagent, and faced that it do not handling correctry some options, which is described in prometheus docs.

1. `proxy_url` in job definition:

`config from "/etc/vmagent.yml": cannot unmarshal data: yaml: unmarshal errors:
  line 74: field proxy_url not found in type promscrape.ScrapeConfig`

2. `refresh_interval` in `consul_sd_configs` section:

`config from "/etc/vmagent.yml": cannot unmarshal data: yaml: unmarshal errors:
  line 13: field refresh_interval not found in type consul.SDConfig`

**Comment by valyala** [comment] 2020-05-19 21:43
Both `proxy_url` and `refresh_interval` options aren't supported by `vmagent` yet.

`refresh_interval` can be substituted by `-promscrape.*CheckInterval` command-line flags:

```
  -promscrape.configCheckInterval duration
    	Interval for checking for changes in '-promscrape.config' file. By default the checking is disabled. Send SIGHUP signal in order to force config check for changes
  -promscrape.consulSDCheckInterval consul_sd_configs
    	Interval for checking for changes in consul. This works only if consul_sd_configs is configured in '-promscrape.config' file. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config for details (default 30s)
  -promscrape.dnsSDCheckInterval dns_sd_configs
    	Interval for checking for changes in dns. This works only if dns_sd_configs is configured in '-promscrape.config' file. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config for details (default 30s)
  -promscrape.ec2SDCheckInterval ec2_sd_configs
    	Interval for checking for changes in ec2. This works only if ec2_sd_configs is configured in '-promscrape.config' file. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config for details (default 1m0s)
  -promscrape.fileSDCheckInterval duration
    	Interval for checking for changes in 'file_sd_config'. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config for details (default 30s)
  -promscrape.gceSDCheckInterval gce_sd_configs
    	Interval for checking for changes in gce. This works only if gce_sd_configs is configured in '-promscrape.config' file. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#gce_sd_config for details (default 1m0s)
  -promscrape.kubernetesSDCheckInterval kubernetes_sd_configs
    	Interval for checking for changes in Kubernetes API server. This works only if kubernetes_sd_configs is configured in '-promscrape.config' file. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config for details (default 30s)
```

Let's keep this issue open in the hope support for these params will be added into `vmagent` in the future.

**Comment by waldoweng** [comment] 2020-11-18 09:10
@valyala I see http/https proxy is supported by valyala/fasthttp, will this feature be available on VictoriaMetrics/fasthttp recently?

This feature should be very useful to support `proxy_url` option.

**Comment by valyala** [comment] 2020-11-18 12:36
The `proxy_url` option should be supported eventually, but there is no ETA for this yet :(

**Comment by nickmy9729** [comment] 2020-12-18 02:59
Is there anyway to bump this up in priority?  Proxy_url configs are needed in enterprise setups especially when utilizing pull scrapes.  Network zones and FW rules are a pain to navigate with our dedicated proxies.  We have a very large Prometheus setup and would like to convert over to VM but this is holding us up from being able to drop Prometheus all together.

**Comment by valyala** [comment] 2020-12-18 11:02
@f41gh7 , could you look into this?

**Comment by valyala** [comment] 2020-12-24 09:45
vmagent gained support for `proxy_url` option starting from the commit 820669da697353166cd54adb4bbe73e2f8c29587 . @wf1nder , @waldoweng , @nickmy9729 , could you build vmagent from this commit and verify whether this option works as intended? See [build instructions for vmagent](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources).

**Comment by nickmy9729** [comment] 2020-12-24 14:52
Building and testing today.  Going to test against 3-4k targets using proxy_url.

**Comment by nickmy9729** [comment] 2020-12-24 21:58
Tested with 4K targets going through different proxies.  Looks great!  Thank you very much!

**Comment by valyala** [comment] 2020-12-28 00:39
vmagent supports `proxy_url` config option starting from [release v1.51.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing this issue as done.

There are no plans for adding `refresh_interval` config option, since it has been replaced by the corresponding `-promscrape.*CheckInterval` command-line flags:
```
  -promscrape.configCheckInterval
  -promscrape.consulSDCheckInterval
  -promscrape.dnsSDCheckInterval
  -promscrape.dockerswarmSDCheckInterval
  -promscrape.ec2SDCheckInterval
  -promscrape.eurekaSDCheckInterval
  -promscrape.fileSDCheckInterval
  -promscrape.gceSDCheckInterval
  -promscrape.kubernetesSDCheckInterval
  -promscrape.openstackSDCheckInterval
```

**Closed by valyala** 2020-12-28 00:39 UTC
Labels: enhancement
