### ISSUE TITLE
Add a new flag and functionality to convert InfluxDB fields that will be support Prometheus metric naming specification

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#3133] opened 2022-09-20 07:02 UTC
**Is your feature request related to a problem? Please describe.**

When Telegraf sends metrics to VictoriaMetrics and the metrics names contain `-` symbol, then VictoriaMetrix will create metrics with the same names. This name does not support [Prometheus metric naming specification](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels).

See an example below:

`linux_sysctl_fs,host=foo dentry-want-pages=0i,file-max=44222i,aio-max-nr=65536i,inode-preshrink-nr=0i,dentry-nr=64340i,dentry-unused-nr=55274i,file-nr=1568i,aio-nr=0i,inode-nr=35952i,inode-free-nr=12957i,dentry-age-limit=45i 1490982022000000000`  

```console 
curl -v -d 'linux_sysctl_fs,host=foo dentry-want-pages=0,file-max=44222,aio-max-nr=65536,inode-preshrink-nr=0,dentry-nr=64340,dentry-unused-nr=55274,file-nr=1568,aio-nr=0,inode-nr=35952,inode-free-nr=12957,dentry-age-limit=45' -X POST 'http://127.0.0.1:8428/write'
```
```console 
curl -G 'http://127.0.0.1:8428/api/v1/export' -d'match={host="foo"}'
```

```
{"metric":{"__name__":"linux_sysctl_fs_aio-max-nr","host":"foo"},"values":[65536],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_dentry-unused-nr","host":"foo"},"values":[55274],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_dentry-nr","host":"foo"},"values":[64340],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_dentry-want-pages","host":"foo"},"values":[0],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_inode-preshrink-nr","host":"foo"},"values":[0],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_inode-free-nr","host":"foo"},"values":[12957],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_inode-nr","host":"foo"},"values":[35952],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_dentry-age-limit","host":"foo"},"values":[45],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_file-max","host":"foo"},"values":[44222],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_file-nr","host":"foo"},"values":[1568],"timestamps":[1663654902276]}
{"metric":{"__name__":"linux_sysctl_fs_aio-nr","host":"foo"},"values":[0],"timestamps":[1663654902276]}
```

**Describe the solution you'd like**
Add a new flag and functionality that will enable converting metrics from Telegraf to Prometheus metric naming style. For example:
`linux_sysctl_fs_dentry_age_limit` instead of `linux_sysctl_fs_dentry-age-limit`

**Describe alternatives you've considered**
Add relabeling in Telegraf config:
```console
[[processors.regex]]
  namepass = ["*"]
  [[processors.regex.field_rename]]
    pattern = "-"
    replacement = "_"
```

See more https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3113

**Comment by erkexzcx** [comment] 2022-09-21 07:18
Telegraf [Prometheus output plugin ](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/prometheus_client)actually replaces all illegal characters to `_`:
```go
var invalidNameCharRE = regexp.MustCompile(`[^a-zA-Z0-9_:]`)
...
func sanitize(value string) string {
	return invalidNameCharRE.ReplaceAllString(value, "_")
}
```

I expect VictoriaMetrics to do the same approach. Please implement identical approach to VictoriaMetrics.

**Comment by valyala** [comment] 2022-09-26 10:23
Closing this feature request as a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3113 . See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3113#issuecomment-1257495964 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3113#issuecomment-1257814343 for details.

**Closed by valyala** 2022-09-26 10:23 UTC
Labels: enhancement, influxdb
