### ISSUE TITLE
reduce disk write frequency?

### ISSUE THREAD

**Issue by thomas725** [VictoriaMetrics/VictoriaMetrics#3337] opened 2022-11-11 13:27 UTC
**Is your feature request related to a problem? Please describe.**
I'm running the victoria metrics single server version on a Raspberry Pi4 with only a microsd card for storage.

Since microsd cards die quite fast when written to too often, I'm using [log2ram](https://github.com/azlux/log2ram) which creates and mounts zram devices for all the configured directories, which I've made to be a list of all directories that get written to frequently. log2ram takes care of writing the data back to "disk"=microsd card on reboots and at a configured regular interval, in my case once per day.

For my research setup, I've included VictoriaMetrics data storage folder in my log2ram configuration, but that will of course only work as long as it's small enough to fit into RAM (as compressed zram disk).

**Describe the solution you'd like**
Can I somehow control / influence the frequency with which VictoriaMetrics writes to disk, effectively holding the recently submitted data only in memory? At the moment my instance writes ~300kb every 5 seconds, with some additional writes at longer / random intervals.

**Describe alternatives you've considered**
Maybe I could trim my log2ram config to include only the folders / partition representing the recent data, excluding partitions for past months from the zram mirroring.

**Comment by thomas725** [comment] 2022-11-13 08:11
Another maybe easier alternative I've just thought of: add an optionally configurable second data-directory for archived data, that if specified is used to to infrequently move data that is older than a certain threshold timespan from the main data directory there.

**Comment by valyala** [comment] 2022-11-21 14:24
@thomas725 , the feature for controlling the frequency of disk writes in VictoriaMetrics looks really interesting for Raspberry PI-like cases where the data is stored to an ordinary SD card.

Currently VictoriaMetrics flushes incoming data to disk at least every 5 seconds - see [inmemoryPartsFlushInterval](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/b796a0dc3f511a1e4a46ce6c3b41381701d3a246/lib/storage/partition.go#L94). The incoming data can be flushed to disk more frequently if it fills the in-memory buffers faster than in 5 seconds. I think it would be great converting this constant to a command-line flag, so users could control it manually according to their needs.

**Comment by valyala** [comment] 2022-12-06 00:26
The commit 8189770c50165b62867327ad388f2c2ef237ab6f adds `-inmemoryDataFlushInterval` command-line flag to VictoriaMetrics. This flag allows controlling the frequency of the ingested in-memory data flush to disk. For example, `-inmemoryDataFlushInterval=1h` instructs VictoriaMetrics to flush the in-memory data to disk only once per hour. This should significantly save flash write cycles on low-end flash devices.

VictoriaMetrics can flush in-memory data more frequently than the value specified at `-inmemoryDataFlushInterval` command-line flag if the ingested data overflows the limit for in-memory data. In this case the overflown in-memory data is flushed to disk.

The in-memory data is lost on unclean shutdown such as power off, OOM crash or `SIGKILL` signal. VictoriaMetrics persists the in-memory data to disk on graceful shutdown via `SIGINT` signal.

The in-memory data becomes available for querying in a second after the ingestion. This delay doesn't depend on the `-inmemoryDataFlushInterval` command-line flag value. Note that by default VictoriaMetrics doesn't query up to 30 seconds of recently ingested data, since this data may be incomplete yet. For example, if multiple clients ingest data into VictoriaMetrics every 30 seconds at random offsets, then `count(some_metric)` would return smaller than expected results during the recent 30 seconds. This delay can be controlled with the `-search.latencyOffset` command-line flag.

@thomas725 , could you build VictoriaMetrics from the commit 8189770c50165b62867327ad388f2c2ef237ab6f according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it reduces disk writes frequency when setting bigger values to `-inmemoryDataFlushInterval` command-line flag on your workload?

**Comment by valyala** [comment] 2022-12-11 11:33
The `-inmemoryDataFlushInterval` command-line flag is available starting from [VictoriaMetrics v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Closed by valyala** 2022-12-11 11:33 UTC
Labels: enhancement

**Comment by thomas725** [comment] 2022-12-15 17:14
I found a little extra time and since the feature has already been integrated in a release build it was super easy to upgrade my victoria-metrics-prod binary and add the switch into my service definition file, seems to work great! no disks writes to the sd card in the few minutes I've tested so far and the vmui still shows the data right away a few seconds after ingestion!

Thank you for this great feature, loving it!!!

**Comment by valyala** [comment] 2022-12-20 09:05
@thomas725 , thanks for the confirmation that the feature works as intended! Please note that it is recommended to upgrade to [v1.85.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since the previous releases contain [the issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3502), which can result in missing historical data in query responses.

**Comment by thomas725** [comment] 2022-12-22 00:00
Thanks for the hint, updated to v1.85.3 an hour ago :)

**Comment by valyala** [comment] 2023-02-11 20:13
It has been appeared that long background merges could lead to data ingestion slowdown and query performance degradation on systems with low number of available CPU cores (1 or 2). This issue has been addressed in the commit 3ec8a4dc80e650dbdad9a73b0cd9b78eb292a1bf , which will be included in the next release. The temporary workaround is to run single-node VictoriaMetrics (or `vmstorage` in cluster version) with the `GOMAXPROCS=3` environment variable.

**Comment by valyala** [comment] 2023-02-25 00:23
FYI, the fix for [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3337#issuecomment-1426867605) has been included in [VictoriaMetrics v1.87.2](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment] 2023-02-25 03:37
FYI, [the issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3337#issuecomment-1426867605) has been fixed also in [VictoriaMetrics v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html).
