### ISSUE TITLE
Display large numbers in full, not in exponential form.

### ISSUE THREAD

**Issue by vc43** [VictoriaMetrics/VictoriaMetrics#2418] opened 2022-04-07 15:05 UTC
Large numbers on vmui charts and in alerts are displayed in exponential form.
It would be nice to have an option that will display the numbers completely without shortening.

**Comment by tredondo** [comment] 2022-04-08 08:38
This is a dupe of #2409.

**Comment by hagen1778** [comment] 2022-04-11 18:07
Closed as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2409

**Closed by hagen1778** 2022-04-11 18:07 UTC
