### ISSUE TITLE
Regexp grouping does not work in v1.66.0

### ISSUE THREAD

**Issue by fredrik84** [VictoriaMetrics/VictoriaMetrics#1644] opened 2021-09-23 06:19 UTC
Describe the bug
Regexp grouping does not work. Works fine in v.1.65.0. This seems to be a connected PR [1610](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1610).

To Reproduce
Queries like `{__name__=~"(foo|bar)"}` does not work in v1.66.0. It produces zero results. 
Other regexp syntax however does like `{__name__=~"f.+"}`

Expected behavior
Regexp grouping works :)

**Comment by valyala** [comment] 2021-09-23 11:03
This also may be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1601

**Comment by valyala** [comment] 2021-09-23 11:09
I cannot reproduce the bug in v1.66.0 and v1.66.1  - the query `{__name__=~"up|scrape_duration_seconds"}` works as expected - it returns time series with `up` and `scrape_duration_seconds` names. @fredrik84 , could you provide more details for your case? E.g. the exact time series names and the exact query which doesn't return the expected results.

**Comment by fredrik84** [comment] 2021-09-23 11:54
`sum(ascent_over_time({__name__=~"deals_count_(Market1|Market2)"}[1i]))`
I have not tried v1.66.1, it was not the latest version when I pulled the container, I should mention I'm running standalone version.
Same query works if I replace `(Market1|Market2)` with `(.+)` (but then I cannot filter on specifics, there are more metrics named similarly). I did test some parts of it with just bare metric names (no functions) and it didn't work.

**Comment by fredrik84** [comment] 2021-09-23 12:30
Seems like the problem occurs when matching other labels in the query.
This query returns 0 results
`sum(ascent_over_time({__name__=~"deals_count_(Market1|Market2)", environment=~"prod"}[1i]))`
This however does
`sum(ascent_over_time({__name__=~"deals_count_(Market1|Market2)"}[1i]))`

Also each metric works when addressing them directly (or with `(.+)`)
`sum(ascent_over_time({__name__=~"deals_count_Market1", environment=~"prod"}[1i]))`

**Comment by fredrik84** [comment] 2021-09-23 12:52
This query works:
`sum by (market,environment) (ascent_over_time(label_replace({__name__=~"deals_count_(Market1|Market2)"}, 'market', '$1', '__name__', 'deals_count_(.+)')[1i]))`
and produces the results in the image below
![image](https://user-images.githubusercontent.com/5592150/134509361-b2d8ceb9-7079-4cda-9c25-5884f60a5e2a.png)

This query does not work either:
`sum by (market,environment) (ascent_over_time(label_replace({__name__=~"deals_count_(Market1|Market2)", environment=~'.+'}, 'market', '$1', '__name__', 'deals_count_(.+)')[1i]))`
Leaving environment label blank (`environment=''`) makes it work thou.

**Comment by valyala** [comment] 2021-09-23 18:51
Confirmed the issue. It should be fixed in the commit 718eca33ab62695248831f26a13efdc3d5d3d870 .
@fredrik84 , could you build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the issue is gone?

**Comment by valyala** [comment] 2021-09-23 20:53
@fredrik84 , could you verify whether the issue is fixed in [v1.66.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by fredrik84** [comment] 2021-09-23 21:33
Yes it is working as expected now :)

**Comment by valyala** [comment] 2021-09-23 22:37
Thanks for the confirmation! Then closing the issue as fixed.

**Closed by valyala** 2021-09-23 22:37 UTC
Labels: bug
