### ISSUE TITLE
vmagent couldn't send a block with size 13112 bytes

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#361] opened 2020-03-06 12:28 UTC
**Describe the bug**
Get error for send metric with remoteWrite protocol
2020-03-06T12:16:23.846Z	error	VictoriaMetrics/app/vmagent/remotewrite/client.go:243	couldn't send a block with size 13112 bytes to "http://127.0.0.1:2006": write tcp4 127.0.0.1:30208->127.0.0.1:2006: write: broken pipe; re-sending the block in 2.000 seconds

metrics still get stored and are available in grafana, but I would like to understand the reason for the error and whether it is possible to remove them ?

**To Reproduce**
telegraf with conf:
```
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8429"]

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.net]]
  interfaces = ["bond*", "e*", "vlan*"]

[[inputs.netstat]]

[[inputs.processes]]

[[inputs.system]]
```
vmagent:
`/vmagent-prod --remoteWrite.url=http://127.0.0.1:2006`

**Expected behavior**
no error in log

**Version**
```
docker image victoriametrics/vmagent:v1.34.2-cluster
```

**Comment by valyala** [comment] 2020-03-06 18:32
The `broken pipe` error means that `vmagent` connected to the provided `-remoteWrite.url=http://127.0.0.1:2006`, but the remote server unexpectedly closed the connection while `vmagent` was trying to push collected data to it. Make sure that VictoriaMetrics or other remote storage runs at `http://127.0.0.1:2006` and it properly accepts Prometheus `remote_write` data. Look into logs for the remote server at `127.0.0.1:2006` in order to detect the root cause of the issue. I suspect that it doesn't accept `remote_write` requests at this endpoint. Probably, you forgot adding `/api/v1/write` suffix to the `-remoteWrite.url`.

**Comment by ihard** [comment] 2020-03-11 23:24
I use carbon-clickhouse to receive metrics, this connector also uses prometheus to send metrics, and there are no errors when sending metrics.
Metrics from vmagent reach clickhouse and are visible in grafana.
Is it possible to configure the minimum package size for sending metrics from vmagent ?

**Comment by valyala** [comment] 2020-03-13 22:43
> Is it possible to configure the minimum package size for sending metrics from vmagent ?

Yes - see `-remoteWrite.maxBlockSize` command-line flag in `vmagent`. The list of supported command-line flags with descriptions is available when passing `-help` to `vmagent`:
```
./vmagent -help
vmagent-20200313-224233-heads-master-0-g9d45022d
Usage of bin/vmagent:
  -allowMissingConfig
    	Don't terminate the app if the ini file cannot be read.
  -allowUnknownFlags
    	Don't terminate the app if ini file contains unknown flags.
  -authDBHost string
    	Hostname where postgres database is set up (default "localhost")
  -authDBName string
    	Postgres database name to connect to (default "vmetrics")
  -authDBPassword string
    	User password to access database (default "neex7yoiNaiY6bah")
  -authDBUser string
    	Postgres user name to connect with (default "vmreadonly")
  -authDisabled
    	Disable authToken verification if set to true. This mode is useful for a single-user setup without vmadmin and postgres
  -config string
    	Path to ini config for using in go flags. May be relative to the current executable path.
  -configUpdateInterval duration
    	Update interval for re-reading config file set via -config flag. Zero disables config file re-reading.
  -dumpflags
    	Dumps values for all flags defined in the app into stdout in ini-compatible syntax and terminates the app.
  -enableTCP6
    	Whether to enable IPv6 for listening and dialing. By default only IPv4 TCP is used
  -fs.disableMmap
    	Whether to use pread() instead of mmap() for reading data files
  -graphiteListenAddr string
    	TCP and UDP address to listen for Graphite plaintext data. Usually :2003 must be set. Doesn't work if empty
  -http.disableResponseCompression
    	Disable compression of HTTP responses for saving CPU resources. By default compression is enabled to save network bandwidth
  -httpListenAddr string
    	TCP address to listen for http connections. Set this flag to empty value in order to disable listening on any port. This mode may be useful for running multiple vmagent instances on the same server. Note that /targets and /metrics pages aren't available if -httpListenAddr='' (default ":8429")
  -httpServerMetricsAuthKey string
    	Auth key for /metrics access
  -httpServerPprofAuthKey string
    	Auth key for /pprof access
  -httpServerRedirectToHTTPS
    	Whether to redirect to https
  -import.maxLineLen int
    	The maximum length in bytes of a single line accepted by /api/v1/import (default 104857600)
  -influxListenAddr string
    	TCP and UDP address to listen for Influx line protocol data. Usually :8189 must be set. Doesn't work if empty
  -influxMeasurementFieldSeparator string
    	Separator for '{measurement}{separator}{field_name}' metric name when inserted via Influx line protocol (default "_")
  -influxSkipSingleField
    	Uses '{measurement}' instead of '{measurement}{separator}{field_name}' for metic name if Influx line contains only a single field
  -insert.maxQueueDuration duration
    	The maximum duration for waiting in the queue for insert requests due to -maxConcurrentInserts (default 1m0s)
  -loggerLevel string
    	Minimum level of errors to log. Possible values: INFO, ERROR, FATAL, PANIC (default "INFO")
  -loggerOutput string
    	Output for the logs. Supported values: stderr, stdout (default "stderr")
  -loggerStackDriverProjectID string
    	If non-empty, send a copy of logs to stackdriver using the given CGP project ID
  -maxConcurrentInserts int
    	The maximum number of concurrent inserts; see also -insert.maxQueueDuration (default 16)
  -maxInsertRequestSize int
    	The maximum size in bytes of a single Prometheus remote_write API request (default 33554432)
  -memory.allowedPercent float
    	Allowed percent of system memory VictoriaMetrics caches may occupy (default 60)
  -opentsdbHTTPListenAddr string
    	TCP address to listen for OpentTSDB HTTP put requests. Usually :4242 must be set. Doesn't work if empty
  -opentsdbListenAddr string
    	TCP and UDP address to listen for OpentTSDB metrics. Telnet put messages and HTTP /api/put messages are simultaneously served on TCP port. Usually :4242 must be set. Doesn't work if empty
  -opentsdbhttp.maxInsertRequestSize int
    	The maximum size of OpenTSDB HTTP put request (default 33554432)
  -promscrape.config string
    	Optional path to Prometheus config file with 'scrape_configs' section containing targets to scrape. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config for details
  -promscrape.disableCompression
    	Whether to disable sending 'Accept-Encoding: gzip' request headers to scrape targets. This may reduce CPU usage on scrape targets at the cost of higher network bandwidth utilization
  -promscrape.fileSDCheckInterval duration
    	Interval for checking for changes in 'file_sd_config'. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config (default 1m0s)
  -promscrape.maxScrapeSize int
    	The maximum size of scrape response in bytes to process from Prometheus targets. Bigger responses are rejected (default 16777216)
  -remoteWrite.basicAuth.password string
    	Optional basic auth password to use for -remoteWrite.url
  -remoteWrite.basicAuth.username string
    	Optional basic auth username to use for -remoteWrite.url
  -remoteWrite.bearerToken string
    	Optional bearer auth token to use for -remoteWrite.url
  -remoteWrite.flushInterval duration
    	Interval for flushing the data to remote storage. Higher value reduces network bandwidth usage at the cost of delayed push of scraped data to remote storage (default 1s)
  -remoteWrite.label value
    	Optional label in the form 'name=value' to add to all the metrics before sending them to -remoteWrite.url. Pass multiple -remoteWrite.label flags in order to add multiple flags to metrics before sending them to remote storage
  -remoteWrite.maxBlockSize int
    	The maximum size in bytes of unpacked request to send to remote storage. It shouldn't exceed -maxInsertRequestSize from VictoriaMetrics (default 33554432)
  -remoteWrite.maxDiskUsagePerURL int
    	The maximum file-based buffer size in bytes at -remoteWrite.tmpDataPath for each -remoteWrite.url. When buffer size reaches the configured maximum, then old data is dropped when adding new data to the buffer. Buffered data is stored in ~500MB chunks, so the minimum practical value for this flag is 500000000. Disk usage is unlimited if the value is set to 0
  -remoteWrite.queues int
    	The number of concurrent queues to each -remoteWrite.url. Set more queues if a single queue isn't enough for sending high volume of collected data to remote storage (default 1)
  -remoteWrite.relabelConfig string
    	Optional path to file with relabel_config entries. These entries are applied to all the metrics before sending them to -remoteWrite.url. See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config for details
  -remoteWrite.sendTimeout duration
    	Timeout for sending a single block of data to -remoteWrite.url (default 1m0s)
  -remoteWrite.showURL
    	Whether to show -remoteWrite.url in the exported metrics. It is hidden by default, since it can contain sensistive auth info
  -remoteWrite.tlsCAFile string
    	Optional path to TLS CA file to use for verifying connections to -remoteWrite.url. By default system CA is used
  -remoteWrite.tlsCertFile string
    	Optional path to client-side TLS certificate file to use when connecting to -remoteWrite.url
  -remoteWrite.tlsInsecureSkipVerify
    	Whether to skip tls verification when connecting to -remoteWrite.url
  -remoteWrite.tlsKeyFile string
    	Optional path to client-side TLS certificate key to use when connecting to -remoteWrite.url
  -remoteWrite.tmpDataPath string
    	Path to directory where temporary data for remote write component is stored (default "vmagent-remotewrite-data")
  -remoteWrite.url value
    	Remote storage URL to write data to. It must support Prometheus remote_write API. It is recommended using VictoriaMetrics as remote storage. Example url: http://<victoriametrics-host>:8428/api/v1/write . Pass multiple -remoteWrite.url flags in order to write data concurrently to multiple remote storage systems
  -remoteWrite.urlRelabelConfig value
    	Optional path to relabel config for the corresponding -remoteWrite.url
  -version
    	Show VictoriaMetrics version
```

**Comment by valyala** [comment] 2020-09-11 23:23
@ihard , are there any updates on this issue from your side?

**Comment by valyala** [comment] 2020-09-29 20:20
Closing the issue as resolved. @ihard , feel free re-opening it if you have additional questions / details regarding the issue.

**Closed by valyala** 2020-09-29 20:20 UTC
Labels: question
