### ISSUE TITLE
limit_offset always returns metrics regardless of the value of the offset

### ISSUE THREAD

**Issue by ShadyStego** [VictoriaMetrics/VictoriaMetrics#3312] opened 2022-11-04 00:32 UTC
**Describe the bug**
When I used [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) with offset value > total number of metrics, I will still get the last N values where N is the limit value. 

**To Reproduce**
Simply use `limit_offset` against any metric & group by. Use a big value that exceeds the number of metrics that you expect to return. 

**Expected behavior**
Return no data, which is the same behavior as SQL when using `OFFSET`.

**Comment by valyala** [comment] 2022-11-21 14:49
@ShadyStego , thanks for filing the bugreport! The issue should be fixed in the commit 2c9e403d5f4617c1710709c4a9198b92d415f256 . This commit will be included in the next release of VictoriaMetrics. In the mean time you can build VictoriaMetrics itself from this commit according to [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the fix works as intended.

**Comment by valyala** [comment] 2022-11-26 06:51
[VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) should properly return an empty result from [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function if `offset` arg equals to or exceeds the number of time series passed to the function. Closing this issue as fixed.

**Closed by valyala** 2022-11-26 06:51 UTC
Labels: bug, metricsql
