### ISSUE TITLE
VM gets panic crashes on queries containing "histogram_quantiles("quantile", phi0.1, ..... )"

### ISSUE THREAD

**Issue by mvanyushkin** [VictoriaMetrics/VictoriaMetrics#3026] opened 2022-08-26 11:29 UTC
**Describe the bug**
Hey folks! We use VM in our production for the long time!
It's a great product, perfectly scalable for the high throughput and we can proudly say it's one of the most reliable part in our infrastructure. 
But, we've faced with some weird behaviour of our VM instance today.
Suddenly, the app has started crashing.
Having done a troubleshooting session we've figured out, that there is a kind of queries capable to crash the VM process at all.
We haven't tried yet to update to the latest version yet, but we did some research and found out that the module throwing a panic error hasn't been significantly changed in last releases. 
Actually, the file app/vmselect/promql/transform.go and transformHistogramQuantiles() looks pretty similar in v.1.68.0 and in 1.8.0.
At least the Phi arg parsing uses the same way.

`phiStr := fmt.Sprintf("%g", phiArg[0].Values[0])`

According to the docs https://docs.victoriametrics.com/MetricsQL.html#histogram_quantiles the value should be specified in the range of 0...1, so using 0.5 doesn't seem to be wrong.

**To Reproduce**
The issue can be reproduced by the query like this

`pql histogram_quantiles("quantile", phi0.5, sum(irate(dummy_metric{}[1m])) by (quantile))`

**Expected behavior**
It'd be good to have a validation error or proper queries handling, at least the process should be resilient for the wrong input.

**Logs**

> 
> my-awesome-host victoria-metrics[38559]: panic: runtime error: index out of range [0] with length 0
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:222 +0x65
> my-awesome-host victoria-metrics[38559]: panic({0xa91220, 0xcc1a95bba8})
> my-awesome-host victoria-metrics[38559]:         runtime/panic.go:1038 +0x215 my-awesome-host victoria-metrics[38559]: goroutine 476599929161 [running]:
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.transformHistogramQuantiles(0xcbd0418f60)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/transform.go:816 +0x966
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.evalExpr(0xc93d1e7f40, {0xcf0580, 0xcbd849b590})
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/eval.go:220 +0xe26
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.Exec(0xc93d1e7f40, {0xcbbabc9dd0, 0x8c}, 0x0)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql/exec.go:43 +0x23e
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.queryRangeHandler({0x9f, 0x1, 0x1073320}, {0xcf7140, 0xcbd3d5f5e0}, {0xcbbabc9dd0, 0x
> 6c204a71d035b8}, 0x182d5c988f8, 0x182d5d74498, 0x3a98, ...)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus/prometheus.go:1151 +0x530
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.QueryRangeHandler({0xcf7140, 0xcbd3d5f5e0, 0x1073320}, {0xcf7140, 0xcbd3d5f5e0}, 0x1)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus/prometheus.go:1112 +0x2f8
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect.RequestHandler({0xcf7140, 0xcbd3d5f5e0}, 0xcbd3d57800)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/main.go:220 +0x21ad
> my-awesome-host victoria-metrics[38559]: main.requestHandler({0xcf7140, 0xcbd3d5f5e0}, 0xcbd3d57800)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics/main.go:108 +0x1a8
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc401c6c3c0, {0xcf7140, 0xcbd3d5f5e0}, 0xcbd3d57800, 0xc5a578)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:302 +0xb57
> my-awesome-host victoria-metrics[38559]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xcf7140, 0xcbd3d5f5e0}, 0x10000c8ce512f70)
> my-awesome-host victoria-metrics[38559]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:190 +0x76
> my-awesome-host victoria-metrics[38559]: net/http.HandlerFunc.ServeHTTP(0xcb9a72ec98, {0xcf7140, 0xcbd3d5f5e0}, 0x466aee)
> my-awesome-host victoria-metrics[38559]:         net/http/server.go:2046 +0x2f
> my-awesome-host victoria-metrics[38559]: net/http.serverHandler.ServeHTTP({0xc92b1e4330}, {0xcf7140, 0xcbd3d5f5e0}, 0xcbd3d57800)
> my-awesome-host victoria-metrics[38559]:         net/http/server.go:2878 +0x43b
> my-awesome-host victoria-metrics[38559]: net/http.(*conn).serve(0xc845262460, {0xcfd140, 0xcfd6d277d0})
> my-awesome-host victoria-metrics[38559]:         net/http/server.go:1929 +0xb08
> my-awesome-host victoria-metrics[38559]: created by net/http.(*Server).Serve
> my-awesome-host victoria-metrics[38559]:         net/http/server.go:3033 +0x4e8

**Version**
v1.68.0

**Comment by valyala** [comment] 2022-08-26 22:41
@mvanyushkin , thanks for the detailed bug report! The issue is confirmed and should be fixed in the following commits:

- Single-node VictoriaMetrics - ad11b8d83d910068b37bfbf96b212f4ead12806d
- Cluster version of VictoriaMetrics - 8aaaf221ccd118468ddd43ba9d625bfffa32d03c

These commits will be included in the next release of VictoriaMetrics. In the meantime you can build VictoriaMetrics from these commit according to the following instructions and check whether the issue is fixed:

* [How to build single-node VictoriaMetrics from sources](https://docs.victoriametrics.com/#how-to-build-from-sources)
* [How to build cluster components of VictoriaMetrics from sources](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources)

**Comment by valyala** [comment] 2022-08-30 22:02
VictoriaMetrics should properly handle invalid args passed to [histogram_quantiles](https://docs.victoriametrics.com/MetricsQL.html#histogram_quantiles) starting from [v1.79.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.3).

**Comment by valyala** [comment] 2022-08-31 01:31
The panic at `histogram_quantiles()` should be fixed starting from [VictoriaMetrics v1.81.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed then.

**Closed by valyala** 2022-08-31 01:31 UTC
Labels: bug, metricsql
