### ISSUE TITLE
count_over_time and other aggregation functions returns wrong result for subquery range vector

### ISSUE THREAD

**Issue by maksimr** [VictoriaMetrics/VictoriaMetrics#5452] opened 2023-12-11 18:09 UTC
### Describe the bug

Subquery return range vector with 3 samples if apply `count_over_time` it returns only 2 samples, discarding last sample. The same result for other agg. functions like `sum_over_time` etc

### To Reproduce

1. Create a service which returns metrics

```javascript
require('http').createServer(function(req, res) {
  if (req.url === '/metrics') {
    const metricName = 'foo';
    const metricType = 'gauge';
    const metricValue = new Date().getSeconds();
    const metricTimestamp = new Date().getTime();
    console.log(`(${metricValue},${metricTimestamp / 1000})`);
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    res.write(`# TYPE ${metricName} ${metricType}\n`);
    res.end(`${metricName} ${metricValue} ${metricTimestamp}\n`);
    return;
  }
  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('Not found\n');
}).listen(3000, () => console.log(new Date(), 'Listening on port 3000'));
```

2. Add prometheus.yaml
```yaml
global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'test'
    scrape_interval: 1s
    honor_timestamps: true
    static_configs:
      - targets: ['localhost:3000']
```

3. Run service `node ./index.js`
4. Run victoria metrics
```bash
./victoria-metrics-prod -promscrape.config=./prometheus.yml
```
5. Open `http://localhost:8428/vmui`
6. Type query `foo[2s:1s]` - this should return 3 samples
7. Type query `count_over_time(foo[2s:1s])` for the same evaluation timestamp

ER: 3
AR: 2

### Version

victoria-metrics-20231116-193603-tags-v1.95.1-0-g354563393

### Screenshots

<img width="1440" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/616193/d4f7bf98-6f04-4d99-bc3c-1e7f484a06fa">
<img width="1427" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/616193/6a412b2b-d59c-4052-ab82-dfdcf9c92b4e">

**Comment by zekker6** [comment] 2023-12-14 15:30
Hello @maksimr 

The difference in results is caused by setting lookbehind window and step values for the first query, but setting the same values only for internavl query for the second one.
In order to get matching responses it is needed to update the second query to: `count_over_time(foo[2s:1s])[2s:1s]`

With the given queries the result is:
```
[
  {
    "metric": {
      "__name__": "foo",
      "instance": "localhost:3002",
      "job": "test",
      "monitor": "codelab-monitor"
    },
    "values": [
      [
        1702562707,
        "6"
      ],
      [
        1702562708,
        "7"
      ],
      [
        1702562709,
        "8"
      ]
    ],
    "group": 1
  },
  {
    "metric": {
      "instance": "localhost:3002",
      "job": "test",
      "monitor": "codelab-monitor"
    },
    "values": [
      [
        1702562707,
        "2"
      ],
      [
        1702562708,
        "2"
      ],
      [
        1702562709,
        "2"
      ]
    ],
    "group": 2
  }
]
```

**Comment by zekker6** [comment] 2024-10-03 20:31
Closing as an original question have been answered. Feel free to reopen if additional questions will arise.

**Closed by zekker6** 2024-10-03 20:31 UTC
Labels: question
