### ISSUE TITLE
Crashing and restarting vm does not work (flock error)

### ISSUE THREAD

**Issue by blmhemu** [VictoriaMetrics/VictoriaMetrics#3578] opened 2023-01-02 16:33 UTC
**DIsclaimer**
I am not sure if it is a bug or a feature request or a simple question :(

**Describe the bug**
Here is the scenario: Setup and run vm. Crash it  / force kill it / plug power off. Rerun vm with same data folder.
I get `cannot access resource flock.lock`
Is there a work-around or it is to be fixed ?

**Expected behavior**
I tried with a single vm setup btw.
A force restart / kill and start should work fine. A temporary system crash should not make vm unusuable.

**Logs**
```
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: victoria-metrics-20221220-225921-tags-v1.85.3-0-gf443fad56
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":24407"
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -promscrape.config="/etc/prometheus/prometheus.yml"
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="1"
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -selfScrapeInterval="30s"
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/data"
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/app/victoria-metrics/main.go:58	starting VictoriaMetrics at ":24407"...
2023-01-02T15:56:53.296Z	info	VictoriaMetrics/app/vmstorage/main.go:114	opening storage at "/data" with -retentionPeriod=1
2023-01-02T15:56:53.306Z	fatal	VictoriaMetrics/app/vmstorage/main.go:119	cannot open a storage at /data with -retentionPeriod=1: cannot acquire lock on file "/data/flock.lock": resource temporarily unavailable
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: victoria-metrics-20221220-225921-tags-v1.85.3-0-gf443fad56
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":24407"
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -promscrape.config="/etc/prometheus/prometheus.yml"
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -retentionPeriod="1"
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -selfScrapeInterval="30s"
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageDataPath="/data"
2023-01-02T16:02:32.696Z	info	VictoriaMetrics/app/victoria-metrics/main.go:58	starting VictoriaMetrics at ":24407"...
2023-01-02T16:02:32.697Z	info	VictoriaMetrics/app/vmstorage/main.go:114	opening storage at "/data" with -retentionPeriod=1
2023-01-02T16:02:32.708Z	fatal	VictoriaMetrics/app/vmstorage/main.go:119	cannot open a storage at /data with -retentionPeriod=1: cannot acquire lock on file "/data/flock.lock": resource temporarily unavailable
```

**Version**
1.85.3

**Used command-line flags**
Shown in above logs.

**Comment by hagen1778** [comment] 2023-01-03 10:14
> I get cannot access resource flock.lock
Is there a work-around or it is to be fixed ?

You can delete it manually and try starting the process again.

The file `flock.lock` is created when vmstorage process starts. And is deleted when the process stops.
When process starts it checks whether `flock.lock` exists. If it doesn't process creates new `flock.lock and then starts. If file already exists - process won't start and will log an error.

It is needed to protect data folder from the accidental launching of more than 1 vmstorage process. Because if there are more than 1 vmstorage using the same data folder - data corruption is inevitable.

**Comment by blmhemu** [comment] 2023-01-03 12:09
> You can delete it manually and try starting the process again.

There seem to be multiple flock.lock files in different directories. Should I delete them all ? Also, I am thinking of the possibility of lock expirations. Some kind of timeout after which lock can be forcefully removed.

**Comment by valyala** [comment] 2023-01-06 02:45
> The file flock.lock is created when vmstorage process starts. And is deleted when the process stops.
When process starts it checks whether flock.lock exists. If it doesn't process creates new `flock.lock and then starts. If file already exists - process won't start and will log an error.

The `flock.lock` file isn't deleted when the process stops. VictoriaMetrics tries acquiring [an exclusive lock](https://linux.die.net/man/2/flock) on the `flock.lock` file at startup in order to make sure that no other VictoriaMetrics instances use the same data.

> There seem to be multiple flock.lock files in different directories. Should I delete them all ? 

There is no need in deleting the `flock.lock` files in general case. If these files aren't locked by another VictoriaMetrics instances, then the VictoriaMetrics (or `vmstorage`) should successfully acquire locks on all these files during startup. If it cannot acquire locks, this means that there are other VictoriaMetrics (or `vmstorage`) instances running, which use the same data directory passed via `-storageDataPath` command-line flag. The proper solution is to make sure that every VictoriaMetrics instance (or `vmstorage` instance) exclusively stores data to its' own `-storageDataPath` directory.

> Also, I am thinking of the possibility of lock expirations. Some kind of timeout after which lock can be forcefully removed. (Restic, a popular open source backup tool does this.)

As I know, the lock on the file should be automatically released when the process, which acquired the look, shuts down - see [flock docs](https://linux.die.net/man/2/flock). Probably, some environments / filesystems can violate this property. In this case the `flock.lock` files must be removed manually. Please note that if some process holds the `flock.lock` file and you remove it manually, then another instance of VictoriaMetrics (or `vmstorage`) will successfully create a new `flock.lock` file and start working with the data stored in the `-storageDataPath`. If another process also continues working with the same data, then this may lead to inconsistent data state and/or to data loss.

**Comment by blmhemu** [comment] 2023-01-08 14:16
Hey ! From the man page
> flock() does not lock files over NFS. Use [fcntl](https://linux.die.net/man/2/fcntl)(2) instead: that does work over NFS, given a sufficiently recent version of Linux and a server which supports locking.

I am using NFS. Could this be a / the reason ?

**Comment by valyala** [comment] 2023-01-21 02:01
> I am using NFS. Could this be a / the reason ?

Probably. @dmitryk-dk  , could you try reproducing this issue on NFS disk?

**Comment by dmitryk-dk** [comment] 2023-01-23 14:46
Hi @blmhemu ! I have made some synthetic tests. I will describe how I prepared the environment and what I got.
Maybe you can share your setup, and we can try to reproduce this problem. Or you find some miss-configuration from my test.

So:
1. Setup gcloud instance
```gcloud compute instances create nfs-server --boot-disk-size=30GB --image=ubuntu-2004-focal-v20230113 --image-project=ubuntu-os-cloud --machine-type=f1-micro --tags=nfs```

2. went inside instance
```gcloud compute ssh nfs-server```

3. Installed nfs-server
```sudo apt install -y nfs-kernel-server```

4. Created share directory 
```sudo mkdir /share
sudo chown nobody:nogroup /share
sudo chmod 777 /share
```
5. Added share directory  to nfs exports
```sudo vim /etc/exports```
```/share *(rw,sync,no_subtree_check)```

6. Restarts nfs server
```sudo systemctl restart nfs-kernel-server```

7. Confirmed that the directory is shared
```sudo exportfs``` 

8. Exited from the instance
```exit```

9. Added firewall rules
```gcloud compute firewall-rules create nfs --allow=tcp:111,udp:111,tcp:2049,udp:2049 --target-tags=nfs```

10. Mounted created folder
```
NFS_SERVER_IP=$(gcloud compute instances describe nfs-server \
--format='get(networkInterfaces[0].accessConfigs[0].natIP)')

mkdir ~/test_mount

sudo mount -t nfs -o vers=4 -o resvport \
$NFS_SERVER_IP:/share ~/test_mount
```
<img width="550" alt="Screenshot 2023-01-23 at 16 11 40" src="https://user-images.githubusercontent.com/12189570/214060687-4c18b9ca-9c8b-42e7-a74a-f02e586087a8.png">

After that, I used our single setup via docker [deployment](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker)

I have changed only one line in the setup 
<img width="534" alt="Screenshot 2023-01-23 at 16 09 52" src="https://user-images.githubusercontent.com/12189570/214060304-ad0eb163-cc9a-4e8e-9281-1a34aae3f3e9.png">

On my local machine, from the root of the repository, I have run `make docker-single-up`.

After that i used ```docker kill --signal=SIGKILL <container_id>```. 
And ```docker start <container_id>```

I have tested it several times but can't reproduce the issue.
<img width="449" alt="Screenshot 2023-01-23 at 16 14 34" src="https://user-images.githubusercontent.com/12189570/214061338-1a783fef-3d89-4f1e-bfa1-7abdc55e58fe.png">

<img width="458" alt="Screenshot 2023-01-23 at 16 15 01" src="https://user-images.githubusercontent.com/12189570/214061442-941e0b9a-4e09-423b-88b4-333b27d6f4ff.png">

Also, we have checked your logs, and we found that your service was unavailable
```cannot acquire lock on file "/data/flock.lock": resource temporarily unavailable```

That can be related to https://lists.debian.org/debian-user/2016/08/msg00022.html

**Comment by blmhemu** [comment] 2023-01-25 04:44
Hi @dmitryk-dk ! My setup was pretty similar to your, but I see a few differences:
* I use [CSI](https://gitlab.com/rocketduck/csi-plugin-nfs) for NFS mounts (as vm is run by nomad)
* I used async option to mount the nfs vol
* As I use bare metal, it was a poweroff, I am assuming `docker kill --signal=SIGKILL <container_id>` simulate that more or less.

**Comment by dmitryk-dk** [comment] 2023-01-26 10:38
Hi @blmhemu ! 
What do you mean 
> but the prev data is being shown correctly.
?
`flock()` just only apply or remove an advisory lock on an open file
if you remove flock.lock file then VM can correctly read all files from folder.

**Comment by blmhemu** [comment] 2023-01-26 10:56
By `but the prev data is being shown correctly.` I meant that vm was able to read from NFS mount after flock is removed. As you mentioned `That can be related to https://lists.debian.org/debian-user/2016/08/msg00022.html` Do not take much notice of it :)

**Comment by dmitryk-dk** [comment] 2023-01-26 11:16
@blmhemu ! Can you do some tests on your system, because I haven't any bare metal installation? 
Crash the VM, and check that the flock.lock present, start the VM if it shows the error, and check does some process keeps reading that file. I have only one guess. Because in other cases, Vm should remove this file as expected.

**Comment by blmhemu** [comment] 2023-01-26 11:30
Hey ! I nuked my prev setup and am rebuilding it atm. Will post here once I can run the test.

**Comment by dmitryk-dk** [comment] 2023-01-27 12:33
Hi @blmhemu ! So I made another synthetic test:
1. I deployed the instance as I described before
2. Shared folder 
3. Started first VM process 
```
./victoria-metrics -search.latencyOffset=10s -search.maxUniqueTimeseries=5000000 -retentionPeriod=100y -search.maxSamplesPerSeries=5000000 --storageDataPath=~/test_mount --httpListenAddr=:8430
```
4. After when the first VM starts successfully, run the second VM
```
./victoria-metrics -search.latencyOffset=10s -search.maxUniqueTimeseries=5000000 -retentionPeriod=100y -search.maxSamplesPerSeries=5000000 --storageDataPath=~/test_mount --httpListenAddr=:8431
```
And I got the error that you described.
```
2023-01-27T12:05:29.071Z        fatal   app/vmstorage/main.go:119       cannot open a storage at ~/test_mount with -retentionPeriod=100y: cannot create lock file in "~/test_mount"; make sure the dir isn't used by other processes or manually delete the file if you recover from abrupt VictoriaMetrics crash; error: cannot acquire lock on file "~/test_mount/flock.lock": resource temporarily unavailable
```
So when you start your process, another VM process is not yet finished. Or when you try to start the VM, both processes try to get access to same folder

**Comment by blmhemu** [comment] 2023-01-27 17:01
I just had my aha moment. As I am using an orchestrator to manage vm, I think something funny might be happening if a node crashes and come back online. Let's close this issue for now. I will inspect the scheduling behaviour before I present more info.

**Comment by dmitryk-dk** [comment] 2023-01-27 18:15
Thank you for the information. I closed it as resolved. Feel free to reopen if you find something unexpected.

**Closed by dmitryk-dk** 2023-01-27 18:15 UTC
Labels: bug
