### ISSUE TITLE
export API - JSON line format - invalid number +Inf

### ISSUE THREAD

**Issue by nikitapecasa** [VictoriaMetrics/VictoriaMetrics#3161] opened 2022-09-26 09:14 UTC
**Describe the bug**
[Export API JSON](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) response contains invalid number value `+Inf`, which is not supported by JSON or JSON5 specifications (JSON5 [supports](https://spec.json5.org/#numbers) `NaN`/`Infinity` values).

**To Reproduce**
- Ingest samples with `+Inf` values
- `api/v1/export -d 'match[]=metric_with_inf_values'`
- JSON response would contain invalid value `"values":[+Inf]`

Please note that https://github.com/valyala/fastjson most probably supports such values,
also `jq` utility converts `+Inf` value to `1.7976931348623157e+308`.

**Expected behavior**
JSON response should contain valid JSON lines.
Somehow related bugfix where staleness markers are exported as `null` instead of `NaN` - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2518.

But tbh I'm not sure if it would be correct to replace `+Inf`/`-Inf` values with `null`,
I don't know what are the use cases for such values (never used them explicitly or even heard of someone using them),
however they are legal values in Prometheus and can be returned by functions like `ln`/`predict_linear`/`histogram_quantile`, and IIUC can be stored as sample values via recording rules, which is then can be imported to VM via prometheus' remote write (please correct me if I'm wrong).

When querying the same data in Prometheus or VictoriaMetrics using UI or APIs (`api/v1/query`, `api/v1/query_range`)
[quoted JSON strings are used rather than raw numbers.](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-query-result-formats) - `"+Inf"` - which makes a valid JSON response.

**Version**
v1.76.0

**Comment by hagen1778** [comment] 2022-09-29 09:02
@dmitryk-dk are you interested in implementing support for Inf's?

**Comment by dmitryk-dk** [comment] 2022-09-29 09:02
Yes).I will take a look

> @dmitryk-dk are you interested in implementing support for Inf's?

**Comment by dmitryk-dk** [comment] 2022-09-29 11:14
Hi @nikitapecasa ! There is one interesting thing with JSON. We export values as an array. In JSON specification [array](https://spec.json5.org/#arrays) can contain only 
[JSON5Null](https://spec.json5.org/#prod-JSON5Null)
[JSON5Boolean](https://spec.json5.org/#prod-JSON5Boolean)
[JSON5String](https://spec.json5.org/#prod-JSON5String)
[JSON5Number](https://spec.json5.org/#prod-JSON5Number)
[JSON5Object](https://spec.json5.org/#prod-JSON5Object)
[JSON5Array](https://spec.json5.org/#prod-JSON5Array)

In our case, it would be valued with 
[JSON5String](https://spec.json5.org/#prod-JSON5String)
[JSON5Number](https://spec.json5.org/#prod-JSON5Number)

Where JSON5String will be presented as "Infinity", "-Infinity", "NaN". 
We can't represent these values such as literals like `Infinity`, `-Infinity`, `NaN`.
Because specification of JSON has these restrictions.

Would it be helpful for you?

**Comment by nikitapecasa** [comment] 2022-09-29 14:13
@dmitryk-dk Hi, thanks for such a prompt reply :)

I understand that representing values as `[Infinity, -Infinity, NaN]` might not be an option here
as it violates [JSON specification](https://www.json.org/) (please note that those values are allowed in [JSON5 spec](https://spec.json5.org/).
At the same time current implementation also violates JSON spec, as it produces value like `+Inf` which is not supported by both specs JSON and JSON5.
Representing values as [quoted JSON strings are used rather than raw numbers](https://prometheus.io/docs/prometheus/latest/querying/api/#expression-query-result-formats) might be a good idea, and that's what happening in Prometheus and VictoriaMetrics query APIs.
But I don't have enough experience/knowledge of VictoriaMetrics export API and it's usage to say that it would be a safe breaking change, because value type is going to change from Number to String (which is totally fine in my use case btw).

So as potential solution such change could be introduced with a feature toggle to preserve old/current behaviour by default, feature toggle could be implemented via startup config or url param `api/v1/export?stringify_values=1`,
what do you think?

I'm parsing the JSON using different JSON parsing libs in different applications, nothing special there to be honest, it's just that some JSON parsing libs are very strict and return an error when illegal value is used (e.g. `NaN` for JSON, or `+Inf` for JSON and JSON5 specs)

**Comment by valyala** [comment] 2022-10-06 12:00
The commit ec04fcac938245e003477e1ab37da2bf070e124c exports `inf` numbers as `"Infinity"` strings via [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format). This allows parsing the returned result with standard JSON parsers. Note that the application, which consumes the returned result, must iterate over the returned values and properly convert `"Infinity"` and `"-Infinity"` strings into the corresponding `Infinity` and `-Infinity` numbers before further processing of the received data.

The commit also adds proper parsing for `"Infinity"` and `"-Infinity"` strings at [/api/v1/import](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format).

This commit will be included in the next release. In the meantime it is possible to build VictoriaMetrics from this commit according to [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it works as intended.

**Comment by valyala** [comment] 2022-10-07 02:29
VictoriaMetrics should export `Inf` numbers as `"Infinity"` strings at [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) endpoint starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See more details in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3161#issuecomment-1269905606).

Closing the issue as fixed.

**Closed by valyala** 2022-10-07 02:29 UTC
Labels: enhancement
