### ISSUE TITLE
VMUI turn off dashboard `PER-JOB RESOURCE USAGE`

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#3740] opened 2023-02-01 15:40 UTC
### Describe the solution you'd like

It would be nice if VM select had functionality to disable default dasboard when i'm using my own
For example, i'm using my own dashboard `vmui.customDashboardsPath: /vm-dashboard/` but default `PER-JOB RESOURCE USAGE` is still showing up, please, take a look screenshoot bellow
![image](https://user-images.githubusercontent.com/70581130/216089384-3a379b9e-e5e6-4915-a272-4fda4cf9e373.png)

**Comment by valyala** [comment] 2023-02-10 00:18
The `PER-JOB RESOURCE USAGE` dashboard should be hidden if `-vmui.customDashboardsPath` points to a directory with custom dashboards starting from [v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as resolved.

@yuriydzobak , feel free re-opening this issue or creating the linked one if the issue isn't resolved yet in some ways.

**Closed by valyala** 2023-02-10 00:18 UTC
Labels: enhancement, vmui
