### ISSUE TITLE
vmselect panic cause cannot unmarshal blockHeader: too big RowsCount

### ISSUE THREAD

**Issue by jingb** [VictoriaMetrics/VictoriaMetrics#4754] opened 2023-08-01 07:33 UTC
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

i was doing an performance benchmark about vm cluster. 
2 instance of vmselect, 2 instance of vminsert and 5 instance.  here are some configuration.  
```
docker run -d --name vmselect \
--cpus="30" --memory="90G" \
--network host \
--entrypoint=/vmselect-prod \
victoriametrics/vmselect:v1.91.0-cluster \
--storageNode=ipaddress1:8401 ……  
-search.maxUniqueTimeseries=2000000 \
-search.maxQueryDuration=300s \
-dedup.minScrapeInterval=10s 

docker run -d --name vmstorage \
--cpus="30" --memory="90G" \
--network host \
--entrypoint=/vmstorage-prod \
-v /home/service/var/data2/vmstorage:/home/vmstorage \
victoriametrics/vmstorage:v1.91.0-cluster \
-retentionPeriod=90d --storageDataPath=/home/vmstorage -dedup.minScrapeInterval=10s

docker run -d --name vminsert \
--cpus="30" --memory="90G" \
--network host \
--entrypoint=/vminsert-prod \
victoriametrics/vminsert:v1.91.0-cluster \
-rpc.disableCompression \
-replicationFactor=2 \
--storageNode=…… 
```
and i use https://github.com/VictoriaMetrics/prometheus-benchmark to do the benchmark.
here are some significant configuration
```
targetsCount: 10000
and the node exporter metrics count in my instance is 200+ 
scrapeInterval: 10s 
writeReplicas: 4
scrapeConfigUpdatePercent: 1
scrapeConfigUpdateInterval: 10m  
```

from the grafana the vmstorage is overload and the vmselect panic. 
and  i decrease the load targetsCount 1w -> 2k, the vmselect still panic. but such load is ok for at least several hours before i increase targetsCount to 1w

2023-08-01T06:44:59.936Z	panic	VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:166	FATAL: cannot unmarshal data at offset 88128067, size 97, tbfIdx 0: cannot unmarshal blockHeader: too big RowsCount; got 414633; cannot exceed 16384
2023-08-01T06:44:59.936Z	panic	VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:166	FATAL: cannot unmarshal data at offset 88079442, size 97, tbfIdx 0: cannot unmarshal blockHeader: too big RowsCount; got 1777467392; cannot exceed 16384
2023-08-01T06:44:59.936Z	panic	VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:166	FATAL: cannot unmarshal data at offset 88093501, size 98, tbfIdx 0: cannot unmarshal blockHeader: RowsCount in block header cannot be zero
2023-08-01T06:44:59.936Z	panic	VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:166	FATAL: cannot unmarshal data at offset 88091287, size 98, tbfIdx 0: cannot unmarshal blockHeader: RowsCount in block header cannot be zero
2023-08-01T06:44:59.936Z	panic	VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:166	FATAL: cannot unmarshal data at offset 88111952, size 98, tbfIdx 0: cannot unmarshal blockHeader: too big RowsCount; got 33554434; cannot exceed 16384
2023-08-01T06:44:59.936Z	panic	VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:166	FATAL: cannot unmarshal data at offset 88134955, size 97, tbfIdx 0: cannot unmarshal blockHeader: RowsCount in block header cannot be zero
panic: FATAL: cannot unmarshal data at offset 88128067, size 97, tbfIdx 0: cannot unmarshal blockHeader: too big RowsCount; got 414633; cannot exceed 16384

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment] 2023-08-01 08:03
duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4537

@jingb could you go through the mentioned issue and try following recommendation here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4537#issuecomment-1653895868 ?
We suspect there could be a bug in compression lib we use.

**Closed as completed by hagen1778** 2023-08-01 08:04 UTC
Labels: question
