### ISSUE TITLE
VictoriaMetrics: increased chance of metricsID discrepancy between cache and indexdb in 1.99

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5959] opened 2024-03-12 11:50 UTC
### Describe the bug

Based on user reports, after updating to 1.99 version users experience temporary performance degradation and potential metrics visibility decrease. The degradation happening to the following aspects:
1. Ingestion rate drops for short periods of time. The drop correlates by sudden spike of SlowInserts and drop of TSID cache utilization.
2. Some metrics that were queryable before aren't returned any more. However, they become visible after rollback or after some time.

The degradation seems to be resolved with time, as well as metrics become visible as well.
During performance degradation, users observe an increase of the `vm_missing_metric_names_for_metric_id_total` metric, which is updated each time the metricID can be found in the cache but is missing in indexdb. 
So far, it is unclear what the root cause of the issue is.  

### To Reproduce

It is unclear how to reproduce this yet. The issue is based on user reports.

### Version

v1.99.0

**Comment by valyala** [comment] 2024-03-17 22:44
The issue must be fixed by the commit 76f00cea6b9bf02a262275a112040c2680ed472c .

**Comment by valyala** [comment] 2024-04-04 13:19
Closing this issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5948

**Comment by f41gh7** [comment] 2024-04-06 19:12
Still exists at. 1.100 release.

**Comment by nemobis** [comment] 2024-04-16 07:00
FWIW, I can't reproduce the issue in v1.100.1. In about one month of running v1.99, the `vm_missing_metric_names_for_metric_id_total` occasionally spiked a bit, but it hasn't yet since the upgrade to v1.100.1 (the latest small spike in the chart was before the upgrade).

![Screenshot_20240416_095511](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/901528/afe81034-2a78-4ed8-88d1-3463335a6a21)

**Comment by valyala** [comment] 2024-04-16 17:25
Closing the issue as fixed in [v1.100.1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.100.1).

**Closed by valyala** 2024-04-16 17:25 UTC
Labels: bug
