### ISSUE TITLE
"found duplicate key" error writing metrics

### ISSUE THREAD

**Issue by glightfoot** [VictoriaMetrics/VictoriaMetrics#172] opened 2019-09-03 18:35 UTC
**Describe the bug**
We started seeing the following error in our VictoriaMetrics logs when writing metrics from Kubernetes endpoints:

```
Aug 30 14:37:05 node08<sensitive>.com victoria-metrics-prod[514]: 2019-08-30T14:37:05.954+0000        error        lib/httpserver/httpserver.go:425        
error in "/api/v1/write": cannot store metrics: errors occurred during rows addition: cannot obtain TSID for MetricName 
"kube_node_labels\x01dc\x01atl\x01env\x01prod\x01cluster\x01cluster1.prod\x01job\x01kubernetes-service-endpoints\x01instance\x0110.<sensitive>:8080\x01node\x01node17.<sensitive>.com\x01app\x01kube-state-metrics\x01kubernetes_io_name\x01kube-state-metrics\x01kubernetes_name\x01kube-state-metrics\x01kubernetes_namespace\x01monitoring\x01label_beta_kubernetes_io_arch\x01amd64\x01label_beta_kubernetes_io_os\x01linux\x01label_kubernetes_io_hostname\x01node17.<sensitive>.com\x01label_platform_rsglab_com_dc\x01atl01\x01label_platform_rsglab_com_k8s_ceph_rbd\x01true\x01label_platform_rsglab_com_k8s_ceph_rbd\x01true\x01label_platform_rsglab_com_k8s_controller\x01false\x01label_platform_rsglab_com_k8s_prom_allowed\x01true\x01label_platform_rsglab_com_rack\x01r4c1\x01label_platform_rsglab_com_rack_identifier\x01atl01.108-34.r4c1\x01label_platform_rsglab_com_rack_top\x016\x01prometheus_cluster\x01prometheus-dedicated-atl\x01": 
cannot create TSID by MetricName "kube_node_labels\x01dc\x01atl\x01env\x01prod\x01cluster\x01cluster1.prod\x01job\x01kubernetes-service-endpoints\x01instance\x0110.<sensitive>:8080\x01node\x01node17.<sensitive>.com\x01app\x01kube-state-metrics\x01kubernetes_io_name\x01kube-state-metrics\x01kubernetes_name\x01kube-state-metrics\x01kubernetes_namespace\x01monitoring\x01label_beta_kubernetes_io_arch\x01amd64\x01label_beta_kubernetes_io_os\x01linux\x01label_kubernetes_io_hostname\x01node17.<sensitive>.com\x01label_platform_rsglab_com_dc\x01atl01\x01label_platform_rsglab_com_k8s_ceph_rbd\x01true\x01label_platform_rsglab_com_k8s_ceph_rbd\x01true\x01label_platform_rsglab_com_k8s_controller\x01false\x01label_platform_rsglab_com_k8s_prom_allowed\x01true\x01label_platform_rsglab_com_rack\x01r4c1\x01label_platform_rsglab_com_rack_identifier\x01atl01.108-34.r4c1\x01label_platform_rsglab_com_rack_top\x016\x01prometheus_cluster\x01prometheus-dedicated-atl\x01": 
cannot unmarshal metricName "kube_node_labels\x01dc\x01atl\x01env\x01prod\x01cluster\x01cluster1.prod\x01job\x01kubernetes-service-endpoints\x01instance\x0110.<sensitive>:8080\x01node\x01node17.<sensitive>.com\x01app\x01kube-state-metrics\x01kubernetes_io_name\x01kube-state-metrics\x01kubernetes_name\x01kube-state-metrics\x01kubernetes_namespace\x01monitoring\x01label_beta_kubernetes_io_arch\x01amd64\x01label_beta_kubernetes_io_os\x01linux\x01label_kubernetes_io_hostname\x01node17.<sensitive>.com\x01label_platform_rsglab_com_dc\x01atl01\x01label_platform_rsglab_com_k8s_ceph_rbd\x01true\x01label_platform_rsglab_com_k8s_ceph_rbd\x01true\x01label_platform_rsglab_com_k8s_controller\x01false\x01label_platform_rsglab_com_k8s_prom_allowed\x01true\x01label_platform_rsglab_com_rack\x01r4c1\x01label_platform_rsglab_com_rack_identifier\x01atl01.108-34.r4c1\x01label_platform_rsglab_com_rack_top\x016\x01prometheus_cluster\x01prometheus-dedicated-atl\x01": 
found duplicate key "label_platform_rsglab_com_k8s_ceph_rbd"
```

The prometheus writing the metrics displays it like this:
```
kube_node_labels{app="kube-state-metrics",
instance="10.<sensitive>:8080",
job="kubernetes-service-endpoints",
kubernetes_io_name="kube-state-metrics",
kubernetes_name="kube-state-metrics",
kubernetes_namespace="monitoring",
label_beta_kubernetes_io_arch="amd64",
label_beta_kubernetes_io_os="linux",
label_kubernetes_io_hostname="node17.<sensitive>.com",
label_platform_rsglab_com_dc="atl01",
label_platform_rsglab_com_k8s_ceph_rbd="true",
label_platform_rsglab_com_k8s_controller="false",
label_platform_rsglab_com_k8s_prom_allowed="true",
label_platform_rsglab_com_rack="r4c1",
label_platform_rsglab_com_rack_identifier="atl01.108-34.r4c1",
label_platform_rsglab_com_rack_top="6",
node="node17.<sensitive>.com"}
```

The exporter is exposing the metric like this:
```
kube_node_labels{label_beta_kubernetes_io_arch="amd64",
label_beta_kubernetes_io_os="linux",
label_kubernetes_io_hostname="node17.<sensitive>.com",
label_platform_rsglab_com_dc="atl01",
label_platform_rsglab_com_k8s_ceph_rbd="true",
label_platform_rsglab_com_k8s_ceph_rbd="true",
label_platform_rsglab_com_k8s_controller="false",
label_platform_rsglab_com_k8s_prom_allowed="true",
label_platform_rsglab_com_rack="r4c1",
label_platform_rsglab_com_rack_identifier="atl01.108-34.r4c1",
label_platform_rsglab_com_rack_top="6",
node="node17.<sensitive>.com"} 1
```

**To Reproduce**
Ingest a metric with a duplicated label name into prometheus that is remote writing to VictoriaMetrics.

**Expected behavior**
Prometheus handles the error silently. We expect VictoriaMetrics to be able to ingest everything that Prometheus is able to ingest. Not sure what the best way to surface the error is, since it could lead to some unexpected behavior...

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190828-210620-tags-v1.27.0-0-g4c0a262a
```

**Additional context**
N/A

**Comment by valyala** [comment] 2019-09-03 21:31
A temporary workaround is to remove duplicate `label_platform_rsglab_com_k8s_ceph_rbd` label from the exporter output.

**Comment by valyala** [comment] 2019-09-04 15:16
@glightfoot , try building VictoriaMetrics from 16dd145586d5c1e139a3288aeb96e47fea21f263 and verifying whether the issue is fixed. This commit removes duplicate labels on ingestion path.

See [build instructions](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources).

**Comment by valyala** [comment] 2019-09-05 09:39
@glightfoot , could you verify release [v1.27.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)? It contains the fix for this issue.

**Comment by glightfoot** [comment] 2019-09-09 15:51
looks to be running fine. Thanks!

**Comment by valyala** [comment] 2019-09-13 21:04
Then closing the issue

**Closed by valyala** 2019-09-13 21:04 UTC
Labels: bug, enhancement
