### ISSUE TITLE
Disable hostname TLS verification

### ISSUE THREAD

**Issue by yasvanth** [VictoriaMetrics/VictoriaMetrics#2490] opened 2022-04-22 09:02 UTC
Hi, 

Is there a command-line flag to disable TLS hostname verification when enabling `mTLS`?

`Error on  vminsert`
<pre>
VictoriaMetrics/app/vminsert/netstorage/netstorage.go:257	cannot dial storageNode "vmstorage-3m-01:8400": x509: certificate is valid for vmstorage-*, vminsert-*, vmselect-*,  not vmstorage-3m-01
</pre>

`Error on vmstorage` 

<pre>
2022-04-22T08:56:25.139Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:123	cannot perform vminsert handshake with client "10.0.6.36:45068": cannot read hello: cannot read message with size 11: remote error: tls: bad certificate; read only 0 bytes
2022-04-22T08:56:25.141Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:98	accepted vminsert conn from 10.0.6.9:41902
2022-04-22T08:56:25.153Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:123	cannot perform vminsert handshake with client "10.0.6.9:41902": cannot read hello: cannot read message with size 11: remote error: tls: bad certificate; read only 0 bytes
2022-04-22T08:56:25.194Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:98	accepted vminsert conn from 10.0.6.8:50586
2022-04-22T08:56:25.202Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:123	cannot perform vminsert handshake with client "10.0.6.8:50586": cannot read hello: cannot read message with size 11: remote error: tls: bad certificate; read only 0 bytes
2022-04-22T08:56:25.329Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:98	accepted vminsert conn from 10.0.6.36:45070

</pre>

**Comment by f41gh7** [comment] 2022-04-22 15:16
Hello, with `mTLS` enabled, it's not possible to disable certificate hostname verification. It's enforced by design.

 Can you describe your case, why you want to use `mTLS` with invalid certificates?

**Comment by yasvanth** [comment] 2022-04-22 19:36
I have generated server certs with regex in hostname/dns as `vmstorage-*, vminsert-*, vmselect-*` which should allow `vmstorage-3m-01 ` or `vmstorage-3m-02` or `vmstorage-1m-01` but didnt, where `*-1m-*` denotes rention period.

My storage nodes runs in containers so I am not mapping host's `hostname`  because container names will be random. `vminsert` connect to `vmstorage` based on the service name. if I set the container's  `hostname` the same as the service name will fix the issue or service name needs to be added in the cert?

**Comment by f41gh7** [comment] 2022-05-02 14:26
partial-wildcard name isn't supported by `golang` and modern crypto packages. 
https://go-review.googlesource.com/c/go/+/134715/

 you could use `statefulset`.

 I've created small examples, how to use secure mTls with official helm chart 

https://gist.github.com/f41gh7/76ed8e5fb1ebb9737fe746bae9175ee6

**Comment by valyala** [comment] 2022-05-03 10:19
@yasvanth , `vminsert`, `vmselect` and `vmstorage` components in the next release of VictoriaMetrics will support `-cluster.tlsInsecureSkipVerify` command-line option, which can be used for disabling peer TLS certificate verification. Note that this breaks mTLS security. See [mTLS docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection) for details.

**Comment by yasvanth** [comment] 2022-05-03 15:01
I thought I did reply but not.  Generating certificate with hostnames in the cert works fine.  `-cluster.tlsInsecureSkipVerify` will be a good option for dev/test.

**Comment by valyala** [comment] 2022-05-05 10:18
Cluster components of VictoriaMetrics support `-cluster.tlsInsecureSkipVerify` command-line flag starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection). Closing the feature request as done.

**Closed by valyala** 2022-05-05 10:18 UTC
Labels: enhancement, enterprise
