### ISSUE TITLE
vmagent remoteWrite buffer size vs. single-node victoriametrics data storage size

### ISSUE THREAD

**Issue by MHOOO** [VictoriaMetrics/VictoriaMetrics#7654] opened 2024-11-25 16:57 UTC
### Is your question request related to a specific component?

vmagent & victoriametrics stand-alone

### Describe the question in detail

Hi there,

I noticed that the amount of data that `vmagent` requires for buffering while a remote write instance is not available, is significantly higher than the amount of data that is required when actually storing the data inside a single-node VictoriaMetrics instance.
On a single-node VictoriaMetrics instance I'm getting ~ `0.17 bytes` per datapoint according to the grafana panels that are shipped with this repository.
The buffer directory (`-tmpDataPath` argument) however is growing by ~ `9.045 KB/s`, which with the `528 datapoints/s` that I'm seeing would amount to ~ `17.5 bytes` per datapoint. It makes sense that the compaction on the database side has some difference, but this is a >100x increase. Is there something that I can do, to decrease the size of data that is stored by `vmagent` when a remote-write instance is not available?

I've already added the following arguments to the `vmagent` instance to write less data overall:
- `-remoteWrite.forceVMProto`
- `-remoteWrite.vmProtoCompressLevel 4`
- `-remoteWrite.roundDigits 4`

I've also tried the `-remoteWrite.flushInterval` argument, but it did not appear to impact the compression rate inside the `tmpDataPath` directory at all.

I'm using victoriametrics `1.105.0`

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment] 2024-11-26 15:07
Hello. I'm trying to reproduce this. After 1 succeed remote write and 1 failed remote write:
- VictoriaMetrics presisted ~10KiB under `.../victoria-metrics-data/data/small/2024_11/180B8BC72225DF47/`
- vmagent presisted ~12KiB under `.../vmagent-remotewrite-data/persistent-queue/1_A1034CECB2A6FE4E/`

And do it again for 10 succeed + 10 failed:
- VictoriaMetrics: ~27 KiB
- vmagent: ~132 KiB

In other word, this should be expected. And the reason behind this:
1. vmagent presist every request into the on-disk queue, without seperating metadata and values. It reads through the queue according to the offset. For example, offset [0, 100] contains all data a remote write request need. And [101, 200] contains all data the next remote write request need. Most of the metadata are identical and not well compressed.
2. In VictoriaMetrics/vmstorage, metadata and sample value are stored seperately so that it don't have to repeat the redundant metadata and saved tons of space.

Example (just to show the concept. not the real content in disk):
1. vmagent queue content: 
```
my_metrics{label="a"},timestamp1,value1;
my_metrics{label="a"},timestamp2,value2;
my_metrics{label="a"},timestamp3,value3;
```
2. VictoriaMetrics/vmstorage data:
```sh
# metadata file
my_metrics{label="a"}

# timestamp file
timestamp1,timestamp2,timestamp3

# value file
value1,value2,value3
```

So more sample (or larger metadata size, image you have a time series with 100 labels) you have, more space VictoriaMetrics/vmstorage could save.

As for the issue you have, I think the correct way is to understand why vmagent has to buffer data:
1. Is data ingestion on VictoriaMetrics side slow? Why?
2. Is the network bandwidth enough for pushing these data?

I would recommand checking our [troubleshooting guide - slow ingestion](https://docs.victoriametrics.com/troubleshooting/#slow-data-ingestion) first. Also, setting up the monitor [dashboard](https://grafana.com/orgs/victoriametrics/dashboards) for vmagent and VictoriaMetrics, and provide more info so that hopefully we could have some useful suggestion for you.

**Comment by jiekun** [comment] 2024-12-02 08:09
Hello @MHOOO, may I ask if you are still experiencing this issue and require assistance from us?

**Comment by MHOOO** [comment] 2024-12-02 10:52
Hi there,

Thanks for the thorough explanation. In my case there is a flaky connection
that may drop at any time and stay dropped until a human re-establishes it.
This cannot be done automatically so we will have to live with some data
loss.
I guess I was simply surprised at how much of a difference there is in the
amount of saved data, but with your explanation it makes sense and I think
there's not much that can be done about it... Unless there's maybe a way to
send data efficiently from one single node VictoriaMetrics instance to
another?

Zhu Jiekun ***@***.***> schrieb am Mo., 2. Dez. 2024, 09:09:

**Comment by jiekun** [comment] 2024-12-02 13:31
Thanks for confirming. 

> Unless there's maybe a way to
> send data efficiently from one single node VictoriaMetrics instance to
> another

I think the answer is no. Currently, vmagent is the only option for buffering remote write data. And yes it seems that not much can be done besides improving the stability of the connection.

I'm closing this issue as answered. But please feel free to reopen it if you have more questions on this topic.

**Closed by jiekun** 2024-12-02 13:31 UTC
Labels: question, need more info, vmstorage
