### ISSUE TITLE
Grafana shows data points when service was down

### ISSUE THREAD

**Issue by jcmoraisjr** [VictoriaMetrics/VictoriaMetrics#141] opened 2019-08-05 22:02 UTC
**Describe the bug**

Grafana shows some data points when the whole host of Victoria Metrics and Prometheus was turned off.

**To Reproduce**

Insert data from a Prometheus' remote_write for a couple of hours, shutdown the services and the host, turn on everything in the next day, see some data points after the machine is turned off and before it is turned on again. I'm scraping cadvisor of two k8s clusters (total 7 VMs) from k8s api, and also VictoriaMetrics, m3db and Prometheus metrics as well.

**Expected behavior**

No data points when the service isn't active.

**Screenshots**

8h30 - 11h30:

![8h](https://user-images.githubusercontent.com/1457820/62400604-31460c80-b556-11e9-98c6-a877490236b5.png)

9h30 - 11h30:

![9h](https://user-images.githubusercontent.com/1457820/62400634-428f1900-b556-11e9-8fd9-402643baef2a.png)

The machine with prometheus and VictoriaMetrics was turned on about 10h55.

**Version**

`1.23.1` and `1.24.0`

**Additional context**

I chose some of the most used metrics from cadvisor and a time frame that I'm sure the services were down and the machine was turned off. Following table shows the number of time series per metric on the database.

|metric|num of time series|before start with 1.23.1|before start with 1.24.0|
|---|---|---|---|
|container_memory_working_set_bytes|690|90|410|
|container_cpu_usage_seconds_total|456|29|146|
|container_network_receive_bytes_total|333|6|48|

* **num of time series**: number of time series of that metric I can see when the services are running
* **before start with 1.23.1**: number of time series of that metric that I can see after turn off with 1.23.1 and turn on again with the same version, last week.
* **before start with 1.24.0**: number of time series of that metric that I can see after turn off with 1.23.1 and turn on again with 1.24.0, today.

**Comment by valyala** [comment] 2019-08-06 12:47
The issue has been narrowed down to special optimization for constant values, which turned out to be incorrect. The optimization was replacing the original timestamps for time series with constant values or values with constant delta by calculated timestamps with constant delta. This should improve compression ratio. But this could result to the issue similar to this one. The fix just deletes the broken optimization - see 0b488f1e37cea5e6675585557a26c3fe4ec4fccd .

Unfortunately previously stored time series with incorrectly calculated timestamps cannot be fixed. Newly written time series with constant values shouldn't suffer from this problem after the commit 0b488f1e37cea5e6675585557a26c3fe4ec4fccd .

**Comment by valyala** [comment] 2019-08-06 12:59
The issue must be fixed in [v1.24.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment] 2019-08-06 13:01
@jcmoraisjr , could you verify whether the issue is fixed in [v1.24.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)? Note that the issue shouldn't be reproduced with newly inserted data. Unfortunately the old data will remain broken :(

**Comment by jcmoraisjr** [comment] 2019-08-06 13:55
Hi, I'll restart the tests today and will update the issue as soon as I have more info. No problem if I reuse the same database?

**Comment by valyala** [comment] 2019-08-06 14:12
> No problem if I reuse the same database?

This is OK, but the previously collected data will remain broken :(

**Comment by kmansoft** [comment] 2019-08-06 20:15
Is this supposed to fix the case in #120 as well?

**Comment by valyala** [comment] 2019-08-07 08:06
> Is this supposed to fix the case in #120 as well?

Yes

**Comment by jcmoraisjr** [comment] 2019-08-07 12:52
Hi, did some tests now and everything sounds to be working as expected. I'm fine to close this issue. Btw thanks for the great job!

**Comment by kmansoft** [comment] 2019-08-07 12:55
In my tests, #120 looks fixed too. Thanks!

**Comment by valyala** [comment] 2019-08-14 00:10
Then closing the issue

**Closed by valyala** 2019-08-14 00:10 UTC
Labels: bug
