### ISSUE TITLE
VMUI: option to sort by time always

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6669] opened 2024-07-18 13:32 UTC
### Is your feature request related to a problem? Please describe

Add the option (by default turned on) to sort all fields by time 

### Describe the solution you'd like

option to see sorted logs by time 

### Describe alternatives you've considered

every time add ` | sort by (_time)'` to query

**Comment by valyala** [comment] 2024-07-22 06:01
VictoriaLogs returns log entries sorted by time if they are requested via [`/select/logsql/query`](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs) with `limit=N` query arg. In this case it returns up to `N` last log entries with the biggest [`_time`](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) on the selected time range. If this isn't the case, then this is a bug, which must be fixed.

[Web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) must always pass the `limit=N` query arg to `/select/logsql/query` HTTP endpoint in order to obtain up to `N` logs with the biggest `_time` field values (aka timestamps). The same applies to [VictoriaLogs plugin for Grafana](https://github.com/VictoriaMetrics/victorialogs-datasource/issues/47).

**Comment by Loori-R** [comment] 2024-07-23 16:11
The Web UI always passes `limit=N`, and the data on the 'group' and 'json' tabs are displayed in the same order as returned by VictoriaLogs. It might be confusing that by default, data in the table is sorted in descending order by time.

**Comment by unlightable** [comment] 2024-08-22 15:32
I'm not sure if it's allright to use hijack this issue, but it seems like passing `limit` arg breaks natural order of logs.
I mean if some log entries occur at the same time, I still want them to be ordered the way there were pushed.
But applying limit can mix them up. E.g.
`/select/logsql/query?query=app%3A+TEST&start=2024-08-21T15%3A25%3A14.398Z&end=2024-08-22T15%3A25%3A14.398Z`

```
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"1","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"2","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"3","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"4","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"5","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"6","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"7","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"8","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"9","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"10","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"1","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"2","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"3","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"4","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"5","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"6","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"7","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"8","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"9","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"10","app":"TEST"}
```

but 
`/select/logsql/query?query=app%3A+TEST&start=2024-08-21T15%3A25%3A14.398Z&end=2024-08-22T15%3A25%3A14.398Z&limit=1000`

```
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"10","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"4","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"3","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"1","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"2","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"5","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"6","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"7","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"8","app":"TEST"}
{"_time":"2024-08-21T17:15:25Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"9","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"1","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"2","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"3","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"4","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"5","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"6","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"7","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"8","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"9","app":"TEST"}
{"_time":"2024-08-21T17:26:10Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"10","app":"TEST"}
{"_time":"2024-08-21T17:50:42Z","_stream_id":"0000000000000000eecfc3ffe965aa2a3fc869ebf4e3b211","_stream":"{app=\"TEST\"}","_msg":"1","app":"TEST"}
```

**Comment by valyala** [comment] 2024-11-05 14:36
> I'm not sure if it's allright to use hijack this issue, but it seems like passing limit arg breaks natural order of logs.

This is expected behaviour, which cannot be fixed - see [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7045#issuecomment-2448284268). The workaround is to put the log timestamp into other than `_time` field during data ingestion. Then VictoriaLogs will automatically assign the curren timestamp with nanosecond precision to the `_time` field according to [these docs](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field).

See also [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7397).

Closing this feature request, since [VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) always passes `limit` query arg to [`/select/LogsQL/query` endpoint](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs), so it returns up to `limit` the most recent logs sorted by time as documented [here](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs). Web UI then displayed the returned logs in the same order as they are received from VictoriaLogs.

**Closed by valyala** 2024-11-05 14:36 UTC
Labels: enhancement, vmui, victorialogs
