### ISSUE TITLE
Help needs difficult to limit targets exposed too many id type labels

### ISSUE THREAD

**Issue by recoilRailGun** [VictoriaMetrics/VictoriaMetrics#3410] opened 2022-11-29 14:14 UTC
**Is your feature request related to a problem? Please describe.**
We are encountering abusive usage from k8s_sd, like ESK from aws.
Their system produced exporter with image id or persisted volume id as metrics labels.
Some metrics have more than 100 label values with very low cardinality. And as targets discovered from k8s_sd, in one cluster, we might have 1k+ to 10k targets. This made the result of the Cartesian product.
We have difficulty finding or limiting this problem.
1 in vmagent, the /API/v1/target only counted the result by  __address__ for target, which is 100% not shown in the final vmstorage tsdb,
2 in the vmagent scrape job is counted by the original job name, which, as your quotation marked, may be dropped or replaced.
3 remotewrite data well included some useful information to detect the target but:
	
```Golang
PushData func(at *auth.Token, wr *prompbmarshal.WriteRequest)

type TimeSeries struct {
	Labels  []Label  `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels"`
	Samples []Sample `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples"`
}
````
where the `wr` contained data is not nested as map[string]interface{}  to access the correct label, needs quite a lot of time
(as slow as vmselect do count by(label_a,label_b.......))
**Describe the solution you'd like**
Seeking help to understand how to control this problem.

**Comment by hagen1778** [comment] 2022-11-29 15:02
Hi @recoilRailGun! Thanks for the request!
Do you know or have you seen in other solution ways to control this behaviour?

**Comment by recoilRailGun** [comment] 2022-12-01 04:11
> Hi @recoilRailGun! Thanks for the request! Do you know or have you seen in other solution ways to control this behaviour?

Sorry, well I am still looking on this issue, so far not much fund. I post this is to have a topic to discussing here, how to prevent abuse happened. In my case, is hard to use tenet mode.

Cause we use some centralized systems. End point users may not able to setup the data source with /accountId:projectId

So it came back to the original point, that how to limit with a efficient way.

**Comment by recoilRailGun** [comment] 2022-12-01 04:14
So far what i got is to build a procedure to do a pre-injection scrape. Then count label value cardinality and check if it is reasonable or not. Then put the target into vmagent configuration file. This cannot stop some cases like 
```
ubt{searchCharts="base64enc(search key)"}
```
this type of dynamic labels, at moment to verify it will be 0, but as time flies by  there will be more and more.

**Comment by f41gh7** [comment] 2022-12-01 08:39
Hello, probably cardinality limiter per target will help you to solve an issue. It could be configured at vmagent with flag `-promscrape.seriesLimitPerTarget`. Limit applied for 24hours, any new series that exceed configured limit will be dropped.

https://docs.victoriametrics.com/vmagent.html#cardinality-limiter

**Comment by recoilRailGun** [comment] 2023-01-13 07:31
> Hello, probably cardinality limiter per target will help you to solve an issue. It could be configured at vmagent with flag `-promscrape.seriesLimitPerTarget`. Limit applied for 24hours, any new series that exceed configured limit will be dropped.
> 
> https://docs.victoriametrics.com/vmagent.html#cardinality-limiter

Thanks for this suggestion. this is not suite able for this case.
What you proposed is not validated, vmagent in cluster mode did not store the history of the target scraped histories.
The issue is, in any moment, the target exports reasonable labels, but for a time duration such as 1day, it might accumulated many label values.

for example, as user id in any second snapshot ,there only QPS equally numbers of id, but in a whole day there might be  millions of possible id.

**Comment by hagen1778** [comment] 2023-01-13 08:35
> What you proposed is not validated, vmagent in cluster mode did not store the history of the target scraped histories.
The issue is, in any moment, the target exports reasonable labels, but for a time duration such as 1day, it might accumulated many label values.

So you're looking for the limiter which can be configured to measure the number of series exposed by a target on a fixed interval of an hour or day. Is this correct?

**Comment by hagen1778** [comment] 2023-01-25 08:44
So it looks like some extension of the `series_limit ` config but with a time window, just like for `-remoteWrite.maxHourlySeries` and `-remoteWrite.maxDailySeries`. 
Looking at the code,  `series_limit ` actually has a TTL of 24h for entries. So from my perspective, it looks like something you're looking for. 
I'm sorry if I'm missing something from your explanation.

**Comment by recoilRailGun** [comment] 2023-04-19 09:34
> So it looks like some extension of the `series_limit ` config but with a time window, just like for `-remoteWrite.maxHourlySeries` and `-remoteWrite.maxDailySeries`. Looking at the code, `series_limit ` actually has a TTL of 24h for entries. So from my perspective, it looks like something you're looking for. I'm sorry if I'm missing something from your explanation.

sorry replied late after few months

may be this can help. But need to know more about how the vmagent limiting it.

**Comment by zekker6** [comment] 2023-04-20 10:27
@recoilRailGun You can find more details about cardinality limiting configuration in [this](https://docs.victoriametrics.com/vmagent.html#cardinality-limiter) doc.

Internally, vmagent uses [Bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) to store information about series which have been written to the remote storage. `-remoteWrite.max*` flags values is limiting number of entries to store in this filter. After filter storage have been filled filter will only allow to remote write values that have already been stored in filter and rejecting new series.

Please, note that Bloom filter is a [probabilistic](https://en.wikipedia.org/wiki/Probabilistic) data structure, which means that vmagent limits are approximate and can exceed exact number specified via flags.

**Closed** 2024-07-22 07:30 UTC
Labels: question, vmagent
