### ISSUE TITLE
vmalert ignores -remoteWrite.maxQueueSize parameter

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [VictoriaMetrics/VictoriaMetrics#4845] opened 2023-08-16 12:11 UTC
Seems **vmalert** ignores `-remoteWrite.maxQueueSize` parameter.
**vmalert** is running with parameters `-remoteWrite.maxBatchSize 10000 -remoteWrite.maxQueueSize 1000000` (I set it 10 times bigger: 100 000 (default) -> 1 000 000), but periodically logs errors on recording rules calculation:
```
# ps ax | fgrep vmalert
10816 ?        Ssl   10:16 /usr/local/bin/vmalert \
    -datasource.url  http://127.0.0.1:8428 \
    -remoteWrite.url http://127.0.0.1:8428 \
    -remoteRead.url  http://127.0.0.1:8428 \
    -notifier.url    http://127.0.0.1:9093 \
    ..... \
    -remoteWrite.maxBatchSize 10000 \
    -remoteWrite.maxQueueSize 1000000
```
```
Aug 16 11:04:49 metrics0 vmetrics@vmalert[10816]: error VictoriaMetrics/app/vmalert/group.go:326
    group "nginx pre-calculations": rule "nginx_http_request_duration_seconds_bucket:increase5m":
    remote write failure: failed to push timeseries - queue is full (100000 entries).
    Queue size is controlled by -remoteWrite.maxQueueSize flag
```

### To Reproduce

Install the latest (1.93.0) version on **vmalert** and configure recording rules with more than 100 000 metrics.

### Version

```
#  victoria-metrics --version
victoria-metrics-20230812-130456-tags-v1.93.0-0-g59f7d810c9

#  vmalert --version
vmalert-20230812-130925-tags-v1.93.0-0-g59f7d810c9
```

### Logs

```
Aug 16 11:04:49 metrics0 vmetrics@vmalert[10816]: error VictoriaMetrics/app/vmalert/group.go:326
    group "nginx pre-calculations": rule "nginx_http_request_duration_seconds_bucket:increase5m":
    remote write failure: failed to push timeseries - queue is full (100000 entries).
    Queue size is controlled by -remoteWrite.maxQueueSize flag
```

### Used command-line flags

`-remoteWrite.maxBatchSize 10000 -remoteWrite.maxQueueSize 1000000`

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment] 2023-08-16 16:45
> have you restarted your vmalert?

Yes, as you see there is `ps ax` output in my first message with parameters and correct values.
At first I didn't specify them at all, I had **vmalert** running without `-remoteWrite.maxBatchSize` and `-remoteWrite.maxQueueSize`. But after I saw the log messages suggesting to encrease maxQueueSize, I added them and restarted **vmalert**. Nothing has changed - the logs are still coming and with default values:
```
... queue is full (100000 entries).
```

Tried to change it to 5 000 000:
```
root@metrics0:~#  ps ax | fgrep /vmalert
18773 ?        Ssl    0:16 /usr/local/bin/vmalert -datasource.url http://127.0.0.1:8428 -remoteWrite.url http://127.0.0.1:8428 -remoteRead.url http://127.0.0.1:8428 -notifier.url http://127.0.0.1:9093 -external.url http://monitoring.local.domain:8880 -disableAlertgroupLabel -loggerLevel WARN -loggerDisableTimestamps -replay.disableProgressBar -rule "/etc/vmetrics/recording-rules.d/*.yml" -rule "/etc/vmetrics/alerting-rules.d/*.yml" -evaluationInterval 15s -rule.validateExpressions true -rule.validateTemplates true -remoteWrite.maxBatchSize 10000 -remoteWrite.maxQueueSize 5000000

root@metrics0:~#  tail /var/log/monitoring.log
Aug 16 16:39:18 metrics0 vmetrics@vmalert[18773]: error VictoriaMetrics/app/vmalert/group.go:326        group "nginx pre-calculations": rule "nginx_http_request_duration_seconds_bucket:increase5m": remote write failure: failed to push timeseries - queue is full (100000 entries). Queue size is controlled by -remoteWrite.maxQueueSize flag
```

**Comment by dmitryk-dk** [comment] 2023-08-16 17:14
Ok, let me recheck it. I have changed the flags and saw that they are changed. But will try to reproduce

**Comment by dmitryk-dk** [comment] 2023-08-17 10:56
Hi @Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk ! Found the reason, i'm not sure that is the bag with `flag.Bool()`.
Here is some explanation
```golang
func main() {

	flag.Parse()

	log.Printf("bool flag: %v", *boolFlag)
	log.Printf("int flag: %v", *intFlag)
}

// first run
 go run main.go -bool=true -int=1
2023/08/17 14:36:28 bool flag: true
2023/08/17 14:36:28 int flag: 1

// second run
 go run main.go -bool true -int=1
2023/08/17 14:36:33 bool flag: true
2023/08/17 14:36:33 int flag: 0
```
As you can see, if after flag name `=` is not present, the next flag will be ignored and set to the default value.

As a workaround you can run your `vmagent` as an example below:

```
/usr/local/bin/vmalert
  -datasource.url=http://127.0.0.1:8428 \
  -remoteWrite.url=http://127.0.0.1:8428 \
  -remoteRead.url=http://127.0.0.1:8428 \
  -notifier.url=http://127.0.0.1:9093 \
  -external.url=http://monitoring.local.domain:8880 \
  -disableAlertgroupLabel \
  -loggerLevel=WARN \
  -loggerDisableTimestamps \
  -replay.disableProgressBar \
  -rule="/etc/vmetrics/recording-rules.d/*.yml" \
  -rule="/etc/vmetrics/alerting-rules.d/*.yml" \
  -evaluationInterval=15s \
  -rule.validateExpressions=true \
  -rule.validateTemplates=true \
  -remoteWrite.maxBatchSize=10000 \
  -remoteWrite.maxQueueSize=5000000
  ```

**Comment by valyala** [comment] 2023-08-17 11:10
Boolean command-line flags in programs written in Go do not support the form `-boolFlagName value`. They should have the following forms:

* `-boolFlagName=true`
* `-boolFlagName=false`
* `-boolFlagName` - this is equivalent to `-boolFlagName=true`

See https://pkg.go.dev/flag#hdr-Command_line_flag_syntax for more details.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment] 2023-08-17 11:57
Thanks, changed all options to have `=` sing, now it works.
Please, can you fix `--help` output to be with `=` signs in options. Because now it specifies options with space delimiter:
```
  -remoteWrite.maxQueueSize int
        Defines the max number of pending datapoints to remote write endpoint (default 100000)
```

**Comment by valyala** [comment] 2023-08-17 12:03
@Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk , we made better handling of such issues - the commit cd9f86afe15c346be60d8e1b36b3a8fba9a2af13 completely disallows running VictoriaMetrics components with invalid boolean command-line flag form `-boolFlag value`. This commit will be included in the next release.

**Closed** 2023-08-17 12:38 UTC
Labels: question, vmalert

**Comment by valyala** [comment] 2023-08-24 18:56
FYI, VictoriaMetrics components refuse specifying boolean command-line flag in the form `-boolFlagName value` starting from [v1.93.1](https://docs.victoriametrics.com/CHANGELOG.html). They should exit with the error at startup. The solution is to use `-boolFlagName=value` form.

**Comment by valyala** [comment] 2023-09-01 23:57
FYI, the bugfix for this issue has been back-ported to [v1.87.8 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.8).
