### ISSUE TITLE
victorialog filter stream for other error

### ISSUE THREAD

**Issue by zainal-abidin-assegaf** [VictoriaMetrics/VictoriaMetrics#7567] opened 2024-11-18 10:14 UTC
### Describe the bug

When i do Ctrl + Click to filter by the _stream for other there is error

### To Reproduce

Ctrl + Click to filter by the _stream for other there is error:

_stream: {other} AND (*)

`remoteAddr: "10.0.0.2:62689"; requestURI: /select/logsql/query?end=2024-11-18T10%3A10%3A42.229Z&limit=50&query=_stream%3A+%7Bother%7D+AND+%28%2A%29&start=2024-11-18T10%3A05%3A42.229Z; cannot parse query [_stream: {other} AND (*)]: unsupported operation "}" in _steam filter for "other" field; supported operations: =, !=, =~, !~; context: [_stream: {other}]`

### Version

victoriametrics/victoria-logs:v1.0.0-victorialogs

### Logs

`remoteAddr: "10.0.0.2:62689"; requestURI: /select/logsql/query?end=2024-11-18T10%3A10%3A42.229Z&limit=50&query=_stream%3A+%7Bother%7D+AND+%28%2A%29&start=2024-11-18T10%3A05%3A42.229Z; cannot parse query [_stream: {other} AND (*)]: unsupported operation "}" in _steam filter for "other" field; supported operations: =, !=, =~, !~; context: [_stream: {other}]`

### Screenshots

![image](https://github.com/user-attachments/assets/5bdd9bde-2404-4d45-850b-031245a5f6a5)

**Comment by Fusl** [comment] 2024-11-18 22:33
Duplicate of #7552

**Comment by jiekun** [comment] 2024-11-21 10:06
Hi. Please track this issue with #7552 I'd like to close it as duplicated. Thanks!

**Closed by jiekun** 2024-11-21 10:06 UTC
Labels: bug, victorialogs
