### ISSUE TITLE
vmui: cardinality explorer requests seems off

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5231] opened 2023-10-24 14:06 UTC
### Describe the bug

I've opened [Cardinality Explorer page](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality?date=2023-10-24&match=&topN=50&focusLabel=) and checked network tab:
<img width="990" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/7edf6a01-9e6e-415e-8e22-57fdd573207a">

I see 3 requests to the API:
1. Is the main request for current date
2. Is the request for prev date to use as a comparison with current date
3. ?

It is unclear what 3rd request is doing and why it doesn't respect `topN`argument

### To Reproduce

Open [Cardinality Explorer page](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality?date=2023-10-24&match=&topN=50&focusLabel=) and check NetworkTab in broswer.

### Version

1.94

cc @Loori-R

**Comment by Loori-R** [comment] 2023-10-25 17:55
The third request (with topN=0) is needed to obtain the overall totalSeries (without a filter) for "Percentage from total" (The share of these series in the total number of time series).
I have checked, and it is possible to reduce the calls to this request since it is not necessary for all tables.

**Comment by valyala** [comment] 2024-06-07 20:45
Closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6240

**Closed by valyala** 2024-06-07 20:45 UTC
Labels: bug, vmui
