### ISSUE TITLE
After the vmstorage-retentionPeriod is changed, the disk usage increases instead of being released

### ISSUE THREAD

**Issue by SRE-Rick** [VictoriaMetrics/VictoriaMetrics#6522] opened 2024-06-24 07:01 UTC
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

I have three VMstorages. When I changed the retentionPeriod from 3y to 180d, the disk space of only one vmstorage node was freed, while the disk space usage of the other two VMstorages increased
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/86993048/aadc77ef-9f82-4193-b379-0881012e8963)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by SRE-Rick** [comment] 2024-06-24 07:58
It looks like a new snapshot was created

**Comment by hagen1778** [comment] 2024-07-01 06:45
Hey @SRE-Rick! Did you find the root cause? Was it undeleted snapshot?

**Comment by SRE-Rick** [comment] 2024-07-31 11:43
> 嘿@SRE-Rick！你找到根本原因了吗？是未删除的快照吗？

Yes, the number of snapshots on several nodes is inconsistent

**Comment by SRE-Rick** [comment] 2024-07-31 11:43
@hagen1778 
Yes, the number of snapshots on several nodes is inconsistent

**Comment by hagen1778** [comment] 2024-07-31 11:51
Thanks for responding! I'm closing the issue then.

**Closed by hagen1778** 2024-07-31 11:51 UTC
Labels: question, need more info
