### ISSUE TITLE
instant query has unexpected overlapping series

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#943] opened 2020-12-07 01:48 UTC
**Describe the bug**
Looking at VM `vm_app_version` metric during an upgrade, there is a moment where the instant query returns two series, even though range query confirms there is no overlap and gap of 2 minutes when there is no series.

**Expected behavior**
Instant and range queries should be consistent.  There is several minute gap while the VM server was restarting, which is confirmed by the range query, but contradicted by instant query.

**Screenshots**
range query:
![Screen Shot 2020-12-07 at 10 24 09 AM](https://user-images.githubusercontent.com/1708631/101300499-205b8880-3879-11eb-8536-dab2013fb788.png)

instant query has overlapping series at time 10:10:
![Screen Shot 2020-12-07 at 10 46 13 AM](https://user-images.githubusercontent.com/1708631/101300633-8a742d80-3879-11eb-9fad-d8d352ee1833.png)

**Version**
1.49.0

**Comment by hagen1778** [comment] 2022-02-07 09:37
@valyala @belm0 is this issues still relevant?

**Comment by belm0** [comment] 2022-02-12 02:20
The problem still exits in 1.72.0.  It seems like a bug of instant query worth investigating.

![Screen Shot 2022-02-12 at 11 19 48 AM](https://user-images.githubusercontent.com/1708631/153692769-c15018ed-2933-42a9-b0e5-513877cd0885.png)

![Screen Shot 2022-02-12 at 11 20 06 AM](https://user-images.githubusercontent.com/1708631/153692776-2f493cf9-de27-4c19-951f-9970b2d39c91.png)

**Comment by valyala** [comment] 2024-02-08 13:38
@belm0 , it looks like the root cause of the issue is that single-node VictoriaMetrics didn't store [staleness markers](https://docs.victoriametrics.com/vmagent/#prometheus-staleness-markers) for the self-scraped metrics  on graceful shutdown if `-selfScrapeInterval` command-line flag was set to positive value. VictoriaMetrics uses the default 5 minute staleness interval when deciding which time series must be returned from [`/api/v1/query`](https://docs.victoriametrics.com/keyconcepts/#instant-query) if there are no staleness markers. That's why it was returning stale time series together with new time series during 5 minutes. The staleness interval can be adjusted at query side by passing `step` query arg to `/api/v1/query`.

This issue must be fixed in the commit a354924b0d52bafd3ded17dd518f6db39877a877 . This commit will be included in the next release. In the mean time you can build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it works as expected. Note that you need restarting the newly built VictoriaMetrics at least two times in order to see the effect of the bugfix. You can pass different values to `-selfScrapeInstance` command-line flag in order to emulate new `vm_app_version` time series after VictoriaMetrics restart.

**Comment by valyala** [comment] 2024-02-14 16:02
Single-node VictoriaMetrics should properly store staleness markers on graceful shutdown when it runs with `-selfScrapeInterval` commnad-line flag set to positive duration. Closing this issue as fixed then.

**Closed by valyala** 2024-02-14 16:02 UTC
Labels: bug

**Comment by valyala** [comment] 2024-02-14 16:55
FYI, the bugfix has been included also in [v1.97.2 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.2).

**Comment by valyala** [comment] 2024-02-14 18:14
The bugfix has been also included in [v1.93.12 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.12).
