### ISSUE TITLE
last_over_time not working as expected

### ISSUE THREAD

**Issue by kernel164** [VictoriaMetrics/VictoriaMetrics#949] opened 2020-12-09 18:15 UTC
**Describe the bug**

last_over_time not working as expected

**To Reproduce**

following example shows that last_over_time returns 1607535665 which is mostly the current time.

`/api/v1/query?query=last_over_time(vital_hr{user_id="5fce28b3d77c0500087f3d24"}[24h])`

```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "vital_hr",
          "device_id": "5fce28a9d77c0500087f3d1f",
          "user_id": "5fce28a5d77c0500087f3d1c"
        },
        "value": [
          1607535665,
          "78"
        ]
      }
    ]
  }
}
```

raw export shows timestamp as 1607529090505 which is correct.

`/api/v1/export?match[]=vital_hr{user_id="5fce28b3d77c0500087f3d24"}`

```json
{
  "metric": {
    "__name__": "vital_hr",
    "device_id": "5fce28a9d77c0500087f3d1f",
    "user_id": "5fce28a5d77c0500087f3d1c"
  },
  "values": [
    78
  ],
  "timestamps": [
    1607529090505
  ]
}
```

**Expected behavior**

last_over_time should return latest timestamp for the value not the current timestamp.

**Version**

```
using victoria-metrics-single helm chart version 0.6.6 (app version: 1.49.0)
```

**Comment by valyala** [comment] 2020-12-11 16:02
This is expected behavior.

VictoriaMetrics follows Prometheus data model for queries sent to `/api/v1/query` and `/api/v1/query_range` handlers. This means the following:
* a single **calculated** datapoint is returned from [/api/v1/query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) with timestamp equal to `time` query arg. If `time` isn't specified, then the current time is used.

* fixed number of **calculated** datapoints is returned from [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) on a time range specified by `start` and `end` query args. The distance between the returned datapoints always equals to `step`.

See more details about this behavior at https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness .

If you want actual timestamp for the last value, then either use `/api/v1/export` API, which returns all the raw datapoints stored in the database or use `timestamp` function from [MetricsQL](https://victoriametrics.github.io/MetricsQL.html): `timestamp(vital_hr{user_id="5fce28b3d77c0500087f3d24"}[24h])` should return actual timestamp for the last value for the given time series.

**Comment by kernel164** [comment] 2020-12-11 17:42
Hello @valyala . Thanks for the explanation. I ended up using `timestamp(vital_hr{user_id="5fce28b3d77c0500087f3d24"}[24h])` but I have to query for `last_over_time({__name__=~"vital.*",user_id="5fce28b3d77c0500087f3d24"}[24h])` and iterate over each metric from the result and do http call to get latest timestamp using timestamp(). looks hacky workaround.

Is it not simply possible to get the latest value and timestamp in a single call? does /api/v1/export support to fetch last/latest record only for a given period of time.

**Comment by valyala** [comment] 2020-12-11 19:50
> Is it not simply possible to get the latest value and timestamp in a single call?

It is should be possible. Try the following [MetricsQL](https://victoriametrics.github.io/MetricsQL.html) query:

```metricsql
(
  alias(timestamp(vital_hr{user_id="5fce28b3d77c0500087f3d24"}[24h]), "timestamp"),
  last_over_time(vital_hr{user_id="5fce28b3d77c0500087f3d24"}[24h]),
)
```

It will return `vital_hr` and `timestamp` time series in a single response. Then you can match the returned time series by their labels.

**Comment by kernel164** [comment] 2020-12-15 17:28
Cool!. It works!. Thanks.

**Comment by kernel164** [comment] 2020-12-16 09:54
Hmm. In my case metrics are dynamic &/ multiple. so, this scenario not working.

```
metric1,id=1 xx=75 1608111416740000000
metric1,id=1 yy=96 1608111956780000000
```

```
(
  alias(timestamp({__name__=~"metric1.*",id="1"}[24h]), "timestamp"),
  last_over_time({__name__=~"metric1.*",id="1"}[24h]),
)
```
I have to use `metric1.*` to get all latest metrics for the period which can be dynamic. using above query, I get only one timestamp. but I need latest timestamp of each metric. i.e `(metric1_xx, 160811141674) & (metric1_yy, 160811195678)`

So, I'm currently falling back to my hacky workaround. strange that this simple case is not covered in tsdb.

**Comment by valyala** [comment] 2020-12-17 14:00
The `{__name__=~"metric1.*"}` query should select all the time series with names starting with `metric1`, i.e. `metric1_xx`, `metric1_yy`, `metric123`, etc. Try removing `id="1"` filter from the query above, since it filters out metrics without `id="1"` label.

**Comment by kernel164** [comment] 2020-12-17 14:31
id="1" is important filter for my usecase and I get all the metrics with `{__name__=~"metric1.*"}`, so that works fine. 
The problem is, I don't get latest timestamp for each metrics - I get only one timestamp for that query, as shown below.

```
timestamp: 160811141.674
metric1_xx 75
metric1_yy 96
```
as output.

but I need latest timestamp for each metric as shown below.
```
metric1_xx 75 160811141.674
metric1_yy 96 160811195.678
```

**Comment by valyala** [comment] 2020-12-17 15:58
Ah, I see the issue - `alias(m, "timestamp")` substitutes all the metric names with `timestamp` metric name. Then try the following request: 

```metricsql
(
  label_set(timestamp({__name__=~"metric1.*",id="1"}[24h]), "_type", "timestamp"),
  last_over_time({__name__=~"metric1.*",id="1"}[24h]),
)
```

It will set `_type="timestamp"` label to all the timestamps

**Comment by kernel164** [comment] 2020-12-17 16:10
I still don't get latest timestamp corresponding to each metrics.


*Metrics:*

```
metric1,id=1 xx=55 1608214816196000000
metric1,id=1 yy=90 1608215226205000000
```

*Query Output:*

```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "_type": "timestamp",
          "id": "1"
        },
        "value": [
          1608220886,
          "1608214816.196"
        ]
      },
      {
        "metric": {
          "__name__": "metric1_xx",
          "id": "1"
        },
        "value": [
          1608220886,
          "55"
        ]
      },
      {
        "metric": {
          "__name__": "metric1_yy",
          "id": "1"
        },
        "value": [
          1608220886,
          "90"
        ]
      }
    ]
  }
}
```

*Expecting following information in query results*

```
xx=55 1608214816.196
yy=90 1608215226.205
```

**Comment by valyala** [comment] 2020-12-18 11:22
It looks like `timestamp()` function strips metric name :( Try the following query then:

```metricsql
(
  timestamp(label_copy({__name__=~"metric1.*",id="1"}, "__name__", "timestamp")[24h:30s]),
  last_over_time({__name__=~"metric1.*",id="1"}[24h]),
)
```

It will round returned timestamps to 30 seconds according to `30s` value (aka `step`) in the subquery. See [docs about subqueries](https://valyala.medium.com/prometheus-subqueries-in-victoriametrics-9b1492b720b3) for more details. It is recommended setting this value to interval between samples in time series in order to reduce the rounding error. It isn't recommended setting `step` to smaller values smaller than scrape interval, since this may increase CPU usage and memory usage during query execution.

**Comment by kernel164** [comment] 2021-03-15 11:45
sorry to get back to this late.

in the above query, label_copy changes the returned timestamp value frequently. i.e its not even static, changes(increments) every few seconds.

```
(
  timestamp(label_copy({__name__=~"metric1.*",id="1"}, "__name__", "timestamp")[24h:30s]),
  last_over_time({__name__=~"metric1.*",id="1"}[24h]),
)
```

Without labelcopy, it returns wrong `1615808400` timestamp, it gets incremented after sometime when I run the same query again e.g. `1615808500`.

```
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "timestamp": "metric1_xx",
          "id": "1"
        },
        "value": [
          1615820886,
          "1615808400"
        ]
      },
      {
        "metric": {
          "__name__": "metric1_xx",
          "id": "1"
        },
        "value": [
          1615820886,
          "55"
        ]
      }
    ]
  }
}
```

Without labelcopy, it returns `1615807200` timestamp correctly but misses "__name__" label.

```
(
  timestamp({__name__=~"metric1.*",id="1"}[24h:30s]),
  last_over_time({__name__=~"metric1.*",id="1"}[24h]),
)
```

```
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "id": "1"
        },
        "value": [
          1615820886,
          "1615807200"
        ]
      },
      {
        "metric": {
          "__name__": "metric1_xx",
          "id": "1"
        },
        "value": [
          1615820886,
          "55"
        ]
      }
    ]
  }
}
```

**Comment by mactyr** [comment] 2021-12-09 17:33
I'm encountering this same need to know the latest value for a number of metrics along with the actual timestamps of the latest values -- this comes up quite often in my IoT application. For now, I am following the [suggestion](#issuecomment-743331613) to iterate over the results of `last_over_time()` to get each metric's `timestamp()` but it is pretty awkward and, I imagine, slower than getting the desired data in one query if such a thing were possible. (It doesn't seem like any of the later suggestions worked reliably for the issue reporter.)

Could MetricsQL have an extension like `last_over_time_with_timestamp()` that behaves like `last_over_time()` but returns the actual timestamps of the last points?

**Comment by valyala** [comment] 2021-12-15 21:20
> Could MetricsQL have an extension like last_over_time_with_timestamp() that behaves like last_over_time() but returns the actual timestamps of the last points?

I'd add `timestamp_with_name()` function, which will return the same values as `timestamp()`, but won't drop metric names from the output time series.

There is more general solution - to allow using [label manipulation functions](https://docs.victoriametrics.com/MetricsQL.html#label-manipulation-functions) inside [rollup functions](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) such as `timestamp()` without triggering [subquery behavior](https://docs.victoriametrics.com/MetricsQL.html#subqueries). In this case it will be possible moving the metric name to an additional label before applying `timestamp()` function and without losing timestamp precision for the returned data. Something like `timestamp(label_copy({__name__="metric"}, "__name__", "metirc_name")[24h])`

**Comment by mactyr** [comment] 2021-12-15 21:35
> I'd add timestamp_with_name() function, which will return the same values as timestamp(), but won't drop metric names from the output time series.

Ok, that'd be two queries for my use case (one for all the values, one for all the timestamps) which isn't as good as one query, but is definitely an improvement over `(number of metrics) + 1` queries! I'd be happy with that.

I did try the `label_copy` approach you mentioned and found that it didn't work, though I'm not expert enough yet to be able to explain to myself why, so thanks for clarifying that. If that could be made to work, that sounds good to me as well, from a "new user" perspective.

**Comment by valyala** [comment] 2021-12-15 21:40
The `timestamp_with_name()` function has been added in the commit 5efe377a26799210a3f974655a07af6b715a6c98 . It will be included in the next release of VictoriaMetrics. In the mean time it is possible to build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the function works as expected.

**Comment by valyala** [comment] 2021-12-15 21:45
>  that'd be two queries for my use case (one for all the values, one for all the timestamps) which isn't as good as one query

You can merge this into one query:

```metricsql
with (q = {some="filters",here=~"xyz"})
(
    label_set(last_over_time(q[1d]), "kind", "value"),
    label_set(timestamp_with_name(q[1d]), "kind", "timestamp"),
)
```

This query will return both values and timestamps for the given query `q`. Time series with values will have `kind="value"` additional label, while time series with timestamps will have `kind="timestamp"` additional label.

**Comment by mactyr** [comment] 2021-12-15 22:03
Aha, even better. Love it. Thanks.

**Comment by valyala** [comment] 2022-01-14 02:21
FYI, the commit 1bdc71d917f9d586aadff90b7a5ef9fd830633bb adds ability to specify `keep_metric_names` modifier to any [rollup function](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) or [transform function](https://docs.victoriametrics.com/MetricsQL.html#transform-functions). This modifier preserves the original metric names for functions, which delete metric names by default. For example, `timestamp({some="filters",here=~"xyz"}) keep_metric_names` is equivalent to `timestamp_with_name({some="filters",here=~"xyz"})`. This commit will be included in the next release of VictoriaMetrics. In the mean time it is possible to play with this feature by building VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by valyala** [comment] 2022-01-18 22:05
FYI, the `keep_metric_names` modifier can be applied to all the [rollup functions](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) and [transform functions](https://docs.victoriametrics.com/MetricsQL.html#transform-functions) starting from [VictoriaMetrics v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing this issue as fixed, since there are a few workarounds exist.

**Closed by valyala** 2022-01-18 22:05 UTC
Labels: question

**Comment by mactyr** [comment] 2022-02-01 21:58
Just confirmed that a query like this in VictoriaMetrics 1.72.0 gets me the data I need, at a price I can afford. Thanks again.

      with (q = myMetric{some="filters",here=~"xyz"}[5y])
      (
        label_set(last_over_time(q), "kind", "value"),
        label_set(timestamp(q) keep_metric_names, "kind", "timestamp"),
      )
