### ISSUE TITLE
incorrect binary operator result with string comparation

### ISSUE THREAD

**Issue by mxlxm** [VictoriaMetrics/VictoriaMetrics#717] opened 2020-08-24 12:00 UTC
**Describe the bug**
any query with a string comparation returns empty. 

**To Reproduce**
up AND on() ("x" == "x") 
up AND on() ("x" != "y")
up if ("y" == "y") 
// got nothing

**Expected behavior**
conditional query if given string equals or not.

**Version**
master

**Additional context**
usage: 
mixed datasource in Grafana, need this to do conditional query with variables. 

it seems `evalString` build a NaN array
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/10601bc6522f3ebd651cbed9f2d7348793b80c0a/app/vmselect/promql/eval.go#L823
and then all removed by `BinaryOpFunc`
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/10601bc6522f3ebd651cbed9f2d7348793b80c0a/app/vmselect/promql/binary_op.go#L102

**Comment by valyala** [comment] 2020-09-03 16:53
VictoriaMetrics should properly compare string literals starting from the commit e1c2757f70f67b0abfb4974aba008ca004252b9b (single-node version) and commit fcde009e11411efa878b6fe713364294205b0d47 (cluster version). These commits will be included into the next release.

@mxlxm , could you build VictoriaMetrics from the mentioned commits according to [these instructions](https://victoriametrics.github.io/#how-to-build-from-sources) and verify whether the issue is fixed there?

**Comment by valyala** [comment] 2020-09-04 00:16
The feature has been released in [v1.40.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it as done.

@mxlxm , feel free re-opening it if it doesn't work as expected for your case.

**Closed by valyala** 2020-09-04 00:16 UTC
Labels: enhancement

**Comment by mxlxm** [comment] 2020-09-04 00:23
It works. Thank you.
