### ISSUE TITLE
MetricsQL:  != operator ignored when querying __name__ with certain regex patterns

### ISSUE THREAD

**Issue by jduncan0000** [VictoriaMetrics/VictoriaMetrics#2238] opened 2022-02-23 02:16 UTC
**Describe the bug**

When executing query expressions with a specific regex selector on `__name__`, other selectors using `!=`  are ignored.

Example:

When running this query, metrics with job="victoriametrics" are returned in the results (not expected):
`{__name__=~"(vm_app_version|anything)",job!="victoriametrics"}`

Changing the regex matcher to something other than a literal string match seems to resolve the issue:
`{__name__=~"(vm_app_version|an.thing)",job!="victoriametrics"}`

**To Reproduce**
1.  Execute (instant or range) query with the following selectors:
     - regex match on `__name__` with pattern `__name__=~"(string1|string1)"`
     - not equal selector on a different label `job!="string1"`
2. Results will not honor the `job!="string1"` selector
3. Change the regex pattern to `__name__=~"(string1|st.ing1)"`
4. Results will honor the `job!="string1"` selector (expected behavior)

 

**Expected behavior**
Both of the above queries should return the same results and should not include results with job="victoriametrics"

**Logs**
None

**Screenshots**
Grafana - Query returns sample with job="victoriametrics" when it should not:
![image](https://user-images.githubusercontent.com/3580723/155249282-b668309b-e18f-46cc-be82-42c360b1f1ea.png)

Grafana - Expected results are returned after adding another regex character to the `__name__` matcher:
![image](https://user-images.githubusercontent.com/3580723/155249478-bcc4c2eb-f5d5-42c6-95ad-59952ef6e1a1.png)

**Version**
victoria-metrics-20220221-194700-heads-public-single-node-0-gf72b35665

**Comment by valyala** [comment] 2022-02-24 10:17
@jduncan0000 , thanks for the details and narrowed down bugreport! The issue should be fixed in the commit a16f1ae565415bf8225063b7235eae057f0ea6d2 . Could you build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the issue is gone there?

**Comment by jduncan0000** [comment] 2022-02-25 02:43
Hi, I tested and confirmed that the issue is fixed with that commit. Thanks for the quick response!

**Comment by valyala** [comment] 2022-03-03 18:27
@jduncan0000 , thanks for the confirmation!

The bugfix has been included in [VictoriaMetrics v1.74.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Closed by valyala** 2022-03-03 18:27 UTC
Labels: bug
