### ISSUE TITLE
vmagent  discovers targets for kubernetes role pods incorrectly

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1170] opened 2021-03-31 14:22 UTC
**Describe the bug**

 When job contains multiple namespaces, targets discovery becomes inconsistent - some ports are missing, if pod has multiple ports.

**To Reproduce**
```yaml
scrape_configs:
  - job_name: 'kubernetes-pods'

    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - tvpp-cis
        - tvpp-b2b-cis1
        - tvpp-b2b-cis2

    relabel_configs:
    - source_labels: [meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
      action: keep_if_equal
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_component]
      action: drop
      regex: (springboot|jboss)
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path
      regex: (.+)
    - source_labels: [address, meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_annotation_application_framework]
      action: replace
      target_label: application_framework
```
**Expected behavior**

 Must discover all targets.
**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
1.55 +
```

**Additional context**
```bash
v1.55.1 - VictoriaMetrics/lib/promscrape/scraper.go:353  kubernetes_sd_configs: added targets: 210, removed targets: 0; total targets: 210
v.1.56.0 -  VictoriaMetrics/lib/promscrape/scraper.go:359  kubernetes_sd_configs: added targets: 29, removed targets: 0; total targets: 29
v1.57.1 -  VictoriaMetrics/lib/promscrape/scraper.go:359  kubernetes_sd_configs: added targets: 58, removed targets: 0; total targets: 58
```
```bash
ports:
  - containerPort: 8080
  - containerPort: 9080
```

**Comment by lujiajing1126** [comment] 2021-04-01 10:08
@f41gh7 Would this issue cause `pod` label missing in some metrics, since we've observed this behavior recently.

**Comment by f41gh7** [comment] 2021-04-01 16:19
> @f41gh7 Would this issue cause `pod` label missing in some metrics, since we've observed this behavior recently.

 I'm not sure.

 This case related to kubernetes discovery, when you specify more then one namespace at job name, like:
```yaml
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - tvpp-cis
        - tvpp-b2b-cis1
```

 In this case only targets from one of namespaces will be added to the scraping.

**Comment by valyala** [comment] 2021-04-02 11:30
@f41gh7 , could you verify whether the issue is fixed by the commit 12e4785fe8dc64d6c4422725e833cefdab49d8f6 ?

**Comment by valyala** [comment] 2021-04-02 11:48
It has been appeared that the commit 12e4785fe8dc64d6c4422725e833cefdab49d8f6 could improperly track objects with identical names in different namespaces. This should be fixed in 5b08e6fb1695429c1785aeac67ff54fb34e3b911 .

**Comment by valyala** [comment] 2021-04-02 22:05
> Would this issue cause pod label missing in some metrics, since we've observed this behavior recently.

@lujiajing1126 , this can be related to the limit on the number of labels per metric VictoriaMetrics can accept. By default it is set to 30. It can be changed with `-maxLabelsPerTimeseries` command-line flag:

```
  -maxLabelsPerTimeseries int
        The maximum number of labels accepted per time series. Superfluous labels are dropped (default 30)
```

The number of dropped labels can be monitored with `vm_metrics_with_dropped_labels_total` metric if [montirong](https://victoriametrics.github.io/#monitoring) is set up for VictoriaMetrics.

**Comment by lujiajing1126** [comment] 2021-04-03 03:02
> > Would this issue cause pod label missing in some metrics, since we've observed this behavior recently.
> 
> @lujiajing1126 , this can be related to the limit on the number of labels per metric VictoriaMetrics can accept. By default it is set to 30. It can be changed with `-maxLabelsPerTimeseries` command-line flag:
> 
> ```
>   -maxLabelsPerTimeseries int
>         The maximum number of labels accepted per time series. Superfluous labels are dropped (default 30)
> ```
> 
> The number of dropped labels can be monitored with `vm_metrics_with_dropped_labels_total` metric if [montirong](https://victoriametrics.github.io/#monitoring) is set up for VictoriaMetrics.

![image](https://user-images.githubusercontent.com/2568208/113466116-c906a700-946b-11eb-9257-0d2aefb7cba3.png)

We are suffering from such cases. For the same metric, `pod` label is missing from only some of the `VMServiceScrape`s.

For this metric, we only have about 10 labels.

**Comment by valyala** [comment] 2021-04-03 23:07
> We are suffering from such issue: for the same metric, pod label is missing from only some of the VMServiceScrapes

This looks weird. @f41gh7 , could you look at it?

> BTW, vm_metrics_with_dropped_labels_total is shown as Rows dropped by relabeling?

No, the `vm_metrics_with_dropped_labels_total` is shown on the `Labels limit exceeded` graph in the `troubleshooting` section.

**Comment by valyala** [comment] 2021-04-08 07:26
`vmagent` should properly discover Kubernetes targets when multiple namespaces are specified in `kubernetes_sd_configs` starting from [v1.58.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Closed by valyala** 2021-04-08 07:26 UTC
Labels: bug, vmagent
