### ISSUE TITLE
Delete time series API doesn't work via Prometheus' client library

### ISSUE THREAD

**Issue by ashv1n** [VictoriaMetrics/VictoriaMetrics#766] opened 2020-09-14 06:00 UTC
**Is your feature request related to a problem? Please describe.**
I am using prometheus’ go client library and it looks like it’s DeleteSeries function doesn’t work well with VictoriaMetrics. I get this error at VM
`error in "/api/v1/admin/tsdb/delete_series": start and end aren't supported. Remove these args from the query in order to delete all the matching metrics`
But [DeleteSeries function](https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go#L638) needs start and end time.

**Describe the solution you'd like**
Add support for start and end time. 

**Describe alternatives you've considered**
Sending http request without using Prometheus client.

**Comment by belm0** [comment] 2020-09-15 01:16
duplicate of #164

**Comment by valyala** [comment] 2020-09-16 19:56
Closing as duplicate for #164 .

@belm0 , thanks for pointing to duplicate issue!

**Closed by valyala** 2020-09-16 19:56 UTC
Labels: enhancement
