### ISSUE TITLE
Different result same query to Prometheus and VictoriaMetrics

### ISSUE THREAD

**Issue by a-illiushchenia** [VictoriaMetrics/VictoriaMetrics#237] opened 2019-11-15 15:26 UTC
**Describe the bug**
I use same query to Prometheus and VictoriaMetrics in Grafana, but have different graphs in Grafana (see screenshots):
* graph in Prometheus higher (value = 2), but shorter (two times: 15:50:45 - 15:51:30, 15:51:45 - 15:52:30);
* graph in Prometheus lower (value = 1), but longer (one time: 15:50:45 - 15:53:00);

**To Reproduce**
Use one query to Prometheus and VictoriaMetrics

**Expected behavior**
Graphs must be same

**Screenshots**
Graph for prometheus:

![prometheus](https://user-images.githubusercontent.com/10823552/68948704-820e0800-07c9-11ea-873f-c855dff68204.png)

Graph for victoriaMetric:

![victoriaMetric](https://user-images.githubusercontent.com/10823552/68948722-89351600-07c9-11ea-83d8-26ea85f7dd36.png)

**Version**
victoria-metrics-20190822-120009-tags-v1.26.0-0-g1272e407

**Additional context**

**Comment by valyala** [comment] 2019-11-15 18:35
This issue can be related to the fact that Prometheus and VictoriaMetrics differently calculate `increase`:
- VictoriaMetrics always returns the difference between the last and the first raw data points on the interval from square brackets - `[1m]` in your case.
- Prometheus calculates interpolated value for `increase` - see https://github.com/prometheus/prometheus/issues/3746 .

IMHO, VictoriaMetrics' calculations are better than Prometheus' in this case, since they never return floating-point values for integer counter increase.

In order to prove the assumption, could you post graphs for the following query on both Prometheus and VictoriaMetrics on the same time range as graphs above?

```
ssw_log:counter:by_instance_level_source{job="ssw-log", level="E", instance="ss5-ss-prod-3:3903"}
```

This will allow calculating manually `increase` values according to the aforementioned algorithms for VictoriaMetrics and PRometheus.

**Comment by valyala** [comment] 2019-11-21 15:48
@a-illiushchenia , are there any updates?

**Comment by a-illiushchenia** [comment] 2019-11-22 08:07
Yes, and it is wery interesting:
I took enather interval:

1.  sum(ssw_log:counter:by_instance_level_source{job="ssw-log", level="E", instance="ss5-ss-prod-1:3903"})

We have increace 1 point and it dispay correct in Prometheus and VictoriaMetrics:

Prometheus:

![Prom_1](https://user-images.githubusercontent.com/10823552/69408290-985f1b00-0d17-11ea-966f-11cb279c7829.png)

![Prom_2](https://user-images.githubusercontent.com/10823552/69408303-9dbc6580-0d17-11ea-8fff-f25d4d18c818.png)

VictoriaMetrics:

![VictMetr_1](https://user-images.githubusercontent.com/10823552/69408326-a6ad3700-0d17-11ea-8646-12c388a2ce38.png)

![VictMetr_2](https://user-images.githubusercontent.com/10823552/69408347-b3ca2600-0d17-11ea-8bd6-26a15b7f905d.png)

2.  sum by (instance)(increase(ssw_log:counter:by_instance_level_source{job="ssw-log", level="E"}[1m]))

Prometheus:

![Prom_3](https://user-images.githubusercontent.com/10823552/69408444-f2f87700-0d17-11ea-96a5-17420bdf922d.png)

VictoriaMetrics:

![VictMetr_3](https://user-images.githubusercontent.com/10823552/69408466-fd1a7580-0d17-11ea-8eda-0be380c058a1.png)

**Comment by hagen1778** [comment] 2019-11-22 09:54
Hi @a-illiushchenia !
Which instance has that `2` increase on Prometheus pic? Could you pls compare sum and increase for that particular instance in both Prom and VM?

**Comment by lammel** [comment] 2019-11-25 11:05
We found the prometheus implementations of increase and delta pretty useless for our data, as the extrapolation performed in the functions does not deliver correct results, Usually actual increases in the metric are ignored.

This is why we replaced our queries

    sum(idelta(my_metrics{instance=~"$instance"}[$__interval]) by (something)

with:

    sum(my_metrics{instance=~"$instance"} - my_metrics{instance=~"$instance"} offset $__interval >= 0) by (something)

This (although requiring double lookups of the series) correct results and does not miss increases of a time series.

**Comment by valyala** [comment] 2019-11-25 19:02
@a-illiushchenia , the graphs show that Prometheus returns incorrect `+2` increase for the actual `+1` increase for the given time series. And the increase lasts for 30 seconds, while it should last for 1 minute according to `[1m]` time window passed to `increase()` function. VictoriaMetrics' graphs look correct.

@lammel , great solution! Note that the query can be improved with [`with` templates](https://victoriametrics.com/promql/expand-with-exprs) and `remove_resets()` function from [Extended PromQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL) in the following ways:
1) Mention `my_metric{instance=~"$instance"}` only once.
2) Remove possible counter resets.

The resulting query would look like:
```promql
with (
    q = remove_resets(my_metrics{instance=~"$instance"})
)
sum(q - q offset $__interval) by (something)
```

**Comment by lammel** [comment] 2019-11-27 20:30
@valyala , the extended promql looks very polished. We will look into VM soon with the prometheus remote write setup.

Do the increase/delta functions work correct without extrapolation in victoria metrics (can I assume no increase is missed)? 
From your update in prometheus [issue 3806#](https://github.com/prometheus/prometheus/issues/3806#issuecomment-457831932) I assume that VM delta function can be safely used, is efficient and correct.

**Comment by valyala** [comment] 2019-11-27 21:06
> Do the increase/delta functions work correct without extrapolation in victoria metrics (can I assume no increase is missed)?

Yes, both functions in VictoriaMetrics should return the exact increase / delta on the given time window in square brackets. If the time window is missing, then it is equal to `step` value - i.e. the interval between two adjacent points on the graph.

**Comment by valyala** [comment] 2019-11-27 21:08
As for PromQL, it is great, but unfortunately is cannot be used with [Promxy](https://github.com/jacksontj/promxy) yet, since it understands only standard PromQL :( There are plans to fix this in the future - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/56) for details.

**Comment by valyala** [comment] 2019-11-27 21:10
@a-illiushchenia , I'm going to close this issue as `working as intended`. Feel free re-opening it or adding additional details if you feel that VictoriaMetrics has issues with PromQL results.

**Closed by valyala** 2019-11-27 21:11 UTC
Labels: bug

**Comment by wentfar** [comment] 2022-08-15 04:39
> 

this do not process application restart that causes metric reset
