### ISSUE TITLE
Unexplained results of count_over_time and raw display of a metric in grafana

### ISSUE THREAD

**Issue by Vimao** [VictoriaMetrics/VictoriaMetrics#6773] opened 2024-08-07 09:33 UTC
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Querying VictoriaMetrics gives me unexplainable results.

I send one sample of a metric with a timestamp in epoch milliseconds, eg. a line of:

InteractionToNextPaint{LABELS_REDACTED} 192 1722351115718

Querying VM with either VMUI or Grafana gives me some weird results. If querying the result without any function:

![image](https://github.com/user-attachments/assets/15a32bac-2a7c-469d-ae99-76266b74193d)

i see the results extrapolated over the next 5 intervals.

Once i do count_over_time for it, the result is always 2, even though i sent just one sample.
![image](https://github.com/user-attachments/assets/46ea95b3-d5f8-40e4-a573-9eef3910cd6a)

Can you explain why do i see such results even though i sent just one sample?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment] 2024-08-08 04:38
Hi. Interesting questions.

For the first question (got 5 samples), it's related to: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/139 and 
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/3c02937a34719505df9d4661dd6f60f2a6e9ac18/app/vmselect/promql/rollup.go#L867 

In short, if you are using short step in query (e.g. 500ms), `maxPrevInterval` = 2500ms. VictoriaMetrics will generate datapoint for you if you have sample in the pass 2500ms, with a interval of 500ms.

For the 2nd question, I tested it but could not reproduce. Will take a look later.

**Comment by Vimao** [comment] 2024-08-08 06:27
Hello, thanks for the response. That does make sense in relation to the first part of my question.

For the second, maybe more details about my usecase will help.

I have a webapp that, whenever a user opens the page, saves some statistics to the S3 bucket. Each refresh is a new set of stats, with the timestamp of when they are created in epoch millis.

Those samples are then sent to VictoriaMetrics with basically 0 transformations.. So i would expect that if i open a webpage once in a period of time, count_over_time will show 1, instead of 2.

I am also currently on v1.101.0, cluster version.

**Comment by jiekun** [comment] 2024-08-08 06:39
Could you export those raw data following the doc here: https://docs.victoriametrics.com/url-examples/#apiv1export

I would like to test it on my local setup and see if I could help.

**Comment by Vimao** [comment] 2024-08-08 06:54
I exported this specific metric with the specific labels (i redacted some labels) that are on the screenshots and well, it seems like i might be ingesting it twice?

`{"metric":{"__name__":"InteractionToNextPaint","context_executor":"realUser","location_environment":"redacted","location_origin":"redacted","location_path":"redacted","location_region":"redacted","unit_centralReservationOfficeId":"NA","unit_propertyId":"redacted","unit_tenantId":"redacted"},"values":[192,192],"timestamps":[1722351115718,1722351115718]}`

So i'll need to look into my ingestion flow too i think

**Comment by jiekun** [comment] 2024-08-08 07:08
That's cool. So I think this issue could be closed as answered?

**Comment by Vimao** [comment] 2024-08-08 07:10
Yes, thanks for the help and sorry for taking your time!

**Closed** 2024-08-08 07:13 UTC
Labels: question, metricsql
