### ISSUE TITLE
avg_over_time() around max() fails unexpectedly

### ISSUE THREAD

**Issue by aarnej** [VictoriaMetrics/VictoriaMetrics#1914] opened 2021-12-08 09:49 UTC
**Describe the bug**
Executing a query `avg_over_time(max(non_existing_metric)[0.01s])` fails unexpectedly with an unexpected error message if step is equal to `0.01`. The metric apparently doesn't even have to exist to trigger the error.

When looking at the error message, some of the values for `start`, `end` and `step` don't seem to match with requested values.

`curl 'http://localhost:8428/api/v1/query_range' -d 'query=avg_over_time(max(non_existing_metric)[0.01s])&step=0.01&start=1638955484&end=1638955486'`

`{"status":"error","errorType":"422","error":"error when executing query=\"avg_over_time(max(non_existing_metric)[0.01s])\" on the time range (start=1638955484000, end=1638955486000, step=
10): cannot execute query: cannot evaluate \"avg_over_time(max(non_existing_metric)[0.01s])\": too many points for the given step=10, start=1638955183980 and end=1638955486010: 30204; can
not exceed -search.maxPointsPerTimeseries=30000"}`

**To Reproduce**
On an empty VM instance, execute the query above.

**Expected behavior**
The query shouldn't give an error.

**Logs**
No other errors in the logs apart from the one mentioned above.

**Screenshots**
NA

**Version**
`victoria-metrics-20211202-133618-tags-v1.70.0-0-g7f2f26b25`

**Used command-line flags**
`-storageDataPath /victoria-metrics-data -retentionPeriod=180d -memory.allowedPercent=30 -selfScrapeInterval=10s -search.minStalenessInterval=20s -search.cacheTimestampOffset=6m0s`

**Comment by hagen1778** [comment] 2021-12-09 06:54
Hi @aarnej!

> When looking at the error message, some of the values for start, end and step don't seem to match with requested values.

`start` and `end` params are the same, it is just you send it in seconds and VM log prints in milliseconds (extra 000).
The step changed indeed, which aligns with MetricsQL step adjustment:
```
In MetricsQL, a lookbehind window in square brackets may be omitted. VictoriaMetrics automatically selects the lookbehind window depending on the current step, so rate(node_network_receive_bytes_total) works just as rate(node_network_receive_bytes_total[$__interval]). And even if the interval is too small to capture enough data points, MetricsQL will automatically expand it.
```
Please note, interval expands up to the scrape_interval value (range between observations) to capture at least two datapoints for calculation.
Please, read more about this at [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html) or check the article about how [MetricsQL is different to PromQL](https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e).

**Comment by aarnej** [comment] 2021-12-09 07:50
Hi @hagen1778! Thanks for looking into this. 

I'm still puzzled a bit. For functions such as rate and deriv, looking back makes sense to me since a nearby historical  value can affect the outcome. But I'm not sure how that applies to functions used here. For max and avg_over_time (and max_over_time it turns out), automatic looking back seems unexpected. Intuitively, samples outside the user given range, in the lookback, should not affect the outcome for these functions. If they don't, is the lookback done nevertheless?

Also, the other thing that is unclear is why some related queries like `max(non_existing_metric)` and `max_over_time(non_existing_metric[1s])` do not produce the error message. Based on your explanation I would've assumed they did.

**Comment by aarnej** [comment] 2021-12-09 08:24
One additional observation: the latter `start` and `end` timestamps in the error messages seem to be about 5 minutes apart. Where this time comes from is unclear.

**Comment by hagen1778** [comment] 2021-12-13 15:45
Hi @aarnej! Sorry for the late reply!
I misread your initial question, my apologies. I'll try to answer questions in this reply.

> Executing a query avg_over_time(max(non_existing_metric)[0.01s]) fails unexpectedly with an unexpected error message if step is equal to 0.01. The metric apparently doesn't even have to exist to trigger the error.

I can confirm this. VM does additional alignment of `start` param for [subqueries](https://docs.victoriametrics.com/MetricsQL.html#subqueries) processing which accounts for `5m` of staleness interval. So the `start` in your example is shifted by `5m`. Because of this, the number of points for such a query will be `(end-start)/step)=30k`, which exceeds default value for flag `search.maxPointsPerTimeseries`. This calculation happens before running actual query - that's why you're getting error for non-existing metric.

@aarnej is this a real case you faced while working with VM? Can you elaborate more which problem are you trying to solve with this query?

@valyala is this essential to make a 5min shift for subqueries processing?

**Comment by aarnej** [comment] 2021-12-14 10:34
> @aarnej is this a real case you faced while working with VM? Can you elaborate more which problem are you trying to solve with this query?

Yes, it came up in actual use. The purpose of `max()` in the query `query avg_over_time(max(metric)[0.01s])` is to join consequtive time series into one. We use consequtive time series in attempt to reduce memory usage during querying. This is based on the observation that querying a long time series with a long range tends to use too much memory for our system. But if we split the long time series into smaller chunks, by adding labels like "month=june2021", and then join them during querying, we seem to be able to use longer ranges with the same data without exhausting the memory. For the high frequency metrics (that triggered the present issue), we wouldn't need long query ranges, but to keep our metrics injector simple, we add the chunking label to all the metrics at the moment, with `/api/v1/import/prometheus?extra_label=...`  We would gladly not use this artificial splitting if there is some other way to reduce memory usage.

Regarding the original issue itself, we found that setting  `-search.maxPointsPerTimeseries=40000` seems to fix the issue for us.

**Comment by valyala** [comment] 2021-12-14 12:33
> We use consequtive time series in attempt to reduce memory usage during querying. This is based on the observation that querying a long time series with a long range tends to use too much memory for our system. But if we split the long time series into smaller chunks, by adding labels like "month=june2021", and then join them during querying, we seem to be able to use longer ranges with the same data without exhausting the memory.

This is an interesting and smart workaround for the issue with high memory usage when querying high frequency series! See the related comment, which explains why VictoriaMetrics uses high amounts of memory for high-freqency series - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1067#issuecomment-780208906 .

If you need calculating the average value over multiple consecutive time series, then the following query should work faster and should need lower amounts of memory for processing:

```
sum(sum_over_time(metric)) / sum(count_over_time(metric))
```

This query doesn't trigger [subquery handling](https://docs.victoriametrics.com/MetricsQL.html#subqueries), since only [series selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors) is passed to the [rollup functions](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) used in the query - `sum_over_time` and `count_over_time`.

The duration in square brackets inside `*_over_time()` functions is optional - it is automatically set to the `step` value passed to `/api/v1/query_range` if it is missing. See [these docs](https://docs.victoriametrics.com/MetricsQL.html#implicit-query-conversions) for more details.

**Comment by aarnej** [comment] 2021-12-14 13:39
> If you need calculating the average value over multiple consecutive time series, then the following query should work faster and should need lower amounts of memory for processing:
> 
> ```
> sum(sum_over_time(metric)) / sum(count_over_time(metric))
> ```
> 
Thanks for the tip, @valyala! And I'm glad to see that reducing the memory usage for high frequency series is already being considered!

Regarding the original question, what do you think about the question @hagen1778 posted above? 

> is this essential to make a 5min shift for subqueries processing?

Although we were able to work around it, It feels like something that would be interesting to understand.

**Comment by valyala** [comment] 2024-02-13 20:27
The 5min shift is the default lookback window used when executing queries via [`/api/v1/query`](https://docs.victoriametrics.com/keyconcepts/#instant-query). It can be changed by passing different duration to `step` query arg there. For example, the request to `/api/v1/query?query=foo&step=1m&time=<timestamp>` returns the last [raw sample](https://docs.victoriametrics.com/keyconcepts/#raw-samples) value per each time series with the name `foo` on the interval `(timestamp - 1m ... timestamp]`.

Now, let me explain how does `avg_over_time(max(foo)[:0.01s])` work in VictoriaMetrics (note that I added `:` in front of `0.01s`, since otherwise the query shouldn't return any errors). This query is automatically transformed into [subquery](https://docs.victoriametrics.com/metricsql/#subqueries), since the `max(foo)` isn't a [series selector](https://docs.victoriametrics.com/keyconcepts/#filtering) - see [implicit query conversion rules](https://docs.victoriametrics.com/metricsql/#implicit-query-conversions) for details. So, VictoriaMetrics transforms this query into the following one before starting to execute it:

```metricsql
avg_over_time(
  max(
    default_rollup(foo)
  )[1i:0.01s]
)
```

The `1i` is replaced with `step=5m`:

```metricsql
avg_over_time(
  max(
    default_rollup(foo)
  )[5m:0.01s]
)
```

This query is executed in the following steps:

1. To select [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) for time series with the name `foo` on the time range `(time - 5m ... time]`, where `time` is the timestamp passed to [`/api/v1/query`](https://docs.victoriametrics.com/keyconcepts/#instant-query) (by default it equals to the current time).
2. To calculate `default_rollup(foo)` at the following timestamps: `time-5m`, `time-5m+0.01s`, `time-5m+2*0.01s`, ... , `time`. The number of such points equals to `5m/0.01s + 1 = 30001`. See [default_rollup](https://docs.victoriametrics.com/metricsql/#default_rollup) docs.
3. To calculate [`avg_over_time`](https://docs.victoriametrics.com/metricsql/#avg_over_time) over the calculated results at the previous step.

As you can see, the number of calculated samples per each matching [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) at the step 2 can be quite big. These samples are stored in RAM during query execution. That's why VictoriaMetrics limits the number of these samples with the `-search.maxPointsSubqueryPerTimeseries` command-line flag value (this flag has been added in VictoriaMetrics v1.81.0 - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2922 ). If you hit this limit, then just increase the value for `-search.maxPointsSubqueryPerTimeseries` command-line flag.

I suspect the calculations above aren't what you really wanted. It is likely you wanted calculating `max(max_over_time(some_metric[some_duration])))` or `max(avg_over_time(some_metric[some_duration])))`. Both queries are performed in a streaming manner by VictoriaMetrics, so they can process billions of samples over millions of time series without significant RAM usage. I recommend you reading [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html) in order to better understand how does it work.

Closing the issue as answered.

**Closed by valyala** 2024-02-13 20:27 UTC
Labels: question
