### ISSUE TITLE
cannot create txn directory ".../data/small/2023_03/txn": the ".../data/small/2023_03/txn" already exists

### ISSUE THREAD

**Issue by AnhaoROMA** [VictoriaMetrics/VictoriaMetrics#3979] opened 2023-03-20 06:36 UTC
### Describe the bug

When I look into the log-file, I found the VictoriaMetrics itself has some ERROR messages.

And these ERROR messages are identical:

```
2023-03-19T01:44:16.525160+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.524Z#011warn#011VictoriaMetrics/app/vminsert/main.go:166#011remoteAddr: "100.82.2.195:51486"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: error occurred during rows addition: cannot add rows to table: errors while adding rows to table "/var/lib/victoria-metrics-data/data": cannot create directories for small parts "/var/lib/victoria-metrics-data/data/small/2023_03": cannot create txn directory "/var/lib/victoria-metrics-data/data/small/2023_03/txn": the "/var/lib/victoria-metrics-data/data/small/2023_03/txn" already exists
2023-03-19T01:44:16.525289+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.525Z#011info#011VictoriaMetrics/lib/storage/partition.go:216#011creating a partition "2023_03" with smallPartsPath="/var/lib/victoria-metrics-data/data/small/2023_03", bigPartsPath="/var/lib/victoria-metrics-data/data/big/2023_03"
```

I have used VictoriaMetrics for several months, and this problem occurs **occasionally**. However, it will continuously write ERROR into log-file and fill the var-disk as the result. Maybe there is a hidden/concealed bug when creating partition.

### To Reproduce

I have used VictoriaMetrics for several months, and this problem occurs **occasionally**. However, it will continuously write ERROR into log-file and fill the var-disk as the result. Since it happens not that frequently, I have no idea how to reproduce.

### Version

The version that I am using is ```v1.88.1```.
```
$ ./victoria-metrics-prod --version
victoria-metrics-20230228-014443-tags-v1.88.1-0-g95e117342
```

### Logs

The last 9 lines from log-file are as below. 

```
2023-03-19T01:44:16.425665+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.425Z#011info#011VictoriaMetrics/lib/storage/partition.go:216#011creating a partition "2023_03" with smallPartsPath="/var/lib/victoria-metrics-data/data/small/2023_03", bigPartsPath="/var/lib/victoria-metrics-data/data/big/2023_03"
2023-03-19T01:44:16.425792+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.425Z#011warn#011VictoriaMetrics/app/vminsert/main.go:166#011remoteAddr: "100.82.2.108:7736"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: error occurred during rows addition: cannot add rows to table: errors while adding rows to table "/var/lib/victoria-metrics-data/data": cannot create directories for small parts "/var/lib/victoria-metrics-data/data/small/2023_03": cannot create txn directory "/var/lib/victoria-metrics-data/data/small/2023_03/txn": the "/var/lib/victoria-metrics-data/data/small/2023_03/txn" already exists
2023-03-19T01:44:16.433050+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.433Z#011info#011VictoriaMetrics/lib/storage/partition.go:216#011creating a partition "2023_03" with smallPartsPath="/var/lib/victoria-metrics-data/data/small/2023_03", bigPartsPath="/var/lib/victoria-metrics-data/data/big/2023_03"
2023-03-19T01:44:16.433162+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.433Z#011warn#011VictoriaMetrics/app/vminsert/main.go:166#011remoteAddr: "100.82.3.92:63623"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: error occurred during rows addition: cannot add rows to table: errors while adding rows to table "/var/lib/victoria-metrics-data/data": cannot create directories for small parts "/var/lib/victoria-metrics-data/data/small/2023_03": cannot create txn directory "/var/lib/victoria-metrics-data/data/small/2023_03/txn": the "/var/lib/victoria-metrics-data/data/small/2023_03/txn" already exists
2023-03-19T01:44:16.492923+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.492Z#011info#011VictoriaMetrics/lib/storage/partition.go:216#011creating a partition "2023_03" with smallPartsPath="/var/lib/victoria-metrics-data/data/small/2023_03", bigPartsPath="/var/lib/victoria-metrics-data/data/big/2023_03"
2023-03-19T01:44:16.493143+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.492Z#011warn#011VictoriaMetrics/app/vminsert/main.go:166#011remoteAddr: "100.82.2.195:3571"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: error occurred during rows addition: cannot add rows to table: errors while adding rows to table "/var/lib/victoria-metrics-data/data": cannot create directories for small parts "/var/lib/victoria-metrics-data/data/small/2023_03": cannot create txn directory "/var/lib/victoria-metrics-data/data/small/2023_03/txn": the "/var/lib/victoria-metrics-data/data/small/2023_03/txn" already exists
2023-03-19T01:44:16.524933+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.524Z#011info#011VictoriaMetrics/lib/storage/partition.go:216#011creating a partition "2023_03" with smallPartsPath="/var/lib/victoria-metrics-data/data/small/2023_03", bigPartsPath="/var/lib/victoria-metrics-data/data/big/2023_03"
2023-03-19T01:44:16.525160+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.524Z#011warn#011VictoriaMetrics/app/vminsert/main.go:166#011remoteAddr: "100.82.2.195:51486"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: error occurred during rows addition: cannot add rows to table: errors while adding rows to table "/var/lib/victoria-metrics-data/data": cannot create directories for small parts "/var/lib/victoria-metrics-data/data/small/2023_03": cannot create txn directory "/var/lib/victoria-metrics-data/data/small/2023_03/txn": the "/var/lib/victoria-metrics-data/data/small/2023_03/txn" already exists
2023-03-19T01:44:16.525289+00:00 vsa10461068 victoria-metrics-prod[1412]: 2023-03-19T01:44:16.525Z#011info#011VictoriaMetrics/lib/storage/partition.go:216#011creating a partition "2023_03" with smallPartsPath="/var/lib/victoria-metrics-data/data/small/2023_03", bigPartsPath="/var/lib/victoria-metrics-data/data/big/2023_03"
```

If you need more, I will provide more details.

**Comment by hagen1778** [comment] 2023-03-21 13:16
Hello!
Can you verify that `/var/lib/victoria-metrics-data/data/small/2023_03/txn` exists on disk for the vmstorage which emitted this error? 
Does it happen during regular data ingestion or during backfilling?

**Comment by hagen1778** [comment] 2023-03-26 18:05
Hello @AnhaoROMA!
Thanks for detailed response. One more question - does this happen only on start-up or during normal operation as well?

**Comment by AnhaoROMA** [comment] 2023-03-26 18:09
@hagen1778 
During normal operation.
And, everytime I re-start VictoriaMetrics when this problem happens, it can recover.

**Comment by valyala** [comment] 2023-03-27 21:23
> From the logs it looks like VM process first initied the data path, and only after that systemd mounted it.

This can lead to the `cannot create txn directory ... already exists` error if the following sequence of actions is performed:
1. Start VictoriaMetrics with `-storageDataPat=/var/lib/victoria-metrics-data`. The directory doesn't contain data for `2023_03` partition yet.
2. Mount some other volume at `/var/lib/victoria-metrics-data` with the existing VictoriaMetrics data at `2023_03` partition
3. Try sending samples for March 2023 to VictoriaMetrics. It will try creating a directory for `2023_03` partition, since it isn't aware that the partition already exists after the step 2. VictoriaMetrics will emit `cannot create txn directory .... already exists` error in this case every time it receives new sample for `2023_03` partition.

The solution is to make sure that the `/var/lib/victoria-metrics-data` directory is successfully mounted before VictoriaMetrics starts. Also make sure that the contents of the directory pointed by `-storageDataPath` isn't changed by a third-party app when VictoriaMetrics runs.

**Comment by AnhaoROMA** [comment] 2023-03-28 01:05
@hagen1778 
I mounted a 500 GB NFS volume to ```/var/lib/victoria-metrics-data```.

**Comment by hagen1778** [comment] 2023-03-28 07:29
@AnhaoROMA how exactly mounting is performed? Do you mount the NFS disk on system start?
Is there possibility that VM process start and disk mount are happening concurrently? Or is that mount changing over time while VM process continues to work?

It is very likely the problem is in FS, not in VM process. I'd recommend checking the mount settings. If possible, avoid using NFS.

**Comment by AnhaoROMA** [comment] 2023-03-28 07:34
@hagen1778
I have added this item into ```/etc/fstab```.

**Comment by AnhaoROMA** [comment] 2023-03-28 11:14
@zekker6 
Great, thanks!

**Comment by AnhaoROMA** [comment] 2023-04-13 13:26
@zekker6 @hagen1778 
Yes, you are right. Today I found that the volume was mounted after (while it should be before) VictoriaMetrics began to writting data into that mount point.

**Comment by zekker6** [comment] 2023-04-20 11:12
Going to close this as original issue have been resolved, feel free to reopen if new questions will arise.

**Closed by zekker6** 2023-04-20 11:12 UTC
Labels: question
