### ISSUE TITLE
vmagent: 403 error while scraping with bearer_token

### ISSUE THREAD

**Issue by virtualb0x** [VictoriaMetrics/VictoriaMetrics#3253] opened 2022-10-20 12:12 UTC
**Describe the bug**
I've receive 403 error while trying to scrpape hashicorp vault metrics endpoint via vmagent.

I have got prometheus and victoriametrics deployments in k8s cluster. I have identical scrape_configs for boths pods (vmagent and prometheus):

```
- job_name: vault
  metrics_path: /v1/sys/metrics
  params:
    format:
    - prometheus
  scheme: https
  bearer_token: hvs.CAESIC_Rm1HPfXz2HcQ7B2OH_mybearertokenstringendshere
  static_configs:
  - targets:
    - vault.hashicorp.svc.cluster.local:8200

```

But if prometheus returns 1 for availability of metrics endpoint, so vmagent always returns 0
I've found the error log:
2022-10-20T12:05:49.658Z warn VictoriaMetrics/lib/promscrape/scrapework.go:388 cannot scrape \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\" (job \"vault\", labels {instance=\"vault.hashicorp.svc.cluster.local:8200\",job=\"vault\"}): cannot read data: unexpected status code returned when scraping \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\": 403; expecting 200; response body: \"{\\\"errors\\\":[\\\"permission denied\\\"]}\\n\"\n"

It seems like vmagent doesn't put bearer_token. But  I do not know how  to explore problem exactly

**To Reproduce**
Move scrape config for hashicorp vauult from prometheus to vm agent and receive 0  for availability
**Expected behavior**
VMagent returns metrics for hashicorp vault according to https://developer.hashicorp.com/vault/docs/configuration/telemetry#prometheus

**Logs**
2022-10-20T12:05:49.658Z warn VictoriaMetrics/lib/promscrape/scrapework.go:388 cannot scrape \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\" (job \"vault\", labels {instance=\"vault.hashicorp.svc.cluster.local:8200\",job=\"vault\"}): cannot read data: unexpected status code returned when scraping \"http://vault.hashicorp.svc.cluster.local:8200/v1/sys/metrics?format=prometheus\": 403; expecting 200; response body: \"{\\\"errors\\\":[\\\"permission denied\\\"]}\\n\"\n"

**Version**
1.82.0

**Comment by valyala** [comment] 2022-10-29 01:15
@denisgolius , could you try reproducing this issue?

**Comment by virtualb0x** [comment] 2022-11-15 06:17
Is my case like https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3317 ?
Can I help to investigate it somehow?

**Comment by valyala** [comment] 2022-11-21 14:39
@virtualb0x , thanks for linking to the related issue! Let's close this issue as a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3317 , since the linked issue contains more details on why `vmagent` fails to scrape Consul targets (e.g. it doesn't persist the configured auth tokens if scrape target performs redirect).

**Closed by valyala** 2022-11-21 14:39 UTC
Labels: bug, vmagent
