### ISSUE TITLE
Seems victoria improper return datapoint when requested with __graphite__

### ISSUE THREAD

**Issue by tantra35** [VictoriaMetrics/VictoriaMetrics#1396] opened 2021-06-18 23:20 UTC
**Describe the bug**
Suppose we have only 2 datapoints;

1. at 12:30  with value 42
2. at  15:30 with value also 42

then we try to get data points in interval between 12:30 and 15:30, also we set step parameter to 20 seconds, and expect got only 2 meaning points at 12:30 and 15:30 in other points we expected to see null, but not with request:

`http://victoria-a.service.atf01.consul:2022/api/v1/query_range?end=1623866459&query=%7B__graphite__%3D%22test.ruslan.foo.bar%22%7D&start=1623831955&step=20s`

we got many points with the same value 42:

```
"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"test.ruslan.foo.bar"},"values":[[1623835800,"42"],[1623835820,"42"],[1623835840,"42"],[1623835860,"42"],[1623835880,"42"],[1623835900,"42"],[1623835920,"42"],[1623835940,"42"],[1623835960,"42"],[1623835980,"42"],[1623836000,"42"],[1623836020,"42"],[1623836040,"42"],[1623836060,"42"],[1623836080,"42"],[1623836100,"42"],[1623836120,"42"],[1623836140,"42"],[1623836160,"42"],[1623836180,"42"],[1623836200,"42"],[1623836220,"42"],[1623836240,"42"],[1623836260,"42"],[1623836280,"42"],[1623836300,"42"],[1623836320,"42"],[1623836340,"42"],[1623836360,"42"],[1623836380,"42"],[1623836400,"42"],[1623836420,"42"],[1623836440,"42"],[1623836460,"42"],[1623836480,"42"],[1623836500,"42"],[1623836520,"42"],[1623836540,"42"],[1623836560,"42"],[1623836580,"42"],[1623836600,"42"],[1623836620,"42"],[1623836640,"42"],[1623836660,"42"],[1623836680,"42"],[1623836700,"42"],[1623836720,"42"],[1623836740,"42"],[1623836760,"42"],[1623836780,"42"],[1623836800,"42"],[1623836820,"42"],[1623836840,"42"],[1623836860,"42"],[1623836880,"42"],[1623836900,"42"],[1623836920,"42"],[1623836940,"42"],[1623836960,"42"],[1623836980,"42"],[1623837000,"42"],[1623837020,"42"],[1623837040,"42"],[1623837060,"42"],[1623837080,"42"],[1623837100,"42"],[1623837120,"42"],[1623837140,"42"],[1623837160,"42"],[1623837180,"42"],[1623837200,"42"],[1623837220,"42"],[1623837240,"42"],[1623837260,"42"],[1623837280,"42"],[1623837300,"42"],[1623837320,"42"],[1623837340,"42"],[1623837360,"42"],[1623837380,"42"],[1623837400,"42"],[1623837420,"42"],[1623837440,"42"],[1623837460,"42"],[1623837480,"42"],[1623837500,"42"],[1623837520,"42"],[1623837540,"42"],[1623837560,"42"],[1623837580,"42"],[1623837600,"42"],[1623837620,"42"],[1623837640,"42"],[1623837660,"42"],[1623837680,"42"],[1623837700,"42"],[1623837720,"42"],[1623837740,"42"],[1623837760,"42"],[1623837780,"42"],[1623837800,"42"],[1623837820,"42"],[1623837840,"42"],[1623837860,"42"],[1623837880,"42"],[1623837900,"42"],[1623837920,"42"],[1623837940,"42"],[1623837960,"42"],[1623837980,"42"],[1623838000,"42"],[1623838020,"42"],[1623838040,"42"],[1623838060,"42"],[1623838080,"42"],[1623838100,"42"],[1623838120,"42"],[1623838140,"42"],[1623838160,"42"],[1623838180,"42"],[1623838200,"42"],[1623838220,"42"],[1623838240,"42"],[1623838260,"42"],[1623838280,"42"],[1623838300,"42"],[1623838320,"42"],[1623838340,"42"],[1623838360,"42"],[1623838380,"42"],[1623838400,"42"],[1623838420,"42"],[1623838440,"42"],[1623838460,"42"],[1623838480,"42"],[1623838500,"42"],[1623838520,"42"],[1623838540,"42"],[1623838560,"42"],[1623838580,"42"],[1623838600,"42"],[1623838620,"42"],[1623838640,"42"],[1623838660,"42"],[1623838680,"42"],[1623838700,"42"],[1623838720,"42"],[1623838740,"42"],[1623838760,"42"],[1623838780,"42"],[1623838800,"42"],[1623838820,"42"],[1623838840,"42"],[1623838860,"42"],[1623838880,"42"],[1623838900,"42"],[1623838920,"42"],[1623838940,"42"],[1623838960,"42"],[1623838980,"42"],[1623839000,"42"],[1623839020,"42"],[1623839040,"42"],[1623839060,"42"],[1623839080,"42"],[1623839100,"42"],[1623839120,"42"],[1623839140,"42"],[1623839160,"42"],[1623839180,"42"],[1623839200,"42"],[1623839220,"42"],[1623839240,"42"],[1623839260,"42"],[1623839280,"42"],[1623839300,"42"],[1623839320,"42"],[1623839340,"42"],[1623839360,"42"],[1623839380,"42"],[1623839400,"42"],[1623839420,"42"],[1623839440,"42"],[1623839460,"42"],[1623839480,"42"],[1623839500,"42"],[1623839520,"42"],[1623839540,"42"],[1623839560,"42"],[1623839580,"42"],[1623839600,"42"],[1623839620,"42"],[1623839640,"42"],[1623839660,"42"],[1623839680,"42"],[1623839700,"42"],[1623839720,"42"],[1623839740,"42"],[1623839760,"42"],[1623839780,"42"],[1623839800,"42"],[1623839820,"42"],[1623839840,"42"],[1623839860,"42"],[1623839880,"42"],[1623839900,"42"],[1623839920,"42"],[1623839940,"42"],[1623839960,"42"],[1623839980,"42"],[1623840000,"42"],[1623840020,"42"],[1623840040,"42"],[1623840060,"42"],[1623840080,"42"],[1623840100,"42"],[1623840120,"42"],[1623840140,"42"],[1623840160,"42"],[1623840180,"42"],[1623840200,"42"],[1623840220,"42"],[1623840240,"42"],[1623840260,"42"],[1623840280,"42"],[1623840300,"42"],[1623840320,"42"],[1623840340,"42"],[1623840360,"42"],[1623840380,"42"],[1623840400,"42"],[1623840420,"42"],[1623840440,"42"],[1623840460,"42"],[1623840480,"42"],[1623840500,"42"],[1623840520,"42"],[1623840540,"42"],[1623840560,"42"],[1623840580,"42"],[1623840600,"42"],[1623840620,"42"],[1623840640,"42"],[1623840660,"42"],[1623840680,"42"],[1623840700,"42"],[1623840720,"42"],[1623840740,"42"],[1623840760,"42"],[1623840780,"42"],[1623840800,"42"],[1623840820,"42"],[1623840840,"42"],[1623840860,"42"],[1623840880,"42"],[1623840900,"42"],[1623840920,"42"],[1623840940,"42"],[1623840960,"42"],[1623840980,"42"],[1623841000,"42"],[1623841020,"42"],[1623841040,"42"],[1623841060,"42"],[1623841080,"42"],[1623841100,"42"],[1623841120,"42"],[1623841140,"42"],[1623841160,"42"],[1623841180,"42"],[1623841200,"42"],[1623841220,"42"],[1623841240,"42"],[1623841260,"42"],[1623841280,"42"],[1623841300,"42"],[1623841320,"42"],[1623841340,"42"],[1623841360,"42"],[1623841380,"42"],[1623841400,"42"],[1623841420,"42"],[1623841440,"42"],[1623841460,"42"],[1623841480,"42"],[1623841500,"42"],[1623841520,"42"],[1623841540,"42"],[1623841560,"42"],[1623841580,"42"],[1623841600,"42"],[1623841620,"42"],[1623841640,"42"],[1623841660,"42"],[1623841680,"42"],[1623841700,"42"],[1623841720,"42"],[1623841740,"42"],[1623841760,"42"],[1623841780,"42"],[1623841800,"42"],[1623841820,"42"],[1623841840,"42"],[1623841860,"42"],[1623841880,"42"],[1623841900,"42"],[1623841920,"42"],[1623841940,"42"],[1623841960,"42"],[1623841980,"42"],[1623842000,"42"],[1623842020,"42"],[1623842040,"42"],[1623842060,"42"],[1623842080,"42"],[1623842100,"42"],[1623842120,"42"],[1623842140,"42"],[1623842160,"42"],[1623842180,"42"],[1623842200,"42"],[1623842220,"42"],[1623842240,"42"],[1623842260,"42"],[1623842280,"42"],[1623842300,"42"],[1623842320,"42"],[1623842340,"42"],[1623842360,"42"],[1623842380,"42"],[1623842400,"42"],[1623842420,"42"],[1623842440,"42"],[1623842460,"42"],[1623842480,"42"],[1623842500,"42"],[1623842520,"42"],[1623842540,"42"],[1623842560,"42"],[1623842580,"42"],[1623842600,"42"],[1623842620,"42"],[1623842640,"42"],[1623842660,"42"],[1623842680,"42"],[1623842700,"42"],[1623842720,"42"],[1623842740,"42"],[1623842760,"42"],[1623842780,"42"],[1623842800,"42"],[1623842820,"42"],[1623842840,"42"],[1623842860,"42"],[1623842880,"42"],[1623842900,"42"],[1623842920,"42"],[1623842940,"42"],[1623842960,"42"],[1623842980,"42"],[1623843000,"42"],[1623843020,"42"],[1623843040,"42"],[1623843060,"42"],[1623843080,"42"],[1623843100,"42"],[1623843120,"42"],[1623843140,"42"],[1623843160,"42"],[1623843180,"42"],[1623843200,"42"],[1623843220,"42"],[1623843240,"42"],[1623843260,"42"],[1623843280,"42"],[1623843300,"42"],[1623843320,"42"],[1623843340,"42"],[1623843360,"42"],[1623843380,"42"],[1623843400,"42"],[1623843420,"42"],[1623843440,"42"],[1623843460,"42"],[1623843480,"42"],[1623843500,"42"],[1623843520,"42"],[1623843540,"42"],[1623843560,"42"],[1623843580,"42"],[1623843600,"42"],[1623843620,"42"],[1623843640,"42"],[1623843660,"42"],[1623843680,"42"],[1623843700,"42"],[1623843720,"42"],[1623843740,"42"],[1623843760,"42"],[1623843780,"42"],[1623843800,"42"],[1623843820,"42"],[1623843840,"42"],[1623843860,"42"],[1623843880,"42"],[1623843900,"42"],[1623843920,"42"],[1623843940,"42"],[1623843960,"42"],[1623843980,"42"],[1623844000,"42"],[1623844020,"42"],[1623844040,"42"],[1623844060,"42"],[1623844080,"42"],[1623844100,"42"],[1623844120,"42"],[1623844140,"42"],[1623844160,"42"],[1623844180,"42"],[1623844200,"42"],[1623844220,"42"],[1623844240,"42"],[1623844260,"42"],[1623844280,"42"],[1623844300,"42"],[1623844320,"42"],[1623844340,"42"],[1623844360,"42"],[1623844380,"42"],[1623844400,"42"],[1623844420,"42"],[1623844440,"42"],[1623844460,"42"],[1623844480,"42"],[1623844500,"42"],[1623844520,"42"],[1623844540,"42"],[1623844560,"42"],[1623844580,"42"],[1623844600,"42"],[1623844620,"42"],[1623844640,"42"],[1623844660,"42"],[1623844680,"42"],[1623844700,"42"],[1623844720,"42"],[1623844740,"42"],[1623844760,"42"],[1623844780,"42"],[1623844800,"42"],[1623844820,"42"],[1623844840,"42"],[1623844860,"42"],[1623844880,"42"],[1623844900,"42"],[1623844920,"42"],[1623844940,"42"],[1623844960,"42"],[1623844980,"42"],[1623845000,"42"],[1623845020,"42"],[1623845040,"42"],[1623845060,"42"],[1623845080,"42"],[1623845100,"42"],[1623845120,"42"],[1623845140,"42"],[1623845160,"42"],[1623845180,"42"],[1623845200,"42"],[1623845220,"42"],[1623845240,"42"],[1623845260,"42"],[1623845280,"42"],[1623845300,"42"],[1623845320,"42"],[1623845340,"42"],[1623845360,"42"],[1623845380,"42"],[1623845400,"42"],[1623845420,"42"],[1623845440,"42"],[1623845460,"42"],[1623845480,"42"],[1623845500,"42"],[1623845520,"42"],[1623845540,"42"],[1623845560,"42"],[1623845580,"42"],[1623845600,"42"],[1623845620,"42"],[1623845640,"42"],[1623845660,"42"],[1623845680,"42"],[1623845700,"42"],[1623845720,"42"],[1623845740,"42"],[1623845760,"42"],[1623845780,"42"],[1623845800,"42"],[1623845820,"42"],[1623845840,"42"],[1623845860,"42"],[1623845880,"42"],[1623845900,"42"],[1623845920,"42"],[1623845940,"42"],[1623845960,"42"],[1623845980,"42"],[1623846000,"42"],[1623846020,"42"],[1623846040,"42"],[1623846060,"42"],[1623846080,"42"],[1623846100,"42"],[1623846120,"42"],[1623846140,"42"],[1623846160,"42"],[1623846180,"42"],[1623846200,"42"],[1623846220,"42"],[1623846240,"42"],[1623846260,"42"],[1623846280,"42"],[1623846300,"42"],[1623846320,"42"],[1623846340,"42"],[1623846360,"42"],[1623846380,"42"],[1623846400,"42"],[1623846420,"42"],[1623846440,"42"],[1623846460,"42"],[1623846480,"42"],[1623846500,"42"],[1623846520,"42"],[1623846540,"42"],[1623846560,"42"],[1623846580,"42"],[1623846600,"42"],[1623846620,"42"],[1623846640,"42"],[1623846660,"42"],[1623846680,"42"],[1623846700,"42"],[1623846720,"42"],[1623846740,"42"],[1623846760,"42"],[1623846780,"42"],[1623846800,"42"],[1623846820,"42"],[1623846840,"42"],[1623846860,"42"],[1623846880,"42"],[1623846900,"42"],[1623846920,"42"],[1623846940,"42"],[1623846960,"42"],[1623846980,"42"],[1623847000,"42"],[1623847020,"42"],[1623847040,"42"],[1623847060,"42"],[1623847080,"42"],[1623847100,"42"],[1623847120,"42"],[1623847140,"42"],[1623847160,"42"],[1623847180,"42"],[1623847200,"42"],[1623847220,"42"],[1623847240,"42"],[1623847260,"42"],[1623847280,"42"],[1623847300,"42"],[1623847320,"42"],[1623847340,"42"],[1623847360,"42"],[1623847380,"42"],[1623847400,"42"],[1623847420,"42"],[1623847440,"42"],[1623847460,"42"],[1623847480,"42"],[1623847500,"42"],[1623847520,"42"],[1623847540,"42"],[1623847560,"42"],[1623847580,"42"],[1623847600,"42"],[1623847620,"42"],[1623847640,"42"],[1623847660,"42"],[1623847680,"42"],[1623847700,"42"],[1623847720,"42"],[1623847740,"42"],[1623847760,"42"],[1623847780,"42"],[1623847800,"42"],[1623847820,"42"],[1623847840,"42"],[1623847860,"42"],[1623847880,"42"],[1623847900,"42"],[1623847920,"42"],[1623847940,"42"],[1623847960,"42"],[1623847980,"42"],[1623848000,"42"],[1623848020,"42"],[1623848040,"42"],[1623848060,"42"],[1623848080,"42"],[1623848100,"42"],[1623848120,"42"],[1623848140,"42"],[1623848160,"42"],[1623848180,"42"],[1623848200,"42"],[1623848220,"42"],[1623848240,"42"],[1623848260,"42"],[1623848280,"42"],[1623848300,"42"],[1623848320,"42"],[1623848340,"42"],[1623848360,"42"],[1623848380,"42"],[1623848400,"42"],[1623848420,"42"],[1623848440,"42"],[1623848460,"42"],[1623848480,"42"],[1623848500,"42"],[1623848520,"42"],[1623848540,"42"],[1623848560,"42"],[1623848580,"42"],[1623848600,"42"],[1623848620,"42"],[1623848640,"42"],[1623848660,"42"],[1623848680,"42"],[1623848700,"42"],[1623848720,"42"],[1623848740,"42"],[1623848760,"42"],[1623848780,"42"],[1623848800,"42"],[1623848820,"42"],[1623848840,"42"],[1623848860,"42"],[1623848880,"42"],[1623848900,"42"],[1623848920,"42"],[1623848940,"42"],[1623848960,"42"],[1623848980,"42"],[1623849000,"42"],[1623849020,"42"],[1623849040,"42"],[1623849060,"42"],[1623849080,"42"],[1623849100,"42"],[1623849120,"42"],[1623849140,"42"],[1623849160,"42"],[1623849180,"42"],[1623849200,"42"],[1623849220,"42"],[1623849240,"42"],[1623849260,"42"],[1623849280,"42"],[1623849300,"42"],[1623849320,"42"],[1623849340,"42"],[1623849360,"42"],[1623849380,"42"],[1623849400,"42"],[1623849420,"42"],[1623849440,"42"],[1623849460,"42"],[1623849480,"42"],[1623849500,"42"],[1623849520,"42"],[1623849540,"42"],[1623849560,"42"],[1623849580,"42"],[1623849600,"42"],[1623849620,"42"],[1623849640,"42"],[1623849660,"42"],[1623849680,"42"],[1623849700,"42"],[1623849720,"42"],[1623849740,"42"],[1623849760,"42"],[1623849780,"42"],[1623849800,"42"],[1623849820,"42"],[1623849840,"42"],[1623849860,"42"],[1623849880,"42"],[1623849900,"42"],[1623849920,"42"],[1623849940,"42"],[1623849960,"42"],[1623849980,"42"],[1623850000,"42"],[1623850020,"42"],[1623850040,"42"],[1623850060,"42"],[1623850080,"42"],[1623850100,"42"],[1623850120,"42"],[1623850140,"42"],[1623850160,"42"],[1623850180,"42"],[1623850200,"42"],[1623850220,"42"],[1623850240,"42"],[1623850260,"42"],[1623850280,"42"],[1623850300,"42"],[1623850320,"42"],[1623850340,"42"],[1623850360,"42"],[1623850380,"42"],[1623850400,"42"],[1623850420,"42"],[1623850440,"42"],[1623850460,"42"],[1623850480,"42"],[1623850500,"42"],[1623850520,"42"],[1623850540,"42"],[1623850560,"42"],[1623850580,"42"],[1623850600,"42"],[1623850620,"42"],[1623850640,"42"],[1623850660,"42"],[1623850680,"42"],[1623850700,"42"],[1623850720,"42"],[1623850740,"42"],[1623850760,"42"],[1623850780,"42"],[1623850800,"42"],[1623850820,"42"],[1623850840,"42"],[1623850860,"42"],[1623850880,"42"],[1623850900,"42"],[1623850920,"42"],[1623850940,"42"],[1623850960,"42"],[1623850980,"42"],[1623851000,"42"],[1623851020,"42"],[1623851040,"42"],[1623851060,"42"],[1623851080,"42"],[1623851100,"42"],[1623851120,"42"],[1623851140,"42"],[1623851160,"42"],[1623851180,"42"],[1623851200,"42"],[1623851220,"42"],[1623851240,"42"],[1623851260,"42"],[1623851280,"42"],[1623851300,"42"],[1623851320,"42"],[1623851340,"42"],[1623851360,"42"],[1623851380,"42"],[1623851400,"42"],[1623851420,"42"],[1623851440,"42"],[1623851460,"42"],[1623851480,"42"],[1623851500,"42"],[1623851520,"42"],[1623851540,"42"],[1623851560,"42"],[1623851580,"42"],[1623851600,"42"],[1623851620,"42"],[1623851640,"42"],[1623851660,"42"],[1623851680,"42"],[1623851700,"42"],[1623851720,"42"],[1623851740,"42"],[1623851760,"42"],[1623851780,"42"],[1623851800,"42"],[1623851820,"42"],[1623851840,"42"],[1623851860,"42"],[1623851880,"42"],[1623851900,"42"],[1623851920,"42"],[1623851940,"42"],[1623851960,"42"],[1623851980,"42"],[1623852000,"42"],[1623852020,"42"],[1623852040,"42"],[1623852060,"42"],[1623852080,"42"],[1623852100,"42"],[1623852120,"42"],[1623852140,"42"],[1623852160,"42"],[1623852180,"42"],[1623852200,"42"],[1623852220,"42"],[1623852240,"42"],[1623852260,"42"],[1623852280,"42"],[1623852300,"42"],[1623852320,"42"],[1623852340,"42"],[1623852360,"42"],[1623852380,"42"],[1623852400,"42"],[1623852420,"42"],[1623852440,"42"],[1623852460,"42"],[1623852480,"42"],[1623852500,"42"],[1623852520,"42"],[1623852540,"42"],[1623852560,"42"],[1623852580,"42"],[1623852600,"42"],[1623852620,"42"],[1623852640,"42"],[1623852660,"42"],[1623852680,"42"],[1623852700,"42"],[1623852720,"42"],[1623852740,"42"],[1623852760,"42"],[1623852780,"42"],[1623852800,"42"],[1623852820,"42"],[1623852840,"42"],[1623852860,"42"],[1623852880,"42"],[1623852900,"42"],[1623852920,"42"],[1623852940,"42"],[1623852960,"42"],[1623852980,"42"],[1623853000,"42"],[1623853020,"42"],[1623853040,"42"],[1623853060,"42"],[1623853080,"42"],[1623853100,"42"],[1623853120,"42"],[1623853140,"42"],[1623853160,"42"],[1623853180,"42"],[1623853200,"42"],[1623853220,"42"],[1623853240,"42"],[1623853260,"42"],[1623853280,"42"],[1623853300,"42"],[1623853320,"42"],[1623853340,"42"],[1623853360,"42"],[1623853380,"42"],[1623853400,"42"],[1623853420,"42"],[1623853440,"42"],[1623853460,"42"],[1623853480,"42"],[1623853500,"42"],[1623853520,"42"],[1623853540,"42"],[1623853560,"42"],[1623853580,"42"],[1623853600,"42"],[1623853620,"42"],[1623853640,"42"],[1623853660,"42"],[1623853680,"42"],[1623853700,"42"],[1623853720,"42"],[1623853740,"42"],[1623853760,"42"],[1623853780,"42"],[1623853800,"42"],[1623853820,"42"],[1623853840,"42"],[1623853860,"42"],[1623853880,"42"],[1623853900,"42"],[1623853920,"42"],[1623853940,"42"],[1623853960,"42"],[1623853980,"42"],[1623854000,"42"],[1623854020,"42"],[1623854040,"42"],[1623854060,"42"],[1623854080,"42"],[1623854100,"42"],[1623854120,"42"],[1623854140,"42"],[1623854160,"42"],[1623854180,"42"],[1623854200,"42"],[1623854220,"42"],[1623854240,"42"],[1623854260,"42"],[1623854280,"42"],[1623854300,"42"],[1623854320,"42"],[1623854340,"42"],[1623854360,"42"],[1623854380,"42"],[1623854400,"42"],[1623854420,"42"],[1623854440,"42"],[1623854460,"42"],[1623854480,"42"],[1623854500,"42"],[1623854520,"42"],[1623854540,"42"],[1623854560,"42"],[1623854580,"42"],[1623854600,"42"],[1623854620,"42"],[1623854640,"42"],[1623854660,"42"],[1623854680,"42"],[1623854700,"42"],[1623854720,"42"],[1623854740,"42"],[1623854760,"42"],[1623854780,"42"],[1623854800,"42"],[1623854820,"42"],[1623854840,"42"],[1623854860,"42"],[1623854880,"42"],[1623854900,"42"],[1623854920,"42"],[1623854940,"42"],[1623854960,"42"],[1623854980,"42"],[1623855000,"42"],[1623855020,"42"],[1623855040,"42"],[1623855060,"42"],[1623855080,"42"],[1623855100,"42"],[1623855120,"42"],[1623855140,"42"],[1623855160,"42"],[1623855180,"42"],[1623855200,"42"],[1623855220,"42"],[1623855240,"42"],[1623855260,"42"],[1623855280,"42"],[1623855300,"42"],[1623855320,"42"],[1623855340,"42"],[1623855360,"42"],[1623855380,"42"],[1623855400,"42"],[1623855420,"42"],[1623855440,"42"],[1623855460,"42"],[1623855480,"42"],[1623855500,"42"],[1623855520,"42"],[1623855540,"42"],[1623855560,"42"],[1623855580,"42"],[1623855600,"42"],[1623855620,"42"],[1623855640,"42"],[1623855660,"42"],[1623855680,"42"],[1623855700,"42"],[1623855720,"42"],[1623855740,"42"],[1623855760,"42"],[1623855780,"42"],[1623855800,"42"],[1623855820,"42"],[1623855840,"42"],[1623855860,"42"],[1623855880,"42"],[1623855900,"42"],[1623855920,"42"],[1623855940,"42"],[1623855960,"42"],[1623855980,"42"],[1623856000,"42"],[1623856020,"42"],[1623856040,"42"],[1623856060,"42"],[1623856080,"42"],[1623856100,"42"],[1623856120,"42"],[1623856140,"42"],[1623856160,"42"],[1623856180,"42"],[1623856200,"42"],[1623856220,"42"],[1623856240,"42"],[1623856260,"42"],[1623856280,"42"],[1623856300,"42"],[1623856320,"42"]]}]}}
```

its very confused because we expect only 2 meaning points 

**Version**
```
victoria-metrics-20210613-171559-tags-v1.61.1-0-g2ef2e3d-dirty-da39a3ee
```

**Comment by faceair** [comment] 2021-06-21 02:33
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/549 https://github.com/zhihu/promate/blob/v1.0.0/cmd/matecarbon/main.go#L351
You can use the `max_lookback` parameter.

**Comment by tantra35** [comment] 2021-06-21 21:05
@faceair  great thanks, miss this parameter `max_lookback`  in readme

**Comment by valyala** [comment] 2021-06-22 19:37
This is expected behavior for `/api/v1/query_range` handler. This handler returns exactly `N = 1 + (end - start) / step` samples per each returned time series, where `start`, `end` and `step` are query args passed to `/api/v1/query_range` - see https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries . The distance between the returned samples always equals to `step`. VictoriaMetrics follows Prometheus data model for this API. This data model returns the previous real sample value per each `step` unless gap exists in the time series. The data model expects that every time series has real samples at regular intervals (these intervals are called `scrape_interval`). There could be a gap, which is determined as the absence of samples during `2x scrape_interval`. The `/api/v1/query_range` doesn't return a points in place of gaps.

This data model can be adjusted with `max_lookback` query arg as @faceair mentioned above. It can also be adjusted with `-search.maxStalenessInterval` command-line flag. See `./victoria-metrics -help` output for this command-line flag:

>   -search.maxStalenessInterval duration
        The maximum interval for staleness calculations. By default it is automatically calculated from the median interval between samples. This flag could be useful for tuning Prometheus data model closer to Influx-style data model. See https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness for details. See also '-search.maxLookback' flag, which has the same meaning due to historical reasons

If you need obtaining the real samples stored in VictoriaMetrics, then take a look at [various export API options](https://docs.victoriametrics.com/#how-to-export-time-series).

**Comment by valyala** [comment] 2021-06-22 19:38
FYI, VictoriaMetrics implements Graphite render API, so it can be queried with Graphite queries - see [these docs](https://docs.victoriametrics.com/#graphite-render-api-usage) for details.

**Comment by valyala** [comment] 2024-02-08 22:29
FYI, there is also `-search.setLookbackToStep` command-line flag, which automatically limits the maximum lookback window to the `step` query arg passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyconcepts/#range-query).

Closing the question as resolved.

**Closed by valyala** 2024-02-08 22:29 UTC
Labels: question
