### ISSUE TITLE
EFS STORAGE: panic: FATAL: cannot open file /storage/data/small/XXXX/XXXX/timestamps.bin : no such file or directory

### ISSUE THREAD

**Issue by rooque** [VictoriaMetrics/VictoriaMetrics#3038] opened 2022-08-29 12:53 UTC
**Describe the bug**
Hello 👋 

Using VM for about 2 months, and this error happened 2 times. VM could not open timestamps.bin because the file does not exist. The only way I found to "fix" it, is by deleting the folder (/storage/data/small/XXXX/XXXX/) that was supposed to contain the file timestamps.bin, otherwise, VM does not go up. I think this makes the system lose a portion of the data (don't know how much)

SETUP:

- VM Single Mode
- K8S (EKS) - Install using Helm Chart
- Using EFS as PV

**To Reproduce**

I think it happens when for some reason K8S kills the pod to reallocate it to another node (so VM restart); But not entirely sure

**Expected behavior**

VM does not try to open a file that does not exist;

**Logs**

[container (2).log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9444563/container.2.log)
[container (1).log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9444564/container.1.log)

**Version**

victoriametrics/victoria-metrics:v1.79.2

**Used command-line flags**
 
```
 -configAuthKey="secret"
-deleteAuthKey="secret"
-envflag.enable="true"
-envflag.prefix="VM_"
-flagsAuthKey="secret"
-forceMergeAuthKey="secret"
-loggerFormat="json"
-memory.allowedPercent="80"
-pprofAuthKey="secret"
-retentionPeriod="1"
-search.maxQueryDuration="30m0s"
-search.maxQueueDuration="30m0s"
-search.maxSamplesPerQuery="1000000000"
-search.maxSamplesPerSeries="1000000000"
-search.maxSeries="1000000000"
-search.maxTagKeys="secret"
-search.maxTagValues="1000000000"
-search.maxUniqueTimeseries="1000000000"
-search.resetCacheAuthKey="secret"
-snapshotAuthKey="secret"
-storageDataPath="/storage"
```

**Comment by valyala** [comment] 2022-08-30 07:42
It is likely the issue is in the combination of the used [EFS file system](https://aws.amazon.com/efs/) and unclean shutdown, e.g. when the VictoriaMetrics is terminated via `kill -9`, out of memory error, hardware reset, etc. instead of performing graceful shutdown by sending `SIGINT` or `SIGTERM` signal and waiting until VictoriaMetrics process finishes.

VictoriaMetrics creates files on disk at `<-storageDataPath>/data/` folder in the following way:

1. It buffers incoming data in memory and saves the buffered data to a temporary directory under `<-storageDataPath>/data/small/YYYY_MM/tmp` directory. The temporary directory is named `part`.
2. It calls [fsync](https://man7.org/linux/man-pages/man2/fdatasync.2.html) on all the files inside the created `part` directory under `<-storageDataPath>/data/small/YYYY_MM/tmp` in order to make sure that the operating system saves the data to disk, and then calls `fsync` on the `part` directory itself in order to make sure that the operating system saves the `part` directory contents (aka directory structure) to disk.
3. It atomically moves the created `part` directory from the `<-storageDataPath>/data/small/YYYY_MM/tmp` folder into `<-storageDataPath>/data/small/YYYY_MM/` with the [rename](https://man7.org/linux/man-pages/man2/rename.2.html) syscall.
4. It calls `fsync` on the directory `<-storageDataPath>/data/small/YYYY_MM/` where the part was moved to in order to guarantee that the operating system stores to disk the updated directory structure for `<-storageDataPath>/data/small/YYYY_MM/`

VictoriaMetrics periodically merges already existing `parts` into bigger ones in background. This is needed in order to minimize the number of parts on disk, to improve compression rate for the data stored on disk (bigger parts usually have better compression rate) and to improve query performance (smaller number of parts are inspected faster during queries). The background merge process is performed in the temporary directory - `<-storageDataPath>/data/small/YYYY_MM/tmp`, and then the contents of this directory is atomically moved to `<-storageDataPath>/data/small/YYYY_MM/` in the way described above. See [these docs](https://docs.victoriametrics.com/#storage) for details on how VictoriaMetrics storage work.

These algorithms guarantee that the contents of `<-storageDataPath>/data/` directory is always in a consistent state even if VictoriaMetrics is terminated uncleanly (e.g. via hardware reset, `kill -9`, out of memory error, etc.).

But, it looks like EFS filesystem sometimes may violate `fsync()` syscall guarantees. E.g. it return `success` from this syscall even if the file data or the directory structure isn't written to persistent storage yet (for example, if the data still remains in some in-memory buffers controlled by the operating system). Then this data may be lost during unclean shutdown, so next time VictoriaMetrics cannot locate the expected files inside `part` directories such as `timestamps.bin`.

The temporary solution is to use other persistent storage than EFS. For example, [EBS](https://aws.amazon.com/ebs/). The long-term solution is to either fix `fsync()` semantics in EFS or to find working workaround at VictoriaMetrics side, which guarantees that the data and the directory structure is successfully stored to persistent storage.

**Comment by rooque** [comment] 2022-08-30 20:07
@valyala just got another error like this one, looks like is something about the data being removed after the retention period and for some reason, it's trying to read something that was already been deleted.

I have retention = 1, the folder that always gets the error is the month before...

[container (4).log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9456244/container.4.log)

**Comment by valyala** [comment] 2022-09-02 19:30
Just discovered that VictoriaMetrics doesn't perform atomic removal of the directory with part files outside the configured retention. It sequentially removes files inside the part directory and then removes an empty directory itself. If VictoriaMetrics process crashes in the middle of directory removal, then it may hit the `cannot open file .../data/small/YYYY_MM/XXXX/timestamps.bin : no such file or directory` error on the next startup. Temporary workaround is to manually remove the `.../data/small/YYYY_MM/XXXX/` directory and then start VictoriaMetrics again.

The following enhancement must be implemented in the long term for parts' deletion outside the retention: to create a `transaction` file for directory removal for the part outside the retention and then replay it. This mechanism is already used when multiple source parts are merged into a bigger destination part. The `transaction` files are replayed on the next start of VictoriaMetrics. This guarantees that the part directories are removed on the next start of VictoriaMetrics if they weren't removed because of unclean shutdown (e.g. crash, `kill -9`, hardware reset, etc.).

**Comment by rooque** [comment] 2022-09-02 20:39
> Just discovered that VictoriaMetrics doesn't perform atomic removal of the directory with part files outside the configured retention. It sequentially removes files inside the part directory and then removes an empty directory itself. If VictoriaMetrics process crashes in the middle of directory removal, then it may hit the `cannot open file .../data/small/YYYY_MM/XXXX/timestamps.bin : no such file or directory` error on the next startup. Temporary workaround is to manually remove the `.../data/small/YYYY_MM/XXXX/` directory and then start VictoriaMetrics again.
> 
> The following enhancement must be implemented in the long term for parts' deletion outside the retention: to create a `transaction` file for directory removal for the part outside the retention and then replay it. This mechanism is already used when multiple source parts are merged into a bigger destination part. The `transaction` files are replayed on the next start of VictoriaMetrics. This guarantees that the part directories are removed on the next start of VictoriaMetrics if they weren't removed because of unclean shutdown (e.g. crash, `kill -9`, hardware reset, etc.).
> 
> Another possible enhancement for atomic deletion of part directories with multiple files is to use the following algorithm:
> 
> 1. To move the part directory under `<-storageDataPath>/data/{small,big}/YYYY_MM/XXX/tmp` directory. This operation must be atomic according to [rename docs](https://man7.org/linux/man-pages/man2/rename.2.html) even if the directory contains multiple files / subdirectories.
> 2. To delete the part directory under `.../tmp` folder in background. Unclean shutdown shouldn't be an issue, since the `.../tmp` directory is automatically cleaned up on the next VictoriaMetrics start.

Nice that we were able to discover the root problem of the issue. I think this is not related to EFS anymore, right? We can rename this issue to describe it better. Also, is this considered a bug or an enhancement?

(just a side note here: we are loving to use VM ❤️ )

**Comment by valyala** [comment] 2022-09-13 10:24
> I think this is not related to EFS anymore, right?

The issue still may be related to EFS (and any other [NFS](https://en.wikipedia.org/wiki/Network_File_System)-based filesystem), since NFS has slightly [different behavior when deleting directories with open files](https://linux-nfs.org/wiki/index.php/Server-side_silly_rename) comparing to other [POSIX](https://en.wikipedia.org/wiki/POSIX)-compatible filesystems. So VictoriaMetrics falls back to asynchronous directory removal on NFS - see [this code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/57ea8dbb36b8525f4822885fcd2b098e11042a2a/lib/fs/dir_remover.go#L41-L57) for details.

> We can rename this issue to describe it better

There is no need in renaming the issue, so it could be located by others who experience the same issue.

> Also, is this considered a bug or an enhancement?

Let's consider it as an enhancement :)

**Comment by valyala** [comment] 2022-09-13 13:23
@rooque , VictoriaMetrics should atomically delete directories for snapshots, parts and partitions starting from the commit 25c9a1604ac77039526a1599e1d391e7df6f492d (actually, this is the last commit in the series of commits for this issue) .  Could you build VictoriaMetrics from this commit and verify whether the issue is gone there? See [build instructions](https://docs.victoriametrics.com/#how-to-build-from-sources). If everything is OK, then these commits will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment] 2022-09-13 14:49
The related Prometheus issues:
- https://github.com/prometheus/prometheus/issues/10679 
- https://github.com/prometheus/prometheus/issues/7397

**Comment by valyala** [comment] 2022-10-07 01:48
VictoriaMetrics should atomically delete old directories on NFS starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). This should prevent from the `no such file or directory` error after unclean shutdown. Closing the issue as fixed then.

@rooque , feel free re-opening the issue if it is reproduced in VictoriaMetrics v1.82.0 or later versions.

**Closed by valyala** 2022-10-07 01:48 UTC
Labels: enhancement

**Comment by Lusitaniae** [comment] 2023-02-05 15:56
@valyala comment in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/63#issuecomment-500975055 seems to be relevant if you need to cleanup/recover from the error above.

Basically find all dirs missing timestamps.bin and remove/move them away

This might come in hand
```
find /victoriadatabase/data/big/<date>/ -type d '!' -exec test -e "{}/timestamps.bin" ';' -print
```
