### ISSUE TITLE
Consider adding HELP & TYPE info to component metrics page

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/VictoriaMetrics#1705] opened 2021-10-14 04:10 UTC
**Is your feature request related to a problem? Please describe.**

I'm debugging a problem about vmalert and want to find some useful information from its metrics (:8880/metrics endpoint). But I'm wondering about the exact meaning of each metric. 

**Describe the solution you'd like**

Provide HELP & TYPE info of metrics, like the Prometheus style. 

**Describe alternatives you've considered**

**Comment by valyala** [comment] 2024-02-13 00:51
Closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/210

**Closed by valyala** 2024-02-13 00:51 UTC
Labels: enhancement, question
