### ISSUE TITLE
Partial deletion of timeseries data

### ISSUE THREAD

**Issue by liamaharon** [VictoriaMetrics/VictoriaMetrics#2234] opened 2022-02-22 01:12 UTC
**Is your feature request related to a problem? Please describe.**

Hi, I'm using VM to store blockchain related data. Occasionally chain reorganizations occur, invalidating up to the last one hour of metrics that have been imported.

In issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/164#issuecomment-590488660 the suggested the way to deal with this is to 

1. Fetch the original raw data via [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series)
2. Remove incorrect data points from the exported data, delete the whole time series via [delete api](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-delete-time-series) 
3. Import the corrected data via [/api/v1/import](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-time-series-data)

This would be fine if we were working with a small data set, however we are working with billions of datapoints which take minutes to unload, validate, and then re-load.

**Describe the solution you'd like**

Ideally, we would be able to specify `start` and `end` when calling the `delete_series` API, like is possible in Prometheus.

**Describe alternatives you've considered**

We have considered
- Seperate timeseries metrics for recent and old data
- Following the 3 step process above (this is non-optimal due to it taking a long time, and the complexity to ensure we don't lose data) 

**Additional context**

Any advice on how we can handle removing only the recent metrics for a very large timeseries would be appreciated. 

Thanks!

**Comment by valyala** [comment] 2024-02-14 00:08
Closing this issue as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3759

**Closed by valyala** 2024-02-14 00:08 UTC
Labels: enhancement
