### ISSUE TITLE
vmselect  -search.maxSamplesPerQuery Parameter configuration bug

### ISSUE THREAD

**Issue by aluode99** [VictoriaMetrics/VictoriaMetrics#5851] opened 2024-02-22 13:22 UTC
### Describe the bug

Querying data from 19:00 to 20:00 today is successful, but querying data from the same time period next day results in an error stating that the query exceeds the limit.
The normal query results are as follows:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/bb3595b2-6a4e-43fe-8791-bd7e726b0fe5)
When querying data from the same time period next day, an error is reported for exceeding the query limit, and this error persists even when the query range is limited to 1 minute.
![1ec0aad65b220bfbac95b0becc04295a](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/f8c9e8fe-ac54-471c-bb56-62ba5fe7b702)
The search.maxSamplesPerQuery limit applies to the data within a block, not to the data within a time range. As blocks merge, the amount of data in a block increases, leading to inconsistent query performance for the same time range.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/b3fd1e9a-b92f-458e-9a78-0578bcd2a7d9)
Is there a more rational way to set the search.maxSamplesPerQuery limit to achieve consistent query results?

### To Reproduce

As mentioned above.

### Version

v1.96.0-cluster

**Comment by f41gh7** [comment] 2024-02-22 14:38
Hello, 
 
 This statement is not correct:
> The search.maxSamplesPerQuery limit applies to the data within a block, not to the data within a time range. As blocks merge, the amount of data in a block increases, leading to inconsistent query performance for the same time range.
image

 Limit is applied to the raws with-in time range. At the given screenshot, rowsCount atomically added to the context variable `samples`. Result of this operation returned as `n`.

 Yes, this limit maybe inconsistent and background merge could significantly increase number of rows within block. Exact time range filter applied at vmselect side, vmstorage may return packed data block outside time range.

 Main purpose of this limit is vmselect protection from possible OOM.

**Comment by dglushenok** [comment] 2024-05-29 15:46
Same problem on v1.98.0 - when you hit the limit once, shorting the time range will not help to avoid the error. This makes `search.maxSamplesPerQuery` unusable.

**Comment by Haleygo** [comment] 2024-06-03 13:50
Hi @dglushenok ,
>when you hit the limit once, shorting the time range will not help to avoid the error.

What's the time range do you query here, for old data like past month? How much did you shorten the time range?

**Comment by dglushenok** [comment] 2024-06-03 14:40
> What's the time range you query here, for old data like past month?

I've noticed the problem browsing dashboards after shortening `search.maxSamplesPerQuery`. First time the error was generated on 24h time range, IIRC.

> How much did you shorten the time range?

After catching the error first time, I've tried to change range up to 5min, still getting the error.

**Comment by hagen1778** [comment] 2024-06-04 07:25
I think we should try to fix this issue. Checking number of samples in block header is an optimization, it allows to discard expensive queries without going into unpacking the received blocks. But it also has this worsening accuracy. We should try checking the limit for samples after the time filter was applied.
@zekker6 @Haleygo @AndrewChubatiuk do you want to take a look?

**Comment by hagen1778** [comment] 2024-06-14 13:41
@dglushenok @aluode99 the [fix](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6464) was merged and will be included into the next release. Meanwhile you can try building VM binaries [from sources](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by valyala** [comment] 2024-06-25 01:16
@aluode99 , the purpose of `-search.maxSamplesPerQuery` is to limit CPU usage per single query - see https://docs.victoriametrics.com/#resource-usage-limits . VictoriaMetrics spends CPU time on unpacking all the samples for all the blocks on the requested time range. That's why the `-search.maxSamplesPerQuery` command-line flag takes into account all the samples in every unpacked block instead of taking into account only the samples, which are left after filtering out unpacked samples outside the requested time range.

It is incorrect if `-search.maxSamplesPerQuery` takes into account only samples left after filtering out samples outside the requested time range, since in this case this command-line flag won't limit CPU usage. For example, if the query requests a billion of historical time series on some very narrow time range, then VictoriaMetrics needs to unpack a billion of full blocks of samples (8K samples per each block), and then leave only a few samples on the selected narrow time range per each unpacked block for further processing. This results in excess CPU usage, which is unexpected by most users, who set the `-search.maxSamplesPerQuery` command-line flag.

That's why [the pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6464) has been reverted in the commit b07a02c5161950ab735f9d0762b32252a8debc27 .

**Comment by valyala** [comment] 2024-06-25 01:16
Closing the issue as "working as intended".

**Closed by valyala** 2024-06-25 01:16 UTC
Labels: enhancement, waiting for release
