### ISSUE TITLE
Different behaviour for kubernetes discovery for vmagent and prometheus during big redeployments

### ISSUE THREAD

**Issue by dmitry-tiger** [VictoriaMetrics/VictoriaMetrics#3747] opened 2023-02-02 13:24 UTC
### Describe the bug

During big redeploy (6-8k targets) VictoriaMetrics has gap in metrics due to absence of active targets, but prometheus with the same configuration has no gap
![image](https://user-images.githubusercontent.com/4358421/216326055-fd7e764a-8787-47c1-825c-e4a5ee30ea45.png)
yellow line: count(up{job="our-job"}==1)
green line: count(up{job="our-job"}==0)
se we have no metrics from 12:23 to 12:25 and lack of metrics near that interval
In prometheus we have the same job configuration but behaviour is different
![image](https://user-images.githubusercontent.com/4358421/216326848-1df62767-2b50-4031-84b8-dbf1d38742b9.png)
yellow line: count(up{job="one-of-our-job"}==0)
green line: count(up{job="one-of-our-job"}==1)
so we didn't have gap in metrics

vmagent has some non default startup configuration options
-promscrape.discovery.concurrency=1000 
-promscrape.discovery.concurrentWaitTime=2m 
-promscrape.kubernetes.apiServerTimeout=15m 
-promscrape.kubernetesSDCheckInterval=15s 
-promscrape.maxScrapeSize=967772169
-promscrape.noStaleMarkers=true 
-promscrape.streamParse=true 

Also we have two remote writes from vmagent and one of them start using persistent queue, could that affect discovery process?

### To Reproduce

-

### Version

vmagent-20230118-201742-tags-v1.86.2-0-g9785b3f57

### Screenshots

![image](https://user-images.githubusercontent.com/4358421/216335454-94ab6ce0-315a-424f-861f-225d23ad1551.png)
![image](https://user-images.githubusercontent.com/4358421/216335743-b38c81b4-9b17-4acb-93a0-6938054b0fac.png)
![image](https://user-images.githubusercontent.com/4358421/216336037-7bb7ebd4-c9ed-405f-829f-84b3540bace9.png)

### Used command-line flags

-promscrape.discovery.concurrency=1000 
-promscrape.discovery.concurrentWaitTime=2m 
-promscrape.kubernetes.apiServerTimeout=15m 
-promscrape.kubernetesSDCheckInterval=15s 
-promscrape.maxScrapeSize=967772169
-promscrape.noStaleMarkers=true 
-promscrape.streamParse=true 

### Additional information

![image](https://user-images.githubusercontent.com/4358421/216337512-dd89b378-60ef-4b6f-924a-cf117b6ae174.png)
vm_promscrape_service_discovery_duration_seconds shows big values during that redeploy probably it depends on our configuration with concurrency

**Comment by dmitry-tiger** [comment] 2023-02-02 14:44
@zekker6 sorry I forgot to mention that we have 3 agents  
 -promscrape.cluster.membersCount=3
 vmagent couldn't reach targets because those targets were terminated and new targets hadn't beet added(discovered) at that moment. More over prometheus is deployed in the same cluster and have the same amount of targets and don't have that behavior (new targets appear without delay)

**Comment by zekker6** [comment] 2023-02-03 14:53
@dmitry-tiger Could you please share config which is used for vmagent which experiences this delay and flags which are used to run prometheus?
Also, it would be great if you could take a [CPU profile](https://docs.victoriametrics.com/vmagent.html#profiling) for vmagent during reload. It will highlight slow paths which we can optimize.

**Comment by valyala** [comment] 2023-02-03 22:43
The graphs above show that there is enough spare CPU during the redeployment (around 50% of CPU is free). The graphs have the following anomalies during the redeployment time frame:

- 2x increased memory usage from 1.9GB to 3.4GB. this may be fixed in [vmagent v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3675 .
- Increased disk write IO from zero to around 50MB/s with peaks up to 90MB/s. This is because vmagent started flushing pending data to disk (aka persistent queue) because it couldn't send it to the configured `-remoteWrite.url` in a timely manner.

It is likely the increased disk write IO is the main reason for the slower than expected re-discovery of new targets in k8s after the re-deployment. The solution is to switch to disks with higher write IO bandwidth. Another solution is to increase the number of `vmagent` shards in [the cluster](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets), so the summary disk write IO could be spread among bigger number of `vmagent` shards.

**Comment by hagen1778** [comment] 2023-02-07 12:26
@valyala vmagent contains a `Network Usage` panel in `Resource usage` row on Grafana dashboard and it is present on provided screenshots. Or did you mean something different?

**Comment by valyala** [comment] 2023-02-08 03:39
Probably the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3356

**Comment by valyala** [comment] 2023-02-08 03:50
> vmagent contains a Network Usage panel in Resource usage row on Grafana dashboard and it is present on provided screenshots

Oh, I didn't notice these graphs :) These graphs show almost stable network ingress usage around 2.3 Gbit/s during the incident. Probably, there is a network bandwidth limit at the host where vmagent runs, which was preventing to scrape targets at the expected rate during the incident.

**Comment by zekker6** [comment] 2023-02-08 15:49
Hi @dmitry-tiger 
The following PR is expected to fix this issue - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3791

There is a docker image build from this PR sources -` victoriametrics/vmagent:heads-fix-vmagent-scrape-requests-cancellation-0-g2f7537bf7-dirty-618bbb33`
It would be great if you could run this version and verify if it helps.

**Comment by dimakrapiva** [comment] 2023-02-08 19:53
<img width="1648" alt="Снимок экрана 2023-02-08 в 22 48 07" src="https://user-images.githubusercontent.com/44891198/217636595-00af16e5-eb91-4bc0-a0b1-16d16fbf62cf.png">

hot-fix has not solved this problem :(

VMAgent Params 
        promscrape.kubernetesSDCheckInterval: 30s
        promscrape.maxScrapeSize: "967772169"
        promscrape.suppressDuplicateScrapeTargetErrors: "true"
        promscrape.suppressScrapeErrors: "true"
        remoteWrite.maxDiskUsagePerURL: "0"
        promscrape.discovery.concurrency: "10000"
        #promscrape.cluster.name: "AZ1"
        sortLabels: "true"
        promscrape.streamParse: "false"
        #promscrape.noStaleMarkers: "true"
        promscrape.discovery.concurrentWaitTime: 1m
        promscrape.kubernetes.apiServerTimeout: 5m

version: heads-fix-vmagent-scrape-requests-cancellation-0-g2f7537bf7-dirty-618bbb33

**Comment by dimakrapiva** [comment] 2023-02-08 20:01
logs are identical in three shards

2023-02-08T22:43:53.711+0300	info	VictoriaMetrics/lib/promscrape/scraper.go:422	kubernetes_sd_configs: added targets: 7, removed targets: 0; total targets: 2697
2023-02-08T22:44:01.165+0300	error	VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:698	error when reading WatchEvent stream from "https://{ip}:443/api/v1/namespaces/{namespace}/endpoints?watch=1&allowWatchBookmarks=true&timeoutSeconds=270&resourceVersion=1722067262": cannot parse WatchEvent json response: context deadline exceeded (Client.Timeout or context cancellation while reading body)
2023-02-08T22:44:01.165+0300	error	VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:698	error when reading WatchEvent stream from "https://{ip}:443/api/v1/namespaces/{namespace}/pods?watch=1&allowWatchBookmarks=true&timeoutSeconds=270&resourceVersion=1722067058": cannot parse WatchEvent json response: context deadline exceeded (Client.Timeout or context cancellation while reading body)
2023-02-08T22:44:03.872+0300	info	VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:641	reloaded 114 objects from "https://{ip}:443/api/v1/namespaces/{namespace}/endpoints" in 1.703s; updated=16, removed=0, added=0, resourceVersion="1722085213"
2023-02-08T22:44:03.885+0300	info	VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:641	reloaded 777 objects from "https://{ip}:443/api/v1/namespaces/{namespace}/pods" in 1.717s; updated=104, removed=337, added=43, resourceVersion="1722085213"
2023-02-08T22:44:22.626+0300	info	VictoriaMetrics/lib/promscrape/scraper.go:422	kubernetes_sd_configs: added targets: 35, removed targets: 40; total targets: 2692
2023-02-08T22:44:48.374+0300	info	VictoriaMetrics/lib/promscrape/scraper.go:422	kubernetes_sd_configs: added targets: 2, removed targets: 0; total targets: 2694
2023-02-08T22:47:20.869+0300	info	VictoriaMetrics/lib/promscrape/scraper.go:422	kubernetes_sd_configs: added targets: 1, removed targets: 3; total targets: 2692

Problem release with ~800 pods

**Comment by zekker6** [comment] 2023-02-09 09:27
@dimakrapiva Could you please check this with ` -promscrape.streamParse=true` being set?
This fix was made in order to fix this for `streamParse` mode for now, I though you're using it based on initial configuration flags provided.
We are also working on fix for the case when `streamParse` is not enabled, but is will be available a bit later as it requires changes in underlying library.

**Comment by valyala** [comment] 2023-02-10 00:22
FYI, configuration reload should take less time in `vmagent` starting from [v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html) when [stream parsing mode](https://docs.victoriametrics.com/vmagent.html#stream-parsing-mode) is enabled. The fix for the disabled stream parsing mode will be provided in the future releases.

**Comment by dmitry-tiger** [comment] 2023-02-22 10:54
Behaviour on vmagent-20230208-154606-heads-fix-vmagent-scrape-requests-cancellationn-0-g2f7537bf7-dirty-618bbb33 with streamparse mode still unchanged in our case.
Agent doesn't add new targets before get rid of all old ones
so graph of active targets/not active during redeployment within one job looks similar (in a moment when we have 0 active targets there are dozens of undiscovered pods running few or more minutes)
![image](https://user-images.githubusercontent.com/4358421/220599407-8ceeb290-ea44-4964-ad6d-d99a3b0ef557.png)
 
![image](https://user-images.githubusercontent.com/4358421/220599537-78c53a57-c0eb-45d3-9e5d-1378a8efaa39.png)

**Comment by zekker6** [comment] 2023-02-22 11:40
@dmitry-tiger Thanks for checking!
Could you try `victoriametrics/vmagent:heads-fix-vmagent-cancel-inflight-req-0-g2ff125e9d` image?
It is build from #3853

**Comment by valyala** [comment] 2023-02-24 20:29
It is better to build `vmagent` from the commit c6ad3692ad77307215b8cf77a073cc62af1744ae , since it fixes yet another source of possible delay during targets' redeployment. This commit will be included in the next release.

**Comment by valyala** [comment] 2023-02-25 00:17
FYI, all the fixes mentioned above have been included in [vmagent v1.87.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.2).

**Comment by valyala** [comment] 2023-02-25 03:33
All the fixes mentioned above are also included in [vmagent v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). @dmitry-tiger , could you check whether `vmagent v1.88.0` fixes the issue with slow discovery of new targets during big redeployments in Kubernetes?

**Comment by dimakrapiva** [comment] 2023-02-28 06:58
Hello!
we have updated, we are watching

**Comment by valyala** [comment] 2023-03-28 02:54
@dimakrapiva , I suppose the issue is gone with vmagent v1.88.0 , since you didn't post an update after that. Then closing the issue. Feel free re-opening it if the the issue is still present in the [latest release](https://docs.victoriametrics.com/CHANGELOG.html).

**Closed by valyala** 2023-03-28 02:54 UTC
Labels: bug, vmagent
