### ISSUE TITLE
Contextual logs

### ISSUE THREAD

**Issue by lujiajing1126** [VictoriaMetrics/VictoriaMetrics#6724] opened 2024-07-29 10:52 UTC
### Is your feature request related to a problem? Please describe

Currently, selecting surrounding logs for the matching logs in [logs stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) but with a fuzzy search manner is supported by VictoriaLogs.

https://docs.victoriametrics.com/victorialogs/logsql/#stream_context-pipe

In Alicloud SLS product, contextual logs query at **log-level** is supported. I am wondering if VictoriaLogs can support such method.

1. GetCursor: https://www.alibabacloud.com/help/en/sls/developer-reference/api-sls-2020-12-30-getcursor
2. GetContextLogs: https://www.alibabacloud.com/help/en/sls/developer-reference/api-sls-2020-12-30-getcontextlogs

### Describe the solution you'd like

Allow to search query at log level by something like cursor. This is very useful if you want to see the context just before and after the exception.

**Comment by valyala** [comment] 2024-09-26 07:43
Closing this feature request as a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7063 .

**Closed by valyala** 2024-09-26 07:43 UTC
Labels: enhancement, victorialogs
