### ISSUE TITLE
vm-auth high memery&cpu usage in docker

### ISSUE THREAD

**Issue by lcasi** [VictoriaMetrics/VictoriaMetrics#1000] opened 2021-01-08 03:33 UTC
Hi, I have deployed vm-auth in docker,and found the memory & cpu usage of vm-auth container increased slowlly until oom:
* memory usage:
![image](https://user-images.githubusercontent.com/47807658/103970083-59518a80-51a2-11eb-83d6-03d058cdc97b.png)

* cpu_usage:
![image](https://user-images.githubusercontent.com/47807658/103970234-b2b9b980-51a2-11eb-9b66-9c0dc7857680.png)

* http qps
![image](https://user-images.githubusercontent.com/47807658/103970478-4d19fd00-51a3-11eb-9733-5c70ea303f2b.png)

* pprof

mem heap:
```shell
(pprof) top 20
Showing nodes accounting for 61MB, 100% of 61MB total
Showing top 20 nodes out of 41
      flat  flat%   sum%        cum   cum%
      46MB 75.41% 75.41%       46MB 75.41%  context.WithValue
    8.50MB 13.93% 89.34%    54.50MB 89.34%  github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.serveWithListener.func1
    3.50MB  5.74% 95.08%     3.50MB  5.74%  net.sendFile
    1.50MB  2.46% 97.54%     1.50MB  2.46%  net/textproto.canonicalMIMEHeaderKey
    0.50MB  0.82% 98.36%     0.50MB  0.82%  bufio.NewWriterSize
    0.50MB  0.82% 99.18%     0.50MB  0.82%  runtime.allocm
    0.50MB  0.82%   100%     0.50MB  0.82%  net.uitoa
         0     0%   100%     3.50MB  5.74%  bufio.(*Writer).ReadFrom
         0     0%   100%    54.50MB 89.34%  github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.Serve
         0     0%   100%     1.50MB  2.46%  github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1
         0     0%   100%     1.50MB  2.46%  github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper
         0     0%   100%    54.50MB 89.34%  github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.serveWithListener
         0     0%   100%     3.50MB  5.74%  io.Copy
         0     0%   100%     3.50MB  5.74%  io.copyBuffer
         0     0%   100%     1.50MB  2.46%  main.requestHandler
         0     0%   100%     0.50MB  0.82%  net.(*TCPAddr).String
         0     0%   100%     3.50MB  5.74%  net.(*TCPConn).ReadFrom
         0     0%   100%     3.50MB  5.74%  net.(*TCPConn).readFrom
         0     0%   100%     0.50MB  0.82%  net.itoa
         0     0%   100%     3.50MB  5.74%  net/http.(*Request).write
```
cpu profile:
```shell
(pprof) top20
Showing nodes accounting for 90.56s, 97.81% of 92.59s total
Dropped 51 nodes (cum <= 0.46s)
Showing top 20 nodes out of 47
      flat  flat%   sum%        cum   cum%
    29.77s 32.15% 32.15%     29.77s 32.15%  runtime.futex
    15.94s 17.22% 49.37%     28.56s 30.85%  context.(*valueCtx).Value
     6.75s  7.29% 56.66%     23.23s 25.09%  runtime.gentraceback
     6.36s  6.87% 63.53%      6.36s  6.87%  context.parentCancelCtx
     4.99s  5.39% 68.92%     17.11s 18.48%  context.propagateCancel
     3.26s  3.52% 72.44%      8.91s  9.62%  net.(*Dialer).DialContext
     3.10s  3.35% 75.79%      7.62s  8.23%  runtime.getStackMap
     2.82s  3.05% 78.83%      2.82s  3.05%  context.WithDeadline
     2.81s  3.03% 81.87%      2.82s  3.05%  net.(*Dialer).deadline
     2.35s  2.54% 84.40%      2.67s  2.88%  runtime.findfunc
     1.94s  2.10% 86.50%     11.13s 12.02%  runtime.adjustframe
     1.83s  1.98% 88.48%         2s  2.16%  runtime.funcdata
     1.80s  1.94% 90.42%      1.80s  1.94%  runtime.usleep
     1.66s  1.79% 92.21%      1.92s  2.07%  runtime.pcvalue
     1.46s  1.58% 93.79%      1.46s  1.58%  runtime.memmove
     1.33s  1.44% 95.23%      2.17s  2.34%  runtime.pcdatavalue
     1.27s  1.37% 96.60%      1.27s  1.37%  runtime.adjustpointers
     1.10s  1.19% 97.79%      2.25s  2.43%  runtime.funcspdelta
     0.01s 0.011% 97.80%      6.96s  7.52%  runtime.findrunnable
     0.01s 0.011% 97.81%      1.85s  2.00%  runtime.sysmon
(pprof) 
```

**Version**
v1.42.0 & master branch

**Used command-line flags**
```shell
 /data/app/vm-auth/vmauth-prod -http.pathPrefix /vm-auth -auth.config=/data/app/vm-auth/conf.yml -metricsAuthKey xxx -pprofAuthKey xxx
```

**Comment by f41gh7** [comment] 2021-01-08 12:52
I'll investigate, thanks for reporting.

**Comment by f41gh7** [comment] 2021-01-08 15:13
@lcasi may i ask you to share memory and goroutine profile? You can send it to the info@victoriametrics.com or post here.
 Goroutine profile can be collected with command: ```curl localhost:8427/debug/pprof/goroutine > goroutine.pprof```
 
 I cannot reproduce this behavior locally.

**Comment by lcasi** [comment] 2021-01-09 06:24
The pprof file as follows:
[heap.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/5790239/heap.txt)
[goroutine.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/5790241/goroutine.txt)
[allocs.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/5790242/allocs.txt)

**Comment by f41gh7** [comment] 2021-01-13 10:39
Thx for profiles. I wasn't able to anything suspicious, memory usage is low, according to heap file. 

 One more point, can you collect profile from vmauth container, when it uses 10-11GB of memory? 

 And how often auth config is reloaded?

**Comment by valyala** [comment] 2021-02-11 10:48
@lcasi , are there any updates on this issue?

**Comment by valyala** [comment] 2023-11-13 19:48
[vmauth](https://docs.victoriametrics.com/vmauth.html) internals have been changed since this issue has been filed (see, for example, 372b1688d73cd5b55d45ce390fe57c7defb07c72 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3346 ), so it is likely this issue with high memory usage at `vmauth` shouldn't be triggered now. Closing the issue as outdated then.

@lcasi , feel free re-opening this issue or creating new one if [the latest version of vmauth](https://docs.victoriametrics.com/CHANGELOG.html) still uses high amounts of CPU and memory under your workload.

**Closed by valyala** 2023-11-13 19:48 UTC
Labels: vmauth
