### ISSUE TITLE
Add ability to check relabel config from vmui

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#2835] opened 2022-07-06 10:18 UTC
**Is your feature request related to a problem? Please describe.**
It would be useful to check relabel config in one place on VictoriaMetrics like it does
https://relabeler.promlabs.com/

**Describe the solution you'd like**
Implement relabel config checker with features which VictoriaMetrics support

**Comment by hagen1778** [comment] 2023-02-14 15:50
closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3807

this issue is closed since it contains less details than linked one

**Closed by hagen1778** 2023-02-14 15:50 UTC
Labels: enhancement, vmui
