### ISSUE TITLE
VictoriaLogs doesn't expose process_resident_memory_bytes metric

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4980] opened 2023-09-08 13:32 UTC
### Describe the bug

I see when `process_resident_memory_bytes 0` /metircs page
I run it on m1 in docker

### To Reproduce

open VL metric page 

### Version

master

**Comment by zekker6** [comment] 2023-09-08 13:49
Currently, https://github.com/VictoriaMetrics/metrics library implements parsing of process metrics based on linux `/proc/self/stat`.
On m1 in docker it reports:
```
cat /proc/1/stat
1 (victoria-logs-p) S 0 1 1 0 -1 1077936384 22595 0 0 0 1871 467 0 0 20 0 13 0 4844074 1573474304 22241 18446744073709551615 2900224 4590696 281474769233024 0 0 0 0 0 2143420159 0 0 0 17 5 0 0 0 0 0 4959640 5038760 876843008 281474769235732 281474769235841 281474769235841 281474769235940 0
```
Where the last item is expected to be RSS memory which is reported as 0.

Closing as issue is caused by docker on m1.

**Closed by zekker6** 2023-09-08 13:49 UTC
Labels: bug
