### ISSUE TITLE
vmalert: Configuration File

### ISSUE THREAD

**Issue by hdost** [VictoriaMetrics/VictoriaMetrics#1049] opened 2021-02-03 09:58 UTC
**Is your feature request related to a problem? Please describe.**
When configuring vmalert it is quite annoying to have only command line arguments as the method to configure the program. This makes it much easier to configure in a production system. Allowing for syntax and configuration validation.

**Describe the solution you'd like**
To be able to pass a -config.file config.yml to the application.

**Comment by valyala** [comment] 2021-02-03 19:22
All the config options accepted by `vmalert` (and any other VictoriaMetrics component) via command line arguments cannot be changed dynamically, i.e. they require `vmalert` restart if they need to be changed. If these options will be put in a `-config.file`, then it is natural to expect dynamic update for these options (like for configs pointed by `-rule` command-line flag, which can be updated via SIGHUP signal or via a request to `/-/reload` http endpoint). The task for converting statically configured options to dynamically converted options is non-trivial with unclear gains. So I'm unsure `vmalert` needs `-config.file` support.

The workaround is to put all the config options into a file using the following syntax:

```
/path/to/vmalert \
  -option1=value1 \
  -option2=value2 \
  ... \
  -optionN=valueN
```

**Comment by hdost** [comment] 2021-02-11 00:14
The main issue is around the alertmanager perhaps instead allow for consul discovery or other mechanism.

**Comment by hagen1778** [comment] 2022-02-02 15:50
> The main issue is around the alertmanager perhaps instead allow for consul discovery or other mechanism.

Hi @hdost! Please check https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1947
In this PR vmalert gain ability to read config file for alertmanager (notifier) configuration with Consul SD support. 

Closing this issue as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1947 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/730

**Closed by hagen1778** 2022-02-02 15:50 UTC
Labels: enhancement, vmalert
