### ISSUE TITLE
limitk returns different data when query db everytimes for time series with gaps

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#951] opened 2020-12-10 11:49 UTC
limitk returns different data when query db everytimes for time series with gaps

below is my query
```
WITH(
  mostDeviant(k,selector)=selector and on (entity_name)
  limitk(k,sort_desc(
    running_avg(sum2_over_time(selector-range_avg(selector)))
  ))
)

mostDeviant($metric_number,max(sys.cpu.util_percent.per_core_value{appid=~'.*$appid.*',object_kind="pod", region=~'$idc', group=~'$group'})by(__name__,entity_name, appid,region))
```

**Comment by valyala** [comment] 2020-12-11 16:08
This is expected behavior, since `limitk` doesn't preserve the order of input time series. It just returns an arbitrary `k` time series from the input. This behavior allows implementing various optimizations at query engine such as stopping processing for the remaining time series when `k` time series have been processed.

Try using `topk*` functions instead. See docs about `topk*` functions [at MetricsQL page](https://victoriametrics.github.io/MetricsQL.html).

**Comment by davidsome** [comment] 2020-12-12 01:39
@valyala thank you.

I mean the same query , same start && end timestamp.  first query result is different from second query result. this results in the grafana graph is changing. it seems like a bug ?

**Comment by valyala** [comment] 2020-12-12 12:28
It is OK that `limitk()` function returns different set of time series with each call. Updated `limitk()` function description at f93247e82d3094c8c0c2ffc1d99042ab8d3f93cf . The main purpose of `limitk()` function is to make one-off requests during data exploration in order to limit the number of returned time series. It isn't intended for using in dashboards. It is better using `topk_*` functions instead. Try substituting

```metricsql
limitk(k,sort_desc(
    running_avg(sum2_over_time(selector-range_avg(selector)))
  ))
```

with

```metricsql
topk_avg(k, running_avg(sum2_over_time(selector-range_avg(selector))))
```

**Comment by valyala** [comment] 2021-12-10 13:41
FYI, `limitk()` function should consistently return time series in the same order starting from [v1.68.0](https://docs.victoriametrics.com/CHANGELOG.html#v1680). The order of the returned time series is unspecified.

**Comment by valyala** [comment] 2021-12-13 11:23
The [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function must preserve the order of time series passed to it starting from the commit 1da19c0afbae98fbb403825e6f6129555789c290 . This commit will be included in the next release. In the mean time it is possible to build VictoriaMetrics from this commit according to [build instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the `limit_offset` function works as expected.

**Comment by valyala** [comment] 2021-12-20 18:15
FYI, VictoriaMetrics should preserve the order of input time series for [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing this issue as done.

**Closed by valyala** 2021-12-20 18:15 UTC
Labels: question
