### ISSUE TITLE
Query EOF/Timeout

### ISSUE THREAD

**Issue by AeroNotix** [VictoriaMetrics/VictoriaMetrics#370] opened 2020-03-12 10:54 UTC
**Describe the bug**
Frequent EOF / false timeout errors when querying from Grafana

**To Reproduce**
Deploy VictoriaMetrics, use grafana to query

**Expected behavior**
No errors on a lightly loaded vmselect deployment

**Screenshots**
![Thu_12_Mar_11:45:42_CET_2020](https://user-images.githubusercontent.com/975962/76514162-c64ba500-6457-11ea-90e0-8f2bc33841ae.jpg)

**Version**
v1.31.0

Hi,

I have a victoriametrics-cluster deployment which is working very, very well - sometimes when opening a grafana page I see a bunch of errors regarding EOF/timeouts for some/all queries made within a page.

I took a look over the concurrency limiter and, without being crass/accusatory, the implementation seems complex for what it is doing? The servers themselves aren't at all stressed or running at high load. Queries almost always return in less than a few hundred milliseconds - there are absolutely no queries which would hog a whole connection to the point where new queries are queuing.

**Comment by stigok** [comment] 2020-03-12 11:05
Could it possibly be an inress controller issue, or are you accessing the service directly?

**Comment by AeroNotix** [comment] 2020-03-12 11:10
Queries are made through grafana, which access the kubernetes service DNS names directly.

**Comment by valyala** [comment] 2020-03-12 16:47
@AeroNotix , could you upgrade to [v1.31.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.31.5) and check for this error? This release has improved error logging, which could help determining the root cause of the issue.

**Comment by AeroNotix** [comment] 2020-03-12 18:53
Sure I can upgrade to that version and see if the logging/behaviour is any better. Will do this in a few hours and get back to you.

**Comment by AeroNotix** [comment] 2020-03-12 23:20
@valyala are there fixes in [v1.31.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.31.5)? I've just upgraded to this version and I no longer see the same errors in the logs or in the grafana dashboard.

I don't want to mark this as resolved, unless there was a specific bug that has been fixed in 1.31.5 - as I am concerned the issue takes time to start appearing.

**Comment by valyala** [comment] 2020-03-13 17:01
This can be related to #281 , which has been fixed in `v1.31.5`. Let's keep this issue open for some time and see whether it triggers again.

**Comment by AeroNotix** [comment] 2020-03-15 20:23
So far so good, still not seen this reappear with v1.31.5

**Comment by AeroNotix** [comment] 2020-03-17 12:35
Still so far so good!

**Comment by valyala** [comment] 2020-03-27 20:46
Then closing the issue. Feel free re-opening it if it appears again.

**Closed by valyala** 2020-03-27 20:46 UTC
Labels: bug, need more info
