### ISSUE TITLE
There is always a node in the vm cluster that has a insert performance bottleneck, and it is not the same node every time

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4254] opened 2023-05-05 10:14 UTC
### Is your question request related to a specific component?

vminsert

### Describe the question in detail

There will always be a node in the cluster that has a performance bottleneck, and after each expansion, restarting all vminserts, it may become another node. But there will always be a node with a performance bottleneck:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/52991866/236431853-67f9fa97-e1f4-4d08-8b91-e888680719ea.png">

This node with a bottleneck will also be accompanied by high cpu usage:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/52991866/236431919-f648e569-2ded-4642-9dae-f681f24190b7.png">

Is it possible that it has something to do with the hash mapping of a certain process, causing this node to process more data, resulting in data imbalance？

I can't find the reason at the moment, and I hope to get suggestions for troubleshooting

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment] 2023-05-09 07:33
duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4219

**Closed by hagen1778** 2023-05-09 07:33 UTC
Labels: question
