### ISSUE TITLE
Does VictoriaMetrics plan to support storage exemplar?

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#1169] opened 2021-03-31 10:28 UTC
https://docs.google.com/document/d/1ymZlc9yuTj8GvZyKz1r3KDRrhaOjZ1W1qZVW_5Gj7gA/edit
https://github.com/prometheus/prometheus/pull/6635

**Comment by valyala** [comment] 2021-03-31 12:33
We don't work on Prometheus exemplar (aka [OpenMetrics exemplars](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars)) support at the moment, but there are plans for adding support for exemplars in the future.

**Comment by coryrjohnson** [comment] 2021-07-02 17:07
This would be a great addition, we have started to get exemplar support with our latest prometheus deployments and it would be great to have this functionality on our VM cluster as well.

**Comment by sudeep-ib** [comment] 2021-07-18 06:41
Agreed, this will be great to have as we are starting to explore use of exemplars, and already use VM for stats data store

**Comment by dbaskakov** [comment] 2021-11-03 15:22
+1

**Comment by mrgreyves** [comment] 2021-11-03 15:23
We need this functionality too =)

**Comment by secat** [comment] 2021-11-04 13:17
+1

**Comment by sinkingpoint** [comment] 2021-11-05 21:44
@valyala is there any ETA on this? No exemplars is kind of a show stopper for us. If there's no active development, I'm happy to throw in a PR

**Comment by valyala** [comment] 2021-11-12 11:09
@sinkingpoint , there is no ETA for this feature. It would be great if you could submit a PoC pull request for it!

**Comment by ekarlso** [comment] 2021-12-04 14:24
+1

**Comment by jbdalido** [comment] 2021-12-17 09:33
@sinkingpoint Are you working on this already? If u need a hand we'll be more than happy to help you, that's a kinda game-changer feature.

**Comment by sinkingpoint** [comment] 2021-12-18 04:45
@jbdalido Feel free - I've been a bit bogged down with other stuff. You can see my initial work in https://github.com/sinkingpoint/VictoriaMetrics/tree/exemplars_exemplar - it's gotten as far as writing exemplars to a file in each partition

**Comment by acukan** [comment] 2022-05-31 11:37
Are there any plan to implement real exemplar api for VM?

**Comment by f41gh7** [comment] 2022-06-27 07:04
I think, that this feature should be split into few separate changes:
1) ability to scrape exemplars and forward it to the remote storage. Changes for [vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmagent) and [marshaling](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/lib/prompbmarshal). Help wanted, it's not complicated.
2) add exemplars to the [metrics package](https://github.com/victoriaMetrics/metrics).
3) storing exemplars and querying. Most complicated part, we have some implementation drafts for it.

**Comment by gophper** [comment] 2022-08-08 02:18
Are there plans to support exemplars storage?

**Comment by dafu-wu** [comment] 2022-09-08 08:16
> @jbdalido Feel free - I've been a bit bogged down with other stuff. You can see my initial work in https://github.com/sinkingpoint/VictoriaMetrics/tree/exemplars_exemplar - it's gotten as far as writing exemplars to a file in each partition

@sinkingpoint @jbdalido  Do you have any plans to finish it？

**Comment by wking1986** [comment] 2022-09-16 11:00
+1

**Comment by Frapschen** [comment] 2022-09-22 09:42
+1

**Comment by JaredTan95** [comment] 2022-09-22 09:55
+1
BTW, any processing on this plan? :-P

**Comment by sychevsky** [comment] 2022-10-10 09:17
+1

Waiting for this modern feature

**Comment by rapita** [comment] 2022-10-10 09:18
+1

**Comment by ilumen07** [comment] 2022-10-10 09:23
+1

**Comment by AlexNDRmac** [comment] 2022-10-10 09:33
+1

**Comment by PavloBukoviak** [comment] 2022-10-10 09:42
+1

**Comment by moonchildua** [comment] 2022-10-10 10:05
+1

**Comment by dbaskakov** [comment] 2022-10-10 14:31
+1

**Comment by Alexpdl** [comment] 2022-10-11 08:29
+1

**Comment by Kuzbekov** [comment] 2022-10-11 09:34
To anyone who consider to add more "+1" here - please don't, you will make unnecessary noise message for a lot of people who are subscribed and waiting for any useful information from developers.
Just use thumbs up reaction on the first message. 
Thank you.

**Comment by valyala** [comment] 2023-02-23 23:51
Good news: we decided to add support for [Prometheus examplars](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars-1) in VictoriaMetrics!

At first, let's define an exemplar as a `(value, timestamp)` pair with an optional set of `key=value` pairs, which can be attached to arbitrary [time series](https://docs.victoriametrics.com/keyConcepts.html#time-series) - see [exemplars specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars) for details.

The task for adding the exemplars into VictoriaMetrics can be split in the following sub-tasks:

1. To add an HTTP handler for storing, updating and deleting of exemplars - `/api/v1/update_exemplar`. This handler must accept the following query args:
  - `series` - the [time series](https://docs.victoriametrics.com/keyConcepts.html#time-series) name where the exemplar must be attached. For example, `series=http_requests_total{job="foo",instance="bar"}`.
  - `exemplar` - the exemplar itself in the format specified [here](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars-1). For example, `exemplar={traceID="foo"}%2012.34`. If the timestamp is missing in the exemplar, then the current timestamp is used instead.

   If the database already contains an exemplar for the given `series` with the given timestamp with millisecond precision, then `/api/v1/store_exemplar` must overwrite the existing exemplar with the new one.

   If the `exemplar` contains `NaN` value, then the existing exemplar for the given timestamp must be deleted. For example, `exemplar={}%20NaN%20123456789.456` must delete the exemplar for the given `series` at the timestamp `123456789.456`.

2. To add Prometheus-compatible handler for querying exemplars - [/api/v1/query_exemplars](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-exemplars).

3. To add support for reading and saving exemplars sent to [vmagent](https://docs.victoriametrics.com/vmagent.html) and to a [single-node VictoriaMetrics](https://docs.victoriametrics.com/#prometheus-setup) via Prometheus remote_write protocol.

4. To add support for reading exemplars from metrics exposed by Prometheus-compatible targets in [OpenMetrics format](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars-1).

## Implementation details

The exemplars must be stored in `indexdb`. Every exemplar should be stored as a single entry in the following format:

```
<exemplar_prefix> <metric_id> <timestamp> <version> <value> <key_value_entries>
```

Where:
- `<exemplar_prefix>` is one-byte prefix for fast location of exemplar entries in the `indexdb`.
- `<metric_id>` is an internal id of the time series for the given exemplar
- `<timestamp>` is a timestamp in milliseconds for the given exemplar. The `(metric_id, timestamp)` prefix allows quick locating all the exemplars for the given time series on the given time range during queries to [/api/v1/query_exemplar](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-exemplars).
- `<version>` is the exemplar version. It is incremented each time new exemplar is stored. The [/api/v1/query_exemplar](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-exemplars) must return the exemplar with the biggest `version` out of exemplars with identical `(metric_id, timestamp)` pairs.
- `<value>` is the exemplar value in float64. Deleted exemplar must contain `NaN` value here.
- `<key_value_entries>` is a set of `key="value"` entries associated with the exemplar

Assigning @zekker6 as responsible for exemplar implementation in VictoriaMetrics.

**Comment by ftpilot** [comment] 2023-05-10 10:27
has done this great job?

**Comment by appi101** [comment] 2023-05-21 14:51
Is there an update on this or a way to track/contribute?

**Comment by dave2wave** [comment] 2023-09-18 19:59
@zekker6 I there progress to report? Thanks!

**Comment by loyd** [comment] 2023-10-05 18:29
The most anticipated feature =)

**Comment by lyouthzzz** [comment] 2023-11-21 03:31
Any further news of exemplar? @zekker6

**Comment by orloffv** [comment] 2024-02-13 16:35
Hello @valyala and @zekker6,

Could you please share any updates or plans regarding the implementation of this feature? It would be greatly appreciated to understand your roadmap on this.

Thank you for your hard work to VictoriaMetrics!

**Comment by zekker6** [comment] 2024-03-29 10:33
Hello! 
Here is an update on the progress regarding exemplars: this feature is currently in progress.

The first part of the implementation will add support of scraping and forwarding exemplars at [vmagent](https://docs.victoriametrics.com/vmagent.html). You can find the PR which implements this [here](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5982). Kudos to @possibull for the hard work on this!
Once this PR will be merged the second part of implementation will follow - adding support of exemplars storage to VictoriaMetrics itself.

**Comment by anupam-meesho** [comment] 2024-05-28 08:32
Hello,
I am also looking for the same implementation. It will be a gamechanger for the victoriametrics stack. Any update on the release of the feature.

**Comment by valyala** [comment] 2024-07-03 14:35
We decided to do not add support for Prometheus exemplars into VictoriaMetrics because of the following reasons:

- Exemplars aren't in wide use after three years from their introduction because they have numerous issues which prevent their adoption (see below).
- Adding support for examplars into VictoriaMetrics introduces non-trivial code changes. These code changes need to be supported forever once the release of VictoriaMetrics with exemplar support is published. This doesn't align well with [VictoriaMetrics development goals](https://docs.victoriametrics.com/goals/).
    
# Issues with Prometheus exemplars:
    
- Prometheus still has only experimental support for exemplars after more than three years since they were introduced. It stores exemplars in memory, so they are lost after Prometheus restart. This doesn't look like production-ready feature. See https://github.com/prometheus/docs/blob/0a2f3b37940e2949eefe752ed7b6c768e0b00128/content/docs/instrumenting/exposition_formats.md?plain=1#L153-L159 and https://prometheus.io/docs/prometheus/latest/feature_flags/#exemplars-storage
- It is very non-trivial to expose exemplars alongside metrics in your application, since the official Prometheus SDKs for metrics' exposition ( https://prometheus.io/docs/instrumenting/clientlibs/ ) either have very hard-to-use API for exposing exemplars or do not have this API at all. For example, try figuring out how to expose exemplars via https://pkg.go.dev/github.com/prometheus/client_golang@v1.19.1/prometheus .
- It looks like exemplars are supported for [Histogram](https://docs.victoriametrics.com/keyconcepts/#histogram) metric type only - see https://pkg.go.dev/github.com/prometheus/client_golang@v1.19.1/prometheus#Timer.ObserveDurationWithExemplar . Exemplars aren't supported for [Counter](https://docs.victoriametrics.com/keyconcepts/#counter), [Gauge](https://docs.victoriametrics.com/keyconcepts/#gauge) and [Summary](https://docs.victoriametrics.com/keyconcepts/#summary) metric types.
- Grafana has very poor support for Prometheus exemplars. It looks like it supports exemplars only when the query contains [`histogram_quantile()`](https://docs.victoriametrics.com/metricsql/#histogram_quantile) function. It queries exemplars via [special Prometheus API](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-exemplars) (which is still marked as experimental, btw.) and then displays all the returned exemplars on the graph as special dots. The issue is that this doesn't work in production when the [`histogram_quantile()`](https://docs.victoriametrics.com/metricsql/#histogram_quantile) is calculated over thousands of histogram buckets exposed by big number of application instances. Every histogram bucket may expose an exemplar on every timestamp shown on the graph. This makes the graph unusable, since it is literally filled with thousands of exemplar dots. Neither Prometheus API nor Grafana doesn't provide the ability to filter out unneeded exemplars.
- Exemplars are usually connected to traces. While traces are good for some production cases with low load, they do not work for highly loaded systems, since the costs for storing and processing traces in highly loaded systems are prohibitively high. E.g. you pay much more than you can get from the ability to investigate collected traces.

I doubt exemplars will become production-ready in the near future because of the issues outlined above.
    
# Alternative to exemplars
    
Exemplars are marketed as a silver bullet for the correlation between metrics, traces and logs - just click the exemplar dot on some graph in Grafana and instantly see the corresponding trace or log entry! This doesn't work as expected in production as shown above. Are there better solutions, which work in production? Yes - just use time-based and label-based correlation between metrics, traces and logs. Assign the same `job` and `instance` labels to metrics, logs and traces, so you can quickly find the needed trace or log entry by these labels on the time range with the anomaly on metrics' graph. Of course, this doesn't give you `one click` feeling advertised in exemplars, but you still can find the correlated logs and traces very quickly. Do you really want paying all the costs and inconveniences related to exemplars in order to be able to switch to the related trace or log entry in one click?

Closing this feature request as won't implement because it doesn't align well with [VictoriaMetrics development goals](https://docs.victoriametrics.com/goals/).

**Closed by valyala** 2024-07-03 14:35 UTC
Labels: enhancement

**Comment by szibis** [comment] 2024-07-31 11:46
As VictoriaMetrics support OTLP Exemplars are stable in this protocol https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exemplars which means anyone using OTLP with VictoriaMetrics could expect this support on ingest and store (for example like in Mimir with some limits).
I understand some points here and I have lived in environments that allows just to jump into specific timeranges for specific tags from traces or logs kind of usable but minimize complexity of metrics backend for sure.
Still even for non production use at some point this could be very useful and maybe can be implemented in VM.
