### ISSUE TITLE
interpolate() unexpectedly extrapolates

### ISSUE THREAD

**Issue by mactyr** [VictoriaMetrics/VictoriaMetrics#3816] opened 2023-02-13 20:48 UTC
### Describe the bug

When I use the `interpolate()` MetricsQL function, I expect it to linearly interpolate between existing samples in the series, as the name suggests. I observe that it does this, but it also unexpectedly synthesizes data beyond the end of the available samples (i.e. it extrapolates) which creates the impression that we have data beyond when we actually do.

We would like to be able to use this function on "counter" style data, where linear interpolation is a good approximation of what most likely occurred during a data gap. (Because if we know the counter value at the beginning of the gap and at the end of the gap, assuming the increase was evenly distributed during the gap is a reasonable guess.) However, we do not have a reliable way to estimate what happened to the counter _beyond_ the end of the available samples, because we don't know what the next counter value will wind up being, so `interpolate()` guessing at values beyond the end of the data samples is unsafe for our application. 

### To Reproduce

Apply `interpolate()` to any range query with a time range ending beyond the end of the available samples. Observe that `interpolate()` returns points beyond the end of the available underlying samples, as in the screenshot below.

### Version

`victoria-metrics-20221014-071630-tags-v1.82.1-0-g011f52718`

### Screenshots

Here's an example screenshot. Notice that `interpolate()` fills a small gap between samples (which is good!) but also extends the series well beyond the end of the samples (which is undesirable). I have vertically offset the interpolated series here by a constant amount so they are easy to distinguish visually.

![image](https://user-images.githubusercontent.com/2031680/218569717-dc9a4a68-1cba-4611-8968-28d3b55b5e08.png)

### Used command-line flags

`-retentionPeriod=120 -dedup.minScrapeInterval=1s
-search.disableCache -search.maxPointsPerTimeseries=50000 -search.maxPointsSubqueryPerTimeseries=600000 -search.latencyOffset=1s`

### Additional information

For what it's worth, I am the person who [originally requested the interpolate() function](https://stackoverflow.com/questions/62565021/linear-interpolation-in-promql-or-metricsql). :slightly_smiling_face:

**Comment by valyala** [comment] 2023-02-23 02:41
@mactyr , thanksf for filing the bugreport! The [interpolate](https://docs.victoriametrics.com/MetricsQL.html#interpolate) shouldn't add artificial points outside the real points starting from the commit aaef0bac00dd895c73234583e3406d3428421c45 . This commit will be included in the next release. In the mean time you can build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the fix works as intended.

**Comment by valyala** [comment] 2023-02-25 00:25
The `interpolate()` behavior has been fixed in [v1.87.2](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue then as fixed.

**Closed by valyala** 2023-02-25 00:25 UTC
Labels: bug, metricsql

**Comment by valyala** [comment] 2023-02-25 03:39
FYI, the issue with the `interpolate()` function has been also fixed in [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html).
