### ISSUE TITLE
LTS releases v1.97.2 and v1.97.3 are enterprise only?

### ISSUE THREAD

**Issue by candlerb** [VictoriaMetrics/VictoriaMetrics#6005] opened 2024-03-21 17:36 UTC
### Is your question request related to a specific component?

Community edition (all components)

### Describe the question in detail

v1.97.x is the latest LTS release. However whilst v1.97.0 and v1.97.1 releases include both enterprise and community assets, [v1.97.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/v1.97.2) and [v1.97.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/v1.97.3) assets show only the enterprise components.

Is this intentional? Should community users stick with v1.93.13 LTS?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment] 2024-03-22 07:14
Duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5811

**Closed by hagen1778** 2024-03-22 07:14 UTC
Labels: question
