### ISSUE TITLE
Importing data from Thanos via vmctl fails

### ISSUE THREAD

**Issue by ldx** [VictoriaMetrics/VictoriaMetrics#3132] opened 2022-09-20 04:50 UTC
**Describe the bug**
Trying to import data from Thanos via `vmctl prometheus` fails.

**To Reproduce**
Copied data from a Thanos S3 bucket to local disk, then running:

    vmctl prometheus --prom-snapshot stage/ --vm-addr http://vm-victoria-metrics-single-server.victoria-metrics:8428

fails with the error message:

    2022/09/20 04:41:42 import process failed: read failed for block "01FZ80S3MKJDB1RM746X1K9V88": cannot populate chunk 8: invalid chunk encoding "<unknown>"

**Expected behavior**
Import to succeed.

**Logs**
```vmctl prometheus --prom-snapshot stage/ --vm-addr http://vm-victoria-metrics-single-server.victoria-metrics:8428
Prometheus import mode
Prometheus snapshot stats:
  blocks found: 1;
  blocks skipped by time filter: 0;
  min time: 1646265600000 (2022-03-03T00:00:00Z);
  max time: 1647475200000 (2022-03-17T00:00:00Z);
  samples: 512541101;
  series: 69610009.
Found 1 blocks to import. Continue? [Y/n] y
VM worker 0:↖ ? p/s
VM worker 1:↖ ? p/s
Processing blocks: 0 / 1 [▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒] 0.00%
2022/09/20 04:41:42 import process failed: read failed for block "01FZ80S3MKJDB1RM746X1K9V88": cannot populate chunk 8: invalid chunk encoding "<unknown>"
```

**Version**
vmctl:
    vmctl version vmctl-20220908-105850-tags-v1.81.2-0-gdd1126dcc

VM server: v1.18.2

**Used command-line flags**
See above.

**Comment by dmitryk-dk** [comment] 2022-09-21 07:27
Hi @ldx ! Thank you for your issue. If it is possible can you share data which you try to import? It will help us to investigate the issue

**Comment by ldx** [comment] 2022-09-21 13:26
> Hi @ldx ! Thank you for your issue. If it is possible can you share data which you try to import? It will help us to investigate the issue

I'm afraid I can't, but I'm happy to try debug builds or investigate with other tools if you can guide me. It's 100% reproducible.

**Comment by dmitryk-dk** [comment] 2022-09-21 16:48
Yeah, i understand)! I will try to reproduce it by myself. I think your data was compressed and that is why vmctl can't import it

**Comment by ldx** [comment] 2022-09-21 17:57
> Yeah, i understand)! I will try to reproduce it by myself. I think your data was compressed and that is why vmctl can't import it

Thanks! Let me know if there's anything I can do to help.

**Comment by dmitryk-dk** [comment] 2022-09-22 09:51
Hi @ldx ! Do you use compactor applies the compaction procedure?

**Comment by dmitryk-dk** [comment] 2022-09-23 08:56
Thank you for the information. I will take a look and will try to reproduce it.

**Comment by dupondje** [comment] 2022-11-21 12:47
I do hit the same issue currently when trying to import Thanos data into VictoriaMetrics.

Now what I do notice is that VictoriaMetrics has a prehistoric dependency on Prometheus?
	github.com/prometheus/prometheus v1.8.2-0.20201119142752-3ad25a6dc3d9
	
Is there a reason to use such an old version?

**Comment by hagen1778** [comment] 2022-11-22 11:45
No actual reason for that. It was just used at the moment when feature was added to the code. Do you think bumping the version would fix the error mentioned here?

**Comment by dupondje** [comment] 2022-11-22 11:50
Well I did a custom build with a up-to-date prometheus lib, but issue is the same.
But it seems to be logic, as the blocks are written by Thanos TSDB code, it's not compatible with the Prometheus TSDB code.

Or the code gets adjusted to use Thanos TSDB code so it can read Thanos written blocks which are compacted/downsampled. Or the import is done via Remote Read.

**Comment by hagen1778** [comment] 2022-11-24 14:53
Thanks! I think, we should pursue approach with RemoteRead API via https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3232

**Comment by valyala** [comment] 2022-12-11 11:53
FYI, [vmctl](https://docs.victoriametrics.com/vmctl.html) is able to migrate data from any system, which supports Prometheus remote_read protocol, to VictoriaMetrics, starting from [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/vmctl.html#migrating-data-by-remote-read-protocol).

**Comment by dmitryk-dk** [comment] 2023-01-17 09:21
Hi @ldx ! Can you check the new realization of the vmctl and close the issue?

**Comment by hagen1778** [comment] 2023-01-26 11:45
Closing the issue as inactive. Feel free to reopen if the problem still exists.

**Closed by hagen1778** 2023-01-26 11:45 UTC
Labels: bug, vmctl

**Comment by ldx** [comment] 2023-01-26 15:23
> Hi @ldx ! Can you check the new realization of the vmctl and close the issue?

Sorry for the late reply. I don't have an environment right now to test this, but I can reopen the issue if I bump into this again. Thanks!
