### ISSUE TITLE
vmalert: detect alerting rules which don't match any series at all

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4039] opened 2023-03-30 11:55 UTC
### Is your feature request related to a problem? Please describe

Alerting rules, in most of the cases are defined with some condition in expression. For example:
* `increase(http_requests_errors_total) > 0`
* `changes(app_uptime_seconds) > 2`

If the expression returns something in response, the alert will be triggered. If no response is received, then the alert remains inactive - it is assumed conditions in expression aren't met.

However, there is no way to tell whether it is comparison condition wasn't met or it is series selector returned nothing. It is very easy to make a typo in `http_reqeusts_errors_total` and such an expression will always return nothing.

### Describe the solution you'd like

It would be great if vmalert could differentiate between expressions that do not match any series at all and expressions that do not meet conditions. With recently enhanced response from VM HTTP API it becomes possible - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3925

What can be done:
1. vmalert can start parsing new field `seriesFetched` in response for alerting rules. vmalert shouldn't complain if the field is missing to remain compliant with Prometheus or older versions of VM.
2. The value from this field can be used for the following enhancements:
2.1. expose `seriesFetched` as a metric per alerting rule, in the same fashion as `vmalert_alerting_rules_last_evaluation_samples`. Such a metric can then be used for alerting purposes. For example, `vmalert_alerting_rules_last_evaluation_series_fetched == 0` will identify rules which do not match any series.
2.2. expose `seriesFetched` in vmalert's UI next to alerting rule. Rules with `seriesFetched==0` can be marked as yellow/warn rules which need to be taken care of. UI should contain an explanation why the rule is marked so and what can be done.
3. Changes should be consistent with alert's state object and object representation via API.
4. The improvement is relevant for alerting rules mostly. Recording rules are expected to always produce samples in response, so "bad" recording rules can be easily identified via `vmalert_recording_rules_last_evaluation_samples` metric.

 

### Describe alternatives you've considered

Tools like https://github.com/cloudflare/pint already do such a validation by running alerting rules without conditions. However, such checks are done only periodically: before applying the rule or when making changes to the rule. If the metric changes in a runtime - the problem will remain undetected.
Using https://github.com/cloudflare/pint  is also an extra step to do. It would be great if such a feature was built-in in the ruler.

**Comment by Haleygo** [comment] 2023-03-31 15:24
@hagen1778 I would love to take this task if you want :)

Will add `Stats` when `parsePrometheusResponse` and store it in latest `ruleStateEntry`, is it ok withyou?
<img width="855" alt="image" src="https://user-images.githubusercontent.com/39937150/229154984-e3f73a6a-7dd5-4c13-a95e-7e7f01410abe.png">
<img width="926" alt="image" src="https://user-images.githubusercontent.com/39937150/229159957-c30ed700-2416-4cbf-9c2c-8b0275694672.png">

**Comment by Haleygo** [comment] 2023-04-03 13:58
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/39937150/229527356-028a8632-dd1b-4f03-af48-255d1bb7fc57.png">
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/39937150/229527619-b37086c2-9869-4bf4-be19-473f40fb3914.png">

**Comment by valyala** [comment] 2023-05-10 04:48
The feature has been implemented in the commit 5b8450fc1b0dcd8dcc2a567a8f2fc1fc95544f5c . See [these docs](https://docs.victoriametrics.com/vmalert.html#never-firing-alerts) for details. This feature will be included in the next release. In the mean time it is possible to build `vmalert` from this commit according to [these instructions](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) and verify whether the feature works as intended.

**Comment by valyala** [comment] 2023-05-18 23:15
FYI, `vmalert` exposes `vmalert_alerting_rules_last_evaluation_series_fetched` metric for probably incorrect alerting queries, which match zero time series, starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmalert.html#never-firing-alerts) for details.

Closing the feature request as done.

**Closed by valyala** 2023-05-18 23:15 UTC
Labels: enhancement, vmalert
