### ISSUE TITLE
Out of order labels with the flag -sortLabels set

### ISSUE THREAD

**Issue by carlosrmendes** [VictoriaMetrics/VictoriaMetrics#5461] opened 2023-12-13 22:22 UTC
### Describe the bug

I started to get the error `sending a block with size ***** bytes to "*****" was rejected (skipping the block): status code 409; response body: store locally for endpoint : add ***** series: out of order labels` on version v1.96.0, even with the flag `-sortLabels` set. Previously on version v1.89.1 the error did not occur and vmagent could write all the metrics to thanos receiver successfully.

### To Reproduce

Configure a thanos receiver as remote write endpoint with `-sortLabels` and (at least one) `-remoteWrite.label` flags set

### Version

v1.96.0

**Comment by carlosrmendes** [comment] 2023-12-13 22:35
I figured it out that the `--remoteWrite.label` are now being added at the end of the metric labels, without being sorted with the original labels. Why this behavior change? It can be reverted?

**Comment by carlosrmendes** [comment] 2023-12-13 23:23
on version `v1.93.0`, with the `-sortLabels` and `-remoteWrite.label` flags set is working as expected. On version `v1.93.1` the `out of order labels` error start occurring, so the `-sortLabels` stopped to work as intended, as it started to not include the remoteWrite labels in the sort

**Comment by hagen1778** [comment] 2023-12-19 10:46
Related ticket https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3875

**Comment by Haleygo** [comment] 2024-01-10 09:32
close this as dup with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3875.

**Closed by Haleygo** 2024-01-10 09:32 UTC
Labels: bug

**Comment by valyala** [comment] 2024-01-30 23:48
> I figured it out that the --remoteWrite.label are now being added at the end of the metric labels, without being sorted with the original labels. Why this behavior change? It can be reverted?

The `-remoteWrite.label` labels are added after the [relabeling](https://docs.victoriametrics.com/vmagent/#relabeling) or [stream aggregation](https://docs.victoriametrics.com/stream-aggregation/) in order to guarantee that the labels specified via `-remoteWrite.label` command-line flag are reliably added to all the samples before sending them to `-remoteWrite.url`. Previously it was possible to drop or modify `-remoteWrite.label` labels via relabeling or stream aggregation. This wasn't an intended behavior. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4247#issuecomment-1673219662 for details.
