### ISSUE TITLE
Different record result value

### ISSUE THREAD

**Issue by destanyinside** [VictoriaMetrics/VictoriaMetrics#2023] opened 2021-12-30 09:04 UTC
**Describe the bug**
In different versions of Victoria Metrics, different value of records

**To Reproduce**
I have a records - [pastebin](https://pastebin.com/naQMHs4b)
When I execute query - 
`GET /select/0/prometheus/api/v1/query_range?start=1640851805&end=1640851805&query=`[pastebin](https://pastebin.com/r9g5sq6H)

I have different result:
<details>
<summary>build version: vmstorage-20211022-171744-tags-v1.68.0-cluster-0-g9e0a67cf1</summary>
<br>
{
  "status": "success",
  "isPartial": false,
  "data": {
      "resultType": "matrix",
      "result": [
          {
              "metric": {
                  "cluster": "cluster1"
              },
              "values": [
                  [
                      1640851805,
                      "1.1536226787670585"
                  ]
              ]
          }
      ]
  }
}
</details>
<details>
<summary>build version: vmstorage-20210901-142404-tags-v1.65.0-cluster-0-ga88b02287</summary>
<br>
{
  "status": "success",
  "isPartial": false,
  "data": {
      "resultType": "matrix",
      "result": [
          {
              "metric": {
                  "cluster": "cluster1"
              },
              "values": [
                  [
                      1640851805,
                      "0.9910193813652163"
                  ]
              ]
          }
      ]
  }
}
</details>

**Expected behavior**
Equal results in different versions for the same time interval

**Version**
vmstorage-20211022-171744-tags-v1.68.0-cluster-0-g9e0a67cf1
vmstorage-20210901-142404-tags-v1.65.0-cluster-0-ga88b02287

**Actions**
Was try to delete all time series in job
Was try to delete all records

**Comment by hagen1778** [comment] 2022-01-05 07:11
Hi @destanyinside! Thanks for your request.
The pastebin snippet contains a lot of expressions - which one exactly results into different responses? Could you also provide a dump of raw datapoints acquired via [export API](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-export-time-series) so I can reproduce it locally?

**Comment by destanyinside** [comment] 2022-01-11 07:21
Hi @hagen1778
Dump time series - [here](https://drive.google.com/file/d/1XDegZK2YNVMewpmC5rBbJT3siB0at_eE/view?usp=sharing)
Expression:
<details>
<summary>Expression. Parametrs: Start=1641883905, End=1641883905</summary>
<br>
1 - (<br>
(sum by (cluster) <br>(cluster_verb_scope:apiserver_request_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE", cluster!=""})<br>
  -<br>
  sum by (cluster) <br>(cluster_verb_scope_le:apiserver_request_duration_seconds_bucket:increase30d{verb=~"POST|PUT|PATCH|DELETE",le="1", cluster!=""})<br>
) +<br>
(sum by (cluster) (cluster_verb_scope:apiserver_request_duration_seconds_count:increase30d{verb=~"LIST|GET", cluster!=""})<br>
  -<br>
  (<br>
    (sum by (cluster) <br>(cluster_verb_scope_le:apiserver_request_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope=~"resource|",le="1", cluster!=""})<br>
      or<br>
      vector(0)<br>
    )<br>
    +<br>
    sum by (cluster) <br>(cluster_verb_scope_le:apiserver_request_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="namespace",le="5", cluster!=""})<br>
    +<br>
    sum by (cluster) <br>(cluster_verb_scope_le:apiserver_request_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="cluster",le="40", cluster!=""})<br>
  )<br>
) +<br>
sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5..", cluster!=""} or vector(0))<br>
)<br>
/<br>
sum by (cluster) (code:apiserver_request_total:increase30d{cluster!=""})<br>
</details>

**Comment by hagen1778** [comment] 2022-01-11 10:43
Thanks for provided data!
Looks like the main discrepancy in results between VM versions happens for the following subquery:
```
sum by (cluster)
(cluster_verb_scope_le:apiserver_request_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope=~"resource|",le="1", cluster!=""})
```
Apparently, it is related to `scope=~"resource|"` selector and the relevant issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1601.
The fix for it was released in https://docs.victoriametrics.com/CHANGELOG.html#v1660

**Comment by valyala** [comment] 2024-02-13 21:52
Closing the issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1601 .

**Closed by valyala** 2024-02-13 21:52 UTC
Labels: bug, question
