### ISSUE TITLE
MetricsQL: add Numerical sort / sort_by_label

### ISSUE THREAD

**Issue by synepolskyi** [VictoriaMetrics/VictoriaMetrics#2938] opened 2022-08-04 11:37 UTC
**Is your feature request related to a problem? Please describe.**
I have a set of metrics with pseudo-numerical labels like "1:0:0", "1:0:2", "1:0:15". These metrics are exposed in Grafana dashboards.
I want to sort them in numerical order, i.e. 1:0:0 -> 1:0:1 -> 1:0:2 -> ... -> 1:0:15.
The current `sort_by_label` function result is 1:0:0 -> 1:0:1 -> 1:0:15 -> ... -> 1:0:2 - the alphabetical order - which is not user-friendly and very counter-intuitive.
![image](https://user-images.githubusercontent.com/58190857/182837056-62761217-d766-4c29-bab0-c5b883c29a06.png)

**Describe the solution you'd like**
It'd be nice to have a possibility to set numerical or alphabetical sort mode or to have separate functions for numerical sort.

**Describe alternatives you've considered**
Since the graphical representation of metrics in my case is covered by Grafana, I checked their sort/transformation abilities, but none of them can satisfy the needs.

**Comment by valyala** [comment] 2022-09-14 14:45
@synepolskyi , VictoriaMetrics gained support for [sort_by_label_numeric](https://docs.victoriametrics.com/MetricsQL.html#sort_by_label_numeric) and [sort_by_label_numeric_desc](https://docs.victoriametrics.com/MetricsQL.html#sort_by_label_numeric_desc) functions in the commit b75f1854c55740ca13fc07aca5e93ac8d4c8ca04 . This commit will be included in the next VictoriaMetrics release. In the mean time you can build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether these functions work as intended.

**Comment by valyala** [comment] 2022-10-07 02:13
VictoriaMetrics gains support for sort_by_label_numeric and sort_by_label_numeric_desc functions starting from [release v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.

**Closed by valyala** 2022-10-07 02:13 UTC
Labels: enhancement, metricsql
