### ISSUE TITLE
VictoriaLogs vmui: ability to abort a long-running query 

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#7797] opened 2024-12-11 10:00 UTC
### Is your feature request related to a problem? Please describe

Sometimes the query has very suboptimal parameters (e.g. too large interval or number of records) and execution takes too long.

<img width="2560" alt="image" src="https://github.com/user-attachments/assets/08f5435d-6e5d-46e2-a92f-17c402aad179">

### Describe the solution you'd like

It would be convenient to be able to press Escape to cancel the current query.

**Comment by Loori-R** [comment] 2024-12-12 09:49
Duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7097

**Closed by Loori-R** 2024-12-12 09:49 UTC
Labels: enhancement, vmui, victorialogs
