### ISSUE TITLE
Sudden spike in pendings once in few hours

### ISSUE THREAD

**Issue by eilonmonday** [VictoriaMetrics/VictoriaMetrics#1165] opened 2021-03-31 07:05 UTC
Hello,
We are using vm cluster (v1.56.0-cluster) and we face abnormal behaviour every once in a while.
There is spikes in RPC errors, and in Pendings (see images below)
a bit information about our configuration:
- 12 vminsert
- 8 storage
- replicationFactor: 3
- retentionPeriod: 3
- *Multi AZ
- Storage size 2Ti
- dedup.minScrapeInterval: 15s

![Screen Shot 2021-03-31 at 9 26 53](https://user-images.githubusercontent.com/78688722/113103456-f8b57500-9207-11eb-8ebc-e16b46ccd394.png)
![Screen Shot 2021-03-31 at 9 27 06](https://user-images.githubusercontent.com/78688722/113103464-fb17cf00-9207-11eb-804c-0e69669b52fa.png)
![Screen Shot 2021-03-31 at 9 27 53](https://user-images.githubusercontent.com/78688722/113103466-fc48fc00-9207-11eb-8a1a-beb73b65f8a9.png)

Some interesting logs:
**vmstorage:**
`{"ts":"2021-03-31T01:35:15.864Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:175","msg":"cannot process vminsert conn from 10.32.35.237:49228: cannot read packet size: cannot read data in 151.132 seconds: cannot read data from the underlying reader: read tcp4 10.32.21.184:8400->10.32.35.237:49228: read: connection timed out"}
`
bug 

**vminsert:**
`{"ts":"2021-03-31T02:23:00.308Z","level":"warn","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:236","msg":"cannot send 349917 bytes with 719 rows to -storageNode=\"victoria-metrics-cluster-vmstorage-6.victoria-metrics-cluster-vmstorage.victoria-metrics-cluster.svc.cluster.local:8400\": cannot read `ack` from vmstorage: cannot read data in 0.000 seconds: EOF; closing the connection to storageNode and re-routing this data to healthy storage nodes"}

{"ts":"2021-03-31T04:46:59.509Z","level":"warn","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:206","msg":"cannot dial storageNode \"victoria-metrics-cluster-vmstorage-6.victoria-metrics-cluster-vmstorage.victoria-metrics-cluster.svc.cluster.local:8400\": dial tcp4: lookup victoria-metrics-cluster-vmstorage-6.victoria-metrics-cluster-vmstorage.victoria-metrics-cluster.svc.cluster.local on 172.20.0.10:53: no such host"}
`

**Comment by valyala** [comment] 2021-03-31 13:26
It looks like the issue is related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/791 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1054

**Comment by valyala** [comment] 2021-05-13 06:33
FYI, the probability of the rerouting issue should be decreased starting from [v1.59.0](https://docs.victoriametrics.com/CHANGELOG.html#v1590), since it improves the registration speed for new time series on multi-CPU hosts. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1244 for details.

**Comment by valyala** [comment] 2021-06-18 11:08
@eilonmonday , could you upgrade all the cluster components to [v1.61.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and pass `-disableRerouting` command-line flag to `vminsert` nodes? This should disable the re-routing of new samples to other `vmstorage` nodes if the in-memory buffer for the current `vmstorage` nodes becomes full. This should help reducing the size and the duration of pending time series spikes in your case.

**Comment by valyala** [comment] 2022-02-07 14:44
The next version of VictoriaMetrics will contain improved logic for data re-routing in the event if some of vmstorage nodes are temporarily unavailable or if some of vmstorage nodes temporarily slow down the processing speed for incoming data. The following improvements will be included in the next release of VictoriaMetrics cluster:
* Even series distribution among the remaining vmstorage nodes. Previously some vmstorage nodes could start receiving multiple times more series than other vmstorage nodes if some vmstorage nodes were unavailable or were slower than other vmstorage nodes.
* Reduced the maximum increase in the number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) on the remaining vmstorage nodes after some vmstorage nodes become unavailable or become slow. It will be limited by 100% of the initial number of active time series per vmstorage node in the worst case (e.g. when vmstorage nodes have no enough resources to keep up with the increased load). Under normal conditions the increase in the number of active time series shouldn't exceed `1/N` of the initial number of active time series per vmstorage node, where `N` is the number of `vmstorage` nodes in the cluster. Previously the typical increase in the number of time series per vmstorage node after the re-routing was closer to 100%, while in the worst case it could reach `(N-1)`x.
* The placement of time series among `vmstorage` nodes doesn't depend on the order of `vmstorage` addresses passed to `-storageNode` command-line flag at `vminsert` nodes thanks to the changed consistent hashing algorithm (from [jump hash](https://arxiv.org/abs/1406.2294) to [rendezvous hash](https://www.eecs.umich.edu/techreports/cse/96/CSE-TR-316-96.pdf) ). Previously samples for the same time series could be placed to multiple `vmstorage` nodes if multiple `vminsert` nodes had different order of `vmstorage` nodes passed to `-storageNode` command-line flag. This could result in increased number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) across all the vmstorage nodes, which, in turn, could result in higher resource usage (RAM, CPU, disk IO, disk space) at `vmstorage` nodes.

These improvements should improve the stability of the mode with enabled rerouting in the cluster (e.g. when `-disableRerouting=false` command-line flag is passed to `vminsert`. The re-routing is disabled by default starting from [v1.66.0](https://docs.victoriametrics.com/CHANGELOG.html#v1660) ).

The next release of VictoriaMetrics also adds an ability to drop incoming samples if vmstorage nodes are temporarily unavailable and/or overloaded if `-dropSamplesOnOverload` command-line flag is passed to `vminsert` nodes. By default vminsert slows down accepting new samples if vmstorage cannot keep up with the ingestion rate. This may result in increased number of pending samples at client side, which sends data to vminsert. This increases the delay between samples' generation and samples' ingestion into vmstorage. This may result in incomplete query results, which rely on recently ingested data (e.g. alerting and recording rules). In this case the `-dropSamplesOnOverload` mode may help receiving the most recently generated samples at the cost of dropping older samples. The number of dropped samples is tracked in per-`vmstorage` counter at `vminsert` nodes - `vm_rpc_rows_dropped_on_overload_total` . See more details at [changelog](https://docs.victoriametrics.com/CHANGELOG.html).

The features mentioned above can be tested by building cluster components of VictoriaMetrics from the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster) (currently this is 755e26e67b44962bada3a427e114d3f6ae284b5b ) according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337 .

**Comment by hagen1778** [comment] 2023-01-26 13:52
Closing the issue as inactive. Feel free to reopen if the problem still exists.

**Closed** 2023-04-27 07:29 UTC
Labels: bug
