### ISSUE TITLE
VictoriaMetrics doesn't respect memory limit inside LXC container

### ISSUE THREAD

**Issue by rumanzo** [VictoriaMetrics/VictoriaMetrics#84] opened 2019-06-27 16:26 UTC
HI! I try limit cache of vm with value 8, and got:
`panic: FATAL: -memory.allowedPercent must be in the range [10...200]; got 8.000000`
In my case VictoriaMetrics's instances running in lxc container's, and lxc containers are limited with lxc.cgroup.memory.limit_in_bytes, and I'm afraid that VictoriaMetrics get down (and what will really happend in this case?), if VictoriaMetrics exceed limit. But host server have a lot of RAM (256Gb), and limit even 10% it's too much (container is allowed to use more less).  Can you remove the restriction or make it not relative, but absolute in gb/mb?

**Comment by valyala** [comment] 2019-06-27 16:48
There is no sense in setting too low `-memory.allowedPercent`.

`-memory.allowedPercent` must be calculated relative to the memory limit set in the container. It this doesn't work, then this is bug which should be fixed. VictoriaMetrics reports the calculated limit in bytes when starting. Search for the following line in output logs:
```
limiting caches to XXX bytes of RAM according to -memory.allowedPercent
```

Additionally the maximum allowed memory size in bytes is reported on `/metrics` page via `vm_allowed_memory_bytes` metric.

Check for these limits when starting VictoriaMetrics in the container with constrained memory. If they exceed container's limit, then report it back.

> and what will really happend in this case?

It is likely OOM killer will kill VictoriaMetrics process in this case.

**Comment by rumanzo** [comment] 2019-06-27 17:02
I checked it, seems look like a bug?

> Search for the following line in output logs:
> 
> ```
> limiting caches to XXX bytes of RAM according to -memory.allowedPercent
> ```

... lib/memory/memory.go:33#011limiting caches to 27017510912 bytes of RAM according to -memory.allowedPercent=10


> Additionally the maximum allowed memory size in bytes is reported on `/metrics` page via `vm_allowed_memory_bytes` metric.

vm_allowed_memory_bytes 27017510912

from lxc config:
`lxc.cgroup.memory.limit_in_bytes = 28G
lxc.cgroup.memory.memsw.limit_in_bytes = 28G`

total mem:
`# cat /proc/meminfo
MemTotal:       263842880 kB`

**Comment by valyala** [comment] 2019-06-28 07:14
Could you check whether the memory limit is applied to any container? Probably it is related to https://github.com/lxc/lxc/issues/2845 . The workaround is [to install lxcfs](https://github.com/lxc/lxc/issues/2845#issuecomment-469590817).

**Comment by rumanzo** [comment] 2019-06-28 09:13
> Could you check whether the memory limit is applied to any container?

I checked it, limit is works

on host machine
`
cat /sys/fs/cgroup/memory/lxc/victoriametrics1-1.vm.p/memory.limit_in_bytes
30064771072
`

on container:
\# python3

import psutil
import os
process = psutil.Process(os.getpid())
gb = 'a'*(1024**3)
gbs = ''
while True:
    print(process.memory_info().rss)
    gbs += gb

1083060224
3230756864
4304453632
...
26853019648
27926634496
Killed
\#

**Comment by rumanzo** [comment] 2019-06-28 09:34
We had a negative experience with lxcfs, although a fairly old version. 
There is no other way?

**Comment by valyala** [comment] 2019-06-28 12:39
I tried fixing memory limit reading according to [this suggestion](https://unix.stackexchange.com/questions/242718/how-to-find-out-how-much-memory-lxc-container-is-allowed-to-consume) in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ad436757c3162ee62c0c794d7db0af5ccf4d134c
@rumanzo , could you build VictoriaMetrics from the latest commit and verify whether it properly reads memory limit inside LXC container?

**Comment by rumanzo** [comment] 2019-06-28 13:00
No difference:
# curl -u http://localhost:8428/metrics 2>/dev/null | grep 'vm_app_version\|vm_allowed_memory_bytes'
vm_app_version{version="victoria-metrics-20190628-125306-heads-master-0-g7354f10"} 1
vm_allowed_memory_bytes 27017512550

**Comment by valyala** [comment] 2019-06-28 15:10
OK, then another attempt: update to 7b59466667fc49be0311b3745b955dacb20aaba3 and try again

**Comment by rumanzo** [comment] 2019-06-28 16:00
> OK, then another attempt: update to [7b59466](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7b59466667fc49be0311b3745b955dacb20aaba3) and try again

\# curl -u 'prom:rvFYHpJK7wsmfWP' http://localhost:8428/metrics 2>/dev/null | grep 'vm_app_version\|vm_allowed_memory_bytes'
vm_app_version{version="victoria-metrics-20190628-155702-heads-master-0-g828078e"} 1
vm_allowed_memory_bytes 27017512550
\# expr 27017512550 / 1024 / 1024 / 1024
25

**Comment by valyala** [comment] 2019-06-28 21:14
Well, this is quite strange.

1. What does the following command return from inside the LXC container for VictoriaMetrics with memory limits?
```
cat $(mount | grep cgroup | grep memory | cut -d' ' -f3)$(cat /proc/self/cgroup | grep memory | cut -d: -f3)/memory.limit_in_bytes
```
2. Try [these instructions](https://github.com/moby/moby/issues/396#issuecomment-179470044).

**Comment by rumanzo** [comment] 2019-07-01 09:13
> Well, this is quite strange.
> 
> 1. What does the following command return from inside the LXC container for VictoriaMetrics with memory limits?
> 
> ```
> cat $(mount | grep cgroup | grep memory | cut -d' ' -f3)$(cat /proc/self/cgroup | grep memory | cut -d: -f3)/memory.limit_in_bytes
> ```
> 
> 1. Try [these instructions](https://github.com/moby/moby/issues/396#issuecomment-179470044).
\# cat $(mount | grep cgroup | grep memory | cut -d' ' -f3)$(cat /proc/self/cgroup | grep memory | cut -d: -f3)/memory.limit_in_bytes
cat: /sys/fs/cgroup/memory: Is a directory
cat: /sys/fs/cgroup/memory/lxc/victoriametrics1-1.vm.p/lxc/victoriametrics1-1.vm.p/memory.limit_in_bytes: No such file or directory

right place:
\# cat /sys/fs/cgroup/memory/lxc/victoriametrics1-1.vm.p/memory.limit_in_bytes
30064771072

**Comment by valyala** [comment] 2019-07-01 10:01
I need to determine how to properly construct the path to `/sys/fs/cgroup/memory/lxc/victoriametrics1-1.vm.p/memory.limit_in_bytes` inside LXC container. Could you provide the output of the following commands inside LXC container for VictoriaMetrics?
```
mount | grep cgroup | grep memory
cat /proc/self/cgroup | grep memory
```

**Comment by rumanzo** [comment] 2019-07-01 10:27
> I need to determine how to properly construct the path to `/sys/fs/cgroup/memory/lxc/victoriametrics1-1.vm.p/memory.limit_in_bytes` inside LXC container. Could you provide the output of the following commands inside LXC container for VictoriaMetrics?
> 
> ```
> mount | grep cgroup | grep memory
> cat /proc/self/cgroup | grep memory
> ```

\# mount | grep cgroup | grep memory
cgroup_root on /sys/fs/cgroup/memory type tmpfs (ro,relatime,size=10240k,mode=755)
cgroup on /sys/fs/cgroup/memory/lxc/victoriametrics1-1.vm.p type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
\# cat /proc/self/cgroup | grep memory
10:memory:/lxc/victoriametrics1-1.vm.p

**Comment by valyala** [comment] 2019-07-01 11:03
Try building VictoriaMetrics from the [latest commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c7034fc51b8b03745ab5b275cb2a5714efc021f8) and verifying whether it properly determines memory limit inside LXC container.

**Comment by rumanzo** [comment] 2019-07-01 11:17
> Try building VictoriaMetrics from the [latest commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c7034fc51b8b03745ab5b275cb2a5714efc021f8) and verifying whether it properly determines memory limit inside LXC container.

\# curl http://localhost:8428/metrics 2>/dev/null | grep 'vm_app_version\|vm_allowed_memory_bytes'
vm_app_version{version="victoria-metrics-20190701-111523-heads-master-0-gc7034fc"} 1
vm_allowed_memory_bytes 3006477107

Looks good! Thank you

**Comment by valyala** [comment] 2019-07-01 13:39
Thank you for the assistance in detecting the root cause of the issue!

**Closed by valyala** 2019-07-01 13:39 UTC
Labels: bug, enhancement
