### ISSUE TITLE
vmagent: wrong scrape_duration in one of targets

### ISSUE THREAD

**Issue by mef13** [VictoriaMetrics/VictoriaMetrics#3293] opened 2022-10-31 11:11 UTC
**Describe the bug**
Hi!
I use vmagent to scrape a several targets on localhost and one of targets has wrong scrape_duration duration.

example of my targets:

```yaml 
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  external_labels:
    collector: tester
scrape_configs:

- job_name: test-db
  static_configs:
  - targets:
    - 127.0.0.1:3001
  relabel_configs:
  - source_labels:
    - instance
    replacement: db.test
    target_label: instance

- job_name: test-math
  static_configs:
  - targets:
    - 127.0.0.1:3000
  relabel_configs:
  - source_labels:
    - instance
    replacement: math.test
    target_label: instance
```

And test-db has scrape duration about 2 second

![image](https://user-images.githubusercontent.com/15233008/198993410-e2913d9b-4dab-4bdf-86f4-d172c33d4a62.png)

But if i click on "response" I got ~ 40-60 ms ever.
![image](https://user-images.githubusercontent.com/15233008/198994135-a7cad887-dd82-49c8-91f6-60a6803e987e.png)

**Version**
I test it on 
`vmagent-20221014-071846-tags-v1.82.1-0-g011f52718`
and
`vmagent-20221029-004945-tags-v1.83.0-0-g740f7ac5e`

**Comment by hagen1778** [comment] 2022-11-01 12:25
Hello @mef13! Do you see this 2s duration all the time or just occasionally?
Although, the response size on your screenshot seems too small for 1100 samples - are you sure you're receiving the correct data from the correct target there?

**Comment by mef13** [comment] 2022-11-01 14:45
> Hello @mef13! Do you see this 2s duration all the time or just occasionally?

Hi!
Yes, I see 2s duration all time, with some accuracy. 
![image](https://user-images.githubusercontent.com/15233008/199257487-7fa74005-2937-4062-a432-43aca688276b.png)

> Although, the response size on your screenshot seems too small for 1100 samples - are you sure you're receiving the correct data from the correct target there?

Yes, I receiving the correct data from the correct target there. Maybe chrome compress data..
![image](https://user-images.githubusercontent.com/15233008/199259393-2f38d344-8263-4379-a0aa-db966716c9d8.png)

And postman shows correct size in response (response time longer from network issue)
![image](https://user-images.githubusercontent.com/15233008/199260828-18b77855-d757-4621-9f9e-f4cf3ce801a9.png)

**Comment by mef13** [comment] 2022-11-01 15:40
Maybe important: My targets is nodejs apps with https://github.com/jochen-schweizer/express-prom-bundle package.

**Comment by hagen1778** [comment] 2022-11-02 12:52
Hello! Looks like the difference between targets is that one is parsed in stream fashion and the second one in default one. It is unclear why scrape duration is different between those two. But I'll have a look.

**Comment by guillemj** [comment] 2023-02-08 11:19
We've seen the same thing on our platform, but with victoria-metrics, for two targets that are not golang based and are thus not written using the golang prometheus client modules. One is written in perl based on mojolicious, the other in C based on libwebsockets.

When tracking this down, we found that these other libraries (and I'm assuming the nodejs one above is the same), use short keep-alive timeouts (f.ex. 5s for mojolicious) which are always lower than the scrapping intervals (10s in our case). The golang prometheus client keep-alive timeout seems to be set at 30s, but I guess if you configured a longer scrapping interval in victoria-metrics then you'd easily see this with any of the golang prometheus exporters too.

So what seems to be happening is that victoria-metrics opens a connection, the keep-alive times out and the connection gets closed, and on the next interval victoria-metrics tries to scrap reusing that connection, notices the connection is now closed, and for some reason waits 2s until it opens a new connection, instead of doing that immediately.

Hope that helps.

**Comment by hagen1778** [comment] 2023-02-09 10:32
Ah, that makes sense! VM indeed retries a scrape attempt in 2s after the error https://github.com/VictoriaMetrics/VictoriaMetrics/blob/bff18cb5dd6926e22ee42c36cebe6f7c93ccccfb/lib/promscrape/client.go#L350-L377

To prove this we can verify if `vm_promscrape_scrape_retries_total` metric increments for such target. @mef13 is this what you observe?

Also, no need to wait for 2s here. For a closed connection we can retry immediately. I think, default HTTP client already does it, but we use a modification of fasthttp client here. Tagging @zekker6 here since he was the last who touched that code.

**Comment by mef13** [comment] 2023-02-16 06:01
> To prove this we can verify if `vm_promscrape_scrape_retries_total` metric increments for such target.

Yes, when `scrape_duration` is more 2s, `vm_promscrape_scrape_retries_total` increments every time.

**Comment by valyala** [comment] 2023-02-24 20:32
@mef13 , could you build `vmagent` from the commit c6ad3692ad77307215b8cf77a073cc62af1744ae according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether this fixes the issue with wrong scrape duration for the target?

This commit will be included in the next release.

**Comment by valyala** [comment] 2023-02-25 00:18
FYI, [vmagent v1.87.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.2) contains the fix mentioned above. @mef13 , could you verify whether the issue with wrong scrape duration is gone there?

**Comment by valyala** [comment] 2023-02-25 03:34
The fix mentioned above has been included also in [vmagent v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). @mef13 , could you check whether `vmagent v1.88.0` fixes the issue with wrong scrape duration in your case?

**Comment by mef13** [comment] 2023-03-07 16:40
Hi! Sorry for long response, but I already don't have target with this issue :(

**Comment by zekker6** [comment] 2023-04-20 11:20
Going to close this as resolved, feel free to reopen if issue will become reproducible.

**Closed by zekker6** 2023-04-20 11:20 UTC
Labels: enhancement, vmagent
