### ISSUE TITLE
delta and changes return wrong data 

### ISSUE THREAD

**Issue by manoja1** [VictoriaMetrics/VictoriaMetrics#1556] opened 2021-08-23 21:36 UTC
**Describe the bug**
We are running on the latest v1.64.1

In VictoriaMetrics`delta` and `changes` return `1` even when the previous data point has no data. This is different from how Prometheus works.  

**Screenshots**
See grafana charts below. we started reporting a new metric `asserts:version:info` and immediately `delta[5m]` and `changes[5m]` return `1`.

<img width="2377" alt="Screen Shot 2021-08-23 at 2 30 42 PM" src="https://user-images.githubusercontent.com/33231759/130522154-1c28bbbb-13fc-463b-bd5c-2e25e1a51937.png">

**Expected behavior**
See below promtool test that exhibits the desired behavior.  

```
evaluation_interval: 1m
tests:
  - interval: 1m
    input_series:
      - series: 'test:stale{workload="test"}'
        values: 'stale stale 1  2 stale 2 stale'
    promql_expr_test:
      - expr: changes(test:stale[1m]) > 0
        eval_time: 1m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 2m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 3m
        exp_samples:
          - labels: '{workload="test"}'
            value: 1

      - expr: changes(test:stale[1m]) > 0
        eval_time: 4m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 5m
        exp_samples:

      - expr: changes(test:stale[1m]) > 0
        eval_time: 6m
        exp_samples:
      
      # test delta
      - expr: delta(test:stale[1m]) > 0
        eval_time: 1m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 2m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 3m
        exp_samples:
          - labels: '{workload="test"}'
            value: 1

      - expr: delta(test:stale[1m]) > 0
        eval_time: 4m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 5m
        exp_samples:

      - expr: delta(test:stale[1m]) > 0
        eval_time: 6m
        exp_samples:

```

**Version**
version metric from`vm_app_version`
<img width="1656" alt="Screen Shot 2021-08-23 at 2 29 28 PM" src="https://user-images.githubusercontent.com/33231759/130522033-3466e2ee-f8a5-4a17-a4c7-d84f518591af.png">

**Comment by valyala** [comment] 2021-08-25 06:49
This is the expected behavior. Most users expect that time series start from 0. So if the first sample in the series isn't 0, then it is expected that the `delta()`, which covers the first sample, should return the sample value. For example, if `http_requests_total` series has the following values `[5, 11, 20]` at timestamps `[t1, t2, t3]`, it is expected that the `delta(http_requests_total[1h])` returns the following values if `t3-t1 < 1h`:
* 5 at `t1`
* 11 at `t2`
* 20 at `t3`

Unfortunately, Prometheus ignores the first point in the series when calculating `delta()`, so it returns the following values, which most users don't expect:
* nothing at `t1`
* 6 at `t2`
* 15 at `t3`

Additionally, Prometheus uses extrapolation when calculating `delta()` and `increase()`, so it may return unexpected fractional results for time series containing only integer values. This is documented at [MetricsQL page](https://docs.victoriametrics.com/MetricsQL.html).

Similar logic applies to `changes()`. Most users expect that `changes()` over the first sample in a time series returns 1, since the series has been changed from `nothing` to `something`. Unfortunately, Prometheus returns `nothing` in this case instead of 1.

**Comment by YuriKravetc** [comment] 2022-07-29 18:22
@manoja1 Hi, can we consider this issue as solved?

**Comment by YuriKravetc** [comment] 2022-08-09 17:29
Closing the issue, feel free to reopen it if consider unsolved.

**Closed by YuriKravetc** 2022-08-09 17:29 UTC
Labels: question
