### ISSUE TITLE
"Collapse all" button in vmagent web ui

### ISSUE THREAD

**Issue by wowsel** [VictoriaMetrics/VictoriaMetrics#2021] opened 2021-12-29 08:52 UTC
**Is your feature request related to a problem? Please describe.**

I always get upset when I open vmagent targets ui because I have a lot of collection targets and I really miss the collapse all button.

**Describe the solution you'd like**

"Collapse all" button in the vmagent targets interface. And "expand all". 

**Describe alternatives you've considered**

You can also make sure that all targets are already collapsed when you open the interface.

**Additional context**

![telegram-cloud-photo-size-2-5359331274113791234-y](https://user-images.githubusercontent.com/18245332/147644093-3c0731bc-0999-455a-95e2-55b401a275d1.jpg)

Thanks

**Comment by valyala** [comment] 2022-02-12 16:44
@wowsel , vmagent should provide `collapse all` and `expand all` buttons starting from the commit f10c38b82750650dcd944e454a2b1640af7ecd38 . This commit will be included in the next release. In the mean time you can verify whether this works as intended by building `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment] 2022-02-14 16:57
`vmagent` displays `collapse all` and `expand all` buttons at `http://vmagent:8429/targets` page starting from [v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Closed by valyala** 2022-02-14 16:57 UTC
Labels: enhancement, vmagent
