### ISSUE TITLE
VictoriaLogs UI sometimes loses log records in Firefox

### ISSUE THREAD

**Issue by eduardbareev** [VictoriaMetrics/VictoriaMetrics#6281] opened 2024-05-15 16:19 UTC
### Describe the bug

The number of rows displayed doesn't match the number of rows returned by server.

The issue appears in following browsers:

- Firefox 123.0 (mozilla tarball)
- Firefox 124.0.1 (Fedora system package, clean VM install)

Chrome is not affected probably (never observed the issue)

Please see the video attached:
[viclogslostrows.webm](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/947781/03f16290-aa20-4355-86c4-96d8adcdc970)

### To Reproduce

There is no sure way to reproduce this

### Version

`victoria-logs-20240514-010820-tags-v0.6.1-victorialogs-0-gc90e6de13b`

**Comment by hagen1778** [comment] 2024-05-15 18:33
@Loori-R could you please take a look?

**Comment by Loori-R** [comment] 2024-05-17 14:52
@eduardbareev Hi, could you please send the server response when the logs is not displaying? This will help us identify the issue more easily.

**Comment by eduardbareev** [comment] 2024-05-18 15:33
> @eduardbareev Hi, could you please send the server response when the logs is not displaying? This will help us identify the issue more easily.

While suffering from bugs VictoriaLogs cannot sensibly respond to queries, suddenly it started to return different records in different order in unpredictable manner, therefore I can't make it to return those three records.

However it turned out that I left one of browsers with developer tools open. Attached are screenshot and a HAR file whose last entry corresponds to what's on screenshot.

[viclogsui.har.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/15365867/viclogsui.har.json)

[viclogsui](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/947781/ea7bc795-0b56-4260-9774-20b020169be3)

**Comment by eduardbareev** [comment] 2024-05-18 19:46
@Loori-R  My observation is that whether a record would be missing from rendering correlates to the length of it's `_msg`. In Firefox on my machine, a record with `_msg` of 100k chars have 9/10 chances to not have a row in a resulting table. Small messages are always displayed. With this 3-records dataset [viclogs_jsonlines.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/15366648/viclogs_jsonlines.txt) a second row is the one that gets absent almost always.

**Comment by Loori-R** [comment] 2024-05-20 14:00
@eduardbareev Thanks, your observations were very helpful! I have opened a pull request #6310 with the fix.

**Comment by valyala** [comment] 2024-05-22 20:17
[The fix](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6310) has been included in [VictoriaLogs v0.9.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.9.0-victorialogs). @eduardbareev , could you verify that the issue is fixed in this release?

**Comment by eduardbareev** [comment] 2024-05-22 20:56
> [The fix](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6310) has been included in [VictoriaLogs v0.9.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.9.0-victorialogs). @eduardbareev , could you verify that the issue is fixed in this release?

can't open `/select/vmui/?` in 0.9.0, says 404. `/select/vmui/?` is where "select/vmui - Web UI for VictoriaLogs" link on `/` (main page) points to

**Comment by eduardbareev** [comment] 2024-05-23 10:52
@valyala , checked 0.9.1, seems to me that the bug is gone. 

By the way, I wanted to let you know about this feature request https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6301

**Comment by Loori-R** [comment] 2024-07-11 13:23
The bug has been fixed in [VictoriaLogs v0.9.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.9.0-victorialogs).

**Closed by Loori-R** 2024-07-11 13:23 UTC
Labels: bug, vmui, victorialogs
