### ISSUE TITLE
Add support for Azure blob storage in vmbackup

### ISSUE THREAD

**Issue by sharninder** [VictoriaMetrics/VictoriaMetrics#2596] opened 2022-05-16 11:45 UTC
Any reasons for not supporting Azure blob storage as a destination target in vmbackup ? Are there any plans to supporting it in the future ?

**Comment by valyala** [comment] 2022-10-05 21:26
Closing this feature request as a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1029 .

**Closed by valyala** 2022-10-05 21:26 UTC
Labels: question, backup
