### ISSUE TITLE
vmui calendar does not show last day of a month

### ISSUE THREAD

**Issue by rtm0** [VictoriaMetrics/VictoriaMetrics#6239] opened 2024-05-08 05:38 UTC
### Describe the bug

VMUI calendar widget does not show the last day of a month.

### To Reproduce

1.  Navigate to `Explore > Explore Cardinality`
2. Click on the date in right upper corner. A calendar widget should appear.
3. Choose any month other than current. Confirm that the widget shows `all` days for the chosen month. Example: ![vmui-calendar-01](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/149964189/a6aa38d9-64c8-450f-9e35-ddbf2fa74a21)
4. Pick any day of that month. That should close the widget
5. Click of the date again. A calendar appears again. But this time the last day of the month is not shown. Example: ![vmui-calendar-02](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/149964189/1a628d94-db3b-4096-ac19-e9af92a83f13)

### Version

`v1.100.1` built locally with `make victoria-metrics`

Wasn't able to try on v1.101.0 because for that version the UI won't load at all. Possibly due to #6224

**Comment by Loori-R** [comment] 2024-05-08 08:50
Thank you for pointing out the issue.
Indeed, the calendar does not display correctly in Firefox and Safari.
As an alternative until the issue is resolved, you can use Chrome.

**Comment by Loori-R** [comment] 2024-05-10 14:32
Sorry, this is not related to the browser version. The problem occurs when the time zone is set to `UTC+00:00`

**Comment by hagen1778** [comment] 2024-05-14 07:41
Hey @Loori-R, do you know whether previous versions of VM (1.93, 1.97) were affected?

**Comment by Loori-R** [comment] 2024-05-14 11:23
@hagen1778, It's likely the problem has always been there. At least since `1.85.0`, when the ability to change the timezone was added

**Comment by valyala** [comment] 2024-06-07 20:43
The issue must be fixed in [v1.97.5 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.5) and in [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).

**Closed by valyala** 2024-06-07 20:43 UTC
Labels: bug, vmui
