### ISSUE TITLE
vmagent reload

### ISSUE THREAD

**Issue by symmetriac** [VictoriaMetrics/VictoriaMetrics#2270] opened 2022-03-01 15:52 UTC
**Describe the bug**
We have multiple vmagent configuration.
When one of them reloads configuration we see 
```{"ts":"2022-03-01T11:11:29.949Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:137","msg":"SIGHUP received; reloading Prometheus configs from \"/etc/vmagent/config_out/vmagent.env.yaml\""}
{"ts":"2022-03-01T11:11:29.970Z","level":"info","caller":"VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:157","msg":"SIGHUP received; reloading relabel configs pointed by -remoteWrite.relabelConfig and -remoteWrite.urlRelabelConfig"}
{"ts":"2022-03-01T11:11:29.970Z","level":"info","caller":"VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:164","msg":"Successfully reloaded relabel configs"}
{"ts":"2022-03-01T11:11:50.440Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:388","msg":"kubernetes_sd_configs: added targets: 0, removed targets: 2975; total targets: 0"}
{"ts":"2022-03-01T11:12:01.485Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:388","msg":"kubernetes_sd_configs: added targets: 2975, removed targets: 0; total targets: 2975"}
```

And it stops scraping targets for a few seconds.
In the same time other vmagents were reloaded without a note about removing all targets and their scrape rate remained the same.
When all vmagents are reloaded and removed all their targets there are holes in our metrics, but it happens occasionally. 

Why sometimes vmagent reloads with removing all targets and sometimes without?

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
v1.71.0
```

**Comment by f41gh7** [comment] 2022-03-01 17:52
Hello, can you check if you increase the value for `-promscrape.kubernetesSDCheckInterval=60s`. Will it help? Is a workaround not a solution.

**Comment by jianglinjian** [comment] 2022-03-04 14:54
in my opinion, the root cause is vmagent restart all ScrapeConfigs even if just one ScrapeConfig has been changed. in this issue, k8s service discovery takes almost 30s to ListWatch Objects, so that `GetScrapeWorkObjects` cannot provide any `ScrapeWork` for `scraper` in this period.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/scraper.go#L147-L148
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/config.go#L76-L94

**Comment by symmetriac** [comment] 2022-03-23 14:27
> Hello, can you check if you increase the value for `-promscrape.kubernetesSDCheckInterval=60s`. Will it help? Is a workaround not a solution.

No, it didn't help, still having this issue.

**Comment by valyala** [comment] 2022-04-16 17:37
`vmagent` should stop reloading unmodified scrape configs after the commit 26b78ad707af75074df1d5444add07a4b261ad6a . 

@symmetriac , could you verify whether this reduces config reload times for your case? You can build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources). If you run `vmagent` Docker image, then try the docker image tag `heads-public-single-node-0-g26b78ad70`, which is built from this commit.

**Comment by valyala** [comment] 2022-04-20 13:24
@jianglinjian , @symmetriac , could you try vmagent built from the commit 2341bd48d713492eeb6ec8c368bab34031058c32 ? It should have much better service discovery performance comparing to previous versions of vmagent.

**Comment by valyala** [comment] 2022-05-05 10:02
`vmagent` should [reload](https://docs.victoriametrics.com/vmagent.html#configuration-update) `-promscrape.config` files with big number of scrape_config entries much faster starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). This should be especially visible when `vmagent` runs on multi-CPU systems.

Closing the issue as fixed.

@jianglinjian , @symmetriac , feel free re-opening the issue if `vmagent v1.77.0` still reloads the big `-promscrape.config` files slower than expected.

**Closed by valyala** 2022-05-05 10:02 UTC
Labels: bug, vmagent
