### ISSUE TITLE
Unreliable histogram_quantile after upgrade to v1.102.0

### ISSUE THREAD

**Issue by voron** [VictoriaMetrics/VictoriaMetrics#6714] opened 2024-07-27 06:24 UTC
### Describe the bug

I'm not sure if it's related to #6547, but my charts with `histogram_quantile` become completely unreliable after `vmsingle` v1.101.0->v1.102.0 upgrade

### To Reproduce

Change vmsingle version to v1.102.0 and revert back to v1.101.0, compare `histogram_quantile` charts between versions

### Version

```
/victoria-metrics-prod  -version
victoria-metrics-20240717-185244-tags-v1.102.0-0-g65bb429b81
```

### Screenshots

Here is just one of examples
v1.101.0
<img width="1363" alt="v0 101 0" src="https://github.com/user-attachments/assets/9cd010e6-a0e0-4f62-a16c-b05436f8081b">
v1.102.0
<img width="1366" alt="v0 102 0" src="https://github.com/user-attachments/assets/41ff1e72-c05b-4e00-98fc-7d60db42ccb1">

### Used command-line flags

```
      -dedup.minScrapeInterval=1ms
      -httpListenAddr=:8429
      -maxLabelsPerTimeseries=100
      -retentionPeriod=366
      -search.latencyOffset=1s
      -search.maxQueryLen=65536
      -search.maxSeries=300000
      -storageDataPath=/victoria-metrics-data
      -vmalert.proxyURL=http://vmalert-victoria-metrics-k8s-stack.vm.svc:8080
```

**Comment by jiekun** [comment] 2024-07-30 06:26
Hi @voron . Could you export the raw data for `head_lag_seconds_bucket{<your_label_filter})` so that I could validate it locally.
It could be simple by using the export function under Query.

![image](https://github.com/user-attachments/assets/3eedded2-bf1e-463a-8535-ab676611e46f)

**Comment by Lusitaniae** [comment] 2024-08-09 03:45
Same issue, I wrongly reported to Grafana first

**Comment by zez-drow** [comment] 2024-08-13 07:40
Hello!
We have the same issue after updating vmselect   
 v.1.93.13 
![image](https://github.com/user-attachments/assets/c8d3404c-0e74-437c-8728-d13fcba8d4cf)
 v.1.93.16
 
![image](https://github.com/user-attachments/assets/ee924a79-88f9-4547-ba29-5b12a047b55b)

**Comment by linjunzhe** [comment] 2024-08-13 13:33
Same issue here. We have a v1.93.15 cluster which is working fine, but another v1.93.16 cluster which returns a totally wrong histogram_quantile result with the same data. 
v1.93.15
![image](https://github.com/user-attachments/assets/bb60c14d-ecde-4cff-97f6-37a794035c23)
v1.93.16
![image](https://github.com/user-attachments/assets/11de60e5-3caf-45e7-b12a-abca7d0af447)

**Comment by zekker6** [comment] 2024-08-14 16:30
@Lusitaniae thank you for providing data example, that helped to reproduce and get this fixed in #6807 .


Could you try using the following image and verify if that helps?
vmselect - [docker.io/victoriametrics/vmselect:tags-v1.102.1-cluster-1-g5124bda780](https://hub.docker.com/layers/victoriametrics/vmselect/tags-v1.102.1-cluster-1-g5124bda780/images/sha256-73f7e440fe1e1ddabee8bcc7eec3ce990df51dc8ee2846a9842ea65881600bae?context=explore)
VictoriaMetrics single-node - [docker.io/victoriametrics/victoria-metrics:tags-v1.102.1-1-g76115c611f](https://hub.docker.com/layers/victoriametrics/victoria-metrics/tags-v1.102.1-1-g76115c611f/images/sha256-ee596694eeda00b8fc3e174d7bae51e23b2dd6c81978ebc4a11950f1ded394a4?context=explore)

These images are build on top of [v1.102.1](https://docs.victoriametrics.com/changelog/#v11021) with a fix from PR referenced above cherry-picked on top of the released version.

**Comment by hagen1778** [comment] 2024-08-29 12:35
The bugfix was included into [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030), [v1.102.2](https://docs.victoriametrics.com/changelog/#v11022), [v1.97.7](https://docs.victoriametrics.com/changelog/#v1977).

**Closed by hagen1778** 2024-08-29 12:35 UTC
Labels: bug, metricsql, waiting for release

**Comment by xiaozongyang** [comment] 2024-09-25 09:35
same iusse on `v1.102.1-cluster`, docker image tag is `victoriametrics/vmselect:v1.102.1-cluster`

**Comment by hagen1778** [comment] 2024-09-25 09:55
> Will this be backported to 1.93.x LTS line, or 1.93.16 was the last release?

No. LTS 1.93 is no longer supported. Refer to https://docs.victoriametrics.com/lts-releases/ for current supported lines.

**Comment by hagen1778** [comment] 2024-09-25 09:56
> same iusse on v1.102.1-cluster(vmselect-20240801-130125-tags-v1.102.1-cluster-0-g115a76d28c), docker image tag is victoriametrics/vmselect:v1.102.1-cluster

@xiaozongyang as mentioned [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6714#issuecomment-2317529085) only following versions got the fix:  [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030), [v1.102.2](https://docs.victoriametrics.com/changelog/#v11022), [v1.97.7](https://docs.victoriametrics.com/changelog/#v1977).
Each of these versions has single and cluster versions.

**Comment by xiaozongyang** [comment] 2024-09-25 10:00
@hagen1778 I can't find any docker image with tag like `v1.103.0-cluster` in [dokcer hub](https://hub.docker.com/r/victoriametrics/victoria-metrics/tags?name=v1.103). Do i used a wrong tag keyword?

**Comment by hagen1778** [comment] 2024-09-25 10:02
@xiaozongyang see the following links:
* vmstorage https://hub.docker.com/layers/victoriametrics/vmstorage/v1.103.0-cluster/images/sha256-5cba349fa754651816cfd68cf5a1006f4c3a8dbbe2e8f46177b1cc72d0d8db1a?context=explore
* vmselect https://hub.docker.com/layers/victoriametrics/vmselect/v1.103.0-cluster/images/sha256-3de1e98c871370666f33c490070bbe6f8a5b651ac9848c7ab968b96be32a1f24?context=explore
* vminsert https://hub.docker.com/layers/victoriametrics/vminsert/v1.103.0-cluster/images/sha256-5710918d9bc9e5b18614eca622377e21f51a6e84e093e6c28b64a1543a94dddb?context=explore

**Comment by xiaozongyang** [comment] 2024-09-25 10:05
thanks a lot ! @hagen1778

**Comment by changshun-shi** [comment] 2024-10-25 12:17
Maybe a warning that means there is a bug in v1.93.x if it will be not supported is better. Because it's very new but can not be use.
