### ISSUE TITLE
Some time series are occasionally missing via momentary "query" requests with vmselect v1.44.0

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#847] opened 2020-10-21 14:59 UTC
Today I upgraded vmselect to latest version v1.44.0 and faced the problem that sometimes momentary queries (via ```/api/v1/query?query=```) returning not all time series. This leads to, for example, false positive alerts of services instances count. At the same time range queries and graphs not containing any gaps.

Looks like a bug in the latest version, because problem stopped reproducing when I downgraded vmselect to v1.43.0.

**Comment by f41gh7** [comment] 2020-10-22 00:58
duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/845

**Closed by f41gh7** 2020-10-22 00:58 UTC
