### ISSUE TITLE
v1.63.0 vmstorage panic by accident

### ISSUE THREAD

**Issue by bleedfish** [VictoriaMetrics/VictoriaMetrics#1652] opened 2021-09-26 01:39 UTC
**Describe the bug**
we have more than 100 vmstorage nodes, some vmstorage  may panic  by accident

**Logs**

`unexpected fault address 0x7ee501606000
fatal error: fault
 [signal SIGBUS: bus error code=0x4 addr=0x7ee501606000 pc=0x47da5d]

goroutine 9678329 [running]:
runtime.throw(0x9a4844, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc3aee39708 sp=0xc3aee396d8 pc=0x443112
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:731 +0x2c8 fp=0xc3aee39740 sp=0xc3aee39708 pc=0x45a808
runtime.memmove(0xc32d5d8000, 0x7ee50160558b, 0x2837)
	/usr/local/go/src/runtime/memmove_amd64.s:362 +0x41d fp=0xc3aee39748 sp=0xc3aee39740 pc=0x47da5d
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.(*ReaderAt).MustReadAt(0xc068ccd1a0, 0xc32d5d8000, 0x2837, 0x6000, 0xff58b)
	 /VictoriaMetrics/lib/fs/reader_at.go:57 +0xfb fp=0xc3aee39878 sp=0xc3aee39748 pc=0x6c6cdb
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partSearch).readIndexBlock(0xc2880b3d88, 0xc3c28d59c0, 0x0, 0xc2880b3d90, 0xc3c28d59c0)
	 /VictoriaMetrics/lib/storage/part_search.go:214 +0x113 fp=0xc3aee39920 sp=0xc3aee39878 pc=0x7a97b3
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partSearch).nextBHS(0xc2880b3d88, 0x0)
	 /VictoriaMetrics/lib/storage/part_search.go:162 +0x297 fp=0xc3aee39a00 sp=0xc3aee39920 pc=0x7a8f97
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partSearch).NextBlock(0xc2880b3d88, 0xc0000a6070)
	 /VictoriaMetrics/lib/storage/part_search.go:98 +0x5e fp=0xc3aee39a20 sp=0xc3aee39a00 pc=0x7a8cbe
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partitionSearch).Init(0xc20bfc8c00, 0xc06e5fd380, 0xc3281318c0, 0x1, 0x1, 0x17c03380321, 0x17c03412ae1)
	 /VictoriaMetrics/lib/storage/partition_search.go:99 +0x31a fp=0xc3aee39ae8 sp=0xc3aee39a20 pc=0x7b7f1a
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*tableSearch).Init(0xc2c4edc0a8, 0xc065080180, 0xc3281318c0, 0x1, 0x1, 0x17c03380321, 0x17c03412ae1)
	 /VictoriaMetrics/lib/storage/table_search.go:92 +0x20b fp=0xc3aee39bc0 sp=0xc3aee39ae8 pc=0x7d6b6b
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Search).Init(0xc2c4edc080, 0xc0001a41c0, 0xc0b497c040, 0x1, 0x1, 0x17c03380321, 0x17c03412ae1, 0x186a0, 0x614883b9, 0x8)
	 /VictoriaMetrics/lib/storage/search.go:189 +0x195 fp=0xc3aee39c70 sp=0xc3aee39bc0 pc=0x7ba575
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).processVMSelectSearch(0xc065080380, 0xc2c4edc000, 0x0, 0x0)
	 /VictoriaMetrics/app/vmstorage/transport/server.go:1061 +0x272 fp=0xc3aee39d30 sp=0xc3aee39c70 pc=0x7f20d2
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).processVMSelectRequest(0xc065080380, 0xc2c4edc000, 0x0, 0x0)
	 /VictoriaMetrics/app/vmstorage/transport/server.go:498 +0x48c fp=0xc3aee39e20 sp=0xc3aee39d30 pc=0x7ecaac
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).processVMSelectConn(0xc065080380, 0xc2c4bda090, 0x4, 0x9b21e6)
	 /VictoriaMetrics/app/vmstorage/transport/server.go:275 +0xd1 fp=0xc3aee39ec0 sp=0xc3aee39e20 pc=0x7ea451
github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).RunVMSelect.func1(0xc065080380, 0xaaa4d0, 0xc0b484b3e0)
	 /VictoriaMetrics/app/vmstorage/transport/server.go:208 +0x36a fp=0xc3aee39fc8 sp=0xc3aee39ec0 pc=0x7f3eea`

**Screenshots**

![image](https://user-images.githubusercontent.com/3396080/134790160-c09e289f-e712-4dbc-a956-a897bca8ac79.png)

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:

![image](https://user-images.githubusercontent.com/3396080/134790267-6b456bca-7d2d-43c0-bb51-2270ecf0eeff.png)

$ ./victoria-metrics-prod --version
vmstorage-20210803-072031-heads-downgrade-v1.63.0-add-insert-0-ga2c591d-dirty-9e02d65e

**Comment by f41gh7** [comment] 2021-09-27 06:18
Hello, few questions:
1) which storage are you using, local drives or some kind of network storage?
2) which linux kernel? Did you  try to upgrade it?
3) is it reproducible?

**Comment by valyala** [comment] 2021-09-27 15:11
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/581

**Comment by valyala** [comment] 2021-09-28 12:13
The `SIGBUS` signal can trigger if `-storageDataPath` command-line flag points to a network-attached volume when the volume is temporary unavailable due to network issues. See https://www.sublimetext.com/blog/articles/use-mmap-with-care . The workaround is to pass `-fs.disableMmap` command-line flag to VictoriaMetrics. This flag disables reading data via memory-mapped files and falls back to an ordinary [read()](https://man7.org/linux/man-pages/man2/read.2.html) syscall. VictoriaMetrics will crash with `cannot read from file ...` during temporary network errors in this case instead of panic'ing. As you can see, VictoriaMetrics crashes in both cases. The better solution is to reduce the probability of temporary errors for the used network-based filesystem.

**Comment by bleedfish** [comment] 2021-09-29 07:26
> Hello, few questions:
> 
> 1. which storage are you using, local drives or some kind of network storage?
> 2. which linux kernel? Did you  try to upgrade it?
> 3. is it reproducible?

1. we use local drives
2. linux kernel : 
      Distributor ID: Ubuntu
      Description:    Ubuntu 16.04.4 LTS
      Release:        16.04
      Codename:       xenial
3. so far I cannot reproducible
4. GOVERSION="go1.16.6"


yesterday it panic again，this is one log：

`fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x4 addr=0x7f3529bb2338 pc=0x425d1b]

runtime stack:
runtime.throw(0x9b9618, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5
runtime.(*fixalloc).alloc(0xf1e018, 0x7ed1b3546918)
        /usr/local/go/src/runtime/mfixalloc.go:72 +0x3b
runtime.(*mheap).allocMSpanLocked(0xf077e0, 0x1)
        /usr/local/go/src/runtime/mheap.go:1072 +0x71
runtime.(*mheap).allocSpan(0xf077e0, 0x1, 0x6700, 0x7f307ecd5000)
        /usr/local/go/src/runtime/mheap.go:1186 +0x5aa
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246`

this is another panic log :

`fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x4 addr=0xc2fabe99e0 pc=0x446325]

goroutine 39690182 [running]:
runtime.throw(0x9b9618, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0facff500 sp=0xc0facff4d0 pc=0x443112
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5 fp=0xc0facff538 sp=0xc0facff500 pc=0x45a825
runtime.releaseSudog(0xc2cbb1b980)
        /usr/local/go/src/runtime/proc.go:426 +0x125 fp=0xc0facff5a8 sp=0xc0facff538 pc=0x446325
runtime.selectgo(0xc0facff748, 0xc0facff724, 0x0, 0x0, 0x3, 0x1, 0x0, 0x0)
        /usr/local/go/src/runtime/select.go:372 +0x1051 fp=0xc0facff6e0 sp=0xc0facff5a8 pc=0x456f91
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*indexBlockCache).cleaner(0xc2e857f020)
        /gitlab/VictoriaMetrics/lib/mergeset/part.go:202 +0x129 fp=0xc0facff7a8 sp=0xc0facff6e0 pc=0x74cf29
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.newIndexBlockCache.func1(0xc2e857f020)
        /gitlab/VictoriaMetrics/lib/mergeset/part.go:183 +0x52 fp=0xc0facff7d8 sp=0xc0facff7a8 pc=0x75eff2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0facff7e0 sp=0xc0facff7d8 pc=0x47c861
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.newIndexBlockCache
        /gitlab/VictoriaMetrics/lib/mergeset/part.go:181 +0xe7`

**We have 100+ vmstorage nodes, panic focus on the same 6 nodes。**

panic logs show the same error:
SIGBUS: bus error code=0x4

and I find the siginfo define:

/*
 * SIGBUS si_codes
 */
/* hardware memory error consumed on a machine check: action required */
#define BUS_MCEERR_AR	4

**Comment by bleedfish** [comment] 2021-09-29 08:45
maybe panic is  related to hardware memory error。
in file : /var/log/mcelog，it have error logs:

    mcelog: warning: 16 bytes ignored in each record
    mcelog: consider an update
    mcelog: Family 6 Model 55 CPU: only decoding architectural errors
    Hardware event. This is not a software error.
    MCE 0
    CPU 0 Undecoded extended event ff TSC 20104009351706 
    ADDR 16f3fc9600 
    TIME 1632789919 Tue Sep 28 08:45:19 2021
    MCG status:
    MCi status:
    Corrected error
    Error enabled
    MCi_ADDR register valid
    MCA: MEMORY CONTROLLER RD_CHANNELunspecified_ERR
    Transaction: Memory read error
    STATUS 940000000000009f MCGSTATUS 0
    MCGCAP f000c14 APICID 0 SOCKETID 0 
    CPUID Vendor Intel Family 6 Model 85

time of the vmstorage node's panic log  is around time of mcelog error

**Comment by YuriKravetc** [comment] 2022-08-02 12:55
Hi @bleedfish 
A follow-up on this issue.
Can we consider it solved and close it?
If you can share your own progress/experience or workarounds on this - it would be greatly appreciated.

**Comment by f41gh7** [comment] 2023-07-07 12:01
Closing as stale. Feel free to re-open.

**Closed by f41gh7** 2023-07-07 12:01 UTC
Labels: question
