### ISSUE TITLE
tsdb should deny too large merticname & tagvalue

### ISSUE THREAD

**Issue by flashmouse** [VictoriaMetrics/VictoriaMetrics#647] opened 2020-07-22 02:58 UTC
**Is your feature request related to a problem? Please describe.**
for now vm seems doesn't have any way to deny or monitor mertic that have too large size mr & tag values.  this kind of metric could decrease tsdb system availability seriously.

if a large amount of such metrics wrote to vm, it will need much more memory when doing indexdb big merge than usual, and in the worst situation, vmstorage could stop serve, or we would use a machine with larger memory just to avoid OOM when do merge, it's a big waste.

and now we seem have no easy way to find the problem, in our case, many user write data to vm directly in our company, we finally find the metric by tcpdump command.

last year we use influx have the same problem, and influx has a worst perfomance, although we have upgrade memory size 4x larger than before, it even couldn't restart any more.

the root cause is our tsdb user doesn't use tsdb correctly, but we think system must do something with it, it's hard to tell user to use our production correctly just with document.

**Describe the solution you'd like**
1. vm provide process metric or log or any way to find out the data has problem.
2. vm could provide parameters that deny any metric have too large size metircgroup and tagvalue.
3. or at least, as vm user, we should add a porxy before vminsert, and we do this ourselves.

thx!

**Comment by valyala** [comment] 2020-07-22 10:45
Currently the maximum length for label names and label values for the ingested data is controlled via [maxLabelNameLen](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9a2ba5b6d1bf462efee205982494d384a3e1fcef/lib/storage/metric_name.go#L401) and [maxLabelValueLen](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9a2ba5b6d1bf462efee205982494d384a3e1fcef/lib/storage/metric_name.go#L406) constants. VictoriaMetrics truncates labels with longer names and/or values. Probably, these constants could be converted to command-line flags, so users could control the maximum lengths for labels?

**Comment by valyala** [comment] 2020-07-22 10:50
> if a large amount of such metrics wrote to vm, it will need much more memory when doing indexdb big merge than usual

Merge for indexdb data is performed on 64KB blocks. The maximum number of concurrently merged blocks is limited by [defaultPartsToMerge](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9a2ba5b6d1bf462efee205982494d384a3e1fcef/lib/mergeset/table.go#L42) constant, which equals to 15 now. So the memory usage during merging indexdb data shouldn't depend on the length of entries stored in the indexdb. If this isn't the case, then the root cause leading to high memory usage must be identified and fixed.

**Comment by valyala** [comment] 2024-02-07 23:41
The maximum length of label values and metric names can be controlled via `-maxLabelValueLen` command-line flag, which has been added in [v1.71.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1908).

Closing this issue as done.

**Closed by valyala** 2024-02-07 23:41 UTC
Labels: enhancement
