### ISSUE TITLE
Why the concurrent flushes on disk this metric  reached to max cpu limit during the vmcluster retention period 

### ISSUE THREAD

**Issue by zhuzhuzhu36** [VictoriaMetrics/VictoriaMetrics#3472] opened 2022-12-12 11:41 UTC
**Describe the bug**
Our vmcluster spec :  we have 16 instances(each instance: 16c128g disk: 200G throughput: 300M iops: 10000) for whole vmcluster 

We deployed vmstorage vminsert and vmselect these three components on the same instance 
We just keep 1d data 

Phenomenon:
During  the retention time we found that most instances have already reached the max cpu limit

<img width="2440" alt="image" src="https://user-images.githubusercontent.com/38548395/207032289-0d80a6f9-7496-411d-96e6-1865a6c1b82d.png">

but i think the root cause is not due to the disk iops(not reach our limitation)
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/38548395/207041808-42890588-0d64-4c68-b800-3e90cbe45488.png">

So why does retention this behavior consume so much cpu?
Do we need to add more cpu for vmcluster before retention happened? But outside of this retention the cpu usage is normal
<img width="2486" alt="image" src="https://user-images.githubusercontent.com/38548395/207045477-72b59462-f1af-4df6-8008-989cbaa5b0fd.png">

So is  there  any other good way to avoid consuming so much cpu during the retention period? 

When we check the disk throughput 
<img width="2454" alt="image" src="https://user-images.githubusercontent.com/38548395/207043027-f491dc2d-5d70-4c58-9b92-f7caea216138.png">

some instances have reached the throughput limitation during retention period ,does this limitation cause the high cpu usage?

Results:
During the retention period  vmalert process tries to get the metrics from vmcluster, but the calculation error occurs because the data cannot be read

**Version**
v1.82.1-cluster

**Comment by valyala** [comment] 2022-12-14 17:57
`vmstorage` drops some in-memory caches when it rotates `indexdb` partitions, since these caches must contain data related to the current `indexdb` partition, which becomes empty after the rotation. The `indexdb` rotation is performed once per `-retentionPeriod`. After that `vmstorage` needs to re-read and unpack the data missing in the reset caches. This may increase disk read IO usage and CPU usage for some time as in your case. The main root cause of the issue has been already addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401 , but it looks like there are other smaller issues still exist, which may lead to increased CPU usage and disk read IO usage after the `indexdb` rotation.

Side note - it looks like the disk IO at `vmstorage` nodes is very close to 300MB/s limit just before and after the `indexdb` rotation in your case. This could increase the duration for high CPU and disk read IO usage after the `indexdb` rotation. The 250MB/s disk IO usage per `vmstorage` node looks too high for typical workload. Probably, there are other issues exist in your VictoriaMetrics setup. High disk IO (and increased CPU usage) may point to the lack of memory for various in-memory caches maintained by VictoriaMetrics. It is recommended investigating cache-related graphs on the [official dashboard for VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring) for low cache hit rate and high cache usage. The usual solution for these issues is to either increase available memory for `vmstorage` nodes or decrease the workload. See [these docs](https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion) for more details.

**Closed** 2024-07-22 07:28 UTC
Labels: question
