### ISSUE TITLE
Need help about capacity planning

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#1759] opened 2021-10-27 02:56 UTC
**What we have done**
We are working with the AWS environment, trying to collect the EKSsystem hosted Kubernetes container running systems.
More or less there are around **60K** auto-discovered instances.
As we followed these practices:
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning
We put up a cluster like this:

|Number|Service|Spec|
|:---:|:---:|:---:|
|10|Vmagent|c5.4xlarge 16C 32Gb|
|8|Vminsert|c5.9xlarge 36C 72Gb|
|12|Vmstorage|r5.8xlarge 32C 256Gb|

**What we have met**
Vminsert run with very high load and CPU user time for around 30minutes, afterwards suddenly dropped to 0. Then Vmagent disk usage with path `vmagent-remotewrite-data/persistent-queue`
<img width="684" alt="813d08f2-9498-4064-813d-5db0764c14e8" src="https://user-images.githubusercontent.com/33677006/138990947-1d0f1f35-d325-4fcf-9510-e014ac6553d5.png">
![image](https://user-images.githubusercontent.com/33677006/138991279-af28f261-6b31-48d6-b54f-b36df6cabf6e.png)

**What we expected**
A better understanding of why there is a drop or circuit breaker at some moment after starting this cluster.

**More information**
With not complete calculation and collection (cause by data delaying)
- The vminsert ingestion speed be 20-30Mil/s more close to 25M/s  
- The vminsert requests Rate be max 4k/s, around 3k/s

**Configuration**

- Vmagent:
vmagent-20211008-135241-tags-v1.67.0-0-g6058edb0d
```
-http.connTimeout=1000ms -promscrape.maxScrapeSize=250MB -promscrape.suppressDuplicateScrapeTargetErrors -promscrape.cluster.membersCount=10 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=${n} -promscrape.streamParse -promscrape.consulSDCheckInterval=60s -remoteWrite.queues=32 -insert.maxQueueDuration=30s
```

- Vminsert:
vmselect-20211008-140608-tags-v1.67.0-cluster-0-g20fa4b01c
```
-replicationFactor=2 -maxLabelsPerTimeseries=50 -maxConcurrentInserts=120
```

- Vmstorage:
vmstorage-20211008-140613-tags-v1.67.0-cluster-0-g20fa4b01c
```
-search.maxUniqueTimeseries=2000000 -retentionPeriod=1y -bigMergeConcurrency=1 -smallMergeConcurrency=4 -rpc.disableCompression=false
```

**Comment by renchili** [comment] 2021-11-01 02:56
@valyala any update?  We observed with our number of instances under k8s sd. There is very high network usage. But is not possible to do any estimation as is an auto discovery. May you give some advice about vmagent, vminsert performances dealing with a high volume of time series.

**Comment by valyala** [comment] 2024-02-13 01:38
@renchili , some tips regarding the used VictoriaMetrics setup:

- Please remove `-bigMergeConcurrency` and `-smallMergeConcurrency` command-line flags from `vmstorage`. These flags are deprecated, since users tend to improperly configure them. This could result in uncontrolled growth of parts in the database (see [these docs](https://docs.victoriametrics.com/#storage) for more information about `parts` concept), which, in turn, could result in significant query slowdown and significant increase of CPU and RAM usage at `vmstorage` nodes.
- Please remove `-rpc.disableCompression=false` command-line flag from `vmstorage`, since this is the default value for this flag.
- In general, try minimizing the number of command-line flags for VictoriaMetrics components, since the default flag values should work good in most cases.


- There is little sense in setting `-http.connTimeout=1000ms` command-line flag at VictoriaMetrics components, since it doesn't resolve any issues.
- Your `vmagent` instances scrape the same targets twice according to `-promscrape.cluster.replicationFactor=2`. Your `vminsert` nodes write 2 copies of every ingested sample to `vmstorage` nodes according to `-replicationFactor=2`. This means that your setup writes all the scraped samples four times to `vmstorage` nodes. There is no deduplication at `vmstorage` nodes according to the listed command-line flags for `vmstorage`. This means that all the 4 copies of every scraped sample are stored at `vmstorage` nodes and are never de-duplicated. It is likely you need enabling deduplication at `vmstorage` and `vmselect` nodes according to [these docs](https://docs.victoriametrics.com/cluster-victoriametrics/#deduplication).


> Why vminsert can work well under high CPU usage till a certain moment, then vmagent began ate disk space, then vminsert's CPU usage dropped to as it stopped.

It is likely the issue is at `vmstorage` nodes. They couldn't keep up with the data ingestion rate because of lack of some resources such as RAM, CPU, disk IO or network bandwidth. In this case `vminsert` components pause data ingestion to `vmstorage`, so `vmagent` start buffering scraped data at `-remoteWrite.tmpDataPath` directory, since `vminsert` pauses accepting new data.

I'd recommend reading https://docs.victoriametrics.com/Troubleshooting.html and https://docs.victoriametrics.com/vmagent/#troubleshooting .

It is also recommended updating to [the latest VictoriaMetrics release](https://docs.victoriametrics.com/CHANGELOG.html), since older releases may contain bugs, which could result in sudden slowdowns of data ingestion and querying.

Closing the issue as answered.

**Closed by valyala** 2024-02-13 01:38 UTC
Labels: question
