### ISSUE TITLE
Constant growth of goroutines number at vmstorage

### ISSUE THREAD

**Issue by pavdmyt** [VictoriaMetrics/VictoriaMetrics#316] opened 2020-02-12 14:44 UTC
**Describe the bug**

Running VictoriaMetrics cluster `v1.33.0` with 3 vmstorage instances. Observing constant increase in a number of goroutines at `vmstorage` components. Had same behavior with `v1.32.6`.

**To Reproduce**

These issues just started happening after upgrade from `1.31.5` to `1.32.6`.

**Screenshots**

Drops to zero are caused by `vmstorage` restarts.

<img width="1436" alt="vmstorage-goroutines" src="https://user-images.githubusercontent.com/10200820/74344265-ffd7b480-4db4-11ea-84ac-27cfb2d58be7.png">

**Version**

```
vmstorage-20200204-220434-tags-v1.33.0-cluster-0-g8e77b548
```

**Used command-line flags**

`vmstorage` flags:

```
flag{name="bigMergeConcurrency", value="0"} 1
flag{name="dedup.minScrapeInterval", value="0s"} 1
flag{name="enableTCP6", value="false"} 1
flag{name="fs.disableMmap", value="false"} 1
flag{name="http.disableResponseCompression", value="false"} 1
flag{name="httpListenAddr", value=":8482"} 1
flag{name="loggerFormat", value="default"} 1
flag{name="loggerLevel", value="INFO"} 1
flag{name="loggerOutput", value="stderr"} 1
flag{name="memory.allowedPercent", value="60"} 1
flag{name="precisionBits", value="64"} 1
flag{name="retentionPeriod", value="6"} 1
flag{name="rpc.disableCompression", value="false"} 1
flag{name="search.maxTagKeys", value="secret"} 1
flag{name="search.maxTagValues", value="100000"} 1
flag{name="search.maxUniqueTimeseries", value="300000"} 1
flag{name="smallMergeConcurrency", value="0"} 1
flag{name="snapshotAuthKey", value="secret"} 1
flag{name="storageDataPath", value="/vmstorage-data"} 1
flag{name="version", value="false"} 1
```

**Additional context**

Also attaching `/debug/pprof/goroutine` from every `vmstorage` instance:

[vm-pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4192897/vm-pprof.zip)

**Comment by freeseacher** [comment] 2020-02-13 10:31
got the same "issue". it is not with vmstorage core but in grafana dashboard. go_goroutines is gauge not counter.

**Comment by valyala** [comment] 2020-02-13 11:31
Confirmed the issue. It looks like the issue has been introduced in v1.32.3 . It is related to erroneous use of `time.Timer` instead of `time.Ticker` in cleaner code for index and block caches. Each new block creates new `cleaner` goroutine. This goroutine never finishes due to the issue mentioned above. So the number of goroutines constantly grows.
The bug should be fixed in the following commits:
* single-node version - eceaf13e5e1eb5463770fff3ee19b0f3b51d9713
* cluster version - 347aaba79d44df3b21bef1f8f107352a133a635c 

@pavdmyt , @freeseacher , could you build VictoriaMetrics from these commits and verify whether the issue with growing number of goroutines is gone for your workloads? See instructions on how to build VictoriaMetrics from sources:

* [how to build single-node version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources)
* [how to build cluster version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#building-from-sources)

**Comment by valyala** [comment] 2020-02-13 12:12
Oops, found yet another bug, which could result in stuck goroutines after v1.32.3. The bug should be fixed in the following commits:
* single-node version - 7836ad89078847083ae8f9da92cafabe60a0b274
* cluster version - e3b18ca1ab69082ec46e82acd5909f1311e39cc8

@pavdmyt , @freeseacher , could you build VictoriaMetrics from these commit and verify that they fix the goroutine leak?

**Comment by pavdmyt** [comment] 2020-02-13 12:17
@valyala We don't have described issue at our staging cluster. Maybe you can suggest on how to reproduce it? Then we could build VM with recent fixes and try at our staging.

**Comment by valyala** [comment] 2020-02-13 13:11
The issue must be reproduced by creating new time series at constant pace. These time series would add new entries to inverted index. These entries will be put into new inmemory parts, which should trigger the issue with constantly growing goroutines.

**Comment by pavdmyt** [comment] 2020-02-13 15:32
@valyala I'm working on reproducing the issue at stage cluster. Will post results here (probably tomorrow).

**Comment by valyala** [comment] 2020-02-13 16:58
@pavdmyt , the bugfix is available [v1.33.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), so you can try it and verify whether it fixes the issue.

**Comment by pavdmyt** [comment] 2020-02-14 19:58
@valyala After upgrade to v1.33.1 the goroutine leak have disappeared. Now, 3 hours passed after upgrade and number of `vmstorage` goroutines keeps stable, near 450.

Thanks!

**Comment by valyala** [comment] 2020-02-14 20:49
@pavdmyt , thanks for the confirmation! Closing the issue as fixed.

**Closed by valyala** 2020-02-14 20:49 UTC
Labels: bug
