### ISSUE TITLE
add retention size parameter or manual clean for parameter for cli

### ISSUE THREAD

**Issue by elkh510** [VictoriaMetrics/VictoriaMetrics#2919] opened 2022-07-28 14:45 UTC
**Is your feature request related to a problem? Please describe.**
There is a limit to the age of the oldest record stored in the database, set via the -retentionPeriod option.

But during this time, the total size (on disk) of the database is unbound. Depending on the flux of metrics, it could grow very large, exceeding the storage available to the DB.
After disk is totally full pod just restart and retention can't be done.
so retention size param will be very useful for this.
and will be good to have some sidecar container where user can exec and execute cli command to force rotate data on it(by size or by data), this need for case when disk totally full and VictoriaMetrics deployed into k8s.

**Comment by denisgolius** [comment] 2022-07-28 15:47
HI @elkh510 !

Thanks for feature request!

As a workaround for now I suggest the next:
- Setup self monitoring for your VIctoriaMetrics SIngle node or Cluster version and use prepared alerts for them: [for Cluster version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/alerts.yml#L59-L101) and [for Single node version](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml#L61-L103). 
- When the alerts will fire you can increase the size of your storage and set a lower retention period, so the older data will be deleted with the next merge on VictoriaMetrics side and the storage space will be freed.
- Delete metrics - see https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-delete-time-series

**Comment by denisgolius** [comment] 2022-07-28 15:54
Looks like this ticket is a duplicate #342

**Comment by elkh510** [comment] 2022-08-04 08:33
@denisgolius thank you for you replay
but how can I run retention of old data after alert was fired
thank you!

**Comment by valyala** [comment] 2022-08-08 00:28
Closing this issue as a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/342 . Let's move further discussion to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/342 .

**Closed by valyala** 2022-08-08 00:28 UTC
Labels: enhancement
