### ISSUE TITLE
vmbackup: cannot create backup - http2 client connection lost

### ISSUE THREAD

**Issue by muety** [VictoriaMetrics/VictoriaMetrics#3220] opened 2022-10-10 21:42 UTC
**Describe the bug**
I keep getting the following error when trying to `vmbackup` to a GCS bucket.

```bash
./vmbackup-prod -storageDataPath=./victoria-metrics-data -snapshot.createURL=http://localhost:8428/snapshot/create -dst="gs://mybucket-blaah/" -credsFilePath="./gcp-credentials.json" -http.connTimeout=10m -http.idleConnTimeout=10m
```

```

...
2022-10-10T21:28:56.639Z	info	VictoriaMetrics/lib/backup/actions/backup.go:164	uploaded 1081640 out of 5109725 bytes from src fslocal "victoria-metrics-data/snapshots/20221010212624-1719AD425B7B81B2" to dst GCS{bucket: "mybucket-blaah", dir: "/"} in 2m24.471418715s
2022-10-10T21:28:56.643Z	fatal	VictoriaMetrics/app/vmbackup/main.go:105	cannot create backup: cannot upload part{path: "data/small/2022_10/50_33_20221010212630.000_20221010212633.000_1719C8DF0FB4A5DB/min_dedup_interval", file_size: 2, offset: 0, size: 2} to dst GCS{bucket: "mybucket-blaah", dir: "/"}: cannot upload data to "data/small/2022_10/50_33_20221010212630.000_20221010212633.000_1719C8DF0FB4A5DB/min_dedup_interval" at GCS{bucket: "mybucket-blaah", dir: "/"} (remote path "/data/small/2022_10/50_33_20221010212630.000_20221010212633.000_1719C8DF0FB4A5DB/min_dedup_interval/0000000000000002_0000000000000000_0000000000000002"): Post "https://storage.googleapis.com/upload/storage/v1/b/mybucket-blaah/o?alt=json&name=%2Fdata%2Fsmall%2F2022_10%2F50_33_20221010212630.000_20221010212633.000_1719C8DF0FB4A5DB%2Fmin_dedup_interval%2F0000000000000002_0000000000000000_0000000000000002&prettyPrint=false&projection=full&uploadType=multipart": http2: client connection lost
```

**To Reproduce**
Run command as shown above.

**Expected behavior**
Backup succeeds.

**Logs**
See above.

**Version**

```bash
$ ./victoria-metrics-prod --version
victoria-metrics-20220908-105553-tags-v1.81.2-0-gdd1126dcc

$ ./vmbackup-prod --version
vmbackup-20220908-105918-tags-v1.81.2-0-gdd1126dcc
```

**Comment by zekker6** [comment] 2022-10-11 08:05
Hi @muety 
This error means that there is an error in connection between host and vmbackup. Did you try running backup without customizing values of `-http.connTimeout` and `-http.idleConnTimeout`?
GCP might have their own timeouts configurations which are lower than these which would lead to connection being closed from GCS side.
Also, it might be related to unstable network connection, it would be great to check if TCP errors on host system are present.

**Comment by muety** [comment] 2022-10-11 19:57
Hi @zekker6, thanks for your reply! Yes, I only added these two parameters because of that timeout error, but they don't seem to have changed anything. 

> it would be great to check if TCP errors on host system are present

How would I find out about these?

**Comment by muety** [comment] 2022-12-15 07:07
I still keep getting these errors. Any ideas?

**Comment by muety** [comment] 2022-12-15 07:26
I don't know how much of this is already implemented by vmbackup, but options to work around that issue might be to [set a custom timeout](https://pkg.go.dev/cloud.google.com/go#hdr-Timeouts_and_Cancellation) (and add a command-line parameter for it), to [utilize resumable uploads](https://cloud.google.com/storage/docs/resumable-uploads#client-libraries) or to [implement retries](https://pkg.go.dev/cloud.google.com/go/storage#hdr-Retrying_failed_requests).

**Comment by muety** [comment] 2022-12-15 07:29
Here is a full, exemplary log of a failing backup job:

[vmbackup_error.log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10234710/vmbackup_error.log)

**Comment by zekker6** [comment] 2022-12-15 11:10
Hi @muety 
Starting from v1.82.0 we have added automatic requests retries to avoid issues similar to your case - https://docs.victoriametrics.com/CHANGELOG.html#v1820
Could you try to update to v1.82.1(don't recommend v1.82.0 as it has [the bug](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3227), which may result in incorrect query results and [relabeling](https://docs.victoriametrics.com/vmagent.html#relabeling) results) or later version and check if that helps?

**Comment by muety** [comment] 2022-12-15 11:54
Thanks. Unfortunately, the issue still persists with 1.85.0. Looks like the upload gets stuck in kind of a loop. I switched to S3 storage now.

**Comment by zekker6** [comment] 2022-12-15 12:26
@muety Could you post a log from 1.85.0 if you have it?
Any details to reproduce this issue would be much appreciated.

With the fix at 1.82.0 we have GCS running for a long time without issues, so there might be something else in your setup that we do not use. If possible, could you tell if there are any proxies. NAT or other network configurations that you use?

**Comment by muety** [comment] 2022-12-15 12:39
Actually, the backup seems to have finished fine now. But it look super long (~ 6 minutes), while backing up to S3 only took a couple of seconds.

[vmbackup_error.log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10237002/vmbackup_error.log)

**Comment by zekker6** [comment] 2022-12-15 13:13
Based on time needed to upload files it looks like connection is not very stable, and it needs to run a lot of retries before upload succeeds.
We will test working with GCS to ensure there is nothing we're missing from vmbackup side. Thanks for logs!

**Comment by zekker6** [comment] 2023-03-30 11:44
After adding #3156 we haven't received new reports of this or similar issues happening. 
Going to close this one, feel free to reopen if it will become reproducible with latest releases.

**Closed by zekker6** 2023-03-30 11:44 UTC
Labels: question, backup
