### ISSUE TITLE
vmagent doesn't follow redirects without stream_parse

### ISSUE THREAD

**Issue by vbichov** [VictoriaMetrics/VictoriaMetrics#1945] opened 2021-12-14 13:53 UTC
**Describe the bug**
vmagent doesn't follow redirects without setting stream_parse: true
for details see slack thread:
https://victoriametrics.slack.com/archives/CGZF1H6L9/p1639404018163100

**Expected behavior**
it should follow redirects in a way that is similar to prometheus

**VM agent config**
```
global:
  scrape_interval: 1m0s
scrape_configs:
- job_name: emr
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_ec2_private_ip]
    target_label: __metrics_path__
    replacement: /bi-emr-reverse-logs/$1:4040/metrics/executors/prometheus/
  - source_labels: [__meta_ec2_tag_Name]
    target_label: instance
  - target_label: __address__
    replacement: bo.XX.com
  ec2_sd_configs:
  - region: us-east-1
    access_key: XXX
    secret_key: <secret>
    filters:
    - name: tag:aws:elasticmapreduce:instance-group-role
      values:
      - MASTER
    - name: tag:Name
      values:
      - airflow-shared-persistent-emr-6.3.0
```

**Version**
tried v1.7.0 and v1.68.0 and latest docker version 
```

**Logs**
`unexpected status code returned when scraping "http://bo.XXX.com:80/bi-emr-reverse-logs/10.207.109.205:4040/metrics/executors/prometheus/": 301; expecting 200; response body: "<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body>\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>openresty/1.19.3.1</center>\r\n</body>\r\n</html>\r\n"`

**Workaround**
the issue was resolved by adding stream_parse: true

**Comment by valyala** [comment] 2021-12-15 22:18
`vmagent` was following only a single redirect up to v1.70.0 . It should follow up to 5 redirects when built from the commit a3adf24527336a233cacd5341fca42289c147413 . @vbichov , could you build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether this allows scraping targets without `stream_parse: true` mode?

Note that `vmagent` expects that redirects are performed to the original hostname when `stream_parse: true` isn't set in scrape config.

**Comment by valyala** [comment] 2021-12-20 18:23
`vmagent` should follow for up to 5 redirects starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @vbichov , could you check whether this helps resolving the issue?

**Comment by valyala** [comment] 2022-02-12 18:03
@vbichov , could you check whether the issue persists in vmagent [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by earendilfr** [comment] 2022-12-14 09:50
Hello,

For information, I still have the issue with vmagent v1.79.5...
```
2022-12-14T09:46:18.261Z        warn    VictoriaMetrics/lib/promscrape/scrapework.go:385        cannot scrape "http://xxxxxxx:80/snmp?module=icx&target=xxxxxxx" (job "Switches-foundry", labels {datacenter="XX",env="XX",instance="XX",job="Switches-foundry",monitor="prometheus04",site="XX"}): error when scraping "http://xxxxxxx:80/snmp?module=icx&target=xxxxxxx": too many redirects
2022-12-14T09:46:18.280Z        warn    VictoriaMetrics/lib/promscrape/scrapework.go:385        cannot scrape "http://xxxxxxx:80/probe?module=icmp&target=xxxxxxx" (job "Switches-ping", labels {datacenter="XX",env="XX",instance="XX",job="Switches-ping",monitor="prometheus04",site="XX"}): error when scraping "http://xxxxxxx:80/probe?module=icmp&target=xxxxxxx": too many redirects
2022-12-14T09:46:18.379Z        warn    VictoriaMetrics/lib/promscrape/scrapework.go:385        cannot scrape "http://xxxxxxx:80/probe?module=icmp&target=xxxxxxx" (job "Routers-ping", labels {datacenter="XX",env="XX",instance="XX",job="Routers-ping",monitor="prometheus04",site="XX"}): error when scraping "http://xxxxxxx:80/probe?module=icmp&target=xxxxxxx": too many redirects
```

**Comment by hagen1778** [comment] 2023-04-27 07:48
@earendilfr do you know how many redirects are there? It could be checked via browser...

**Comment by earendilfr** [comment] 2023-05-10 15:36
> @earendilfr do you know how many redirects are there? It could be checked via browser...

@hagen1778 : sorry, I have changed of jobs so hard to me to have this information but, if I remember correctly, I have only one redirect because, in this case, it's was just a redirect from http to https on the same server.

**Comment by yrka5180** [comment] 2023-06-14 09:39
> > @earendilfr do you know how many redirects are there? It could be checked via browser...
> 
> @hagen1778 : sorry, I have changed of jobs so hard to me to have this information but, if I remember correctly, I have only one redirect because, in this case, it's was just a redirect from http to https on the same server.
hi, have you solved this？ 
I am facing the same problem that it shows too many redirect while directing from http to https.

**Comment by yrka5180** [comment] 2023-06-14 09:40
> > @earendilfr do you know how many redirects are there? It could be checked via browser...
> 
> @hagen1778 : sorry, I have changed of jobs so hard to me to have this information but, if I remember correctly, I have only one redirect because, in this case, it's was just a redirect from http to https on the same server.

hi, have you solved this？
I am facing the same problem that it shows too many redirect while directing from http to https.

**Comment by hagen1778** [comment] 2023-06-14 13:05
@yrka5180 have you tried enabling/disabling stream parse?

**Comment by jnadler** [comment] 2023-08-21 17:58
we just ran into this same issue:   a single hop redirect http -> https fails with `too many redirects`

we enabled streamParse for all of vmagent via arguments, but i don't feel we should have to do this

and after enabling streamParse we see some new `skipping duplicate scrape target with identical labels` errors for some of our targets; does streamParse change how relabelling works?

**Comment by hagen1778** [comment] 2023-08-25 11:32
> we just ran into this same issue: a single hop redirect http -> https fails with too many redirects

Is it possible to compile docker-compose env where this issue can be reproduced? This would simplify debug from our side.

> and after enabling streamParse we see some new skipping duplicate scrape target with identical labels errors for some of our targets; does streamParse change how relabelling works?

Not that I'm aware of. Have you checked https://docs.victoriametrics.com/vmagent.html#troubleshooting ?

**Comment by jnadler** [comment] 2023-08-25 16:42
I just turned off streamParse and confirmed we're still facing this problem.   Here's what the redirect looks like:

![Screenshot 2023-08-25 at 9 40 09 AM](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/284279/0f7d15c8-c669-4299-831f-dffdf96c28ed)

The metrics target is cockroachDB.   I'll see if I can reproduce in docker-compose or even better, narrow down the problem in the code.

**Comment by jnadler** [comment] 2023-08-25 17:28
After reading some code, perhaps this behavior is unfortunate but expected.   https://github.com/VictoriaMetrics/VictoriaMetrics/blob/fb9b8f6b1b51d3b0aa235d8fc2a7d4ec608dea73/lib/promscrape/client.go#L291

I expect that http->https qualifies as changing the host, but `fasthttp` is reusing the existing connection to port 80, so of course this will be a redirect loop as the redirect was not followed at all.

**Comment by jnadler** [comment] 2023-08-25 17:48
I believe it will be possible to fix this case, but @valyala may not love it

If we detect this case on redirect and create new `c.hc = &fasthttp.HostClient{` with IsTLS now set appropriately, it will work thereafter.

**Comment by jnadler** [comment] 2023-08-25 20:01
Here's a PR (the code is awful!   it's just to communicate the idea) that shows it is possible to fix this behavior https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4897

**Comment by hagen1778** [comment] 2023-08-29 09:32
I believe, the issue would be fixed if we completely migrate vmagent to native HTTP lib. @zekker6 I recall you was working on that some time ago... wdyt?

**Comment by zekker6** [comment] 2023-08-29 11:06
@hagen1778 When I've been testing this native HTTP lib was consuming more memory than fasthttp, and we decided to keep it as is in order to avoid increasing resource usage during scrapes.
It seems to me like it will be better to add a logic to re-create `fasthttp.HostClient` in case of redirects as it will create much smaller memory footprint than switching to native HTTP lib.

**Comment by jnadler** [comment] 2023-08-29 17:52
Agreed, moving away from `fasthttp` would probably hurt performance in a way that might surprise users.   This change gets it a little closer to the normal behavior expected from the native client.

Note that in my example here I'm only handling http->https redirects but "different hostname" redirects could also be handled with the same approach.

If you'd like me to do any more work down this road, or clean up this code a bit, just let me know!   I factored the creation of the `fasthttp` client out of the `new` method, and could do the same for the streamparse client for consistency (not that there's any reason to recreate that one at runtime).

**Comment by ndevenish** [comment] 2023-09-29 09:08
I ran into this with federation targets. This specifically seems to be a problem because it looks like prometheus doesn't let you write `https://` in the target, but VM defaults to http and fails on the redirect.

I think this means that you can't write a completely compatible configuration that works on both (this is probably only an issue while transitioning)

**Comment by ptimofee** [comment] 2023-12-01 04:49
I can confirm that vmagent (at least v1.93.4) does NOT follow redirect until stream_parse is set to true.
We faced with this with hashicorp vault scape.

What is also being observed here even if you make vmagent follow redirects with stream_parse: true, it does not reattach bearer_token to the redirected endpoint. Creating a bug for this.

**Comment by ptimofee** [comment] 2023-12-04 19:15
I can confirm that at least vmagent v1.93.4 does follow redirects onlt when stream_parse is true, no matter if follow_redirects is set to true or false. I. e. follow_redirects has no effect at all.

**Comment by valyala** [comment] 2024-01-30 22:47
`vmagent` should properly follow redirects at scrape targets when stream parsing mode is disabled starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.

**Closed by valyala** 2024-01-30 22:47 UTC
Labels: bug, vmagent
