### ISSUE TITLE
Wildcard for reading from multi-tenancy cluster setup

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#356] opened 2020-03-03 19:38 UTC
**Is your feature request related to a problem? Please describe.**
I want to read data from all tenant

**Describe the solution you'd like**
I want to send wildcard or/and regex as a accountID

**Describe alternatives you've considered**
Separate promxy source but this is not a native way

**Comment by valyala** [comment] 2020-03-03 19:49
This feature request sounds reasonable. Needs additional time for investigation, since it can be non-trivial to implement.

**Comment by valyala** [comment] 2024-02-08 23:49
Closing this issue as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1434 , since it contains more details.

**Closed by valyala** 2024-02-08 23:49 UTC
Labels: enhancement
