### ISSUE TITLE
vmagent scrape bug!

### ISSUE THREAD

**Issue by mmkkoo** [VictoriaMetrics/VictoriaMetrics#2105] opened 2022-01-26 07:42 UTC
I found that there were occasional continuous burial points：
scrape_interval:15s
Look at the picture below，the timestamp is every 15s，by when 2022-01-26 15:03:36，next timestamp is 2022-01-26 15:03:37，again next timestamp is 2022-01-26 15:03:51，the interval is 15 second！What has caused this phenomenon? 
![image](https://user-images.githubusercontent.com/42405491/151121954-fa0916cc-605f-427b-8bcd-4477030dfcc1.png)

**Comment by zlfloatice** [comment] 2022-01-26 08:55
which version
and how to reproduce?

**Comment by mmkkoo** [comment] 2022-01-26 09:01
Version is 1.72， this problem also exists 1.71
I don't know how to reproduce，Because this is collected by vmagent

**Comment by denisgolius** [comment] 2022-01-26 09:04
> Version is 1.72， this problem also exists 1.71 I don't know how to reproduce，Because this is collected by vmagent

Hi @mmkkoo !
Could you share scrape config for vmagent ? Because it looks like you have duplicated targets in it.

**Comment by mmkkoo** [comment] 2022-01-26 09:09
![image](https://user-images.githubusercontent.com/42405491/151134548-a229b8a0-a783-433e-8b9a-927c88fdfe83.png)
![image](https://user-images.githubusercontent.com/42405491/151134705-3542be61-8be6-46c8-b098-83c8f4dd6a64.png)

**Comment by mmkkoo** [comment] 2022-01-26 09:17
Can we exclude such discontinuous data；For example, our collection time is 15s，when the difference between two timestamps is not equal to 15s，Can we discard it？
This problem currently leads to inaccurate irate data，In fact, the growth has not increased sharply，But because of continuous points, the data increases sharply：
![image](https://user-images.githubusercontent.com/42405491/151135651-a882ee57-439b-409d-ac19-858cc958b79a.png)

**Comment by mmkkoo** [comment] 2022-01-26 09:26
#2022

**Comment by f41gh7** [comment] 2022-01-26 11:29
Probably, it's related with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1807#issuecomment-984523424

**Comment by mmkkoo** [comment] 2022-01-27 01:53
@f41gh7 I think this is the difference of the original data, and there is no data loss, which needs to be supplemented！From the phenomenon, there will be more than one second of timestamp data

**Comment by jiangxinlingdu** [comment] 2022-01-27 05:15
add args: -dedup.minMetricPointInterval to solve vmagent more pointdata let irate jump too much

https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2106

**Comment by mmkkoo** [comment] 2022-01-27 08:13
I don't understand，i have two cluster,belong to different vpc,but the data collected is the same，I found that if bzone has a spike in data rise, azone will have a spike in data decline，And the rising data minus the falling data is just equal to the daily data：
![image](https://user-images.githubusercontent.com/42405491/151317522-6f78d686-3c4b-4f47-bacb-f71264c1e23a.png)

**Comment by mmkkoo** [comment] 2022-01-27 09:12
i find,when i restart vmagent,The problem disappears

**Comment by valyala** [comment] 2024-02-13 22:27
Closing the issue as resolved.

**Closed by valyala** 2024-02-13 22:27 UTC
Labels: need more info, vmagent
