### ISSUE TITLE
v1.29.0 panic: FATAL: couldn't remove NFS directory

### ISSUE THREAD

**Issue by BenB196** [VictoriaMetrics/VictoriaMetrics#234] opened 2019-11-12 13:53 UTC
**Describe the bug**
When upgrading to v1.29.0 the following error will occur after a few minutes of being alive:

```
panic: FATAL: couldn't remove NFS directory "/victoria-metrics-data/indexdb/15C4FBD19C592B29/28_1_15D408006D8CDBD1" in 1m0s

goroutine 15 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xafefbd, 0x5, 0xc00095bf80, 0x74, 0x3)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:124 +0x586
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(0xafefbd, 0x5, 0xb1a98b, 0x2d, 0xc00ab03828, 0x2, 0x2)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:78 +0x112
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:62
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustRemoveAll(0xc00033f200, 0x45)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/fs/fs.go:275 +0x1c6
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.runTransaction(0xc0003dc880, 0xc000966180, 0x2f, 0xc00ab8ea50, 0x44, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table.go:1129 +0x2f2
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc0003dc7e0, 0xc00aaf4000, 0x2, 0x2, 0xc000028d20, 0xc00aaf4000, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table.go:812 +0xe50
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeExistingParts(0xc0003dc7e0, 0x3b9aca01, 0x0, 0x1)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table.go:657 +0xeb
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).partMerger(0xc0003dc7e0, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table.go:671 +0x90
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers.func1(0xc0003dc7e0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table.go:639 +0x2f
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/mergeset/table.go:638 +0x68
```

**To Reproduce**
1. Start a single VM instance using v1.28.3 in docker and mount the storage directory with NFS.
1. Upgrade to v1.29.0
1. Wait a few minutes, VM will start normally and work for a short period of time.
1. After waiting, the panic will occur

**Expected behavior**
This panic should not occur, and the system should work as intended.

**Version**
v1.29.0, single node.

**Additional context**
Note: Downgrading back to v1.28.3, the issue does not occur

Complete startup log with panic:

```
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:11  build version: victoria-metrics-20191112-002907-tags-v1.29.0-0-gb4f44bef
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:12  command line flags
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "bigMergeConcurrency" = "0"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "deleteAuthKey" = "secret"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "graphiteListenAddr" = ""
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "http.disableResponseCompression" = "false"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "httpAuth.password" = "secret"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "httpAuth.username" = "vicMetrics"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "httpListenAddr" = ":8428"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "influxMeasurementFieldSeparator" = "_"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "influxSkipSingleField" = "false"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "loggerLevel" = "INFO"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "maxConcurrentInserts" = "16"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "maxInsertRequestSize" = "33554432"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "maxLabelsPerTimeseries" = "30"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "memory.allowedPercent" = "60"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "metricsAuthKey" = "secret"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "opentsdbHTTPListenAddr" = ""
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "opentsdbListenAddr" = ""
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "pprofAuthKey" = "secret"
2019-11-12T13:38:09.665+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "precisionBits" = "64"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "retentionPeriod" = "16"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.disableCache" = "false"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.latencyOffset" = "1m0s"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.logSlowQueryDuration" = "5s"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxConcurrentRequests" = "8"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxLookback" = "0s"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxPointsPerTimeseries" = "30000"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxQueryDuration" = "30s"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxQueryLen" = "16384"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxQueueDuration" = "10s"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxTagKeys" = "secret"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxTagValues" = "100000"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "search.maxUniqueTimeseries" = "300000"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "smallMergeConcurrency" = "0"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "snapshotAuthKey" = "secret"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "storageDataPath" = "victoria-metrics-data"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "tls" = "false"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "tlsCertFile" = ""
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "tlsKeyFile" = "secret"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/lib/logger/flag.go:20  flag "version" = "false"
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/app/victoria-metrics/main.go:23        starting VictoraMetrics at ":8428"...
2019-11-12T13:38:09.666+0000    info    VictoriaMetrics@/app/vmstorage/main.go:49       opening storage at "victoria-metrics-data" with retention period 16 months
2019-11-12T13:38:09.677+0000    info    VictoriaMetrics@/lib/memory/memory.go:33        limiting caches to 10082242560 bytes, leaving 6721495040 bytes to the OS according to -memory.allowedPercent=60
2019-11-12T13:38:09.677+0000    info    VictoriaMetrics@/lib/storage/storage.go:581     loading MetricName->TSID cache from "/victoria-metrics-data/cache/metricName_tsid"...
2019-11-12T13:38:09.867+0000    info    VictoriaMetrics@/lib/storage/storage.go:586     loaded MetricName->TSID cache from "/victoria-metrics-data/cache/metricName_tsid" in 189.516764ms; entriesCount: 190657; sizeBytes: 34340864
2019-11-12T13:38:09.867+0000    info    VictoriaMetrics@/lib/storage/storage.go:581     loading MetricID->TSID cache from "/victoria-metrics-data/cache/metricID_tsid"...
2019-11-12T13:38:09.873+0000    info    VictoriaMetrics@/lib/storage/storage.go:586     loaded MetricID->TSID cache from "/victoria-metrics-data/cache/metricID_tsid" in 6.163486ms; entriesCount: 0; sizeBytes: 0
2019-11-12T13:38:09.873+0000    info    VictoriaMetrics@/lib/storage/storage.go:581     loading MetricID->MetricName cache from "/victoria-metrics-data/cache/metricID_metricName"...
2019-11-12T13:38:09.884+0000    info    VictoriaMetrics@/lib/storage/storage.go:586     loaded MetricID->MetricName cache from "/victoria-metrics-data/cache/metricID_metricName" in 10.774808ms; entriesCount: 0; sizeBytes: 0
2019-11-12T13:38:09.884+0000    info    VictoriaMetrics@/lib/storage/storage.go:499     loading curr_hour_metric_ids from "/victoria-metrics-data/cache/curr_hour_metric_ids"...
2019-11-12T13:38:09.943+0000    info    VictoriaMetrics@/lib/storage/storage.go:525     discarding curr_hour_metric_ids, since it contains outdated hour; got 436914; want 437101
2019-11-12T13:38:09.943+0000    info    VictoriaMetrics@/lib/storage/storage.go:499     loading prev_hour_metric_ids from "/victoria-metrics-data/cache/prev_hour_metric_ids"...
2019-11-12T13:38:09.997+0000    info    VictoriaMetrics@/lib/storage/storage.go:525     discarding prev_hour_metric_ids, since it contains outdated hour; got 436913; want 437100
2019-11-12T13:38:10.000+0000    info    VictoriaMetrics@/lib/mergeset/table.go:156      opening table "/victoria-metrics-data/indexdb/15C4FBD19C592B29"...
2019-11-12T13:38:10.029+0000    info    VictoriaMetrics@/lib/mergeset/table.go:190      table "/victoria-metrics-data/indexdb/15C4FBD19C592B29" has been opened in 28.814494ms; partsCount: 5; blocksCount: 3039, itemsCount: 4575169; sizeBytes: 10136286
2019-11-12T13:38:10.043+0000    info    VictoriaMetrics@/lib/mergeset/table.go:156      opening table "/victoria-metrics-data/indexdb/15C4FBD19C592B28"...
2019-11-12T13:38:10.049+0000    info    VictoriaMetrics@/lib/mergeset/table.go:190      table "/victoria-metrics-data/indexdb/15C4FBD19C592B28" has been opened in 6.350603ms; partsCount: 0; blocksCount: 0, itemsCount: 0; sizeBytes: 0
2019-11-12T13:38:10.069+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/425947983_86470_20191030091330.000_20191031123356.009_15D27112F8FC6465" in 2.940525ms
2019-11-12T13:38:10.072+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/1475248_73292_20191031235430.000_20191031235849.338_15D27112F8FC830C" in 3.780401ms
2019-11-12T13:38:10.076+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/319895_73292_20191031235840.000_20191031235943.372_15D27112F8FC8316" in 3.126026ms
2019-11-12T13:38:10.079+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/3_3_20191031235950.000_20191031235950.000_15D27112F8FC831B" in 2.974621ms
2019-11-12T13:38:10.082+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/101254_68672_20191031235930.000_20191031235959.997_15D27112F8FC831A" in 3.035052ms
2019-11-12T13:38:10.085+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/3059743_73292_20191031234600.000_20191031235441.662_15D27112F8FC82DD" in 3.405185ms
2019-11-12T13:38:10.089+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_10/202108653_73864_20191031123340.000_20191031234608.959_15D4080072D80C26" in 3.50261ms
2019-11-12T13:38:10.099+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/big/2019_10/9640022431_1212076_20191001000000.000_20191030091345.944_15D4080072D80C25" in 4.471708ms
2019-11-12T13:38:10.108+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_09/50043356_34663_20190930175800.000_20190930215935.085_15C5FE3F8F3E9E49" in 2.966685ms
2019-11-12T13:38:10.112+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_09/24663242_34668_20190930215920.000_20190930235833.214_15C5FE3F8F3EA384" in 3.695624ms
2019-11-12T13:38:10.115+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_09/309037_34663_20190930235820.000_20190930235959.715_15D408007BC01138" in 2.857174ms
2019-11-12T13:38:10.119+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_09/300936339_57694_20190929125840.000_20190930175813.421_15C5FE3F8F3E93B1" in 3.46286ms
2019-11-12T13:38:10.127+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/big/2019_09/1699615727_247215_20190920003309.541_20190926181444.170_15C5FE3F8F3DA027" in 3.4052ms
2019-11-12T13:38:10.195+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/big/2019_09/798317305_104287_20190926181430.000_20190929125855.413_15C5FE3F8F3E4BB6" in 67.492579ms
2019-11-12T13:38:10.204+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/19719_19667_20191112133732.153_20191112133744.345_15D4080082E164FB" in 2.986126ms
2019-11-12T13:38:10.207+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/75614_75518_20191112133740.000_20191112133800.506_15D4080082E164FD" in 2.960744ms
2019-11-12T13:38:10.210+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/19308_19270_20191112133744.544_20191112133755.781_15D4080082E164FE" in 2.752394ms
2019-11-12T13:38:10.213+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/65104_60687_20191112133730.000_20191112133752.075_15D4080082E164FC" in 2.955448ms
2019-11-12T13:38:10.216+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/40614510_204259_20191112114940.000_20191112124258.736_15D4080082E161FD" in 3.072637ms
2019-11-12T13:38:10.219+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/1141360_184856_20191112133506.171_20191112133746.011_15D4080082E164FA" in 2.994126ms
2019-11-12T13:38:10.223+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/1839148_204224_20191112132923.330_20191112133205.759_15D4080082E164B1" in 3.067432ms
2019-11-12T13:38:10.226+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/1648694_201652_20191112133150.000_20191112133545.104_15D4080082E164E2" in 3.018755ms
2019-11-12T13:38:10.229+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/620834_191384_20191112133310.000_20191112133442.561_15D4080082E164D3" in 3.24293ms
2019-11-12T13:38:10.232+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/small/2019_11/36799935_204273_20191112124110.000_20191112132937.791_15D4080082E164C0" in 2.909154ms
2019-11-12T13:38:10.240+0000    info    VictoriaMetrics@/lib/storage/partition.go:1306  opened part "/victoria-metrics-data/data/big/2019_11/10388212393_1436576_20191101000000.000_20191112115047.646_15D4080082E15F7F" in 3.663411ms
2019-11-12T13:38:10.242+0000    info    VictoriaMetrics@/app/vmstorage/main.go:65       successfully opened storage "victoria-metrics-data" in 576.364726ms; partsCount: 25; blocksCount: 4976517; rowsCount: 23617976835; sizeBytes: 8908911077
2019-11-12T13:38:10.248+0000    info    VictoriaMetrics@/app/vmselect/promql/rollup_result_cache.go:50  loading rollupResult cache from "victoria-metrics-data/cache/rollupResult"...
2019-11-12T13:38:10.259+0000    info    VictoriaMetrics@/app/vmselect/promql/rollup_result_cache.go:76  loaded rollupResult cache from "victoria-metrics-data/cache/rollupResult" in 11.226627ms; entriesCount: 0, sizeBytes: 0
2019-11-12T13:38:10.260+0000    info    VictoriaMetrics@/app/victoria-metrics/main.go:30        started VictoriaMetrics in 593.906593ms
2019-11-12T13:38:10.260+0000    info    VictoriaMetrics@/lib/httpserver/httpserver.go:63        starting http server at http://:8428/
2019-11-12T13:38:10.260+0000    info    VictoriaMetrics@/lib/httpserver/httpserver.go:64        pprof handlers are exposed at http://:8428/debug/pprof/
2019-11-12T13:39:10.952+0000    panic   VictoriaMetrics@/lib/fs/fs.go:275       FATAL: couldn't remove NFS directory "/victoria-metrics-data/data/small/2019_11/19308_19270_20191112133744.544_20191112133755.781_15D4080082E164FE" in 1m0s
panic: FATAL: couldn't remove NFS directory "/victoria-metrics-data/data/small/2019_11/19308_19270_20191112133744.544_20191112133755.781_15D4080082E164FE" in 1m0s

goroutine 95 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage(0xafefbd, 0x5, 0xc0088180a0, 0x9b, 0x3)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:124 +0x586
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(0xafefbd, 0x5, 0xb1a98b, 0x2d, 0xc000c0b7e8, 0x2, 0x2)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:78 +0x112
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/logger/logger.go:62
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustRemoveAll(0xc00497e000, 0x6c)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/fs/fs.go:275 +0x1c6
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.runTransaction(0xc00015a688, 0xc0008ca5d0, 0x29, 0xc0008ca600, 0x27, 0xc000130ac0, 0x3e, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:1460 +0x300
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc00015a580, 0xc000054000, 0x2, 0x2, 0xc000028300, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:1062 +0xc5d
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeSmallParts(0xc00015a580, 0x5dcab501, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:949 +0x1c9
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).partsMerger(0xc00015a580, 0xc000c0bf78, 0x0, 0xc00003b7a8)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:817 +0x8c
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).smallPartsMerger(0xc00015a580)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:801 +0x55
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1(0xc00015a580)
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:781 +0x2b
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
        github.com/VictoriaMetrics/VictoriaMetrics@/lib/storage/partition.go:780 +0x6c
```

**Comment by valyala** [comment] 2019-11-12 14:15
It looks like the fix 4c02e496f7ebc3ff36eca6d53a7856705806cc60 doesn't work as intended on NFS. Needs further investigation.

**Comment by valyala** [comment] 2019-11-12 14:44
The commit has been reverted in [v1.29.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release.

**Comment by BenB196** [comment] 2019-11-12 19:38
Thanks for the quick fix. I have updated to the new version and the panic no longer happens.

**Comment by valyala** [comment] 2019-11-12 19:48
Then closing the issue.

Actually there are reports that the https://github.com/VictoriaMetrics/VictoriaMetrics/issues/162 isn't fixed it. The reverted commit was an unsuccessful attempt to fix it :(

**Closed by valyala** 2019-11-12 19:48 UTC
Labels: bug
