### ISSUE TITLE
quantile calculated from stream aggr is inconsistent with raw sample

### ISSUE THREAD

**Issue by HHHHHQL** [VictoriaMetrics/VictoriaMetrics#5545] opened 2023-12-28 14:44 UTC
### Is your question request related to a specific component?

 single-vm

### Describe the question in detail

 The <transaction_timer_seconds_bucket> metric scraped by prometheus was ingested to single-vm through remote write. For the purpose of improving the performance of query, we aggregated <transaction_timer_seconds_bucket>. 
However, the quantile calculated by histogram_quantile based on aggregated  metrics is very different from the quantile based on  raw metrics with the number of instance increasing, especially when the phi>0.99.  
<img width="1453" alt="截屏2023-12-28 21 50 13" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/41057617/e743e97d-83bc-4a0f-a1f7-ccc8ef37ee39">
Besides, another weird thing confused me: the result of a query at a specific timestamp could be slightly different even though it's dramatically different at same timestamp in vmui graph. For example, query at 2023-12-28 15:30:00:
<img width="1464" alt="截屏2023-12-28 21 53 47" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/41057617/574b59ab-501c-4963-a6ca-7877113bf273">
here is aggr-config:
- match: '{__name__=~"transaction_timer_seconds_bucket"}'
  interval: 1m
  without: [instance, hostName, prometheus_replica]
  outputs: [total]
  output_relabel_configs:
  - action: replace_all
    source_labels: ["__name__"]
    target_label: "__name__"
    regex: ":1m_.+"
    replacement: ":1m_cluster"
Is there any solution for this problem? Or do I have misconception about histogram_quantile?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment] 2024-06-19 09:00
duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4580

**Closed by hagen1778** 2024-06-19 09:00 UTC
Labels: question, vmagent, streamaggr
