### ISSUE TITLE
cannot perform vminsert handshake with client

### ISSUE THREAD

**Issue by yzhengwei** [VictoriaMetrics/VictoriaMetrics#1762] opened 2021-10-28 18:31 UTC
I'm running VictoriaMetrics cluster v1.68.0-cluster. but in every vmstorage, I found the error message like this, what mean of this？ 

 ```
2021-10-28T18:29:16.784Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:97	accepted vminsert conn from 10.22.1.193:60988
2021-10-28T18:29:16.784Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:122	cannot perform vminsert handshake with client "10.22.1.193:60988": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
2021-10-28T18:29:26.785Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:97	accepted vminsert conn from 10.22.1.193:61486
2021-10-28T18:29:26.785Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:122	cannot perform vminsert handshake with client "10.22.1.193:61486": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
2021-10-28T18:29:36.782Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:97	accepted vminsert conn from 10.22.1.193:62218
2021-10-28T18:29:36.783Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:122	cannot perform vminsert handshake with client "10.22.1.193:62218": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
2021-10-28T18:29:46.784Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:97	accepted vminsert conn from 10.22.1.193:62874
2021-10-28T18:29:46.784Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:122	cannot perform vminsert handshake with client "10.22.1.193:62874": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
2021-10-28T18:29:56.784Z	info	VictoriaMetrics/app/vmstorage/transport/server.go:97	accepted vminsert conn from 10.22.1.193:63426
2021-10-28T18:29:56.784Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:122	cannot perform vminsert handshake with client "10.22.1.193:63426": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
```

**Comment by valyala** [comment] 2021-11-02 08:09
This usually means that something other than `vminsert` is trying to connect to `vmstorage` at 8400 tcp port. `vmstorage` expects the `hello` message from `vminsert` according to the handshake protocol between `vminsert` and `vmstorage`, but the remote side doesn't send the message and just closes the established connection. This leads to `cannot read hello: cannot read message with size 11: EOF` error message in `vmstorage` logs.

The solution is to identify the app, which mistakenly tries to connect to `vmstorage:8400`, and to configure it properly.

**Comment by FRosner** [comment] 2022-08-10 08:03
I have the same issue, and the pod that is trying to connect (`172.31.171.88`) is vmagent.

```
2022-08-10T07:58:46.781Z    info    VictoriaMetrics/app/vmstorage/servers/vminsert.go:76    accepted vminsert conn from 172.31.171.88:33498
2022-08-10T07:58:46.781Z    error    VictoriaMetrics/app/vmstorage/servers/vminsert.go:101    cannot perform vminsert handshake with client "172.31.171.88:33498": cannot read hello: unexpected message obtained; got "GET /metric"; want "vminsert.02"
```

However, I did not configure vmagent to talk to vmstorage? I mean it scrapes it, but scraping appears to work fine, the dashboards are populated. The remote write URL points to vminsert: `http://vminsert-victoria-metrics-cluster.monitor.svc:8480/insert/0/prometheus/api/v1/write`.

This only happens after I upgrade VictoriaMetrics from 1.61.1 to 1.79.1 though. I'm deploying it using the k8s operator.

**Comment by FRosner** [comment] 2022-08-10 08:32
I did some more investigation and it appears that for some reason the existing scrape configuration broke and the new vmagent version started scraping all pods on all exposed ports. I will need to look into that. Did anything change with respect to vmagent scrape config / target detection?

**Comment by FRosner** [comment] 2022-08-10 09:00
I did some more digging and it seems that our existing pod scrape definition doesn't get rendered correctly.

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  annotations:
    meta.helm.sh/release-name: victoria-metrics-resources
    meta.helm.sh/release-namespace: monitor
  creationTimestamp: "2022-08-10T08:55:35Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: pod-scraper
  namespace: monitor
  resourceVersion: "16940122517"
  uid: a3da33b3-6f58-4533-93a4-ec7416d4f465
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - scrapeTimeout: 15s
  - relabelConfigs:
    - action: keep
      regex: "true"
      sourceLabels:
      - __meta_kubernetes_pod_annotation_prometheus_io_scrape
    - action: replace
      regex: (.+)
      sourceLabels:
      - __meta_kubernetes_pod_annotation_prometheus_io_path
      targetLabel: __metrics_path__
    - action: replace
      regex: (.+)
      sourceLabels:
      - __meta_kubernetes_pod_annotation_cloud_account
      targetLabel: cloud_account
    - action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: ${1}:${2}
      sourceLabels:
      - __address__
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      targetLabel: __address__
    - action: keep_if_equal
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      - __meta_kubernetes_pod_container_port_number
    - action: drop
      regex: "true"
      source_labels:
      - __meta_kubernetes_pod_container_init
    - action: drop
      regex: Pending|Succeeded|Failed
      source_labels:
      - __meta_kubernetes_pod_phase
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_namespace
      targetLabel: kubernetes_namespace
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: kubernetes_pod_name
  selector:
    matchExpressions:
    - key: prometheus.io/do-not-scrape
      operator: DoesNotExist
```

In version 1.61.1 this would get translated to 

```
- job_name: podScrape/monitor/pod-scraper/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_label_prometheus_io_do_not_scrape
    regex: .+
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: monitor/pod-scraper
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
    regex: "true"
    action: keep
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_path
    target_label: __metrics_path__
    regex: (.+)
    action: replace
  - source_labels:
    - __meta_kubernetes_pod_annotation_cloud_account
    target_label: cloud_account
    regex: (.+)
    action: replace
  - source_labels:
    - __address__
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    target_label: __address__
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: ${1}:${2}
    action: replace
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    - __meta_kubernetes_pod_container_port_number
    action: keep_if_equal
  - source_labels:
    - __meta_kubernetes_pod_container_init
    regex: "true"
    action: drop
  - source_labels:
    - __meta_kubernetes_pod_phase
    regex: Pending|Succeeded|Failed
    action: drop
  - regex: __meta_kubernetes_pod_label_(.+)
    action: labelmap
  - source_labels:
    - __meta_kubernetes_pod_namespace
    target_label: kubernetes_namespace
    action: replace
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: kubernetes_pod_name
    action: replace
```

Now with 1.79.1 it creates an additional scrape job which has almost no logic:

```
- job_name: podScrape/monitor/pod-scraper/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
  scrape_timeout: 15s
  relabel_configs:
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_label_prometheus_io_do_not_scrape
    regex: .+
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: monitor/pod-scraper
```

The correct one still exists as `podScrape/monitor/pod-scraper/1` though, which is even weirder.

**Comment by FRosner** [comment] 2022-08-10 09:46
Ok sorry I'm stupid. I added the scrape timeout in the wrong place:

```
  podMetricsEndpoints:
  - scrapeTimeout: 15s
  - relabelConfigs:
```

Please ignore all my above comments :)

**Comment by luhhujbb** [comment] 2022-08-29 10:07
Hello,
My VictoriaMetrics cluster services are monitored by consul agent which handle tcp check/discovery/conf generation.
If I add a vmstorage node, my vminsert nodes and vmselect nodes configuration are updated automatically thanks to consul discovery and template system, pretty cool.
So I received a lots of these logs which, in my case, can be considered as pollution, as by design a tcp check will try to connect to opened port to check its aliveness.
I'm just wondering how can it be handle in a clean way to avoid these logs.
Many thanks !

**Comment by valyala** [comment] 2023-05-18 22:59
@luhhujbb , `vmstorage` shouldn't pollute logs with `cannot read hello` errors messages when TCP health check is performed on communication ports for `vminsert` and `vmselect` components, starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.

**Closed by valyala** 2023-05-18 22:59 UTC
Labels: enhancement, question

**Comment by jsanant** [comment] 2023-10-12 14:33
@valyala - We are also facing this issue after we upgraded from `v1.85.3-cluster` to `v1.89.1-cluster`. And this is happening only in one environment. 

```
{"ts":"2023-10-11T12:36:59.234Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.0.0.1:35554"}

{"ts":"2023-10-11T12:36:59.235Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:101","msg":"cannot perform vminsert handshake with client \"10.0.0.1:35554\": cannot read hello: unexpected message obtained; got \"\\x16\\x03\\x01\\x01+\\x01\\x00\\x01'\\x03\\x03\"; want \"vminsert.02\""}
```

We have verified everywhere and nothing is trying to communicate with vmstorage on port `8400` or `8401`, part from vminsert and vmselect.

Version:
```
vminsert-20230313-022830-tags-v1.89.1-cluster-0-g47c5b77c8
vmselect-20230313-022919-tags-v1.89.1-cluster-0-g47c5b77c8
vmstorage-20230313-023014-tags-v1.89.1-cluster-0-g47c5b77c8
```

**Comment by makasim** [comment] 2025-04-24 10:58
@valyala  Some additional cases have been reported

Timeouts during the initial read phase:
```
2025-04-09T07:08:59.323Z	error	VictoriaMetrics/lib/vmselectapi/server.go:204	cannot perform vmselect handshake with client "<REDACTED>": cannot read hello: cannot read message with size 11: read tcp4 <REDACTED>-><REDACTED>: i/o timeout; read only 0 bytes
```

EOFs occurring later in the handshake process:
```
2025-04-08T18:01:30.783Z	error	VictoriaMetrics/lib/vmselectapi/server.go:204	cannot perform vmselect handshake with client "<REDACTED>": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes
```

Since these are client-side issues (e.g., dropped connections or timeouts), there's nothing actionable we can do on the server side. It would make sense to ignore these cases as well, similar to how we treat EOF during TCP handshake.

cc @hagen1778
