### ISSUE TITLE
Multiple retention policies in a single instance/cluster

### ISSUE THREAD

**Issue by czert** [VictoriaMetrics/VictoriaMetrics#143] opened 2019-08-06 12:56 UTC
If I'm not mistaken, a single VM instance or cluster only supports a single retention setting. When I need more retention policies, I have to run multiple instances or clusters. Are there any plans to support more than one retention in an instance/cluster? Is it feasible, or is it unlikely to ever happen?

**Comment by tenmozes** [comment] 2019-08-06 13:02
hello @czert, yes you're right there is no option to configure multiple retention periods, could you please share your case?

**Comment by czert** [comment] 2019-08-06 13:28
We plan to do downsampling and aggregation in influxdb (in addition to prometheus recording rules). The we'll use VM to expose these aggregated metrics to grafana. We'll have 5-minute, 2-hour and 1-day downsampled series, and each will require their own retention policies to save costs.

I can run an instance for every retention, but it is a bit of a hassle, especially once we try to move to the cluster version of VM. If there are plans to support multiple retentions in a cluster, I could put off moving to the cluster version until this is supported.

**Comment by tenmozes** [comment] 2019-08-06 14:26
thank you for the case, we will think about the solution.
i can not give you 100% sure that feature will be implemented, i will return to you when get the exact details

**Comment by valyala** [comment] 2019-08-06 14:38
While the feature sounds interesting, it can be hard to implement since VictoriaMetrics storage was designed with single retention policy :(

A workaround is to [start multiple VictoriaMetrics instances (or clusters) for distinct retentions](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#multiple-retentions).

Let's keep this feature request open for a while.

**Comment by czert** [comment] 2019-08-07 11:44
Okay, thanks, I kinda expected that. Feel free to close this feature request if you think this unlikely to ever get implemented.

**Comment by CH-JosephBironas** [comment] 2019-08-09 15:46
I think it would be a useful feature, even if there's a way to write to multiple storage back ends with multiple retention policies. I'm already on cluster, so spinning up more pods/disks is not a problem. The user story for me is, as an SRE I would like to be able to retain and query 1+ year of stats efficiently on a cloud provider (ie, I don't have to have 3 replicas of 2+TB (aka "expensive") disks). I've already decided that for those 12+ month calculations, that downsampling is OK.

**Comment by valyala** [comment] 2020-06-19 13:19
Note that [vmauth](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmauth/README.md) may be used for routing requests from particular tenants (users) to VictoriaMetrics instance or cluster with the desired retention.

**Comment by ahmadalli** [comment] 2020-10-27 10:39
I think https://github.com/VictoriaMetrics/VictoriaMetrics/issues/36 will cover this

**Comment by valyala** [comment] 2021-02-11 11:04
It is possible to have multiple retention policies in a single cluster by using the following schema:
- To run multiple sets of `vmstorage` nodes with distinct `-retentionPeriod` command-line flag values. For example, `vmstorage1` and `vmstorage2` has `-retentionPeriod=1y`, while `vmstorage3` has `-retentionPeriod=30d`.
- To run multiple sets of `vminsert` nodes, where each set is configured to write data only to a specific set of `vmstorage` nodes with the given retention. For example, `vminsert1` is configured with `-storageNode=vmstorage1,vmstorage2`, i.e. it is used for writing data with one year retention, while `vminsert2` is configured with `-storageNode=vmstorage3`, i.e. it is used for writing data with 30 days retention.
- To run `vmselect` with `-storageNode=vmstorage1,vmstorage2,vmstorage3`, i.e. it queries all the data with multiple retentions.
- To route incoming data to a particular set of `vminsert` nodes depending on the desired retention. This routing can be built with [vmagent](https://victoriametrics.github.io/vmagent.html) by specifying multiple `-remoteWrite.url` destinations with the specific [relabeling rules](https://victoriametrics.github.io/vmagent.html#relabeling) passed via `-remoteWrite.urlRelabelConfig`.

See the schema below:
```
                                           /-> vmstorage1 <---\
          /-> vminsert-with-1y-retention ->                   |
          |                                \-> vmstorage2 <---|
vmagent ->                                                     <- vmselect
          |                                                   |
          \-> vminsert-with-30d-retention ---> vmstorage3 <---/
```

**Comment by czert** [comment] 2021-02-11 13:41
Thats good news, @valyala! Is it safe to run multiple vmstorages on one host?

**Comment by valyala** [comment] 2021-02-15 09:44
> Is it safe to run multiple vmstorages on one host?

It is safe provided those `vmstorage` nodes listen for different TCP ports and store data in different directories on the host.

**Comment by gnnx0425** [comment] 2021-11-22 03:53
Is there a way to set multiple retention policies for vmstorage in Helm chart deployment file?

**Comment by valyala** [comment] 2022-10-24 14:01
FYI, the next release of [VictoriaMetrics enterprise](https://victoriametrics.com/products/enterprise/) will support multiple retentions for distinct sets of time series and/or tenants - see [these](https://docs.victoriametrics.com/#retention-filters) and [these](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#retention-filters) docs for details. See also [the changelog](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment] 2022-10-29 01:45
VictoriaMetrics supports multiple retention policies for distinct sets of time series / tenants starting from [v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/#retention-filters) for details. Closing the feature request as done.

**Closed by valyala** 2022-10-29 01:45 UTC
Labels: enhancement, enterprise
