### ISSUE TITLE
Missing data in prometheus query_range being returned as NaNs

### ISSUE THREAD

**Issue by jacksontj** [VictoriaMetrics/VictoriaMetrics#153] opened 2019-08-20 04:50 UTC
**Describe the bug**
If a query_range is sent that spans time with missing data VM returns NaN as the value instead of omitting the timestamp. For example if you have time ranges t1, t2, and t3 -- lets say that t1 and t3 have values and t2 does not. If a query_range is sent to prometheus which covers t1 through t3 the values in the response will have a gap in the values for the range of t2 (they are missing entirely). For VictoriaMetrics this same query returns NaNs for all of t2.

**Additional context**
This was originally reported as a bug to promxy -- https://github.com/jacksontj/promxy/issues/203 has some more context.

**Comment by valyala** [comment] 2019-08-20 09:54
Interesting. VictoriaMetrics always was returning NaNs for missing data in `query_range` responses, since it looked like Prometheus did the same when I last checked (a year ago). Will verify again and fix it.

**Comment by valyala** [comment] 2019-08-20 20:15
The issue must be fixed at 7b5168adfb2a304f0f450e4b7f3bac98bd6f7093 . The bugfix will be available in the next release.

**Comment by valyala** [comment] 2019-08-22 12:03
@jacksontj , could you verify whether the issue is fixed in [v1.26.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by jacksontj** [comment] 2019-08-22 14:16
I put it in my same test setup and I can confirm that it is working now,
thanks!

**Comment by valyala** [comment] 2019-08-22 15:26
Thanks for the confirmation! Then closing the issue.

**Closed by valyala** 2019-08-22 15:26 UTC
Labels: bug
