### ISSUE TITLE
VictoriaMetrics about increase function

### ISSUE THREAD

**Issue by jiangxinlingdu** [VictoriaMetrics/VictoriaMetrics#1962] opened 2021-12-18 05:03 UTC
when using Prometheus before, a new metric is added, we find that the increase function will get the result of 0 when the increase function has no value before. 

However, when we use the increase function of victoriametrics, the return value is not 0
like this:
![image](https://user-images.githubusercontent.com/6373972/146722635-f1ffed42-978a-4503-874d-732e9308f0e2.png)

Prometheus increase：
![image](https://user-images.githubusercontent.com/6373972/146722719-54eb3029-25af-4def-a4c8-eb53ebfe6096.png)

but sometimes i expect VictoriaMetrics increase function no value before can get the result of 0, expect the same as Prometheus increase ,what can i do?

**Comment by jiangxinlingdu** [comment] 2021-12-20 06:46
some alarms are based on increase, when metric did not exist before. After adding metric, and metric value not change ，we expect the increase function will get the result of 0, which can avoid unnecessary alarms

**Comment by spjich** [comment] 2021-12-20 06:47
I have the same promble. There are a lot of alarms when a business system restarting because of the  increase function

**Comment by valyala** [comment] 2021-12-20 10:22
The related pull request - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1972

**Comment by valyala** [comment] 2021-12-20 11:29
VictoriaMetrics takes into account the previous sample in the time series before the given lookbehind window `d` when calculating `changes(m[d])`, `increase(m[d])` and `delta(m[d])`. If the previous sample is missing, then it assumes that the time series starts from 0. Prometheus doesn't take into account the previous sample before the given lookbehind window `d` when calculating these functions. This is unexpected behavior for most users, since this means that Prometheus skips time series changes between the last sample before the lookbehind window `d` and the first sample inside the lookbehind widnow. See [this article](https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e) for details.

The commit 177e345d8a7db0ee8520b9d6f74bf8ccdd08ad40 adds `changes_prometheus(m[d])`, `delta_prometheus(m[d])` and `increase_prometheus(m[d])` functions, which don't take into account the last sample before the lookbehind window `d` in the same way as Prometheus does. The commit 974d9c0eeeb2c98d3e05ad21a2dd4d6efd395f5b documents this behavior and simplifies implementation for the added functions. These commits will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment] 2021-12-20 18:19
VictoriaMetrics supports [changes_prometheus](https://docs.victoriametrics.com/MetricsQL.html#changes_prometheus), [increase_prometheus](https://docs.victoriametrics.com/MetricsQL.html#increase_prometheus) and [delta_prometheus](https://docs.victoriametrics.com/MetricsQL.html#delta_prometheus) starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Closed by valyala** 2021-12-20 18:19 UTC
Labels: enhancement, metricsql
