### ISSUE TITLE
Why does a large number of queries increase vm-storage memory usage by at least 40%?

### ISSUE THREAD

**Issue by baosenle** [VictoriaMetrics/VictoriaMetrics#5277] opened 2023-11-02 09:38 UTC
### Is your question request related to a specific component?

Current bahavior:
Under normal circumstances, vm-storage uses 40% memory. When there is a 10k/s read query (alarm rule query metrics data) running for about a day, vm-storage gradually increases to over 90% memory usage.

My Question:
**1. What is the cause of the current behavior?
2. How to optimize? or any suggestions?
3. Can vm-storage nodes expand infinitely? Like 1000 nodes?
4. (By the way) Why does the usage of CPU and mem skyrocket at 8am every morning？**

ENV & VM Cluster size:
version: v1.75.0-cluster
vm-storage: 64 nodes(48c/256g)
vm-select: 20 nodes (12c/90g) 

Thank you in advance！

### Describe the question in detail

Screenshot of the monitoring
<img width="1362" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/87fe9f9e-04f4-4371-8991-5ca6408cfcd2">
<img width="1343" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/577e693b-fc8e-423d-a55a-a88d33b6fc18">
<img width="692" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/12157781-19ce-4431-9dac-5cdd1f098d0d">

vm-select:
<img width="1347" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/f76cd42b-fddf-4d20-a2c6-09ad7060ac23">

vm-storage:
<img width="1369" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/fdbc5302-e6ea-4a01-a4ac-cf333139f6b4">
<img width="1357" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/a76edb8b-f445-4aec-9e74-c8a43fdcc212">
<img width="673" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/836611fd-95f0-498c-b4f9-1f06752f1b83">
<img width="1370" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/b7342892-7ccd-4dab-bede-d4409b485162">

resource usage:
<img width="1370" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52095028/51c565f1-abe5-449d-8522-c23c82fdcb3e">

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment] 2023-11-02 15:23
Hello!

> 1. What is the cause of the current behavior?

The gradual increase of memory usage can be caused by caches growth. Have you observed correlation with that?
It also can be used with the ingestion. Since most of installations have non-zero [churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate), the amount of unique time series constantly grows. Hence, index sizes grow as well.

> 2. How to optimize? or any suggestions?

I'd recommend starting from https://docs.victoriametrics.com/Troubleshooting.html#general-troubleshooting-checklist
For example, updating to newer versions could contain various improvements to resource usage.

> 3. Can vm-storage nodes expand infinitely? Like 1000 nodes?

It can, but it is not recommended to do so due to network scalability. Communicating to vmstorages (on reads or writes) requires network communication. Network is tend to fail: packets can be lost, re-transmitted, corrected.  This results in a delay. These errors aren't frequent, but expected for any distributed system. Since the chance of a network error is > 0, then it will happen eventually. When you add more shards to the distributed systems, you increase the chance for network error to happen. This is simply probabilistic theory: if chance to get a network error while communicating to 1 service is 0.001%, then communicating to 1k services increases the chance by 1k - to 0.001% * 1000 = 100%. Hence, each time you send a request to 1k nodes at least one of them will encounter network error.

> 4. (By the way) Why does the usage of CPU and mem skyrocket at 8am every morning？

I recall some issue related to this. I also recall it was addressed in newer versions of VM. Want to try updating your stack?

**Comment by jiekun** [comment] 2024-07-23 03:46
Close due to inactivity.

**Closed by jiekun** 2024-07-23 03:46 UTC
Labels: question
