### ISSUE TITLE
VM Panic OOM

### ISSUE THREAD

**Issue by qiaogj1** [VictoriaMetrics/VictoriaMetrics#562] opened 2020-06-15 06:41 UTC
**Describe the bug**
Panic due to OOM
Default parameter -memory.allowedPercent not effective,when specifying this parameter set to 60, it will always apply for memory, and the memory is more than 60%.

**To Reproduce**
NA

**Panic Log**
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xbfe1f6, 0x16)
        runtime/panic.go:1116 +0x72
runtime.sysMap(0x10f38000000, 0x82c000000, 0x1173278)
        runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x11584c0, 0x82a800000, 0x11584c8, 0x4152ac)
        runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x11584c0, 0x4152ac, 0x0)
        runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x11584c0, 0x4152ac, 0x100, 0x1173288, 0x300000003)
        runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x11584c0, 0x4152ac, 0x9a0001, 0xd3b0503320)
        runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x82a558000, 0x7db58c320100, 0x1)
        runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        runtime/malloc.go:1047 +0x46
runtime.systemstack(0xd1559e5380)
        runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        runtime/proc.go:1041

goroutine 149 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:330 fp=0xd3b05033f8 sp=0xd3b05033f0 pc=0x4669d0
runtime.mallocgc(0x82a558000, 0x0, 0xd3b0503500, 0x706d39)
        runtime/malloc.go:1046 +0x895 fp=0xd3b0503498 sp=0xd3b05033f8 pc=0x40e895
runtime.growslice(0xb29540, 0x107b99ca000, 0x688443637, 0x688446000, 0x6884476ec, 0x1, 0x107b99ca000, 0x688443637)
        runtime/slice.go:175 +0x14e fp=0xd3b0503500 sp=0xd3b0503498 pc=0x44de3e
github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding.MarshalBytes(0x107b99ca000, 0x6884476ec, 0x688446000, 0xc16f84c000, 0x40b5, 0x6000, 0xc19c728000, 0x10d6c, 0xd3b05035d8)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/encoding/int.go:224 +0x11c fp=0xd3b0503568 sp=0xd3b0503500 pc=0x7139ec
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*metaindexRow).Marshal(0xd2da506758, 0x107b99ca000, 0x688443634, 0x688446000, 0x12000, 0x1e000, 0x4)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/metaindex_row.go:36 +0x6e fp=0xd3b05035e8 sp=0xd3b0503568 pc=0x7af0be
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamWriter).flushIndexData(0xd2da506680)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/block_stream_writer.go:216 +0x185 fp=0xd3b0503648 sp=0xd3b05035e8 pc=0x7a7d85
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamWriter).WriteBlock(0xd2da506680, 0xcd68d00020)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/block_stream_writer.go:194 +0x313 fp=0xd3b05036f8 sp=0xd3b0503648 pc=0x7a7aa3
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamMerger).flushIB(0xcd68d00000, 0xd2da506680, 0xd3b0503d18, 0xc000210010)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/merge.go:193 +0x566 fp=0xd3b0503818 sp=0xd3b05036f8 pc=0x7ae936
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamMerger).Merge(0xcd68d00000, 0xd2da506680, 0xd3b0503d18, 0xc00018f320, 0xc000210010, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/merge.go:134 +0x105 fp=0xd3b05038d8 sp=0xd3b0503818 pc=0x7adf55
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mergeBlockStreams(0xd3b0503d18, 0xd2da506680, 0xd1f82a3540, 0x3, 0x3, 0xc2e008, 0xc00018f320, 0xc000210010, 0x7f770f9c3be0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/merge.go:35 +0x163 fp=0xd3b0503980 sp=0xd3b05038d8 pc=0x7ad823
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc000210000, 0xd1f82a3520, 0x3, 0x4, 0xc00018f320, 0xd1f82a3500, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:794 +0x7c8 fp=0xd3b0503e20 sp=0xd3b0503980 pc=0x7bb998
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeExistingParts(0xc000210000, 0x3b9aca01, 0x0, 0x1)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:671 +0xeb fp=0xd3b0503e98 sp=0xd3b0503e20 pc=0x7baebb
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).partMerger(0xc000210000, 0x0, 0x0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:685 +0x7a fp=0xd3b0503f58 sp=0xd3b0503e98 pc=0x7bafba
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers.func1(0xc000210000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:653 +0x32 fp=0xd3b0503fd8 sp=0xd3b0503f58 pc=0x7c2db2
runtime.goexit()
        runtime/asm_amd64.s:1373 +0x1 fp=0xd3b0503fe0 sp=0xd3b0503fd8 pc=0x468ae1
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startPartMergers
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go:652 +0x68

goroutine 1 [chan receive, 16264 minutes]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/procutil.WaitForSigterm(0x1, 0xbf1747)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/procutil/signal.go:21 +0xdc
main.main()
        github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics/main.go:45 +0x322

goroutine 19 [sleep]:
time.Sleep(0x5f5e100)
        runtime/time.go:188 +0xba
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.dirRemover()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/dir_remover.go:63 +0x6e
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.init.0.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/dir_remover.go:98 +0x4c
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.init.0
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/dir_remover.go:96 +0x4e

goroutine 21 [chan receive]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/fasttime.init.0.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fasttime/fasttime.go:12 +0xa0
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/fasttime.init.0
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fasttime/fasttime.go:9 +0x35

goroutine 85 [sleep]:
time.Sleep(0x3b9aca00)
        runtime/time.go:188 +0xba
github.com/VictoriaMetrics/fasthttp.init.0.func1()
        github.com/VictoriaMetrics/fasthttp@v1.0.1/coarseTime.go:21 +0x51
created by github.com/VictoriaMetrics/fasthttp.init.0
        github.com/VictoriaMetrics/fasthttp@v1.0.1/coarseTime.go:19 +0xaf

goroutine 86 [sleep]:
time.Sleep(0x3b9aca00)
        runtime/time.go:188 +0xba
github.com/VictoriaMetrics/fasthttp.init.1.func1()
        github.com/VictoriaMetrics/fasthttp@v1.0.1/header.go:1338 +0x2a
created by github.com/VictoriaMetrics/fasthttp.init.1
        github.com/VictoriaMetrics/fasthttp@v1.0.1/header.go:1336 +0x3a

goroutine 87 [select, 7 minutes]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).expirationWorker(0xc00064a000, 0x80000, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:113 +0xd4
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func1(0xc00064a000, 0x80000, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:100 +0x6a
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:98 +0x124

goroutine 88 [select]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).cacheSizeWatcher(0xc00064a000, 0x80000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:141 +0x10a
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func2(0xc00064a000, 0x80000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:105 +0x5c
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:103 +0x167

goroutine 8 [sleep]:
time.Sleep(0x22ecb25c00)
        runtime/time.go:188 +0xba
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
        github.com/VictoriaMetrics/metrics@v1.11.3/summary.go:237 +0x161
created by github.com/VictoriaMetrics/metrics.registerSummary
        github.com/VictoriaMetrics/metrics@v1.11.3/summary.go:211 +0x139

goroutine 9 [sleep]:
time.Sleep(0x12a05f200)
        runtime/time.go:188 +0xba
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.errorsLoggedCleaner()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126 +0x30
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Init
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:35 +0x84

goroutine 90 [select]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexBlockCache).cleaner(0xcfd0756190)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:222 +0x100
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.newIndexBlockCache.func1(0xcfd0756190)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:200 +0x52
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.newIndexBlockCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/part.go:198 +0xc2

goroutine 12 [select, 7 minutes]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).expirationWorker(0xc0001d0210, 0x96e3ec333, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:113 +0xd4
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func1(0xc0001d0210, 0x96e3ec333, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:100 +0x6a
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:98 +0x124

goroutine 13 [select]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).cacheSizeWatcher(0xc0001d0210, 0x96e3ec333)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:141 +0x10a
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func2(0xc0001d0210, 0x96e3ec333)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:105 +0x5c
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:103 +0x167

goroutine 14 [select, 7 minutes]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).expirationWorker(0xc0001d02c0, 0x1c4abc499, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:113 +0xd4
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func1(0xc0001d02c0, 0x1c4abc499, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:100 +0x6a
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:98 +0x124

goroutine 15 [select]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).cacheSizeWatcher(0xc0001d02c0, 0x1c4abc499)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:141 +0x10a
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func2(0xc0001d02c0, 0x1c4abc499)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:105 +0x5c
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:103 +0x167

goroutine 16 [select, 7 minutes]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.(*Cache).expirationWorker(0xc0001d0370, 0x389578933, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:113 +0xd4
github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache.func1(0xc0001d0370, 0x389578933, 0x34630b8a000)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:100 +0x6a
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache.newWorkingSetCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/workingsetcache/cache.go:98 +0x124

goroutine 130 [select]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*indexBlockCache).cleaner(0xc00010c960)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go:221 +0x100
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.newIndexBlockCache.func1(0xc00010c960)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go:199 +0x52
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.newIndexBlockCache
        github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go:197 +0xc2 
```

**Screenshots**
*Node Exporter Dashbord*
![20200615142904](https://user-images.githubusercontent.com/20637997/84624808-a7582580-af14-11ea-8a4e-b860f7173923.png)
*VM Dashbord*
![20200615143244](https://user-images.githubusercontent.com/20637997/84625082-23526d80-af15-11ea-89f1-6070af728deb.png)

**Version**
```
victoria-metrics-20200601-100434-tags-v1.36.3-0-g32652485e
```
**Command-Line**
```
./victoria-metrics-prod -maxConcurrentInserts 8000 -maxInsertRequestSize 100000 -retentionPeriod 24 -search.maxConcurrentRequests 5000 -search.maxPointsPerTimeseries 3000000 -search.maxQueryLen 163840 -maxLabelsPerTimeseries 300 -search.maxUniqueTimeseries 30000000
```
**Additional context**
*os Version*
```
[root@SHELNPLMXS3 ~]# uname -a
Linux SHELNPLMXS3 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@SHELNPLMXS3 ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 
```

**Comment by valyala** [comment] 2020-06-18 21:40
@qiaogj1 , could you share other graphs from VM dashboard? They will help determining the real reason behind high memory usage (380GB memory usage looks too high).

As for the command-line:

> ./victoria-metrics-prod -maxConcurrentInserts 8000 -maxInsertRequestSize 100000 -retentionPeriod 24 -search.maxConcurrentRequests 5000 -search.maxPointsPerTimeseries 3000000 -search.maxQueryLen 163840 -maxLabelsPerTimeseries 300 -search.maxUniqueTimeseries 30000000

I'd suggest removing the following command-line options, so VictoriaMetrics could use default values for these options:

* `-search.maxConcurrentRequests`
* `-maxConcurrentInserts`
* `-search.maxPointsPerTimeseries`

VictoriaMetrics uses sane defaults for command-line flags, so it isn't recommended to modify them just in case. The flags may be modified if the real need arises. See [troubleshooting docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#troubleshooting) for details.

**Comment by qiaogj1** [comment] 2020-06-19 02:53
Hi Valyala，

 Thank you very much for your reply. I have solved this problem.In my case there are the following problems.
-  At the same time, there are a large number of /api/v1/import calls, and the data volume is huge, most of the labels are extremely long. When these data are written, we can see that the memory and IO have obvious growth.
   This  case was to store all the slow SQL statements of all the databases and the size of all the objects in the database (table &index) every 12 hours. We had nearly 2000+ data instances. In the future, we will optimize the business 
    - Generate the UUID for each SQL statement, store the configuration in the relational database, and change the SQL statements in the LABLE to UUID
    - Avoid writing most of the data at the same time
- Our storage performance is too poor, only 2000 IOPS, Next week we will build a Cluster version of Victoria Metrics and use AFA Storage.

Thank you very much for providing such a powerful product as Victoria Metrics,it has helped us solve many key problems, wish the  Victoria Metrics more and more powerful.

**Comment by valyala** [comment] 2020-06-19 11:25
> This case was to store all the slow SQL statements of all the databases
> ...
> Generate the UUID for each SQL statement, store the configuration in the relational database, and change the SQL statements in the LABLE to UUID

As I understood, you are storing full SQL statements in labels now. While storing UUID or hash instead of SQL statement may improve ingestion and query performance, it doesn't solve the issue with high number of unique label values, which may lead to high cardinality issues such as high RAM usage and/or slow performance. See [troubleshooting docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#troubleshooting) for details.

I'd recommend storing only SQL templates in labels without variable parts. For example, instead of storing `SELECT a,b,c FROM foo WHERE bar = 123 AND baz IN ('x','y','z')` in the label, store `SELECT a,b,c FROM foo WHERE bar = ? AND baz IN (?)`. This will greatly reduce the number of unique labels and, consequently, the number of unique time series.

**Comment by flashmouse** [comment] 2020-06-20 06:39
@valyala hi guys, according to describe above, I think we have the similar problem.

last month one of our vm-cluster's vmstorage node suddenly oom during doing bigpart merge. the  node has 2 core with 8g mem, the memory usage about 60% for long time. after the oom happened, we couldn't restart service until upgrade hardware to 16g mem.

after some research, we think the cause is index db has a large number of blocks, although each block has limit to force flush when reached 65535byte, but the Metaindex attribute will increase by block num. and because vm use zstd to obtain a better compress ratio, there may be a similar size byte slice used when doing part merge with zstd compress. 

as a result, our vmstorage node restarted successfully after upgrade to 16g mem, we have noticed that after merge end, this process has allocate 12g heap memoey, but 9g is idle.

we think this problem may be partly related to the problem  #490 we had met. beacuse metricName too long, each block in index db keep less number of index, so metaindex size increase.

i think it may not vm's fault, if golang gc may do something more clever, maybe process doesn't need oom, but now it happened.

i have upload our heap profile, hope it may useful.
[gg.3.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4807447/gg.3.gz)

below is the golang heap status now after restart successfully & merge end of the node mentioned above:
go_memstats_heap_alloc_bytes 2030299408
go_memstats_heap_idle_bytes 10161496064
go_memstats_heap_inuse_bytes 2050973696
go_memstats_heap_objects 905315
go_memstats_heap_released_bytes 8801624064
go_memstats_heap_sys_bytes 12212469760

**Comment by valyala** [comment] 2020-06-20 13:31
@flashmouse , thanks for the detailed report! It looks like you run old version of VM cluster (at least lower than `v1.35.0` according to the provided memory profile - it refers to `gozstd v1.6.4`, which has been upgraded to `gozstd v1.7.0` in `v1.35.0`). The #490 has been fixed in `v1.35.5`. Could you upgrade to the [latest release of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and verify whether it has the issue with high memory usage?

**Comment by flashmouse** [comment] 2020-06-22 02:02
@valyala our vmstorage version now is 1.34.3. we'll try new version recently, thanks for reply!

**Comment by valyala** [comment] 2020-06-22 09:31
Note that [v1.35.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.35.0) introduced backwards-incompatible prototocol between `vminsert` and `vmstorage`, so you may see errors about incompatible protocol during the upgrad of `vminsert` and `vmstorage` components from versions older than v1.35.0 to v1.35.0 or higher versions. These error messages should stop appearing after all the `vminsert` and `vmstorage` nodes are upgraded.

**Closed** 2021-06-15 02:20 UTC
Labels: need more info
