### ISSUE TITLE
In the victoria-logs ui make the relative range control relative to the time when the query is run.

### ISSUE THREAD

**Issue by zaphar** [VictoriaMetrics/VictoriaMetrics#6440] opened 2024-06-08 00:14 UTC
### Is your feature request related to a problem? Please describe

I spent several hours trying to figure out why victoria-logs vmui interface wasn't showing me current logs when I clicked the Execute Query button. After a while I realized that I had to re-select the Last 30 Minutes options because it still had the value from when I loaded the page yesterday.

This is surprising behavior because the selector says last 5 minutes but it's actually the last 5 minutes from when you selected that option in the picker.

### Describe the solution you'd like

Everytime you click the execute query button it should recalculate the time range for the requested relative range.

### Describe alternatives you've considered

The workaround for this is to click the time selector instead of the execute query button to update the query but that is surprising behavior that seems wrong for the long term.

### Additional information

I haven't looked at any of the frontend codebase yet but I would be willing to work on a patch for this myself if there is someone available to guide me if necessary.

**Comment by Loori-R** [comment] 2024-06-20 16:09
Duplicate of #6345

**Closed by Loori-R** 2024-06-20 16:09 UTC
Labels: enhancement, victorialogs
