### ISSUE TITLE
VM alert "ConcurrentFlushesHitTheLimit" triggers due to metrics interference from vmalert

### ISSUE THREAD

**Issue by FredTreg** [VictoriaMetrics/VictoriaMetrics#3761] opened 2023-02-05 15:12 UTC
### Describe the bug

When using the `https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml `for monitoring VictoriaMetrics itself, the alarm `ConcurrentFlushesHitTheLimit `will trigger incorrectly as the scraping of vmalert also produces metrics `vm_concurrent_insert_current` and `vm_concurrent_insert_capacity` with a constant value of zero.

As a result, the rule for the alert `avg_over_time(vm_concurrent_insert_current[1m]) >= vm_concurrent_insert_capacity` is always true as `0 >= 0` is true

### To Reproduce

* Install VM single + vmalert + alertmanager
* Configure VM to scrape VM and vmalert
* Configure alertmanager to receive alerts on a channel of your choice
* Add alerts `https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml` to vmalert

=> Alert `ConcurrentFlushesHitTheLimit` is triggered for `vmalert` although this alarm was designed only for VictoriaMetrics in the first place

### Version

v1.87.0

### Additional information

As a workaround I modified the rule to:
`avg_over_time(vm_concurrent_insert_current{job="victoriametrics"}[1m]) >= vm_concurrent_insert_capacity{job="victoriametrics"}`

**Comment by hagen1778** [comment] 2023-02-07 12:04
Hello! This is unexpected for vmalert to expose metric `vm_concurrent_insert_current`. 
This is likely caused by some dependency of vmalert's. I'll check what we can do with this.

**Comment by valyala** [comment] 2023-02-07 19:23
The https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3761 should properly initialize `vm_concurrent_insert_current` metric. This commit will be included in the next release.

**Comment by FredTreg** [comment] 2023-02-07 20:49
Thanks for the fast response! You rock guys!

**Comment by valyala** [comment] 2023-02-08 16:00
Let's re-open this issue, since the long-term solution is to remove the dependency, which adds `vm_concurrent_insert_*` metrics to `vmalert` - these metrics shouldn't be visible in `vmalert`.

**Comment by valyala** [comment] 2023-02-10 00:20
FYI, the `vm_concurrent_insert_current` metric should be properly initialized to non-zero value in `vmalert` starting from [v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by hagen1778** [comment] 2023-03-06 12:03
The issue was fixed in [v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html).

**Closed by hagen1778** 2023-03-06 12:03 UTC
Labels: bug, vmalert
