### ISSUE TITLE
Spikes with increase() and counter restart

### ISSUE THREAD

**Issue by jcmoraisjr** [VictoriaMetrics/VictoriaMetrics#279] opened 2019-12-24 14:57 UTC
**Describe the bug**

Grafana shows a spike when a counter restarts (the service being scraped was restarted)

**To Reproduce**

Combine an `increase()` and a counter restart.

**Expected behavior**

No spikes at all when a counter is restarted.

**Version**

Scrape was on 1.29.4. Both 1.29.4 and 1.31.3 has the same output.

**Additional context**

Here is the query response for `sum(increase(metric{instance=~".*"}[1m])) by (instance)`:

[query-filter-regex.json.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3998539/query-filter-regex.json.gz)

And here is the query response for `sum(increase(metric[1m])) by (instance)`:

[query-no-filter.json.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3998540/query-no-filter.json.gz)

This counter cannot increase more than `15` within `[1m]` so all the values should be `15` or below. These two values are unexpected:

```
$ zegrep -o '.{11}"33".'  query-*
query-filter-regex.json.gz:[1577193075,"33"]
query-no-filter.json.gz:[1577193075,"33"]

$ zegrep -o '.{11}"9783".'  query-*
query-filter-regex.json.gz:[1577193810,"9783"]
```

`~9700` was the counter value before the restart. `33` has no meaning to me, this is a new time series in the metric.

Feel free to ask data for a new query.

**Comment by valyala** [comment] 2019-12-24 19:28
@jcmoraisjr , could you determine the exact time series, which shows incorrect value after applying `increase()` to it? I.e. run `increase(metric[1m])` query and obtain all the labels for the `metric` with incorrect value for `increase()`. Then fetch raw data for the selected metric with labels on the selected time range via [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series) and attach raw data with the data returned by `increase` for this single time series.

**Comment by jcmoraisjr** [comment] 2019-12-25 18:27
HI, here is the export:

[haproxyingress-metric.json.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4000729/haproxyingress-metric.json.gz)

The grouping was made by `instance`: instance5 has the `9783` value and instance2 has the `33`.

**Comment by valyala** [comment] 2019-12-25 21:48
Thanks for the data!

I reproduced the issue on this data using the query `increase(haproxyingress_updates_total{instance=~"instance5.*",status="noop"}[1m])` for timestamps in the range starting from 1577192779 and ending with 1577192849 , i.e. during the first 70 seconds of the time series. This is expected because of the following assumptions:

* `increase()` is applied to counters, i.e. time series, which start from 0 and never go down (except for counter resets, when the value goes to 0).
* Counters always start from 0. If the first value for the counter time series is 9682, then it is expected that `increase()` at the beginning of time series would be close to 9682.

If you start scraping long-living counters with high values (i.e. if time series starts from high value instead of 0) and want removing these values from the output, then add either `clamp_max(query, max_value)` or ` > max_value` to the query.

However, I couldn't reproduce high value on counter reset in the middle of time series around timestamp 1577193810 . Could you

**Comment by jcmoraisjr** [comment] 2019-12-26 15:35
Hi, first the bad news. I cannot reproduce the "9783" spike anymore. This is the one whose counter restarted.

Below a comparison with the exact same query, with the exact same time range.

Perhaps some compressing data "fixed" this? As stated before the scrape was made with 1.29.4 and the first collect (`query1.json`) with 1.31.3:

```
$ diff -u <(cat query1.json | tr ',' '\n') <(cat query2.json | tr ',' '\n')
--- /dev/fd/63    2019-12-26 11:46:51.610476043 -0300
+++ /dev/fd/62    2019-12-26 11:46:51.610476043 -0300
@@ -1448,7 +1448,7 @@
 [1577193795
 "4"]
 [1577193810
+"9783"]
-"3"]
 [1577193825
 "3"]
 [1577193840
```

The good news is that the "33" one was caused by an exporter which was started too early, my fault, sorry about the noise.

Is there something else I can help regarding the remaining issue? Otherwise I think this issue can be closed.

**Comment by valyala** [comment] 2019-12-26 16:00
> Perhaps some compressing data "fixed" this? 

This could be related to incorrect interaction with query cache. VictoriaMetrics splits query time range into two parts if the same query has been already executed in the past and its result has been cached. Then VictoriaMetrics executes the query only on new time range and then merges the result with the cached result for the previous time range. I'll keep an eye on it.

If you'll notice the same issue in the future, then try disabling query cache and re-run the query again in order to verify the hypothesis mentioned above. Query cache can be disabled either by passing `nocache=1` query arg to `/api/v1/query_range` endpoint, i.e. `/api/v1/query_range?nocache=1&query=....` or by passing `-search.disableCache` command-line flag to single-node VictoriaMetrics or `vmselect` on startup.

**Comment by valyala** [comment] 2020-01-10 22:44
I'm going to close this issue. @jcmoraisjr , feel free re-opening it if you'll notice the issue again.

**Closed by valyala** 2020-01-10 22:44 UTC
Labels: bug
