### ISSUE TITLE
predict_linear discrepancy between VictoriaMetrics and Prometheus

### ISSUE THREAD

**Issue by ctrlok** [VictoriaMetrics/VictoriaMetrics#71] opened 2019-06-21 06:57 UTC
The predict_linear function shows false data compare to Prometheus. 
Example
```
predict_linear( node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0"}[1h], 24 * 3600 )
```
Result (look at Y axis):
![Capto_Capture 2019-06-21_09-53-01_AM](https://user-images.githubusercontent.com/3265316/59903761-77ae3480-940a-11e9-9ebf-863ad5e7069f.png)

**Comment by valyala** [comment] 2019-06-21 09:57
At least the shape of the graphs are the same for VictoriaMetrics and Prometheus. It looks like something is broken with the offset calculations inside `predict_linear`. Could you provide the original graph without `predict_linear` for the same time range?

**Comment by valyala** [comment] 2019-06-21 09:58
Try using one-hour offset shift, i.e. use `25*3600` or `23*3600` instead of `24*3600` in VictoriaMetrics and see how the graph changes.

**Comment by ctrlok** [comment] 2019-06-21 10:04
For 24 and 23: 
![Capto_Capture 2019-06-21_01-02-07_PM](https://user-images.githubusercontent.com/3265316/59915228-d2548a00-9424-11e9-9804-6526017a45b7.png)

Also, I found that it changes for [9m] and [10m] as well. 
![Capto_Capture 2019-06-21_01-04-15_PM](https://user-images.githubusercontent.com/3265316/59915354-1ba4d980-9425-11e9-9515-cf4acdcd0bd3.png)

**Comment by ctrlok** [comment] 2019-06-21 10:07
data for `node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0", role="Monitoring"}[10m]` 
![Capto_Capture 2019-06-21_01-06-40_PM](https://user-images.githubusercontent.com/3265316/59915510-79d1bc80-9425-11e9-8b99-ef93c6b4633f.png)
Do you need raw data in json?

**Comment by valyala** [comment] 2019-06-21 20:08
> Also, I found that it changes for [9m] and [10m] as well.

This is expected. It should change in Prometheus as well.

> data for node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0", role="Monitoring"}[10m]

Thanks for these images. Now it is clear why `predict_linear` returns negative values for 24 hours - because the graph mostly contains negative slopes longer than `[10m]` window used in `predict_linear`. Try using window covering more than the negative slope duration - for instance, `predict_linear(node_filesystem_free_bytes[17h])`.

I adjusted data model, so it becomes more similar to the data model from Prometheus. Could you build VictoriaMetrics from the latest commits and verify whether `predict_linear` works as expected.

**Comment by ctrlok** [comment] 2019-06-21 20:36
it's better, but still different data. 
![Capto_Capture 2019-06-21_11-35-13_PM](https://user-images.githubusercontent.com/3265316/59949974-53d80680-947d-11e9-8a92-6b4c31ba043a.png)

**Comment by valyala** [comment] 2019-06-21 21:06
Looks much better! Will investigate the remaining discrepancy

**Comment by valyala** [comment] 2019-06-24 19:47
@ctrlok , could you verify `predict_linear` in the latest commit?

**Comment by valyala** [comment] 2019-08-14 00:21
Closing the issue as fixed. Feel free re-opening it if `predict_linear` doesn't work as intended in [new releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Closed by valyala** 2019-08-14 00:21 UTC
Labels: bug
