### ISSUE TITLE
Datadog: /api/beta/sketches endpoint is not supported

### ISSUE THREAD

**Issue by rodrigc** [VictoriaMetrics/VictoriaMetrics#3091] opened 2022-09-09 15:17 UTC
**Is your feature request related to a problem? Please describe.**
1.  Set up Datadog agent to send metrics to Datadog **and** VictoriaMetrics via use of `additional_endpoints` setting in `datadog.yml`
2. Metrics are sent sucessfully, but Datadog agent's logs have lots of errors like:

```

Sep 03 04:57:35 myhost agent[46534]: 2022-09-03 04:57:35 UTC | CORE | ERROR | (pkg/forwarder/transaction/transaction.go:342 in internalProcess) | Error code "400 Bad Request" received while sending transaction to "http://vminsert-host:8480/insert/0/datadog/api/beta/sketches": "remoteAddr: \"127.0.0.1:40392\"; requestURI: /insert/0/datadog/api/beta/sketches; unsupported path requested: \"/insert/0/datadog/api/beta/sketches\"\n", dropping it
```

**Describe the solution you'd like**
1.  Maybe implement `/datadog/api/beta/sketches` endpoint enough so that it does not trigger Datadog errors in logs, OR
2.  Submit fix upstream to datadog-agent to not try to access this endpoint if it is not supported.  Code for this is:
     https://github.com/DataDog/datadog-agent/blob/8b97e70604f5dec82009f376911e3354a9c503bc/test/integration/serverless/recorder-extension/main.go#L197

**Additional context**

See discussion here: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1662499999540149?thread_ts=1661901178.699309&cid=CGZF1H6L9

See also: https://grafana.com/static/assets/img/blog/datadog_plugin_diagram_new.png

**Comment by tommysitehost** [comment] 2023-05-17 05:36
Seems like this endpoint is needed for [dd serverless plugin](https://docs.datadoghq.com/serverless/installation/go/?tab=serverlessframework). I followed the dd docs and found these error logs:
```
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.runtime_duration","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:false"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":19,"Max":19,"Sum":19,"Avg":19,"Cnt":1}},"ts":1684300190}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.response_latency","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:false"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":19.124,"Max":19.124,"Sum":19.124,"Avg":19.124,"Cnt":1}},"ts":1684300190}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.produced_bytes","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:false"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":4,"Max":4,"Sum":4,"Avg":4,"Cnt":1}},"ts":1684300190}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.estimated_cost","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:true"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":9.333348e-7,"Max":9.333348e-7,"Sum":9.333348e-7,"Avg":9.333348e-7,"Cnt":1}},"ts":1684299960}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.init_duration","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:true"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":0.5864510000000001,"Max":0.5864510000000001,"Sum":0.5864510000000001,"Avg":0.5864510000000001,"Cnt":1}},"ts":1684299960}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.billed_duration","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:true"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":0.044,"Max":0.044,"Sum":0.044,"Avg":0.044,"Cnt":1}},"ts":1684299960}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.invocations","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:false","init_type:on-demand"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":1,"Max":1,"Sum":1,"Avg":1,"Cnt":1}},"ts":1684300190}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"coffee_house.order_value","tags":["env:dev","service:wsr-datadog-apse2","product:latte","order:online","dd_lambda_layer:datadog-go1.19.5","memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd""],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":12.45,"Max":12.45,"Sum":12.45,"Avg":12.45,"Cnt":1}},"ts":1684300190}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : {"metric":"aws.lambda.enhanced.response_duration","tags":["memorysize:1024","service:datadog","region:aws_region","resource:aws_function_name","env:dev","architecture:x86_64","environment:deb","aws_account:aws_account_id","runtime:go1.x","functionname:aws_function_name","dd_extension_version:43","account_id:aws_account_id","git.commit.sha:"***********************************e1cdd"","function_arn:arn:aws:lambda:aws_region:aws_account_id:function:aws_function_name","cold_start:false"],"host":"","interval":10,"points":[{"sketch":{"summary":{"Min":0.078,"Max":0.078,"Sum":0.078,"Avg":0.078,"Cnt":1}},"ts":1684300190}]}
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | The payload was not too big, returning the full payload
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | The payload was not too big, returning the full payload
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | SyncForwarder has flushed 1 transactions
2023-05-17 05:09:50 UTC | DD_EXTENSION | DEBUG | Demultiplexer: sendIterableSeries: stop routine
2023-05-17 05:09:50 UTC | DD_EXTENSION | ERROR | Error code "400 Bad Request" received while sending transaction to "http://victoria-metrics:8428/datadog/api/beta/sketches": "remoteAddr: \"10.0.112.110:38371\"; requestURI: /datadog/api/beta/sketches; unsupported path requested: \"/datadog/api/beta/sketches\"\n", dropping it
```

The enhanced metrics are not accepted by VM

**Comment by valyala** [comment] 2024-02-07 19:50
Support for `/api/beta/sketches` endpoint has been added in the commit a1d1ccd6f21c3ffa40b45112ec4d37ab7cb05d82 . This commit will be included in the next release. In the mean time it is possible to verify whether the `/api/beta/sketches` endpoint works as intended by building VictoriaMetrics from the commit bf9ea249a3128b85a01ef449ccd81b193188e3a4 (this is the latest follow-up commit related to DataDog sketches API) according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verifying whether it properly accepts DataDog sketches at `http://localhost:8428/datadog/api/beta/sketches`  endpoint as described at https://docs.victoriametrics.com/#how-to-send-data-from-datadog-agent .

**Comment by valyala** [comment] 2024-02-14 15:33
VictoriaMetrics and [vmagent](https://docs.victoriametrics.com/vmagent/#how-to-push-data-to-vmagent) support `/api/beta/sketches` endpoint starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [these docs](https://docs.victoriametrics.com/#how-to-send-data-from-datadog-agent). Closing the feature request as done.

**Closed by valyala** 2024-02-14 15:33 UTC
Labels: enhancement, vmagent
