### ISSUE TITLE
Vm scrapping k8s  kubernetes_sd_config, time to time data missing

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#1807] opened 2021-11-11 07:19 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/33677006/141251918-f143c5e4-17e4-4354-84b3-1f80431ec5cc.png)
![image](https://user-images.githubusercontent.com/33677006/141251706-65cd63a9-c6da-44b8-a8b3-acbbf0d8f066.png)

for targets under  kubernetes_sd_configs.
The user reported that data missing from time to time.
And we set up 2 independent clusters that are missing data at different times.
![image](https://user-images.githubusercontent.com/33677006/141252682-2330a05b-3290-4802-a1b7-5d3374951f60.png)
When losing data there is no target unreachable or marked as `down`
**To Reproduce**
configuration is
```
- job_name: kube-state
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: HTTP
  kubernetes_sd_configs:
  - api_server: https://xxxxxxxxxxxxxxxxxxxxxx.xxxxxxx.us-west-2.eks.amazonaws.com
    role: endpoints
    bearer_token_file: /config/eks-center
    tls_config:
      insecure_skip_verify: true
    namespaces:
      names:
      - xxxxxxxxx
```
**Expected behaviour**
No data losing

**Logs**
no log related to this issue

**Version**
vmagent:
vmagent-20211008-135241-tags-v1.67.0-0-g6058edb0d
vmstorage:
vmstorage-20211008-140613-tags-v1.67.0-cluster-0-g20fa4b01c
vmselect:
vmselect-20211008-140608-tags-v1.67.0-cluster-0-g20fa4b01c
vminsert:
vminsert-20211008-140602-tags-v1.67.0-cluster-0-g20fa4b01c

**Used command-line flags**
vmagent:
```
-promscrape.config=prometheus.yml -remoteWrite.url=xxxxx -http.connTimeout=1000ms -promscrape.maxScrapeSize=250MB -promscrape.suppressDuplicateScrapeTargetErrors -promscrape.cluster.membersCount=9 -promscrape.cluster.memberNum=0 -promscrape.streamParse=true -promscrape.consulSDCheckInterval=60s -remoteWrite.queues=10  -promscrape.cluster.replicationFactor=2
```
vmselect:
```
-dedup.minScrapeInterval=13s -search.logSlowQueryDuration=15s -search.maxQueryDuration=50s -cacheDataPath=/logs -search.maxQueryLen=1MB -storageNode=...... 
```
vminsert:
```
-replicationFactor=2 -maxLabelsPerTimeseries=50 -storageNode=....
```
vmstorage：
```
-search.maxUniqueTimeseries=2000000  -storageDataPath=/lingtian/opt/vmstorage-data -retentionPeriod=1y -bigMergeConcurrency=1
```

**Comment by YuriKravetc** [comment] 2021-11-15 14:09
Hello, 
Can you please attach VMCluster graphs and check if there were any spikes in RAM\CPU in those periods of time?

**Comment by f41gh7** [comment] 2021-11-16 08:55
Hi, can you check:
1) Does it affect all metrics or only for specific jobs, like cadvisor metrics?
2) does downgrade to the 1.66.2 version solves an issue?

**Comment by renchili** [comment] 2021-11-16 09:57
@YuriKravetc  no spikes in RAM/CPU quite normal,
you need which graph please let me know more clearly is the victoria metrics grafana dashboards? 
@f41gh7 for 1 yes it only affects Kubernetes ds, 2 we cannot roll back to 1.66.2 cause there other issue or features that made use updated to the new version.
Thanks for everyone help on this. 

we set up some staleness settings to cover this up so far.

**Comment by valyala** [comment] 2021-11-16 23:13
@renchili , could you upgrade `vmagent` to [v1.69.0](https://docs.victoriametrics.com/CHANGELOG.html#v1690) and see whether this helps removing gaps on graphs for the newly ingested data? It is safe downgrading to v1.66.2 in the case if the upgrade to v1.69.0 won't help.

**Comment by renchili** [comment] 2021-11-17 07:41
> @renchili , could you upgrade `vmagent` to [v1.69.0](https://docs.victoriametrics.com/CHANGELOG.html#v1690) and see whether this helps removing gaps on graphs for the newly ingested data? It is safe downgrading to v1.66.2 in the case if the upgrade to v1.69.0 won't help.

Sorry, we cannot do any downgrade, we will try in grey-env to set up 1.69.0

**Comment by renchili** [comment] 2021-11-17 08:41
update: we update to 1.69.0  but issue seems still existed:
![image](https://user-images.githubusercontent.com/33677006/142165949-78c8fc77-96a4-4aa7-90f9-45c2e485b77c.png)
and after the upgrade, the memory usage increased a lot. 
![image](https://user-images.githubusercontent.com/33677006/142166184-8fcc47b0-10a1-460e-8351-b124f24b9f7b.png)

Each version of victoria metrics contains many fixes and new features, some times is better to using a LTS version instead let user ketch up with the latest version

**Comment by valyala** [comment] 2021-11-17 10:25
The time series on the screenshot above has very big number of labels. By default VictoriaMetrics limits the number of labels per each time series to 30. If it sees more labels in the ingested sample, it writes a sample of these labels into the log and then drops the labels exceeding the limit. It also increases the `vm_metrics_with_dropped_labels_total` counter, which can be monitored at `Labels limit exceeded` graph on the [official Grafana dashboard for VictoriaMetrics](https://docs.victoriametrics.com/#monitoring).

While the limit on the number of labels per time series can be adjusted with `-maxLabelsPerTimeseries` command-line flag, it is recommended reducing the number of labels in the ingested samples, since the increased number of labels require additional resources - CPU, RAM, disk IO, disk space. If these labels aren't used, then it is better removing them with [relabeling rules during data ingestion](https://docs.victoriametrics.com/vmagent.html#relabeling).

As for the increased memory usage at vmagent, it is likely it is related to the [added and enabled by default staleness detection](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers). Try following recommendations at [troubleshooting section](https://docs.victoriametrics.com/vmagent.html#troubleshooting) for vmagent in order to reduce memory usage.

**Comment by f41gh7** [comment] 2021-11-17 15:13
@renchili  As workaround can you try to set `honor_timestamps: false`

**Comment by renchili** [comment] 2021-11-18 03:53
> The time series on the screenshot above has very big number of labels. By default VictoriaMetrics limits the number of labels per each time series to 30. If it sees more labels in the ingested sample, it writes a sample of these labels into the log and then drops the labels exceeding the limit. It also increases the `vm_metrics_with_dropped_labels_total` counter, which can be monitored at `Labels limit exceeded` graph on the [official Grafana dashboard for VictoriaMetrics](https://docs.victoriametrics.com/#monitoring).
> 
> While the limit on the number of labels per time series can be adjusted with `-maxLabelsPerTimeseries` command-line flag, it is recommended reducing the number of labels in the ingested samples, since the increased number of labels require additional resources - CPU, RAM, disk IO, disk space. If these labels aren't used, then it is better removing them with [relabeling rules during data ingestion](https://docs.victoriametrics.com/vmagent.html#relabeling).
> 
> As for the increased memory usage at vmagent, it is likely it is related to the [added and enabled by default staleness detection](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers). Try following recommendations at [troubleshooting section](https://docs.victoriametrics.com/vmagent.html#troubleshooting) for vmagent in order to reduce memory usage.

We know about labels limitation we already increased the limit of labels. Thanks for this, is off-topic on this issue.

**Comment by renchili** [comment] 2021-11-18 08:17
> @renchili As workaround can you try to set `honor_timestamps: false`

Well not quite sure why this is related. But yes it seems this will help. And for more information, the incoming data scraped did not contain any timestamp

**Comment by valyala** [comment] 2021-12-02 11:04
`vmagent` was using its own generated timestamps for scraped metrics until [v1.68.0](https://docs.victoriametrics.com/CHANGELOG.html#v1680) unless `honor_timestamps: true` config option was set at [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) section. This wasn't compatible with the default Prometheus behaviour, which uses timestamps from scrape target responses by default unless `honor_timestamps: false` config option is explicitly set at `scrape_config` section. The behaviour of `vmagent` has been aligned with Prometheus behaviour regarding which timestamps to use starting from [v1.68.0](https://docs.victoriametrics.com/CHANGELOG.html#v1680).

It looks like some scrape targets such as `cadvisor` export its own timestamps for some metrics, and the exported timestamps are out of sync with the current time at `vmagent`. This may result in gaps on graphs. For example:

`container_cpu_usage_seconds_total 123 123456789`

Where 123456789 is a timestamp for the exported metric `container_cpu_usage_seconds_total`. vmagent ignored such timestamps by default until v1.68.0. It used its own generated timestamps with scrape time instead. vmagent v1.68.0 and newer versions uses timestamps provided by scrape target by default. This behaviour can be changed by explicitly setting `honor_timestamps: false` in the corresponding `scrape_config` section at `-promscrape.config` file.

The actually stored timestamps for a particular metric can be inspected by exporting raw samples from VictoriaMetrics via `/api/v1/export` - see [these docs](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) for details.

**Comment by valyala** [comment] 2021-12-02 11:10
The proper solution would be to identify metrics with invalid exported timestamps at `cadvisor` and file an issue at [cadvisor repository](https://github.com/google/cadvisor), so cadvisor developers could fix it. The temporary workaround is to set `honor_timestamps: false` for `cadvisor` job at `-promscrape.config`.

**Comment by Vladikamira** [comment] 2021-12-03 13:36
@valyala thanks for the explanation 🙏 
But I still have some questions 😄 : 
- why with `honor_timestamps: true` enabled Prometheus does not have any gaps but Vmagent has? 
- Is that mean that Prometheus does not check the date of the metric's timestamps but Vmagent checks? 
- If so, what is the possible drift of timestamp for a metric?

Here is an example of gaps of `cadvisor` metrics for RSS memory of Vmagent

Prometheus (v2.23)
<img width="1417" alt="Screenshot 2021-12-03 at 14 26 11" src="https://user-images.githubusercontent.com/5423271/144610623-24fa7943-d7a5-4bdf-bf71-69722a6ecd41.png">
Vmagent (v1.70.0)
<img width="1417" alt="Screenshot 2021-12-03 at 14 26 18" src="https://user-images.githubusercontent.com/5423271/144610641-10060d46-4457-4596-b34e-84ea7cf41517.png">

**Comment by shusugmt** [comment] 2021-12-03 14:32
@Vladikamira What value are you setting for `-query.lookback-delta` flag in prometheus setup? The way of handling missing data points is different between VM and prometheus, and that maybe the cause of this difference I think. VM uses a smarter method which is [described at here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/209#issuecomment-542345971) but because of this leads having much shorter lookback-delta = 30s compared to the default of 5min in prometheus if you are scraping 15s interval.

**Comment by Vladikamira** [comment] 2021-12-08 11:04
@shusugmt thanks for explanation! It does make sense to me to have such logic 👌 
However, I cannot fix gaps  by setting 
```
 --search.maxLookback=5m
 --search.maxStalenessInterval=5m
```
on my `vmselect` pods with `honor_timestamps` enabled

> What value are you setting for -query.lookback-delta flag in prometheus setup?
it's the default one `5m`

I also tried to configure `-query.lookback-delta` to `30s` on Prometheus end, and no gaps appeared

for now, only `honor_timestamps: false` helps to remove gaps on graphs

**Comment by weijun876** [comment] 2022-11-24 06:00
> @shusugmt thanks for explanation! It does make sense to me to have such logic 👌 However, I cannot fix gaps by setting
> 
> ```
>  --search.maxLookback=5m
>  --search.maxStalenessInterval=5m
> ```
> 
> on my `vmselect` pods with `honor_timestamps` enabled
> 
> > What value are you setting for -query.lookback-delta flag in prometheus setup?
> > it's the default one `5m`
> 
> I also tried to configure `-query.lookback-delta` to `30s` on Prometheus end, and no gaps appeared
> 
> for now, only `honor_timestamps: false` helps to remove gaps on graphs


Is there any solution for this problem now?
when I add honor_timestamps: false, the monitoring data become incorrect and get some wrong alert

**Comment by zekker6** [comment] 2022-11-24 11:14
@weijun876 The root cause for this issue was related to the exporter reporting incorrect timestamps in the past, so in order to avoid adding `honor_timestamps: false` you need to fix the root case - exporter with incorrect timestamps.

**Comment by weijun876** [comment] 2022-11-25 08:20
> @weijun876 The root cause for this issue was related to the exporter reporting incorrect timestamps in the past, so in order to avoid adding `honor_timestamps: false` you need to fix the root case - exporter with incorrect timestamps.

The problem exists only in cadvisor metrics, can it only be fixed by cadvisor or fixed by vmagent ?i have no idea how to fix it.

**Comment by zekker6** [comment] 2022-11-29 11:39
@weijun876 Could you try to set `honor_timestamps: false` only for the job which is scraping cadvisor metrics?
Unfortunately, there is not much vmagent can do with this apart from that.

**Comment by hagen1778** [comment] 2023-04-27 07:43
Closing the issue as inactive. Feel free to re-open if the problem still exists.

**Closed by hagen1778** 2023-04-27 07:43 UTC
Labels: bug, vmagent
