### ISSUE TITLE
Row Disappeared when no server metric data for specific period and expecting to show the row with empty values(no data)

### ISSUE THREAD

**Issue by ravivish83** [VictoriaMetrics/VictoriaMetrics#5535] opened 2023-12-26 10:07 UTC
### Is your feature request related to a problem? Please describe

We have recently migrated from Redis/Cassandra stack to Victoria Metrics , where we observed that if the server metric path’s data is not presented in the Victoria Metris ,the Server metric path is disappeared in Grafana , and also  it's object array is returned empty with no metric path in Victoria Metrics direct query_range endpoint too . 

Previously when Redis was using, even though the metric path’s data was not presented ,assumed that it searched the path in entire Redis DB cache and returned with empty metric path in array object and hence the server metric path was not disappeared in Grafana side and also in Redis.

### Describe the solution you'd like

For Ex:

I have three servers sending data to VM every day. Corresponding to that, I see three Rows in my dashboard. Yesterday, one server did not send data from 1 PM to 3 PM.

When I select time period from 11 AM to 4 PM, I see three rows in my dashboard. But when I select from 1 PM to say 2 PM, only two row is visible, and 3rd row completely disappear and . I was expecting that second row should be shown with empty value.

**3 Servers displaying the Metric data**
==========================
![All 3 servers](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97023293/ad3ee6d1-20f5-4029-a97c-7ebb03ab2e15)

Metric path -Array 

![All 3 servers-Array](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97023293/171f6d20-067c-4059-9f6a-2ea63c7a219e)

Query the VictoriaMetric- direct endpoint

![All 3 servers-Array-VM Endpoint](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97023293/6f0bc9a9-a44e-4545-880e-01d12fd1d7d4)

**1 Server disappear when no metric data instead of showing the empty value/no data for the server**
=================================================================
![1server-disappear](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97023293/58dec3ec-a316-4c06-8981-50aa80f87dfb)

Metric path -Array 
![1server-disappear-array](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97023293/e4efca6b-deb1-4b4b-9428-c41f9852a721)

Query the VictoriaMetric- direct endpoint
 

we used the query_range as well as render API for examining the data in the backend.. and we see only two server names in the Json for the period where the data is missing for 3rd server.
 
![1server-disappear-VM-endpint](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97023293/fb1c00e0-f697-4fad-8191-d1569b081299)

### Describe alternatives you've considered

We request you please look at the possibilities that even though the metric path’s data was not presented in particular time frame in Victoria Metrics , it should scan in the entire retention period indexes and return with array object of empty metric path value .so it should be expecting to display the server name in the row with  'empty value' / ‘No Data’ , which would help to differentiate the same sever with / without metrics .

**Comment by hagen1778** [comment] 2024-01-19 14:22
Duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5621

**Closed by hagen1778** 2024-01-19 14:22 UTC
Labels: enhancement

**Comment by ravivish83** [comment] 2024-02-06 10:31
Can you please let me know when introduced this new functionality?

I would like to say that Grafana panels (example Time Series, Boom table) handle null values, so Grafana panels are designed in a way that allows distinguishing between temporary "no data" from "metric not defined" but it must get such information from VM. On some panels (example Boom Table) it can be even decided what information / value shall be displayed (0, " no data" or any other string) if there is no data for queried period of time. To display such string, Grafana must get in response an empty array if such metric does not have data points in questioned period of time.

Example: CPU load where server was off thus there are no data points. If Grafana panel receives an empty array in response it displays value defined in null handling (example "no data"). In this case users know that at this period of time there are no datapoints for CPU load but this metric exists. 

 

Also Is there any method that could revert back such information in response?
