### ISSUE TITLE
series queries ignore -search.maxQueryDuration

### ISSUE THREAD

**Issue by nemobis** [VictoriaMetrics/VictoriaMetrics#6018] opened 2024-03-26 10:04 UTC
### Describe the bug

The slow query log shows multiple queries to `/select/0/prometheus/api/v1/series` taking multiple minutes even though the `-search.maxQueryDuration` limit is set to 10 seconds. While such queries are running, all other queries grind to a halt (including ingestion).

### To Reproduce

No idea. The series query in question seemed relatively harmless and returns 0 results.

### Version

v1.99.0-cluster

### Logs

```
slow query according to -search.logSlowQueryDuration=5s: remoteAddr="10.x.y.z:w", duration=287.312 seconds; requestURI: "/select/0/prometheus/api/v1/series?end=1711438009&match%5B%5D=%7B__name__%3D%22node_filesystem_size_bytes%22%7D&start=1695709609"
```

### Screenshots

![Screenshot_20240326_120002](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/901528/6414e1de-7232-40f2-83d2-77876b95246a)

### Used command-line flags

```
  victoria-metrics-cluster-vmselect:
    Container ID:  containerd://2aa9d904df8ea42201a9803c4565b5c96e258bfe74a9874010b04dd4b201010e
    Image:         victoriametrics/vmselect:v1.99.0-cluster
    Image ID:      docker.io/victoriametrics/vmselect@sha256:4c142889029a00196441ae9628ded409e329935511c939f90e4a280d1df2f355
    Port:          8481/TCP
    Host Port:     0/TCP
    Args:
      --cacheDataPath=/cache
[...]
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
      --search.logQueryMemoryUsage=1GiB
      --search.logSlowQueryDuration=5s
      --search.maxConcurrentRequests=8
      --search.maxExportSeries=1000000
      --search.maxSeries=1000000
      --search.maxUniqueTimeseries=1000000
```

**Comment by hagen1778** [comment] 2024-03-26 10:52
Hello @nemobis !

You need to use `-search.maxLabelsAPIDuration` cmd-line flag for this API:
> -search.maxLabelsAPIDuration limits the duration for requests to [/api/v1/labels](https://docs.victoriametrics.com/url-examples/#apiv1labels), [/api/v1/label/…/values](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) or [/api/v1/series](https://docs.victoriametrics.com/url-examples/#apiv1series). These endpoints are used mostly by Grafana for auto-completion of label names and label values. Queries to these endpoints may take big amounts of CPU time and memory when the database contains big number of unique time series because of [high churn rate](https://docs.victoriametrics.com/faq/#what-is-high-churn-rate). In this case it might be useful to set the -search.maxLabelsAPIDuration to quite low value in order to limit CPU and memory usage. See also -search.maxLabelsAPISeries and -search.ignoreExtraFiltersAtLabelsAPI.

See https://docs.victoriametrics.com/#resource-usage-limits

But please note, in 1.99 there is a bug which uses incorrect flag value - this is addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5992 and will be included to the next release.

**Comment by jiekun** [comment] 2024-03-26 11:09
Please excuse my intrusion, but as I have been following the documentation, code, and this issue, I would like to offer a little bit more detail:

(Also cmiiw) The `-search.maxQueryDuration` parameter only limits the amount of time that can be **waited** before a query execution starts. If the query has not begun executing (which means the request is being handled by a handler) within this timeframe, the request will be aborted.

And `vm_request_duration_seconds` metric is for calculating time cost since a handler accept the request and start processing it.

In case you might be interested, here is the related codes:
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/bc79f7196d7502d692b592505f7929d280625a9b/app/vmselect/main.go#L127
- https://github.com/VictoriaMetrics/VictoriaMetrics/blob/bc79f7196d7502d692b592505f7929d280625a9b/app/vmselect/prometheus/prometheus.go#L844

The documentation for `-search.maxQueryDuration` is quite straightforward, yet the name of this parameter could be misleading. Might this be the root cause for the confusion surrounding this issue? :P

**Comment by hagen1778** [comment] 2024-04-17 12:30
Starting from [v.100.0](https://docs.victoriametrics.com/changelog/#v11000) release the `-search.maxLabelsAPIDuration` cmd-line flag should correctly limit execution of queries to [/api/v1/labels](https://docs.victoriametrics.com/url-examples/#apiv1labels), [/api/v1/label/…/values](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) or [/api/v1/series](https://docs.victoriametrics.com/url-examples/#apiv1series) APIs. Closing this issue as done.

**Closed by hagen1778** 2024-04-17 12:30 UTC
Labels: bug

**Comment by hagen1778** [comment] 2024-04-18 14:05
Hi @nemobis ! Could you please confirm that you're using v1.100+?
Please also note, that all deadline in VM limit only execution time, but doesn't limit time spent on transferring the result to the caller. So it could be that slow-reading client can exceed the deadline specified via maxLabelsAPIDuration.

**Comment by nemobis** [comment] 2024-04-18 15:03
> Could you please confirm that you're using v1.100+?

Yes, this is with v1.100.1.

> Please also note, that all deadline in VM limit only execution time, but doesn't limit time spent on transferring the result to the caller. So it could be that slow-reading client can exceed the deadline specified via maxLabelsAPIDuration.

Right. I'd be quite surprised if the transfer took 5 minutes, if those are queries made by Grafana (hosted in the same cluster). But I'll see if I can verify this possibility. Thanks.
