### ISSUE TITLE
Grafana Prometheus Datasource with TLS configured works for metrics but not alerts

### ISSUE THREAD

**Issue by chrisfw** [VictoriaMetrics/VictoriaMetrics#533] opened 2020-06-05 02:27 UTC
**Describe the bug**
It appears that victoriametrics is returning unexpected data via the Prometheus Grafana data source.  The datasource is configured                                                                                                                                                                                     with tls client auth connecting to vmauth which in turn routes to VictoriaMetrics.  Metric queries work fine, but the alerts configured against the same panels/queries fail with the message > error changing state to=alerting
`lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=17 name="Panel Title alert" error="tsdb.HandleRequest() error bad_response: readObjectStart: expect { or n, but found , error found in #1 byte of ...|\tn��l|..., bigger context ...|\tn��l�K��0��r�J��<�k!�.� �B�/���@�vZB�{�|..." changing state to=alerting`

**To Reproduce**
Set up Grafana 6.7.4 and install client certs/key and use them from vmauth which in turn forwards to Victoria Metrics.

**Expected behavior**
Both metrics and alerts should work over tls secured Prometheus datasource.

**Screenshots**
![tls_graf_ds_vmetrics](https://user-images.githubusercontent.com/6135741/83829534-16ca4b80-a6b1-11ea-815c-e082eaa994d8.png)

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20200405-113830-tags-v1.34.7-0-g69962a70
vmauth-20200507-201408-tags-v1.35.3-0-gefc8e3c5
```

**Used command-line flags**
 /opt/victoria-metrics/utils/vmauth-prod -auth.config=/opt/victoria-metrics/utils/authconfig.yml -tls -tlsCertFile=/opt/victoria-metrics/certs/sec.crt -tlsKeyFile=/opt/victoria-metrics/certs/sec.key

**Comment by valyala** [comment] 2020-06-05 09:08
@chrisfw , try upgrading `vmauth` and `VictoriaMetrics` to the [latest release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since the issue may be already fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/514 .

**Comment by chrisfw** [comment] 2020-06-05 09:18
@valyala Thanks for the info.  I will give it a try and let you know.

**Comment by chrisfw** [comment] 2020-06-05 09:37
@valyala That appears to have fixed the problem.  Thanks very much - I really appreciate your assistance!

**Comment by valyala** [comment] 2020-06-05 09:53
Great! Then closing this issue as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/514 .

**Closed by valyala** 2020-06-05 09:53 UTC
Labels: bug
