### ISSUE TITLE
vmagent crashes periodically with error panic: runtime error: index out of range [1024819115206086200] with length 27

### ISSUE THREAD

**Issue by aleksandrbog** [VictoriaMetrics/VictoriaMetrics#1096] opened 2021-02-27 09:22 UTC
Vmagent crashes periodically with error panic: runtime error: index out of range [1024819115206086200] with length 27

Logs:
"ts":"2021-02-27T09:00:15.296Z","level":"info","caller":"VictoriaMetrics/app/vmagent/main.go:111","msg":"started vmagent in 0.001 seconds"}
{"ts":"2021-02-27T09:00:15.297Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:91","msg":"reading Prometheus configs from \"/config/scrape.yml\""}
{"ts":"2021-02-27T09:00:15.297Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:82","msg":"starting http server at http://:8429/"}
{"ts":"2021-02-27T09:00:15.298Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:83","msg":"pprof handlers are exposed at http://:8429/debug/pprof/"}
{"ts":"2021-02-27T09:00:15.332Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:350","msg":"static_configs: added targets: 11, removed targets: 0; total targets: 11"}
{"ts":"2021-02-27T09:00:16.051Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:350","msg":"kubernetes_sd_configs: added targets: 216, removed targets: 0; total targets: 216"}
{"ts":"2021-02-27T09:00:17.846Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/scraper.go:350","msg":"file_sd_configs: added targets: 24517, removed targets: 0; total targets: 24517"}
panic: runtime error: index out of range [1024819115206086200] with length 27

goroutine 85 [running]:
github.com/VictoriaMetrics/metrics.(*Histogram).Update(0xc000161600, 0x3e112e0be826d695)
	github.com/VictoriaMetrics/metrics@v1.14.0/histogram.go:104 +0x252
github.com/VictoriaMetrics/metrics.(*Histogram).UpdateDuration(0xc000161600, 0xc006a0c1d3d8a72b, 0x53d4b7f0f4, 0xe08ae0)
	github.com/VictoriaMetrics/metrics@v1.14.0/histogram.go:179 +0xa6
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeConfig).run.func1(0xc00023c600)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:235 +0x13d
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeConfig).run(0xc00023dd80)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:248 +0x185
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeConfigs).add.func1(0xc00023dbc0, 0xc00023dd80)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:189 +0x59
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeConfigs).add
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:187 +0x1dd

**Comment by valyala** [comment] 2021-02-28 15:45
@aleksandrbog , could you build `vmagent` from the commit 51bf57743181ece22a920931ae83d721a1a6744a and verify whether the issue is gone in this build? See [build instructions for vmagent](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources).

**Comment by aleksandrbog** [comment] 2021-03-01 14:20
@valyala,  vmagent keeps crashing: 

panic: runtime error: index out of range [1024819115206086200] with length 27

goroutine 221801 [running]:
github.com/VictoriaMetrics/metrics.(*Histogram).Update(0xc00016f300, 0x3e112e0be826d695)
	github.com/VictoriaMetrics/metrics@v1.15.1/histogram.go:104 +0x252
github.com/VictoriaMetrics/metrics.(*Histogram).UpdateDuration(0xc00016f300, 0xc0075bbe8e8baeb1, 0x5b6515c44c, 0xe11b40)
	github.com/VictoriaMetrics/metrics@v1.15.1/histogram.go:179 +0xa6
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).scrapeInternal(0xc072924790, 0x177ee26b4fc, 0x177ee26b4fc, 0x2, 0x35)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:310 +0x68e
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).scrapeAndLogError(0xc072924790, 0x177ee26b4fc, 0x177ee26b4fc)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:237 +0x5a
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scrapeWork).run(0xc072924790, 0xc0729287e0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scrapework.go:223 +0x452
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scraperGroup).update.func1(0xc000a08600, 0xc072924790, 0xc03e23ec80)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:330 +0x69
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*scraperGroup).update
	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/scraper.go:328 +0x605
failed to watch file "/var/lib/docker/containers/d877a754ee4be37d84082d8fbd773bba012d1a70345d0d0e83798ac37f3396e6/d877a754ee4be37d84082d8fbd773bba012d1a70345d0d0e83798ac37f3396e6-json.log"

**Comment by valyala** [comment] 2021-03-01 14:50
@aleksandrbog , thanks for the update! The panic must be finally fixed in the commit d6a41b6ea25baaebdbee7b118bddfafe0e1ec825 .

**Comment by valyala** [comment] 2021-03-02 21:26
The bugfix is available starting from [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@aleksandrbog , feel free re-opening the issue if you still see the same panic in v1.55.0 or newer releases.

**Closed by valyala** 2021-03-02 21:26 UTC
Labels: bug, vmagent
