### ISSUE TITLE
Error in vmstorage cannot read packet with size

### ISSUE THREAD

**Issue by guliangsi** [VictoriaMetrics/VictoriaMetrics#763] opened 2020-09-11 08:55 UTC
**Describe the bug**
Hello,

Yesterday afternoon, we encountered a problem around VictoriaMetrics and more precisely around vminsert/vmstorage

I don't know why yet, but around 2:00 p.m utc. we can see error like this in vmstroage logs :
2020-09-10T14:00:11.067Z error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.49.130:53214: cannot read packet size: cannot read data from the underlying reader: read tcp4 10.42.49.141:8400->10.42.49.130:53214: read: connection reset by peer
2020-09-10T14:00:53.533Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.49.130:33096: cannot read packet with size 104857534: cannot read data from the underlying reader: read tcp4 10.42.36.57:8400->10.42.49.130:33096: read: connection reset by peer; read only 50987000 bytes
2020-09-10T14:01:11.377Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.71.254:35408: cannot read packet with size 104857528: cannot read data from the underlying reader: read tcp4 10.42.210.170:8400->10.42.71.254:35408: read: connection reset by peer; read only 96206840 bytes
2020-09-10T14:02:06.110Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.71.254:43420: cannot read packet with size 104857588: cannot read data from the underlying reader: read tcp4 10.42.49.141:8400->10.42.71.254:43420: read: connection reset by peer; read only 79167480 bytes
2020-09-10T14:02:14.625Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.71.254:60040: cannot read packet with size 104857536: cannot read data from the underlying reader: read tcp4 10.42.120.195:8400->10.42.71.254:60040: read: connection reset by peer; read only 46661624 bytes
2020-09-10T14:02:42.061Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.49.130:57018: cannot read packet with size 104857529: cannot read data from the underlying reader: read tcp4 10.42.210.170:8400->10.42.49.130:57018: read: connection reset by peer; read only 34209784 bytes
.....

and in vminsert logs, line like this

2020-09-10T14:25:26.960Z	warn	VictoriaMetrics/app/vminsert/main.go:154	error in "/insert/0/prometheus": cannot read prompb.WriteRequest: cannot read compressed request: read tcp4 10.42.137.82:8480->10.42.173.91:37336: read: connection reset by peer
2020-09-10T14:25:26.960Z	warn	VictoriaMetrics/app/vminsert/main.go:154	error in "/insert/0/prometheus": cannot read prompb.WriteRequest: cannot read compressed request: read tcp4 10.42.137.82:8480->10.42.173.91:37424: read: connection reset by peer
2020-09-10T14:25:26.960Z	warn	VictoriaMetrics/app/vminsert/main.go:154	error in "/insert/0/prometheus": cannot read prompb.WriteRequest: cannot read compressed request: read tcp4 10.42.137.82:8480->10.42.173.91:37352: read: connection reset by peer
2020-09-10T14:25:26.961Z	warn	VictoriaMetrics/app/vminsert/main.go:154	error in "/insert/0/prometheus": cannot read prompb.WriteRequest: cannot read compressed request: read tcp4 10.42.137.82:8480->10.42.173.91:37408: read: connection reset by peer

During this error, we lost about 20 prometheus instance in VictoriaMetrics. It takes 6 hour to recover 10 of them.
But we always have 10 prometheus instance missing in VictoriaMetrics and we don't know why. It seems Victoria is ok now (nothing in the logs)

Can you help us to investigate on our problem and help us to understand why some prometheus instance are missing in VictoriaMetrics ?
Let me know if you want some graph metrics.

**Additional context**
- 4 vminsert 4CPU and 8Go ram
- 4 vmselect 4CPU and 8Go ram
- 4 vmstorage 4CPU and 21Go ram

v1.37.1-cluster

we have about 82 prometheus instance who send metrics to victoriametrics via remote_write
around 300 000 sample/s for 12 Million timeseries

Thanks
Regards
Guillaume

**Comment by guliangsi** [comment] 2020-09-11 09:55
On the VictoriaMetrics Dashboard, we can see strange things on graph rerouted from yesterday 2pm to now. It seems vmstorage4 rows are rerouted to the other vmstorage. However vmstorage4 logs don't show any error !

![rerouted_graph](https://user-images.githubusercontent.com/43655090/92907436-9e98c200-f425-11ea-9905-ea10eccac205.PNG)

**Comment by dxtrzhang** [comment] 2020-09-11 10:17
data will be rerouted to another storage node if the target storage node is unavailable.  Is there any chance that the net connection is unstable or unavailable?

PS: the logs posted here seems not align to the timeline, could you plz update the log?

**Comment by guliangsi** [comment] 2020-09-11 11:21
Hi @dxtrzhang thanks for your response.

At the beginning of the problem (yesterday around 2:00 pm or 14h00) I cannot certify that the network was stable. But currently, vminserts seems to be able to join vmstorage without problem. However, the vmstorage4 reroute the rows to the others

Could the reroute be the cause of our current problem (some prometheus missing in Victoriametrics) ?

for me the logs are align to the timeline graph. In the logs : the problem occured around 2020-09-10T14:00:53.533Z. And on the graph rerouted, the first datapoint is around 2020-09-10T13:57:15.000Z

Thanks

**Comment by valyala** [comment] 2020-09-11 12:40
Error logs mentioned above may be related to unstable network around 14:00 on 2020-09-10. So `vmstorage` couldn't read full data  packets from `vminsert`. This is usually OK - `vminsert` should retry sending failed data packets either to the current `vmstorage` node or to other `vmstorage` nodes if the current one is temporarily unavailable. It looks like `vmstorage4` became unavailable or started working slowly after 14:00 on 2020-09-10 and didn't recover till 10:00 on 2020-09-11 according to `rerouted from` graph. Could you verify whether `vmstorage4` can be reached from `vminsert` nodes? Could you verify error logs for `vmstorage4` node? Try restarting all the `vminsert` nodes and check whether this helps resolving the issue.

It is also recommended upgrading all the cluster components to [the latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since it may contain fixes for bugs discovered since `v1.37.1-cluster`.

**Comment by dxtrzhang** [comment] 2020-09-11 13:09
According to the logs provided:
1. vmstorage logs show that it can not read data from the connection between vmstorage and vminsert
2. vminsert logs show that it cant not read data fron the connetion between vminsert and promethes remote_write

Q: Do you deploy the vmstorage and vminsert at one machine? If so, network must be a positive reason.

---
About the reroute, could you please provide the `Ingestion rate (All)` panel of official vm dashboard, see https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#monitoring

**Comment by guliangsi** [comment] 2020-09-11 13:54
Hello @valyala 

now, vmstorage4 can be reached from vminsert nodes without problem. i can't say if it was yesterday
I attached an extract of the vmstorage4 logs and there are errors like : 

2020-09-10T14:00:11.067Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.49.130:53214: cannot read packet size: cannot read data from the underlying reader: read tcp4 10.42.49.141:8400->10.42.49.130:53214: read: connection reset by peer
2020-09-10T14:03:35.340Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.4.116:42912: cannot flush `ack` to vminsert: write tcp4 10.42.49.141:8400->10.42.4.116:42912: write: broken pipe
2020-09-10T14:03:35.340Z	error	VictoriaMetrics/app/vmstorage/transport/server.go:166	cannot process vminsert conn from 10.42.4.116:42912: cannot flush `ack` to vminsert: write tcp4 10.42.49.141:8400->10.42.4.116:42912: write: broken pipe

from all the vminsert ip.

The current situation is :
	we stopped about 30 prometheus from dev env at 14:15
	following the end of these 30 prometheus, reroute from vmstorage4 is now ok. As you can see on the graph, the reroute from vmstorage4 to vmstorage1/2/3 stopped at 14:15

![reroute_OK](https://user-images.githubusercontent.com/43655090/92933476-956c1d00-f446-11ea-9345-3730fcbe35ee.PNG)

Is there something that can explain this phenomenon ?
	
We also planned to upgrade to last version of victoriametrics !

@dxtrzhang 

No, the vmstorage and the vminsert are not on the same machine. Those are docker containers managed by an orchestrator (Rancher) with host affinity. The dns resolution and communication between vminsert and vmstorage are internal to the stack VictoriaMetrics on Rancher, no external resolution and no external routing.

I provide the Ingestion rate (All) panel
You can see at 09/10 14:00, that we lost data ingestion. About 15min later, the ingestion restart, but we lost 100k. And since this error we never recover the ingestion rate at 300K. Some data of prometheus instance prod never arrived in VictoriaMetrics
We have to stopped a lot of prometheus dev instance, to recover this prometheus prod instance. whereas in normal times we have no problem to ingest 300K.

![ingestion_rate](https://user-images.githubusercontent.com/43655090/92933565-af0d6480-f446-11ea-95b1-19a8eb073ec8.PNG)

What can explain this ?

Thanks you for your help both
Regards
Guillaume

[logs_vmstroage4.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/5209413/logs_vmstroage4.txt)

**Comment by valyala** [comment] 2020-09-11 22:01
Rerouting is enabled in the following cases:
* If certain `vmstorage` node is temporarily unavailable. The the data is re-routed to the remaining healthy `vmstorage` nodes.
* If certain `vmstorage` node cannot keep up with the ingestion rate. Then the data is re-routed to other `vmstorage` node in the hope they have better performance. If this isn't the case, i.e. if all the `vmstorage` nodes are saturated with data ingestion, then the data will be re-routed at high pace between all the available `vmstorage` nodes. In this case the cluster data ingestion capacity must be increased in order to return it to steady state. This can be made by adding more `vmstorage` and/or `vminsert` nodes - see [capacity planning docs](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#capacity-planning) for more details.

As for your case, it definitely shows that only `vmstorage4` couldn't keep up with data ingestion, while it still was accepting data at slightly lower speed comparing to the remaining `vmstorage` nodes according to `ingestion rate` graph above. This graph looks suspicious, since all the `vmstorage` nodes started accepting data at lower ingestion rate starting from 14:00 9/10 . Could you look at `vminsert` graphs on the dashboard? Probably, certain `vminsert` nodes were unavailable during this time, which led to degraded data ingestion performance. Or, probably, incoming connnections from Prometheus instances weren't balanced evenly among all the available `vminsert` nodes at this time.

**Comment by dxtrzhang** [comment] 2020-09-12 02:30
> As for your case, it definitely shows that only vmstorage4 couldn't keep up with data ingestion, while it still was accepting data at slightly lower speed comparing to the remaining vmstorage nodes according to ingestion rate graph above. This graph looks suspicious, since all the vmstorage nodes started accepting data at lower ingestion rate starting from 14:00 9/10 

It actually happens every time when we restart/stop one of the storage node(or one of the node's ingestion rate is low), I guess It may   caused by the reroute, because the reroute happens not only at the stopped(low ingestion rate) node, but also basically every storage node. 

What we did here is restarting one of the storage node
![image](https://user-images.githubusercontent.com/13900390/92984984-2b548600-f4e1-11ea-8e5b-6410ece6427b.png)
The request rate decrease because data was pended at vmagent
![image](https://user-images.githubusercontent.com/13900390/92985025-825a5b00-f4e1-11ea-9e3a-8246c08a7d4e.png)
When this happens, IO  usage and `vm_rows{type="indexdb"}` climbed rapidly
![image](https://user-images.githubusercontent.com/13900390/92985125-5be8ef80-f4e2-11ea-8626-3a65d39b9f60.png)

Maybe the reroute mechanism inserts some “new data(for nodes that the data rerouted to)” to the healthy node, and the node's index data increase, which cause the high IO and slow the data ingestion. Then this node is seen as "low ingestion rate" and data got rerouted to other healthy nodes and so on...   

Does this sound reasonable to you? @valyala

**Comment by guliangsi** [comment] 2020-09-14 08:28
@valyala 
The vminsert graph on the dashboard show a peak on Concurrent inserts at the begining of the problem (14:00) to 175, whereas in normal timeswe are around 3 ! To recover a normal concurrent tasks, we have stopped a lot of prometheus instance. 

![vminserts_graph](https://user-images.githubusercontent.com/43655090/93061908-81a5fe00-f674-11ea-94be-8d472e49babe.PNG)

What can explain this ?

Our remote_write config is the same on all our prometheus instance :
    queue_config:
      capacity: 50000
      max_samples_per_send: 10000
      max_shards: 10

Is this correct, or can we adjust this settings in function of the rate of each prometheus instance ?

Thank you for your help
Regards
Guillaume

**Comment by guliangsi** [comment] 2020-09-14 08:46
the previous zoomed graph

![vminserts_graph_zoom](https://user-images.githubusercontent.com/43655090/93064151-7d2f1480-f677-11ea-9c8a-ef5412b833d3.PNG)

**Comment by dxtrzhang** [comment] 2020-09-15 06:17
Actually when the data ingestion rate is low, concurrent inserts will increase. It is probably a phenomenon, not the cause. @guliangsi

**Comment by valyala** [comment] 2020-11-30 22:39
@guliangsi , @dxtrzhang , could you upgrade all the cluster components to [the latest release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and verify whether this fixes the issue? It is safe upgrading from any older release directly to the latest release. There could be some error logs during the upgrade process - these logs should stop as soon as all the cluster components are upgraded. These errors shouldn't affect data ingestion.

**Comment by guliangsi** [comment] 2020-12-01 07:47
@valyala Yes! we are planning to upgrade to the latest version (v1.40.1 to v1.48.0) tomorrow night! We very much hope that this corrects our problem, we have seen it twice since this issue and each time it's very difficult to restore the situation. I keep you informed !

Thanks

**Comment by dxtrzhang** [comment] 2020-12-04 12:23
@valyala we are pretty sure that the reroute cause the the situation I described above, and we actually open a issue about this, see #791 for detail.

**Comment by valyala** [comment] 2022-02-07 14:48
The next version of VictoriaMetrics will contain improved logic for data re-routing in the event if some of vmstorage nodes are temporarily unavailable or if some of vmstorage nodes temporarily slow down the processing speed for incoming data. The following improvements will be included in the next release of VictoriaMetrics cluster:
* Even series distribution among the remaining vmstorage nodes. Previously some vmstorage nodes could start receiving multiple times more series than other vmstorage nodes if some vmstorage nodes were unavailable or were slower than other vmstorage nodes.
* Reduced the maximum increase in the number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) on the remaining vmstorage nodes after some vmstorage nodes become unavailable or become slow. It will be limited by 100% of the initial number of active time series per vmstorage node in the worst case (e.g. when vmstorage nodes have no enough resources to keep up with the increased load). Under normal conditions the increase in the number of active time series shouldn't exceed `1/N` of the initial number of active time series per vmstorage node, where `N` is the number of `vmstorage` nodes in the cluster. Previously the typical increase in the number of time series per vmstorage node after the re-routing was closer to 100%, while in the worst case it could reach `(N-1)`x.
* The placement of time series among `vmstorage` nodes doesn't depend on the order of `vmstorage` addresses passed to `-storageNode` command-line flag at `vminsert` nodes thanks to the changed consistent hashing algorithm (from [jump hash](https://arxiv.org/abs/1406.2294) to [rendezvous hash](https://www.eecs.umich.edu/techreports/cse/96/CSE-TR-316-96.pdf) ). Previously samples for the same time series could be placed to multiple `vmstorage` nodes if multiple `vminsert` nodes had different order of `vmstorage` nodes passed to `-storageNode` command-line flag. This could result in increased number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series) across all the vmstorage nodes, which, in turn, could result in higher resource usage (RAM, CPU, disk IO, disk space) at `vmstorage` nodes.

These improvements should improve the stability of the mode with enabled rerouting in the cluster (e.g. when `-disableRerouting=false` command-line flag is passed to `vminsert`. The re-routing is disabled by default starting from [v1.66.0](https://docs.victoriametrics.com/CHANGELOG.html#v1660) ).

The next release of VictoriaMetrics also adds an ability to drop incoming samples if vmstorage nodes are temporarily unavailable and/or overloaded if `-dropSamplesOnOverload` command-line flag is passed to `vminsert` nodes. By default vminsert slows down accepting new samples if vmstorage cannot keep up with the ingestion rate. This may result in increased number of pending samples at client side, which sends data to vminsert. This increases the delay between samples' generation and samples' ingestion into vmstorage. This may result in incomplete query results, which rely on recently ingested data (e.g. alerting and recording rules). In this case the `-dropSamplesOnOverload` mode may help receiving the most recently generated samples at the cost of dropping older samples. The number of dropped samples is tracked in per-`vmstorage` counter at `vminsert` nodes - `vm_rpc_rows_dropped_on_overload_total` . See more details at [changelog](https://docs.victoriametrics.com/CHANGELOG.html).

The features mentioned above can be tested by building cluster components of VictoriaMetrics from the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster) (currently this is 755e26e67b44962bada3a427e114d3f6ae284b5b ) according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337 .

**Comment by valyala** [comment] 2023-02-21 02:18
Closing this issue as outdated. @guliangsi , if the issue is still can be reproduced in the [latest release](https://docs.victoriametrics.com/CHANGELOG.html), then please open a new bugreport and mention this one there.

**Closed by valyala** 2023-02-21 02:18 UTC
Labels: need more info
