### ISSUE TITLE
record vmselect data display problem

### ISSUE THREAD

**Issue by jicki** [VictoriaMetrics/VictoriaMetrics#6351] opened 2024-05-27 07:27 UTC
### Describe the bug

vmselect  query  

![img_v3_02b9_16d468ae-bb1f-4446-9daa-cbcf08bd58cg](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/5d3b60cc-1fc7-4b34-baae-ea9edd4e07eb)

![img_v3_02b9_43ef9cf2-bc71-419b-a2a7-1a0c046150cg](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/9caf5fe5-d0b4-4825-aafb-91a0950ae5ca)

### To Reproduce

```
sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (node) / sum(kube_node_status_allocatable{resource="cpu"}) by (node)
```

### Version

./vmselect-prod --version
vmselect-20240425-150446-tags-v1.101.0-cluster-0-g310d100ed

**Comment by jicki** [comment] 2024-05-30 01:11
@Loori-R

**Comment by Loori-R** [comment] 2024-06-03 15:28
Hi @jicki, The issue with data not displaying on the first screenshot is due to the 3-minute step interval, which causes data averaging. Try reducing the step interval to 1 minute or less to get more detailed data. For more information on how the step interval works, refer to the documentation [here](https://docs.victoriametrics.com/keyconcepts/#range-query).

**Comment by jicki** [comment] 2024-06-04 06:40
> Hi @jicki, The issue with data not displaying on the first screenshot is due to the 3-minute step interval, which causes data averaging. Try reducing the step interval to 1 minute or less to get more detailed data. For more information on how the step interval works, refer to the documentation [here](https://docs.victoriametrics.com/keyconcepts/#range-query).

I encountered this issue even when setting the step to 1m in my tests. Currently, I've found that the problem does not occur when the interval configuration of the recording rule is set close to the scrapeInterval.

**Comment by Loori-R** [comment] 2024-06-04 09:57
@dmitryk-dk @hagen1778 Could you share some thoughts here?

**Comment by hagen1778** [comment] 2024-06-04 10:47
Hey @jicki !
Do you face the same behavior for raw query or only for recording rule? What is the interval of this recording rule? Could you please share the full list of cmd-line flags of your vmselect?

**Comment by jicki** [comment] 2024-06-04 10:56
> Hey @jicki ! Do you face the same behavior for raw query or only for recording rule? What is the interval of this recording rule? Could you please share the full list of cmd-line flags of your vmselect?

only for recording rule

recording rule interval 3m 


```
sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests) by (node) / sum(kube_node_status_allocatable{resource="cpu"}) by (node)
```

* record
```
    - expr: |-
        kube_pod_container_resource_requests{resource="cpu",job="kube-state-metrics"}  * on (namespace, pod, cluster)
        group_left() max by (namespace, pod, cluster) (
          (kube_pod_status_phase{phase=~"Pending|Running"} == 1)
        )
      record: cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests
```

**Comment by jicki** [comment] 2024-06-04 11:00
This problem does not necessarily occur. You need to repeat the query multiple times to cause this problem.

**Comment by hagen1778** [comment] 2024-06-04 11:19
@jicki what about this?

>  Could you please share the full list of cmd-line flags of your vmselect?

Could you also repeat your queries multiple time with cache disabled in vmui (see a toggle below query area)?

**Comment by jicki** [comment] 2024-06-05 00:54
> @jicki what about this?
> 
> > Could you please share the full list of cmd-line flags of your vmselect?
> 
> Could you also repeat your queries multiple time with cache disabled in vmui (see a toggle below query area)?


![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/722df5a1-c9e1-4c7a-9e80-31c434ad346d)

**Comment by jicki** [comment] 2024-06-05 00:56
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/859afa3f-197c-440e-a338-8adc894ed4d8)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/8ec557a1-37cd-45ab-b994-2e9674c8bfaa)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/5209eab3-f2d9-4444-9e06-cd9382fedb3b)

**Comment by hagen1778** [comment] 2024-06-05 07:35
@jicki thanks for the screenshots.
But could you please answer on the question below? Please note, I'll asked for it 3 times already.

> Could you please share the full list of cmd-line flags of your vmselect?

**Comment by jicki** [comment] 2024-06-05 07:56
> @jicki thanks for the screenshots. But could you please answer on the question below? Please note, I'll asked for it 3 times already.
> 
> > Could you please share the full list of cmd-line flags of your vmselect?

I'm so sorry, I overlooked it.

```
/vmselect-prod -cacheDataPath=/select-cache -dedup.minScrapeInterval=15s -httpListenAddr=:8481 -replicationFactor=2 -search.logSlowQueryDuration=2m -search.maxConcurrentRequests=64 -search.maxLabelsAPISeries=2000000 -search.maxPointsPerTimeseries=500000 -search.maxQueryDuration=5m -search.maxQueryLen=100000 -search.maxQueueDuration=1m -search.maxSamplesPerQuery=5000000000 -search.maxSeries=500000 -search.maxUniqueTimeseries=20000000 -selectNode=vmselect-victoria-metrics-cluster-0.vmselect-victoria-metrics-cluster.monitor-system:8481,vmselect-victoria-metrics-cluster-1.vmselect-victoria-metrics-cluster.monitor-system:8481 -storageNode=vmstorage-victoria-metrics-cluster-0.vmstorage-victoria-metrics-cluster.monitor-system:8401,vmstorage-victoria-metrics-cluster-1.vmstorage-victoria-metrics-cluster.monitor-system:8401,vmstorage-victoria-metrics-cluster-2.vmstorage-victoria-metrics-cluster.monitor-system:8401,vmstorage-victoria-metrics-cluster-3.vmstorage-victoria-metrics-cluster.monitor-system:8401 -vmalert.proxyURL=http://vmalert-victoria-metrics-cluster.monitor-system:8080 -vmstorageDialTimeout=10s -vmui.defaultTimezone=Asia/Shanghai
```

**Comment by hagen1778** [comment] 2024-06-11 10:21
Thanks @jicki ! The config looks good to me! Could you please [export](https://docs.victoriametrics.com/#how-to-export-time-series) last 1h of raw samples for time series produced by your rule (please export with `reduce_mem_usage=1` param)?

I wasn't able to reproduce the issue. So far my assumptions are the following:
1. Something weird happens during deduplication, maybe samples collide for some reason
2. The expression for this recording rule doesn't return samples on each execution. If expression returns nothing in response, vmalert will mark series as stale. And stale series aren't automatically prolonged. You can check if this is true in vmalert's UI - see https://docs.victoriametrics.com/vmalert/#alerts-state

**Comment by jicki** [comment] 2024-06-12 01:29
@hagen1778 

Sorry, I have never used the export function before. Could you provide an example of how I would use the export interface to export raw data?

vmalert UI:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/6f0fd6fc-f045-4cfb-90d2-d7a066d2dfb2)

**Comment by hagen1778** [comment] 2024-06-12 05:59
> Sorry, I have never used the export function before. Could you provide an example of how I would use the export interface to export raw data?

```
curl http://<vmselect-addr>:8481/select/0/prometheus/api/v1/export -d 'match[]=[up](cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests)' -d 'start=-60m' -d 'reduce_mem_usage=1'
```

See https://docs.victoriametrics.com/url-examples/#apiv1export

**Comment by jicki** [comment] 2024-06-12 07:49
```bash
curl http://vmselect-victoria-metrics-cluster:8481/select/0/prometheus/api/v1/export -d 'match[]=apiserver_request:burnrate5m' -d 'start=-60m' -d 'reduce_mem_usage=1'
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000019513257115345002,0,0,0.00000000000000019550841119700002,-0.000000000000000195096852213],"timestamps":[1718175060000,1718175240000,1718175420000,1718175600000,1718175780000,1718175960000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000039130393892249006,0.000000000000000195061146347,0.00000000000000019472259132900002,0.000000000000000195454631146,0,0.00000000000000019635484591749002,0.00000000000000019590370437278,0,0,-0.00000000000000019458039317939001,0.00000000000000019550841119700002],"timestamps":[1718176140000,1718176320000,1718176500000,1718176680000,1718176860000,1718177040000,1718177220000,1718177400000,1718177580000,1718177760000,1718177940000,1718178120000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0],"timestamps":[1718178300000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000019513257115345002,0],"timestamps":[1718175060000,1718175240000,1718175420000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000019550841119700002,-0.000000000000000195096852213,0,0.00000000000000039130393892249006,0.000000000000000195061146347,0.00000000000000019472259132900002,0.000000000000000195454631146,0],"timestamps":[1718175600000,1718175780000,1718175960000,1718176140000,1718176320000,1718176500000,1718176680000,1718176860000,1718177040000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0.00000000000000019635484591749002,0.00000000000000019590370437278,0],"timestamps":[1718177220000,1718177400000,1718177580000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,-0.00000000000000019458039317939001],"timestamps":[1718177760000,1718177940000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0.000000000000000195508411197],"timestamps":[1718178120000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0],"timestamps":[1718178300000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000015331042917723002,0.00000000000000016010426673278001,-0.00000000000000015547981088842],"timestamps":[1718175060000,1718175240000,1718175420000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[-0.00000000000000015469000052832002,0.00000000000000015986412234000002,0.000000000000000161096448555,0.00000000000000015604891707762002,0.00000000000000031996820883800003,0.00000000000000016012832085939,0,0,0],"timestamps":[1718175600000,1718175780000,1718175960000,1718176140000,1718176320000,1718176500000,1718176680000,1718176860000,1718177040000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000014848343600447002,0.00000000000000014931550905577,0.00000000000000015671432195855],"timestamps":[1718177220000,1718177400000,1718177580000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000016000812245,0],"timestamps":[1718177760000,1718177940000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000032006429538743004],"timestamps":[1718178120000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0],"timestamps":[1718178300000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000015331,0.000000000000000160104,-0.000000000000000155479,-0.00000000000000015469,0.000000000000000159864,0.000000000000000161096,0.000000000000000156048],"timestamps":[1718175060000,1718175240000,1718175420000,1718175600000,1718175780000,1718175960000,1718176140000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000031996820883800003,0.00000000000000016012832085939,0,0,0,0.00000000000000014848343600447002,0.00000000000000014931550905577,0.00000000000000015671432195855,0.00000000000000016000812245,0,0.00000000000000032006429538743004],"timestamps":[1718176320000,1718176500000,1718176680000,1718176860000,1718177040000,1718177220000,1718177400000,1718177580000,1718177760000,1718177940000,1718178120000]}
{"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0],"timestamps":[1718178300000]}

```

**Comment by jicki** [comment] 2024-06-12 07:50
@hagen1778   Thank you very much for the example you provided.

> ```shell
> curl http://vmselect-victoria-metrics-cluster:8481/select/0/prometheus/api/v1/export -d 'match[]=apiserver_request:burnrate5m' -d 'start=-60m' -d 'reduce_mem_usage=1'
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000019513257115345002,0,0,0.00000000000000019550841119700002,-0.000000000000000195096852213],"timestamps":[1718175060000,1718175240000,1718175420000,1718175600000,1718175780000,1718175960000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000039130393892249006,0.000000000000000195061146347,0.00000000000000019472259132900002,0.000000000000000195454631146,0,0.00000000000000019635484591749002,0.00000000000000019590370437278,0,0,-0.00000000000000019458039317939001,0.00000000000000019550841119700002],"timestamps":[1718176140000,1718176320000,1718176500000,1718176680000,1718176860000,1718177040000,1718177220000,1718177400000,1718177580000,1718177760000,1718177940000,1718178120000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0],"timestamps":[1718178300000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000019513257115345002,0],"timestamps":[1718175060000,1718175240000,1718175420000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,0.00000000000000019550841119700002,-0.000000000000000195096852213,0,0.00000000000000039130393892249006,0.000000000000000195061146347,0.00000000000000019472259132900002,0.000000000000000195454631146,0],"timestamps":[1718175600000,1718175780000,1718175960000,1718176140000,1718176320000,1718176500000,1718176680000,1718176860000,1718177040000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0.00000000000000019635484591749002,0.00000000000000019590370437278,0],"timestamps":[1718177220000,1718177400000,1718177580000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0,-0.00000000000000019458039317939001],"timestamps":[1718177760000,1718177940000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0.000000000000000195508411197],"timestamps":[1718178120000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"read"},"values":[0],"timestamps":[1718178300000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000015331042917723002,0.00000000000000016010426673278001,-0.00000000000000015547981088842],"timestamps":[1718175060000,1718175240000,1718175420000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[-0.00000000000000015469000052832002,0.00000000000000015986412234000002,0.000000000000000161096448555,0.00000000000000015604891707762002,0.00000000000000031996820883800003,0.00000000000000016012832085939,0,0,0],"timestamps":[1718175600000,1718175780000,1718175960000,1718176140000,1718176320000,1718176500000,1718176680000,1718176860000,1718177040000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000014848343600447002,0.00000000000000014931550905577,0.00000000000000015671432195855],"timestamps":[1718177220000,1718177400000,1718177580000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000016000812245,0],"timestamps":[1718177760000,1718177940000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000032006429538743004],"timestamps":[1718178120000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0],"timestamps":[1718178300000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000015331,0.000000000000000160104,-0.000000000000000155479,-0.00000000000000015469,0.000000000000000159864,0.000000000000000161096,0.000000000000000156048],"timestamps":[1718175060000,1718175240000,1718175420000,1718175600000,1718175780000,1718175960000,1718176140000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0.00000000000000031996820883800003,0.00000000000000016012832085939,0,0,0,0.00000000000000014848343600447002,0.00000000000000014931550905577,0.00000000000000015671432195855,0.00000000000000016000812245,0,0.00000000000000032006429538743004],"timestamps":[1718176320000,1718176500000,1718176680000,1718176860000,1718177040000,1718177220000,1718177400000,1718177580000,1718177760000,1718177940000,1718178120000]}
> {"metric":{"__name__":"apiserver_request:burnrate5m","cluster":"dev-k8s-cluster","verb":"write"},"values":[0],"timestamps":[1718178300000]}
> ```

**Comment by hagen1778** [comment] 2024-06-12 10:11
Thanks for the data!
@jicki can you reproduce this issue if you set time range interval in vmui to last 1h?
Why I'm asking is because of https://docs.victoriametrics.com/keyconcepts/#range-query
> Sometimes, the lookbehind window for locating the datapoint isn’t big enough and the graph will contain a gap. For range queries, lookbehind window isn’t equal to the step parameter. It is calculated as the median of the intervals between the first 20 raw samples in the requested time range. In this way, VictoriaMetrics automatically adjusts the lookbehind window to fill gaps and detect stale series at the same time.

So in order to automatically calculate the staleness interval VM needs at least 20 samples and calculate median distance between these samples. Since you have 3m eval interval, this will require 20*3m = 60m time interval for auto staleness to work.
If VM doesn't have 20 samples, it uses `step`, which is 1m on your screenshots.

Alternatively, you can set `-search.maxStalenessInterval=3m` or higher (5m maybe) on the vmselect. This will force vmselect to always look back 5m back in time for the datapoint.

**Comment by hagen1778** [comment] 2024-06-18 09:24
Hey @jicki ! Did my recommendation help?

**Comment by jicki** [comment] 2024-06-18 10:34
@hagen1778   Thank you very much for your answer and help. After adding the parameters and testing it a few times, the issue hasn't reappeared. I will continue testing for a while.

**Comment by hagen1778** [comment] 2024-08-16 08:14
Closing this issue for now. Feel free to re-open if you still observe the problem.

**Closed by hagen1778** 2024-08-16 08:14 UTC
Labels: bug, need more info
