### ISSUE TITLE
label_uppercase() / lowercase()

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#936] opened 2020-12-03 02:19 UTC
**Is your feature request related to a problem? Please describe.**
We had a use case requiring label value transform to upper case.  Regex doesn't support it (some regex implementations have extension like `\U`).

As a workaround we used `label_map()` on all the individual values, but this only works because the set was bounded.

**Describe the solution you'd like**
functions `label_uppercase(q, label1, ... labelN)` and `label_lowercase(q, label1, ... labelN)`

**Comment by valyala** [comment] 2020-12-03 19:49
@belm0 , could you build VictoriaMetrics from the commit 66379cc69f0b6d4d5862d38e2d291565fbf20f74 according to [these docs](https://victoriametrics.github.io/#how-to-build-from-sources) and verify whether `label_uppercase()` and `label_lowercase()` functions work as intended there?

**Comment by belm0** [comment] 2020-12-04 11:35
I don't think I'll have time to build & run in advance, but I looked at the commit and the API and unit tests look good.  Thank you!

**Comment by valyala** [comment] 2020-12-05 13:20
`label_uppercase()` and `label_lowercase()` are available starting from [v1.49.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Closed by valyala** 2020-12-05 13:20 UTC
Labels: enhancement
