### ISSUE TITLE
Data compression on vmagent scraped data buffer

### ISSUE THREAD

**Issue by f4t** [VictoriaMetrics/VictoriaMetrics#1225] opened 2021-04-16 04:58 UTC
**Is your feature request related to a problem? Please describe.**
As vmagent documentation highlights, the scraped data buffer directory (from `-remoteWrite.tmpDataPath`) can grow large when remote storage is unavailable for extended periods of time, or scraping large numbers of targets.

**Describe the solution you'd like**
Having an option to enable compression on this temporary data buffer would be helpful to accomodate for cases where storage resource is limited on hosts running vmagent (at the cost of higher CPU utilization).

**Comment by valyala** [comment] 2021-04-16 10:19
vmagent stores data in `-remoteWrite.tmpDataPath` in [Prometheus remote_write format](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write), which represents a [snappy](https://en.wikipedia.org/wiki/Snappy_(compression))-compressed [protocol buffers](https://developers.google.com/protocol-buffers) - see [the corresponding protobuf definitions](https://github.com/prometheus/prometheus/tree/main/prompb). This means that the data is already compressed. The issue is that the Prometheus remote_write format has not so good compression ratio, because it stores full set of labels per each sample. There are plans to add a protocol for data transfer from vmagent to VictoriaMetrics with better compression ratio. This can reduce the size of data stored at `-remoteWrite.tmpDataPath`.

**Comment by f4t** [comment] 2021-04-16 16:18
Thanks for the explanation @valyala and great to hear this is in the pipe. Your plans go beyond what I was hoping for :)

**Comment by valyala** [comment] 2023-02-21 03:56
`vmagent` gains support for [VictoriaMetrics remote write protocol](https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol) in the commit 76f2c70be361c78c52d9fb76e03f4942871a1e9c . The first version of this protocol is very close to the original Prometheus remote write protocol - it just uses [zstd](https://github.com/facebook/zstd/) instead of [snappy](https://github.com/google/snappy) for data compression. This reduces egress network bandwidth usage and disk read/write IO by 2x-4x comparing to Prometheus remote write protocol on real-world production data. The `zstd` compression slightly increases CPU usage (by up to 10% on highly loaded `vmagent`).

The [VictoriaMetrics remote write protocol](https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol) can be enabled on a per-remote storage basis via `-remoteWrite.useVMProto=true` command-line flag. Note that this protocol will be supported only by [recent releases of VictoriaMetrics components](https://docs.victoriametrics.com/CHANGELOG.html). This protocol cannot be used for writing data to older releases of VictoriaMetrics components and to third-party remote storage systems.

The remote storage can detect VictoriaMetrics remote write v1 request by `X-VictoriaMetrics-Remote-Write-Version: 1` http header. In this case it must unpack the request body with `zstd` instead of `snappy`. Another approach is to check for `Content-Encoding: zstd` http header.

The VictoriaMetrics remote write protocol will supported by the following components in the next release:

- `vmagent` will be able to send data to `-remoteWrite.url` via VictoriaMetrics remote write protocol if `-remoteWrite.useVMProto` command-line flag is set
- `vmagent`, single-node VictoriaMetrics and `vminsert` will be able to accept data via VictoriaMetrics remote write protocol at `/api/v1/write` and `/insert/<tenantID>/prometheus/api/v1/write` endpoints (see [these(https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format) docs).

In the mean time is is possible to test the VictoriaMetrics remote write protocol by building VictoriaMetrics components from the latest commits in `master` and `cluster` branches as described [here](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment] 2023-02-24 01:53
The commit c080443fef1d7af47705ab8eeea724cb2efe2681 removes the `-remoteWrite.useVMProto` command-line flag - now `vmagent` automatically detects whether the remote storage supports [VictoriaMetrics remote write protocol](https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol). This simplifies the upgrade path for `vmagent` without the need to specify additional command-line flags.

The commit also introduces the `-remoteWrite.forcePromProto` command-line flag, which can be specified when the Prometheus remote write protocol should be used for sending the data to `-remoteWrite.url` even if the remote storage supports VictoriaMetrics remote write protocol.

**Comment by valyala** [comment] 2023-02-25 03:11
VictoriaMetrics components gain support for [VictoriaMetrics remote write protocol](https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol) starting from [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this feature request as done then.

**Closed by valyala** 2023-02-25 03:11 UTC
Labels: enhancement, vmagent
