### ISSUE TITLE
vmalert external.alert.source urlEncoding was incorrect

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/VictoriaMetrics#3139] opened 2022-09-21 09:13 UTC
vmalert external.alert.source configuration:
`-external.alert.source="explore?orgId=1&left=[\"now-1h\",\"now\",\"Prometheus-DEV\",{\"expr\": \"{{$expr|quotesEscape|crlfEscape|queryEscape}}\"},{\"mode\":\"Metrics\"},{\"ui\":[true,true,true,\"none\"]}]"
`

alert rule expr:
`ingress_nginx_request_qps{status=~"5\\d{2}"} / ignoring(status) group_left() sum without (status) (ingress_nginx_request_qps) * 100 > 1`

encoded url:
`https://grafana.example.com/explore?orgId=1&left=%7B%22datasource%22:%22Prometheus-DEV%22,%22queries%22:%5B%7B%22expr%22:%22ingress_nginx_request_qps%7Bstatus%3D~%5C%225%5C%5Cd%7B2%7D%5C%22%7D%20%2F%20ignoring(status)%20group_left()%20sum%20without%20(status)%20(ingress_nginx_request_qps)%20*%20100%5Cn%20%20%3E%201%5Cn%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D`

Grafana reported a syntax error:
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/28862139/191465010-eeb3a19d-1ce1-4fce-bcc0-41427e1b1577.png">

The expr in Grafana was different from alert rule expr.

**Comment by Howie59** [comment] 2022-09-28 12:47
does it means vmalert should not add Escape Character?

**Comment by dmitryk-dk** [comment] 2022-10-03 14:38
HI @Howie59 ! I think there is a problem with parsing the regexp expression.

**Comment by dmitryk-dk** [comment] 2022-10-03 14:39
There was a similar problem https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3131. But we should test vmalert

**Comment by okzheng** [comment] 2022-10-18 02:53
Any progress in this issue?

**Comment by dmitryk-dk** [comment] 2022-10-18 07:50
Hi @okzheng ! This issue is in backlog and will be fixed soon

**Comment by dmitryk-dk** [comment] 2022-10-27 08:49
Hi @okzheng ! You can build vmalert from this commit [5e855eab](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/00c838353d1246495fd7c7546f3d71095e855eab)

**Comment by valyala** [comment] 2022-10-27 22:00
The original issue is in the fact, that neither of the used template functions for `$expr` encoding - `quotesEscape`, `crlfEscape` and `queryEscape` - didn't escape the backslash at `{status=~"5\\d{2}"}` properly. So this filter was converted into `{status=~"5\d{2}"}` by Grafana before passing it to VictoriaMetrics. Then the VictoriaMetrics couldn't decode `\d` char sequence and returned the error.

The proper fix is implemented at a018b1d75ea638df62b53b331140a368c4071860 - it "upgrades" the `quotesEscape` function, so now it properly escapes all the chars and returns the resulting string, which can be safely embedded into JSON string. This makes obsolete the `crlfEscape` function, so it is advised to drop it everywhere in `vmalert` templating. Moreover, it is advised to use the newly added `jsonEscape` function instead of `quotesEscape` function when properly quoted JSON string must be generated. E.g. the output of `"{{ $expr | quotesEscape }}"` is equivalent to `{{ $expr | jsonEscape }}` - note that the `jsonEscape` template doesn't contain surrounding quotes, because they are added automatically.

The commit a018b1d75ea638df62b53b331140a368c4071860 also documents all the template functions supported by `vmalert` - see [these docs](https://docs.victoriametrics.com/vmalert.html#template-functions).

@okzheng , you can check whether this commit works as intended by building `vmalert` from this commit according to [these docs](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources). This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment] 2022-10-27 22:01
See the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/890

**Comment by valyala** [comment] 2022-10-29 01:38
The bugfix for the issue with improper backslash encoding has been included into [vmalert v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed then.

**Closed by valyala** 2022-10-29 01:38 UTC
Labels: bug, help wanted, vmalert

**Comment by valyala** [comment] 2022-11-11 00:17
FYI, the bugfix has been included in [v1.79.5 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.5).
