### ISSUE TITLE
Serve relevant data on the prometheus API endpoint `/api/v1/status/buildinfo`

### ISSUE THREAD

**Issue by lllamnyp** [VictoriaMetrics/VictoriaMetrics#5382] opened 2023-11-23 14:25 UTC
### Is your feature request related to a problem? Please describe

When Grafana tries to get promQL label values, most of the time it goes for the `/api/v1/series` endpoint. In large installations this is usually an expensive call which results in a 422 error suggesting an increase to the -search.max* flags. However, if the `/api/v1/label/<label_name>/values?match[]=<filters>` endpoint is used this turns out to be a much cheaper and more manageable call.

Unfortunately, Grafana chooses the appropriate endpoint based on the version of prometheus that it could discover at `/api/v1/status/buildinfo`. This is because prometheus did not support `match[]` query params in the label values endpoint (failing silently with a 200 OK, AFAIU) until 2.14x, neither did it serve the buildinfo prior to that. See this issue for details: https://github.com/grafana/grafana/issues/33487

Since vmselect serves a rather unhelpful `{"status":"success","data":{}}` response on the buildinfo endpoint, Grafana falls back to the older, less efficient API.

At the moment this issue can be worked around by explicitly specifying the "Prometheus Type" and "Version" in the datasource configuration.

### Describe the solution you'd like

I propose implementing a similar response in VictoriaMetrics which will let external systems correctly identify the type of server they are talking to. This will then let us push a feature request on Grafana's side to include VictoriaMetrics as a first-class citizen among the known Prometheus types, similar to the already included Cortex, Mimir, and Thanos.

**Comment by Amper** [comment] 2023-11-23 17:09
Duplicate of #5370

**Closed** 2023-11-23 19:32 UTC
Labels: enhancement
