### ISSUE TITLE
vmagent fails to scrape with tcp4 write broken pipe

### ISSUE THREAD

**Issue by amravyan** [VictoriaMetrics/VictoriaMetrics#1044] opened 2021-01-29 09:26 UTC
Hello. 
I've faced a stange issue with vmagent runnning inside k8s cluster (victoriametrics/vmagent:**v1.52.0**): it returns error _write tcp4 write broken pipe_ during scraping only fluent-bit metrics port on all cluster nodes.
curl forks fast and fine, screenshot is attached.
Downgrading to **v1.51.0** fixes issue.

![curl](https://user-images.githubusercontent.com/34545055/106256894-eda48f80-622c-11eb-9ec9-0ecb233bc86a.jpg)
<img width="1899" alt="failed_target" src="https://user-images.githubusercontent.com/34545055/106256910-f09f8000-622c-11eb-985a-8c19e8194386.png">

**Comment by hagen1778** [comment] 2021-01-29 22:47
@f41gh7 could this be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/987 ?

**Comment by f41gh7** [comment] 2021-01-30 20:45
Not sure,  can you try version from the master branch? There was one bug fix. 

 Also, try to use `promscrape.streamParse` for vmagent, does it help?

**Comment by valyala** [comment] 2021-02-03 19:47
This issue should be fixed in the commit 8cea3c3cc49c3c65b39b27dc8943aae070c8a85d , which is included in [v1.53.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)

**Comment by valyala** [comment] 2021-02-03 19:48
@amravyan , could you verify whether the issue is fixed in `vmagent` v1.53.0?

**Comment by amravyan** [comment] 2021-02-04 09:40
> @amravyan , could you verify whether the issue is fixed in `vmagent` v1.53.0?

Hello!
Tried v1.53.0 and yes, looks like the problem is fixed. Thanks a lot.

**Comment by valyala** [comment] 2021-02-04 16:19
@amravyan , thanks for the update! Closing the issue then.

**Closed by valyala** 2021-02-04 16:19 UTC
Labels: bug, vmagent
