### ISSUE TITLE
VMalert: record rule error

### ISSUE THREAD

**Issue by kevinvirs** [VictoriaMetrics/VictoriaMetrics#1293] opened 2021-05-13 07:49 UTC
**Describe the bug**
VMalert generated error every 3min:
```
2021-05-13T06:20:44.457Z        error   VictoriaMetrics/app/vmalert/group.go:250        group "kube-apiserver-availability.rules": rule "code_verb:apiserver_request_total:increase30d": failed to execute: result contains metrics with the same labelset after applying rule labels
2021-05-13T06:23:44.558Z        error   VictoriaMetrics/app/vmalert/group.go:250        group "kube-apiserver-availability.rules": rule "code_verb:apiserver_request_total:increase30d": failed to execute: result contains metrics with the same labelset after applying rule labels
2021-05-13T06:26:44.487Z        error   VictoriaMetrics/app/vmalert/group.go:250        group "kube-apiserver-availability.rules": rule "code_verb:apiserver_request_total:increase30d": failed to execute: result contains metrics with the same labelset after applying rule labels
```
used by with this [rules](https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-availability.rules.yaml) or [equivalent from prometheus](https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/master/manifests/kubernetes-prometheusRule.yaml)

**To Reproduce**
install [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)

**Expected behavior**
code_verb:apiserver_request_total:increase30d must have data, but now is empty

**Version**
```
build version: vmalert-20210501-071339-tags-v1.59.0-0-gfb097ff77
```

**Used command-line flags**
```
flag{name="datasource.appendTypePrefix", value="false"} 1
flag{name="datasource.basicAuth.password", value="secret"} 1
flag{name="datasource.basicAuth.username", value=""} 1
flag{name="datasource.lookback", value="0s"} 1
flag{name="datasource.maxIdleConnections", value="100"} 1
flag{name="datasource.queryStep", value="0s"} 1
flag{name="datasource.tlsCAFile", value=""} 1
flag{name="datasource.tlsCertFile", value=""} 1
flag{name="datasource.tlsInsecureSkipVerify", value="false"} 1
flag{name="datasource.tlsKeyFile", value="secret"} 1
flag{name="datasource.tlsServerName", value=""} 1
flag{name="datasource.url", value="http://vmsingle-vm-victoria-metrics-k8s-stack.monitoring.svc:8429"} 1
flag{name="dryRun", value="false"} 1
flag{name="enableTCP6", value="false"} 1
flag{name="envflag.enable", value="false"} 1
flag{name="envflag.prefix", value=""} 1
flag{name="evaluationInterval", value="15s"} 1
flag{name="external.alert.source", value=""} 1
flag{name="external.label", value="cluster=cluster-name} 1
flag{name="external.url", value=""} 1
flag{name="fs.disableMmap", value="false"} 1
flag{name="http.connTimeout", value="2m0s"} 1
flag{name="http.disableResponseCompression", value="false"} 1
flag{name="http.idleConnTimeout", value="1m0s"} 1
flag{name="http.maxGracefulShutdownDuration", value="7s"} 1
flag{name="http.pathPrefix", value=""} 1
flag{name="http.shutdownDelay", value="0s"} 1
flag{name="httpAuth.password", value="secret"} 1
flag{name="httpAuth.username", value=""} 1
flag{name="httpListenAddr", value=":8080"} 1
flag{name="loggerDisableTimestamps", value="false"} 1
flag{name="loggerErrorsPerSecondLimit", value="0"} 1
flag{name="loggerFormat", value="default"} 1
flag{name="loggerLevel", value="INFO"} 1
flag{name="loggerOutput", value="stderr"} 1
flag{name="loggerTimezone", value="UTC"} 1
flag{name="loggerWarnsPerSecondLimit", value="0"} 1
flag{name="memory.allowedBytes", value="0"} 1
flag{name="memory.allowedPercent", value="60"} 1
flag{name="metricsAuthKey", value="secret"} 1
flag{name="notifier.basicAuth.password", value="secret"} 1
flag{name="notifier.basicAuth.username", value=""} 1
flag{name="notifier.tlsCAFile", value=""} 1
flag{name="notifier.tlsCertFile", value=""} 1
flag{name="notifier.tlsInsecureSkipVerify", value=""} 1
flag{name="notifier.tlsKeyFile", value="secret"} 1
flag{name="notifier.tlsServerName", value=""} 1
flag{name="notifier.url", value="http://vmalert-vm-victoria-metrics-k8s-stack.monitoring.svc::9093"} 1
flag{name="pprofAuthKey", value="secret"} 1
flag{name="remoteRead.basicAuth.password", value="secret"} 1
flag{name="remoteRead.basicAuth.username", value=""} 1
flag{name="remoteRead.lookback", value="1h0m0s"} 1
flag{name="remoteRead.tlsCAFile", value=""} 1
flag{name="remoteRead.tlsCertFile", value=""} 1
flag{name="remoteRead.tlsInsecureSkipVerify", value="false"} 1
flag{name="remoteRead.tlsKeyFile", value="secret"} 1
flag{name="remoteRead.tlsServerName", value=""} 1
flag{name="remoteRead.url", value="http://vmsingle-vm-victoria-metrics-k8s-stack.monitoring.svc:8429"} 1
flag{name="remoteWrite.basicAuth.password", value="secret"} 1
flag{name="remoteWrite.basicAuth.username", value=""} 1
flag{name="remoteWrite.concurrency", value="1"} 1
flag{name="remoteWrite.flushInterval", value="5s"} 1
flag{name="remoteWrite.maxBatchSize", value="1000"} 1
flag{name="remoteWrite.maxQueueSize", value="100000"} 1
flag{name="remoteWrite.tlsCAFile", value=""} 1
flag{name="remoteWrite.tlsCertFile", value=""} 1
flag{name="remoteWrite.tlsInsecureSkipVerify", value="false"} 1
flag{name="remoteWrite.tlsKeyFile", value="secret"} 1
flag{name="remoteWrite.tlsServerName", value=""} 1
flag{name="remoteWrite.url", value="http://vmsingle-vm-victoria-metrics-k8s-stack.monitoring.svc:8429"} 1
flag{name="rule", value="/etc/vmalert/config/vm-vm-victoria-metrics-k8s-stack-rulefiles-0/*.yaml"} 1
flag{name="rule.validateExpressions", value="true"} 1
flag{name="rule.validateTemplates", value="true"} 1
flag{name="tls", value="false"} 1
flag{name="tlsCertFile", value=""} 1
flag{name="tlsKeyFile", value="secret"} 1
flag{name="version", value="false"} 1
```

**Comment by valyala** [comment] 2021-05-14 14:40
@hagen1778 , @f41gh7 , the `code_verb:apiserver_request_total:increase30d` recording rule looks like the following:

```
sum by (code, verb) (increase(apiserver_request_total{job="apiserver",verb="LIST",code=~"2.."}[1h]))
```

It shouldn't return samples with duplicate set of labels. It looks like the issue is in the logic for determining duplicate samples: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e6ec442e9671f7fb13aba1020d6f187074589931/app/vmalert/recording.go#L106-L117 
It returns identical hash (aka hash collision) for samples with different set of labels. It would be better using string representation of the labelset for determining the duplicates. Another option is to remove the duplicate check, since both VictoriaMetrics and Prometheus do not return samples with identical set of labels from [/api/v1/query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries).

**Comment by hagen1778** [comment] 2021-05-14 15:01
> It returns identical hash (aka hash collision)

How do you know it is a hash collision?

> both VictoriaMetrics and Prometheus do not return samples with identical set of labels from /api/v1/query.

the duplicates check is applied after extra labels were applied. It suppose to cover the case when extra_labels override labels which made specific time serie unique. See the following test case - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e6ec442e9671f7fb13aba1020d6f187074589931/app/vmalert/recording_test.go#L112

**Comment by hagen1778** [comment] 2021-05-15 10:17
Hi @kevinvirs! Do you use unmodified [rules](https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-availability.rules.yaml)? Do you have any `external.label` flags, or extra labels in rule's group?

Could you also try to build vmalert from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1301/commits/b3290f9fd24c2682dae8aa8c41d47748c7508a60 and try to run it ? See https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources

**Comment by kevinvirs** [comment] 2021-05-17 05:19
> 
> 
> Hi @kevinvirs! Do you use unmodified [rules](https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-availability.rules.yaml)? Do you have any `external.label` flags, or extra labels in rule's group?
> 
> Could you also try to build vmalert from [b3290f9](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b3290f9fd24c2682dae8aa8c41d47748c7508a60) and try to run it ? See https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources

used this label values https://github.com/VictoriaMetrics/helm-charts/pull/145

**Comment by f41gh7** [comment] 2021-05-20 21:35
> > Could you also try to build vmalert from [b3290f9](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b3290f9fd24c2682dae8aa8c41d47748c7508a60) and try to run it ? See https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources
> 
> can't :)

 Can you try this docker image victoriametrics/vmalert:heads-master-0-g060664e22 

 It was build from current master and contains mentioned commit.

**Comment by valyala** [comment] 2021-05-24 15:34
FYI, the bugfix is available starting from `vmalert` [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@kevinvirs , please re-open the issue if the issue still exists in vmalert v1.60.0.

**Closed by valyala** 2021-05-24 15:34 UTC
Labels: bug, vmalert

**Comment by tumd** [comment] 2021-06-16 06:44
Hi,

I noticed the same errors as in the initial post in v1.59.0, and upgraded to 1.61.1 yesterday, and now I'm seeing similar errors;

```
2021-06-16T06:31:41.753Z        error        VictoriaMetrics/app/vmalert/group.go:256        group "kube-apiserver-availability.rules": rule "code_verb:apiserver_request_total:increase30d": failed to execute: original metric {[{cluster minikube} {code 200} {verb GET}] [1623825000] [8.328583384615385e+06]}; resulting labels "__name__=code_verb:apiserver_request_total:increase30d,alerter=victoria,cluster=minikube,code=200,verb=GET": result contains metrics with the same labelset after applying rule labels
2021-06-16T06:34:41.765Z        error        VictoriaMetrics/app/vmalert/group.go:256        group "kube-apiserver-availability.rules": rule "code_verb:apiserver_request_total:increase30d": failed to execute: original metric {[{cluster minikube} {code 200} {verb GET}] [1623825180] [8.328583384615385e+06]}; resulting labels "__name__=code_verb:apiserver_request_total:increase30d,alerter=victoria,cluster=minikube,code=200,verb=GET": result contains metrics with the same labelset after applying rule labels
2021-06-16T06:37:41.802Z        error        VictoriaMetrics/app/vmalert/group.go:256        group "kube-apiserver-availability.rules": rule "code_verb:apiserver_request_total:increase30d": failed to execute: original metric {[{cluster minikube} {code 200} {verb GET}] [1623825360] [8.328583384615385e+06]}; resulting labels "__name__=code_verb:apiserver_request_total:increase30d,alerter=victoria,cluster=minikube,code=200,verb=GET": result contains metrics with the same labelset after applying rule labels
```

**Comment by hagen1778** [comment] 2021-06-16 07:33
Hi @tumd! Could you please run the following instant query in Grafana against VM datasource and show the output?
```
avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30
```
Thank you!

**Comment by tumd** [comment] 2021-06-16 07:43
Here you go!
<img width="1374" alt="Screenshot 2021-06-16 at 09 40 55" src="https://user-images.githubusercontent.com/463066/122178727-231de280-ce87-11eb-8518-255d4ff9cc84.png">

**Comment by hagen1778** [comment] 2021-06-16 09:21
Thanks for quick response! Do you have any additional labels applied to recording rules (it is likely `alerter` is one of those)?

The issue of duplicated series could be caused by the last metric in the table (or by other metrics which we don't see on screen because of scroll). For example, if vmalert is configured to automatically apply labels `alerter=victoria, cluster=minikube` then the last metric on the screen will be indistinguishable from the first metric on the screen. If vmalert would skip the check, then collision will happen and resulting series  `code_verb:apiserver_request_total:increase30d{verb=GET, cluster=minikube, code=200}` will get two  different values `7547056` and `1091580` (first and last values from the screen),

It is important to understand, which series in the output of `avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30` query will result into duplicates after applying extra labels. Otherwise, it may result into confusion and incorrect results.

**Comment by hagen1778** [comment] 2021-06-16 10:09
Thanks! Are there any other series in response which could result into duplicates? Can you try to [delete series](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-delete-time-series)  generated by temporary `vmalert` if you don't need them?

While the feature of duplicate check seem sane, it may result into such issues like this when testing affects other series calculations. Especially for this specific recording rule which covers `30d` range. I'll think what would be the proper way to fix it: disable duplicates check (Prometheus does not check for duplicates, afaik), add param for disabling duplicates check per-rule, move labels with conflicting keys instead of overwriting them, etc.

**Comment by tumd** [comment] 2021-06-16 10:50
I'll try to delete the unwanted series later to day, and report the outcome.

One thing that I forgot to mention, that may be relevant; I'm using two replicas of vmagent in k8s (`spec.replicaCount: 2`).

**Comment by tumd** [comment] 2021-06-16 13:00
After deleting the unneeded series the error-logging stopped. 👍
