### ISSUE TITLE
vmselect: Instant roll-up query returns incorrect timestamp

### ISSUE THREAD

**Issue by moward** [VictoriaMetrics/VictoriaMetrics#5730] opened 2024-01-30 19:02 UTC
### Describe the bug

With instant queries using the roll-up result cache, sometimes the timestamp returned in the query result doesn't match the `time` parameter passed to the query. Instead, it returns a timestamp in the near past.

### To Reproduce

For this repro, I used the binary from https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.96.0/victoria-metrics-darwin-arm64-v1.96.0.tar.gz (latest release). I've observed the issue on linux distributions as well.

First, start VM, using a fresh data directory:
```sh
$ rm -rf /tmp/victoriametrics-data && ./victoria-metrics-prod -httpListenAddr=127.0.0.1:8428 -storageDataPath=/tmp/victoriametrics-data
```

In a separate terminal from the one running VM, run the following commands. First, ingest a counter:
```
$ curl -X POST -d @- http://localhost:8428/api/v1/import <<EOF
{"metric": {"__name__": "counter"}, "values": [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], "timestamps": [1704070800000, 1704070830000, 1704070860000, 1704070890000, 1704070920000, 1704070950000, 1704070980000, 1704071010000, 1704071040000, 1704071070000, 1704071100000]}
EOF
```

Make one query that aggregates the counter over time, with a lookback of 6 hours:
```
$ curl http://localhost:8428/prometheus/api/v1/query \--data-urlencode 'query=sum(increase(counter{}[6h]))' \
--data-urlencode time=1704071100 \--data-urlencode step=15s \

{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1704071100,"1"]}]},"stats":{"seriesFetched": "1","executionTimeMsec":1}}%
```

The result is correct.

Make another query identical to the first but with a slightly offset `time` parameter:
```sh
$ curl http://localhost:8428/prometheus/api/v1/query \--data-urlencode 'query=sum(increase(counter{}[6h]))' \
--data-urlencode time=1704071160 \--data-urlencode step=15s \

{"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1704071100,"1"]}]},"stats":{"seriesFetched": "2","executionTimeMsec":0}}%
```

**Expected:** The time returned in the query should be 1704071160
**Actual:** The time returned in the query should be 1704071100

### Version

```
$ ./victoria-metrics-prod -version
victoria-metrics-20231212-224437-tags-v1.96.0-0-g304fe0565
```

### Logs

```
2024-01-30T18:48:01.858Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version: victoria-metrics-20231212-224437-tags-v1.96.0-0-g304fe0565
2024-01-30T18:48:01.859Z        info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2024-01-30T18:48:01.859Z        info    VictoriaMetrics/lib/logger/flag.go:20     -httpListenAddr="127.0.0.1:8428"
2024-01-30T18:48:01.859Z        info    VictoriaMetrics/lib/logger/flag.go:20     -storageDataPath="/tmp/victoriametrics-data"
2024-01-30T18:48:01.859Z        info    VictoriaMetrics/app/victoria-metrics/main.go:70 starting VictoriaMetrics at "127.0.0.1:8428"...
2024-01-30T18:48:01.859Z        info    VictoriaMetrics/app/vmstorage/main.go:108       opening storage at "/tmp/victoriametrics-data" with -retentionPeriod=1
2024-01-30T18:48:01.889Z        info    VictoriaMetrics/lib/memory/memory.go:42 limiting caches to 10307921510 bytes, leaving 6871947674 bytes to the OS according to -memory.allowedPercent=60
2024-01-30T18:48:02.084Z        info    VictoriaMetrics/app/vmstorage/main.go:122       successfully opened storage "/tmp/victoriametrics-data" in 0.224 seconds; partsCount: 0; blocksCount: 0; rowsCount: 0; sizeBytes: 0
2024-01-30T18:48:02.089Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:115  loading rollupResult cache from "/tmp/victoriametrics-data/cache/rollupResult"...
2024-01-30T18:48:02.090Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:143  loaded rollupResult cache from "/tmp/victoriametrics-data/cache/rollupResult" in 0.001 seconds; entriesCount: 0, sizeBytes: 0
2024-01-30T18:48:02.091Z        info    VictoriaMetrics/app/victoria-metrics/main.go:80 started VictoriaMetrics in 0.232 seconds
2024-01-30T18:48:02.091Z        info    VictoriaMetrics/lib/httpserver/httpserver.go:101        starting http server at http://127.0.0.1:8428/
2024-01-30T18:48:02.091Z        info    VictoriaMetrics/lib/httpserver/httpserver.go:102        pprof handlers are exposed at http://127.0.0.1:8428/debug/pprof/
2024-01-30T18:48:10.299Z        info    VictoriaMetrics/lib/storage/partition.go:221    creating a partition "2024_01" with smallPartsPath="/tmp/victoriametrics-data/data/small/2024_01", bigPartsPath="/tmp/victoriametrics-data/data/big/2024_01"
2024-01-30T18:48:10.311Z        info    VictoriaMetrics/lib/storage/partition.go:230    partition "2024_01" has been created
2024-01-30T18:48:15.299Z        warn    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:69   resetting rollup result cache because the metric counter{} (Timestamp=1704070800000, Value=0.000000) has a timestamp older than -search.cacheTimestampOffset=5m0s by 2569394.000s
2024-01-30T18:48:15.299Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:203  rollupResult cache has been cleared
2024-01-30T18:48:19.432Z        info    VictoriaMetrics/app/vmselect/querystats/querystats.go:68        enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=1ms
^C2024-01-30T18:57:34.638Z      info    VictoriaMetrics/app/victoria-metrics/main.go:83 received signal interrupt
2024-01-30T18:57:34.638Z        info    VictoriaMetrics/app/victoria-metrics/main.go:87 gracefully shutting down webservice at "127.0.0.1:8428"
2024-01-30T18:57:34.638Z        info    VictoriaMetrics/app/victoria-metrics/main.go:93 successfully shut down the webservice in 0.000 seconds
2024-01-30T18:57:34.638Z        info    VictoriaMetrics/app/vmstorage/main.go:235       gracefully closing the storage at /tmp/victoriametrics-data
2024-01-30T18:57:34.645Z        info    VictoriaMetrics/app/vmstorage/main.go:240       successfully closed the storage in 0.006 seconds
2024-01-30T18:57:34.645Z        info    VictoriaMetrics/app/vmstorage/main.go:242       the storage has been stopped
2024-01-30T18:57:34.645Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:178  saving rollupResult cache to "/tmp/victoriametrics-data/cache/rollupResult"...
2024-01-30T18:57:34.657Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:189  saved rollupResult cache to "/tmp/victoriametrics-data/cache/rollupResult" in 0.012 seconds; entriesCount: 2, sizeBytes: 131072
2024-01-30T18:57:34.657Z        info    VictoriaMetrics/app/victoria-metrics/main.go:100        the VictoriaMetrics has been stopped in 0.019 seconds
```

### Additional information

This issue seems related to https://github.com/VictoriaMetrics/VictoriaMetrics/commit/41a0fdaf39ea99708cf1c899332910965d62dcfc

I only started encountering it when upgrading from v1.94.0 to v1.96.0

**Comment by valyala** [comment] 2024-01-30 20:00
@moward  , thanks for reporting the bug! It should be addressed in the pull request https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5723 . See also the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5659 .

**Comment by moward** [comment] 2024-01-30 20:02
Great to hear! I glanced over #5659 but got thrown off by the "vmalert" in the title. Thanks!

**Comment by valyala** [comment] 2024-01-30 23:02
@moward , could you verify whether the issue is gone in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html)?

**Comment by moward** [comment] 2024-01-31 15:26
I just checked my repro script on [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html) and can confirm the issue is no longer present!

**Closed** 2024-01-31 15:26 UTC
Labels: bug
