### ISSUE TITLE
maxConcurrentInserts default value when running inside a container

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#946] opened 2020-12-08 09:37 UTC
**Is your feature request related to a problem? Please describe.**
When running inside a container the default maxConcurrentInserts doesn't seem to take into account the current cgroup limits but only the root cgroup limits. This can cause default value to be wrong (too high) when running inside Docker/Kubernetes.

**Describe the solution you'd like**
Use current cgroup limits to calculate default value.

**Describe alternatives you've considered**
Set maxConcurrentInserts explicitly.

**Additional context**
This could also be an issue for other calculated parameters.

**Comment by valyala** [comment] 2020-12-08 13:41
What version of VictoriaMetrics (or vminsert) do you run? Try [the latest one](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) (v1.50.0 now). The issue with incorrect limits' detection should be already fixed in `v1.42.0` - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/685#issuecomment-698595309 .

**Comment by alexandv** [comment] 2020-12-08 13:56
I tried with 1.48. I just tested with 1.49 (I don't see 1.50 in the releases) and it get the same issue. On a machine with one core maxConcurrentInserts will be set to 4 and on a machine with 16 cores it will be set to 64. In both cases the CPU limit is set to 0.5 core so I would expect maxConcurrentInserts to be set to 2.

**Comment by alexandv** [comment] 2020-12-08 13:59
The default is `runtime.GOMAXPROCS(-1)*4`
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/writeconcurrencylimiter/concurrencylimiter.go#L16

I guess `runtime.GOMAXPROCS(-1)` only returns number of cores on the machine.

**Comment by valyala** [comment] 2020-12-08 19:19
Confirmed the issue. It should be fixed in the commit 4146fc46681b532ad22973a846c0a0b2941f39ff . @alexandv , could you build VictoriaMetrics from this commit according to [the docs](https://victoriametrics.github.io/#how-to-build-from-sources) and verify whether the CPU limit is applied properly?

**Comment by alexandv** [comment] 2020-12-08 22:47
The maxConcurrentInserts is now 4 for both cases (1 core and 16 core machines). The cpu limit is set to `500m` on the container. Not sure if that's the expected value.

**Comment by alexandv** [comment] 2020-12-08 22:55
I tried setting the limit to `2` and maxConcurrentInserts becomes 8. So that looks good I think

**Comment by valyala** [comment] 2020-12-09 10:52
> The maxConcurrentInserts is now 4 for both cases (1 core and 16 core machines). The cpu limit is set to 500m on the container. Not sure if that's the expected value.

That's expected value, since the number of available CPU cores is rounded to 1 if the limit is smaller than a single CPU core.

**Comment by alexandv** [comment] 2020-12-09 17:21
Sounds good. Thanks @valyala

**Comment by valyala** [comment] 2020-12-15 13:50
All the VictoriaMetrics components properly should properly detect cpu limits when running in containers starting from [v1.50.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by weisdd** [comment] 2020-12-15 20:46
@valyala I don't have an extensive dataset, though I've seen a dramatic increase in CPU usage after upgrading from 1.48.0 to 1.50.0:
![image](https://user-images.githubusercontent.com/46579601/102270208-ca4cac00-3f2e-11eb-9e75-e38f1bbb5c12.png)
![image](https://user-images.githubusercontent.com/46579601/102270302-e3edf380-3f2e-11eb-82c0-b75e947ec718.png)
vmselect stayed at the same level.

```
vminsert:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 300m
      memory: 500Mi

vmstorage:
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
```

I guess it might have something to do with this bugfix.

**Comment by valyala** [comment] 2020-12-15 22:50
@alexandv , could you downgrade cluster components to v1.49.0 and verify whether this reduces CPU usage for your workload? If this reduces CPU usage, then it would be great if you could collect and share CPU profiles for `vmstorage` component for both v1.49.0 and v1.50.0 . See [instructions on how to collect CPU profile in cluster version](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#profiling).

**Comment by alexandv** [comment] 2020-12-16 08:59
I didn't notice any CPU increase myself. But I'm using the single node version.

**Comment by weisdd** [comment] 2020-12-16 13:45
@valyala You're right, I should have downgraded to v1.49.0 before posting anything here. I do see similar behavior there as well. I'll collect more information and create a separate issue for that then.
Sorry for the inconvenience.

**Comment by valyala** [comment] 2020-12-17 13:51
> I'll collect more information and create a separate issue for that then.

Then closing this issue.

**Closed by valyala** 2020-12-17 13:51 UTC
Labels: bug
