### ISSUE TITLE
CPU and RAM surge when the vmstore component starts deleting indexdb 

### ISSUE THREAD

**Issue by ScmTble** [VictoriaMetrics/VictoriaMetrics#4873] opened 2023-08-23 10:43 UTC
### Describe the bug

Using Victoria single ，CPU and RAM surge when the vmstore component starts deleting indexdb ，Vmui is unable to perform queries

### To Reproduce
``` yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: monitoring
  labels:
    app: victoria-single
  name: victoria-single
spec:
  serviceName: victoria-single
  selector:
    matchLabels:
      app: victoria-single
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: victoria-single
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-single
          image: "victoriametrics/victoria-metrics:v1.93.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--retentionPeriod=1d"
            - "--storageDataPath=/storage"
            - -promscrape.config=/scrapeconfig/scrape.yml
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8428
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8428
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources: {}
          volumeMounts:
            - name: server-volume
              mountPath: /storage
              subPath:
            - name: scrapeconfig
              mountPath: /scrapeconfig
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scrapeconfig
          configMap:
            name: victoria-single-scrapeconfig
  volumeClaimTemplates:
    - metadata:
        name: server-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "8Gi"
```

### Version

victoria-metrics-20230812-215739-tags-v1.93.0-0-g59f7d810c9

### Logs

<img width="1581" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/56188521/e5e634ad-4bad-4ae8-ac5c-ece7cb356432">

### Screenshots

<img width="1857" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/56188521/9fa44942-3b08-4a9c-9380-53d150f0ddf7">

### Used command-line flags

- "--retentionPeriod=1d"

**Comment by f41gh7** [comment] 2023-08-23 10:50
Hello, it's a seem to be a bug with next retention deadline calculation.

 Can you plot a value for the metric `vm_next_retention_seconds` ?

**Comment by f41gh7** [comment] 2023-08-23 11:08
I'd recommend to downgrade cluster for https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.3 version.
It should be safe, since it contains no breaking changes.

 Bug'll be fixed at the next release.

**Comment by ScmTble** [comment] 2023-08-23 11:10
> I'd recommend to downgrade cluster for [`v1.91.3` (release)](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.3) version. It should be safe, since it contains no breaking changes.
> 
> Bug'll be fixed at the next release.

thanks!  Is 1.93->1.91.3 compatible?

**Comment by ScmTble** [comment] 2023-08-23 11:13
> 

Thank you, brother @tenmozes  @f41gh7

**Comment by hagen1778** [comment] 2023-08-23 11:23
@ScmTble @f41gh7 https://docs.victoriametrics.com/CHANGELOG.html#v1921 is also available for rollback

**Comment by hagen1778** [comment] 2023-08-23 13:58
@ScmTble @a26nine the issue should be fixed in [1.93.1](https://docs.victoriametrics.com/CHANGELOG.html#v1931). Please, let me know if it helps you.

**Comment by ScmTble** [comment] 2023-08-23 14:33
> @ScmTble @a26nine the issue should be fixed in [1.93.1](https://docs.victoriametrics.com/CHANGELOG.html#v1931). Please, let me know if it helps you.

Upgraded. If there are any other issues, I will comment. Thank you

**Comment by hagen1778** [comment] 2023-08-23 14:43
Closing this issue as done. Feel free to reopen if you see it reproduced.

**Closed by hagen1778** 2023-08-23 14:43 UTC
Labels: bug

**Comment by ScmTble** [comment] 2023-08-24 05:19
@hagen1778  Oh no, vmstore panic !
[victoria-vmstorage-1-logs.csv](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12425646/victoria-vmstorage-1-logs.csv)

**Comment by Haleygo** [comment] 2023-08-24 05:42
> @hagen1778 Oh no, vmstore panic ! [victoria-vmstorage-1-logs.csv](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12425646/victoria-vmstorage-1-logs.csv)

@ScmTble Looks like the exact same error log like yesterday, is vmstorage running with new version v1.93.1?

**Comment by ScmTble** [comment] 2023-08-24 05:43
> > @hagen1778 Oh no, vmstore panic ! [victoria-vmstorage-1-logs.csv](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12425646/victoria-vmstorage-1-logs.csv)
> 
> @ScmTble Looks like the exact same error log like yesterday, is vmstorage running with new version v1.93.1?

yes

**Comment by hagen1778** [comment] 2023-08-24 05:48
@ScmTble could you please provide the full log of vmstorage starting from yesterday's update till now?

**Comment by ScmTble** [comment] 2023-08-24 05:56
> @ScmTble could you please provide the full log of vmstorage starting from yesterday's update till now?

Oh, sorry,I downgraded to 1.92.1,  the log seems to have been overwritten

**Comment by ScmTble** [comment] 2023-08-24 06:01
I have set up two modes, and it seems that there is a problem with the cluster, but not with the single mode
[victoria-single-0-logs.csv](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12425880/victoria-single-0-logs.csv)

**Comment by hagen1778** [comment] 2023-08-24 06:22
Thanks! Single and cluster versions use the same code for rotation. Any chance vmstorage wasn't updated to 1.93.1? Do you have metrics for vmstorage - we can check version there.

**Comment by ScmTble** [comment] 2023-08-24 06:33
> Thanks! Single and cluster versions use the same code for rotation. Any chance vmstorage wasn't updated to 1.93.1? Do you have metrics for vmstorage after the update? We can check version there.

Perhaps for this reason, a new cluster has been created to observe. Thank you to everyone!
<img width="1661" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/56188521/f5aca12a-ebf2-4295-9d5d-be3b67e1b3c8">

**Comment by f41gh7** [comment] 2023-08-24 08:37
Hello, update from our side. Cluster build was made without patch fix by mistake. 

 Today it was rebuild correctly. Docker image and binaries were updated. Please pull new version.

**Comment by wgb1990** [comment] 2023-08-25 09:58
@f41gh7 Is this bug generated by 1.92.0? I upgraded my dev environment to version 1.92.1 last week and did not encounter this issue. I am currently struggling with whether to upgrade my prd environment to version 1.93.1 ?

**Comment by zekker6** [comment] 2023-08-25 10:01
@wgb1990 This bug was introduced in 1.93.0. Previous versions are not affected.
Version 1.93.1 is safe to upgrade as it includes fix for this bug.

**Comment by everythings-gonna-be-alright** [comment] 2023-08-31 06:49
Any options to restore data?
