### ISSUE TITLE
vmrestore downloads full S3 backup every time

### ISSUE THREAD

**Issue by deldering-momo** [VictoriaMetrics/VictoriaMetrics#958] opened 2020-12-11 14:01 UTC
Hi, I'm trying to do incremental backups to S3 and doing an incremental restore from S3 to another machine. Currently what I'm experiencing sadly is that every time I call vmrestore the entire db gets re-downloaded instead of just the new stuff.
```
restored 558815863005 bytes from backup in 160473.110 seconds; deleted 429027306578 bytes; downloaded 547956668510 bytes
```
The storageDataPath and src for vmrestore are the same every time so I do not understand why this isn't working.
Is my intended use just not supported or am I missing something?

PS. I have also tested it in between additional backups, so even when the src and storageDataPath should contain the same stuff it fails.

**Comment by valyala** [comment] 2020-12-11 15:46
`vmrestore` performs incremental restore (i.e. downloads only new files from backup) only if the directory pointed by `-storageDataPath` contains data from the previous `vmrestore` invocation without any modifications. This means that VictoriaMetrics or [vmstorage](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html) shouldn't accept new data on `-storageDataPath` folder with restored data. Otherwise this data is substituted with new data from the backup on the next `vmrestore` call. It looks like this is your case - i.e. 429GB of locally ingested data is substituted with 549GB of new data from the backup.

**Comment by DEldering-Momo** [comment] 2020-12-14 14:47
Alright, I just checked, and if I do not start the restored database on the other machine then indeed it does not re-download everything. Is there a way that would allow me to look inside the backup (with something like grafana) without it modifying the backup? I would rather not have duplicate the data locally to view it.

**Comment by denisgolius** [comment] 2022-07-21 07:51
Hi @DEldering-Momo !
Could you test the [latest version](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.0) of vmbackup and confirm that the problem is still present?

**Comment by kenXengineering** [comment] 2022-10-24 23:57
I've also seen this issue recently when attempting to restore a 700 GB backup from S3.  The Backup was created by an older vmbackup (v1.45.0) as the install I am migrating from is old.

I started vmrestore (v1.82.1) on the new instance and had a network error mid-restore that caused it to stop.  The restore had been running for about 40 minutes by this time.  I restarted the restore without making any modifications to the data.  I currently have the EBS drives attached to a temp instance so that I can test this restore.  However, when vmrestore started to restore, it deleted 154 files, reducing the restored size from 457G to just 5.2G.

Looking at the logs provided, all I see is vmrestore deleting files at the beginning, I just wounder why it has to delete almost all the downloaded data.

**Comment by valyala** [comment] 2024-02-08 13:40
@zekker6 , could you look into this issue?

**Comment by zekker6** [comment] 2024-02-08 14:44
@valyala I've ran a few tests and can confirm that this is no longer reproducible. 
`vmrestore` will delete files on local disk only in the following cases:
- file is `parts.json` or `appliedRetention.txt`
- the same file does not exist in remove location

06eff5a72c42f053a5542380383225682f53d03a could have fixed an issue which was causing deletion of files for original issue author.

I'd suggest to close this issue and suggest to reopen if there will be a way to reproduce it.

**Closed** 2024-04-16 14:48 UTC
Labels: bug, vmrestore
