### ISSUE TITLE
Support for Object Storage as a Storage Backend in VictoriaMetrics Enterprise

### ISSUE THREAD

**Issue by PatMis16** [VictoriaMetrics/VictoriaMetrics#5227] opened 2023-10-23 13:50 UTC
### Is your feature request related to a problem? Please describe

Yes, the feature request is indeed related to a problem. It extends beyond the specific challenge of storage management inside EKS (Amazon Elastic Kubernetes Service) and touches upon a broader issue encountered when deploying VictoriaMetrics Enterprise on Kubernetes (K8s).

The problem centers around the inability to dynamically resize volumes associated with Persistent Volume Claims (PVCs) when using VictoriaMetrics within Kubernetes. This issue affects not only efficient scaling but also presents challenges in long-term data retention. The current process for resizing volumes is complex and disruptive, involving the destruction of existing PVCs, recreation, and restoration from backup.

These challenges have a significant impact on the scalability, cost-effectiveness, and overall ease of managing the storage backend for VictoriaMetrics Enterprise on Kubernetes. While storage management inside EKS exemplifies this issue, it is a concern that transcends specific Kubernetes environments.

To address these issues comprehensively, we are requesting the addition of support for object storage as a storage backend, which offers a more robust and scalable alternative and can address the wider problem of volume resizing within Kubernetes environments.

### Describe the solution you'd like

The solution I'm requesting is the addition of support for object storage as a storage backend in VictoriaMetrics Enterprise. Object storage, which is commonly offered by cloud providers like AWS S3, Azure Blob Storage, and Google Cloud Storage, is a highly efficient and scalable storage solution. Enabling VictoriaMetrics Enterprise to store and retrieve data from object storage would provide users with a cost-effective and flexible alternative to the existing storage options. This enhancement would significantly improve the scalability and long-term data retention capabilities of VictoriaMetrics Enterprise.

### Describe alternatives you've considered

As an alternative to the existing storage solution, we have already implemented the use of Persistent Volume Claims (PVCs) inside EKS with GP3 storage. While this approach provides a degree of scalability, it is still subject to limitations and difficulties related to resizing and long-term data retention. It offers some level of flexibility but does not fully address the challenges associated with storage management within EKS.

Additionally, we considered Amazon Elastic File System (EFS) as an alternative, given its ability to dynamically grow the volume. However, EFS utilizes the Network File System (NFS) protocol, which may not be a suitable alternative for our specific use case. EFS does not provide the same level of performance and efficiency as object storage solutions. Therefore, despite exploring these alternatives, the most effective and streamlined solution remains the addition of support for object storage as a storage backend in VictoriaMetrics Enterprise.

**Comment by hagen1778** [comment] 2023-10-24 09:32
> The problem centers around the inability to dynamically resize volumes associated with Persistent Volume Claims (PVCs) when using VictoriaMetrics within Kubernetes.

@PatMis16 most of cloud providers (AWS, Google, Azure) provide feature of dynamical resizing for block storages. For example, in AWS you need to change the storage class with setting `allowVolumeExpansion: true` to allow disk expanding. In GKE, afaik, this is allowed by default.

@Haleygo @zekker6 correct me if I'm wrong here.

> The solution I'm requesting is the addition of support for object storage as a storage backend in VictoriaMetrics Enterprise.

Please see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/38

**Comment by PatMis16** [comment] 2023-10-24 09:51
@hagen1778 Can I use the `allowVolumeExpansion: true` int the VictoriaMetrics Helm Charts? We do not use the VictoriaMetrics Operator due to security restrictions on our AWS EKS Clusters.

**Comment by PatMis16** [comment] 2023-10-24 10:01
Thing is, Thanos and Grafana Metrics (aka Mimir) do support Object Storage.

**Comment by hagen1778** [comment] 2023-10-24 10:15
>  Can I use the allowVolumeExpansion: true int the VictoriaMetrics Helm Charts? We do not use the VictoriaMetrics Operator due to security restrictions on our AWS EKS Clusters.

I don't know. I hope @Haleygo will address this question.

**Comment by hagen1778** [comment] 2023-10-24 10:20
> Thing is, Thanos and Grafana Metrics (aka Mimir) do support Object Storage.

This is true. You can find reasons why VM doesn't support this here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/38#issuecomment-1484006165. In two words, both Thanos and Mimir still require local filesystem for Proms/Ingesters. It is true that historical data (usually older than a day) will be stored in object storage, but reading data from object storage will be slower and, in some cases, more expensive. For reading data from object storage one should run additional components for accessing that data. These components, in Thanos and Mimir, will require local storage and considerable amounts of memory in order to process data and indexes. You can find a more detailed comparsion between VictoriaMetrics and Mimir approaches for storing and fetching data here - https://victoriametrics.com/blog/mimir-benchmark/

**Comment by zekker6** [comment] 2023-10-24 10:20
@PatMis16 `allowVolumeExpansion: true` option must be enabled for [StorageClass](https://kubernetes.io/docs/concepts/storage/storage-classes/) resource in cluster(not in Helm chart). 
This resource is usually created by cluster administrators / provider, so it might be better to check with cluster provider.

**Comment by PatMis16** [comment] 2023-10-24 11:17
With the Helm deployment, the `vmstorage` component is deployed as a StatefulSet and according to our Kubernetes admins, the PVCs within a StatefulSet are immutable.

**Comment by Haleygo** [comment] 2023-10-24 14:37
> With the Helm deployment, the `vmstorage` component is deployed as a StatefulSet and according to our Kubernetes admins, the PVCs within a StatefulSet are immutable.

Indeed, pvc is immutable for statefulset. But we can bypass this using following steps: 
1. delete vmstorage statefulset with `kubectl delete sts vmstorage-xxx -cascade=orphan` [that will leave storage pod alive but only delete sts];
2. create new vmstorage statefulset with new pvc size;
3. if provider's storageClass is expandable[having `allowVolumeExpansion: true`], pv will expand automatically and vmstorage will use the new size volume.

This process is allowed and already supported by vm-operator[simply adjust the volume size for vmstorage/vmselect under [vmcluster](https://docs.victoriametrics.com/operator/api.html#vmcluster)]. But since you guys don't use operator, you will need cluster administrators permission to perform it by hand.

**Comment by PatMis16** [comment] 2023-10-25 06:03
Thank you @Haleygo 
I know this is our own issue, but we currently do not have access to our Deployment with `kubectl` due to restrictions on our end. I have to check if it is in a way possible with the tools we have at our disposal. 

@hagen1778 
I appreciate the information you provided, and I understand the reasons why VictoriaMetrics (VM) doesn't currently support this. Our Kubernetes administrators recommend keeping storage outside of Kubernetes due to potential issues. That's why we're exploring alternatives. We've come across other solutions that support Object Storage, and we believe it could benefit VictoriaMetrics users as well.

**Comment by hagen1778** [comment] 2023-10-25 07:52
> We've come across other solutions that support Object Storage, and we believe it could benefit VictoriaMetrics users as well.

I understand the intention. Thank you for the clarification!

**Comment by hagen1778** [comment] 2023-10-25 07:53
Closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/38

**Closed by hagen1778** 2023-10-25 07:53 UTC
Labels: enhancement
