### ISSUE TITLE
MetricsQL: `1 and (0 > 1)` should not return `1`

### ISSUE THREAD

**Issue by useredsa** [VictoriaMetrics/VictoriaMetrics#6637] opened 2024-07-12 08:57 UTC
### Describe the bug

The query `1 and (0 > 1)` should not return `1`. The right-hand-side of the expression should contain an empty series that matches the left hand side. But the result from computing the `and` point by point should be that the resulting metric is also empty. Just like `1 and (1 if (time() > ((start() + end()) / 2))))` returns values only for the second half of a range query because for the first half `and` discards the `1` value because the right-hand-side has no value.

### To Reproduce

Bug in [VMUI](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=1+and+%280+%3E+1%29&g0.range_input=1h&g0.end_input=2024-02-07T09%3A00%3A00&g0.tab=0&g0.relative_time=none).

### Version

Present in last version.

**Comment by jiekun** [comment] 2024-07-15 05:32
Hi, I'm checking this issue, and I believe it requires some discussion during our daily meeting.

**Comment by jiekun** [comment] 2024-07-17 07:36
After discussion, this might be the misuse of `and`, which is a **Logical/set binary operators**.

https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators

![peek_1](https://github.com/user-attachments/assets/e5958d05-3dee-472c-818f-f956362d5481)
![peek_2](https://github.com/user-attachments/assets/ba1cebde-5b4c-472e-adbb-04c55c6945ef)

cc @yincongcyincong

**Comment by useredsa** [comment] 2024-07-20 11:04
Hi, @jiekun,

What do you mean by misuse? Can you please phrase how am I misusing it? You only link to the documentation, not quoting anything.

> vector1 and vector2 results in a vector consisting of the elements of vector1 for which there are elements in vector2 with exactly matching label sets. Other elements are dropped. The metric name and values are carried over from the left-hand side vector.

  From this we deduce that (since your documentation says that in MetricsQL there are no scalars, everything is a vector) the output should be what I claimed.

Notice, in fact, that the query `alias(1, "lhs") and alias(0 < 1, "rhs")` works and gives a series (https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=alias%281%2C+%22lhs%22%29+and+alias%280+%3C+1%2C+%22rhs%22%29&g0.range_input=1h&g0.end_input=2024-02-07T09%3A00%3A00&g0.tab=0&g0.relative_time=none), but the query `alias(1, "lhs") and alias(0 > 1, "rhs")` [does not return any series](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=alias%281%2C+%22lhs%22%29+and+alias%280+%3C+1%2C+%22rhs%22%29&g0.range_input=1h&g0.end_input=2024-02-07T09%3A00%3A00&g0.tab=0&g0.relative_time=none). But if I remove the aliases then both return something.

**Comment by changshun-shi** [comment] 2024-07-26 11:34
> Hi, @jiekun,
> 
> What do you mean by misuse? Can you please phrase how am I misusing it? You only link to the documentation, not quoting anything.
> 
> > vector1 and vector2 results in a vector consisting of the elements of vector1 for which there are elements in vector2 with exactly matching label sets. Other elements are dropped. The metric name and values are carried over from the left-hand side vector.
> 
> From this we deduce that (since your documentation says that in MetricsQL there are no scalars, everything is a vector) the output should be what I claimed.
> 
> Notice, in fact, that the query `alias(1, "lhs") and alias(0 < 1, "rhs")` works and [gives a series](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=alias%281%2C+%22lhs%22%29+and+alias%280+%3C+1%2C+%22rhs%22%29&g0.range_input=1h&g0.end_input=2024-02-07T09%3A00%3A00&g0.tab=0&g0.relative_time=none), but the query `alias(1, "lhs") and alias(0 > 1, "rhs")` [does not return any series](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=alias%281%2C+%22lhs%22%29+and+alias%280+%3C+1%2C+%22rhs%22%29&g0.range_input=1h&g0.end_input=2024-02-07T09%3A00%3A00&g0.tab=0&g0.relative_time=none). But if I remove the aliases then both return something.

Hello, 
`and` is an operation  in `prometheus`, which requires that the two parameters in it's `left` and `right` must be `vectors`. but both `1` and `0` is all `scalars`. So it will be returned error in prometheus.

However, in `VictoriaMetrics`, scalar is considered as a special type of vector, so `1 and (0 > 1)` is in expectations. 
the helpful docs are as follows:
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/4472fdb8-5eb1-404d-8e3f-d72fb86bfe03">
which is refered in https://docs.victoriametrics.com/metricsql/

So, maybe there is no bug.

**Comment by useredsa** [comment] 2024-07-27 12:05
> However, in VictoriaMetrics, scalar is considered as a special type of vector, so 1 and (0 > 1) is in expectations.
the helpful docs are as follows:

Yes, exactly, the operation should take place without error. The problem is that the outcome is not correct. The expression `(0 > 1)` should return return an empty series, and then `1 and <that empty series>` should therefore return nothing, not 1. As I say, if you alias the scalars (give then a `__name__` label), it works correctly, even though the name is not used for the `>` or `or`.

Is it clear now what the error is?

**Comment by changshun-shi** [comment] 2024-07-27 12:30
> > However, in VictoriaMetrics, scalar is considered as a special type of vector, so 1 and (0 > 1) is in expectations.
> > the helpful docs are as follows:
> 
> Yes, exactly, the operation should take place without error. The problem is that the outcome is not correct. The expression `(0 > 1)` should return return an empty series, and then `1 and <that empty series>` should therefore return nothing, not 1. As I say, if you alias the scalars (give then a `__name__` label), it works correctly, even though the name is not used for the `>` or `or`.
> 
> Is it clear now what the error is?

Yes, maybe you are right. In `prometheus`, any `vector and nil` should return nil

**Comment by skeagy** [comment] 2024-08-28 07:19
I interpret this differently, perhaps incorrectly. Given that both operands are treated as vectors....
- the result set of the AND vector operation is first populated with all the elements of the first set (which would be a single element with empty metric name and empty labelset with the scalar value 1)
- the result set is then populated with any additional elements from the second set WHERE THE LABELS DON'T MATCH. In other words, any matching labels in first and second set, only the value in the first set is used and the value in the second set is discarded.
- in this case, the second set is empty (because of the definition of binary comparison operators for instant vectors https://prometheus.io/docs/prometheus/latest/querying/operators/#binary-operators).
- given the second set is empty, it can be considered in two ways: either the labelsets match or they don't between the first and second sets. It boils down to whether you consider the second set to be completely empty, versus having a single element with empty string label space and null value. I perceive that it should be a totally empty set, because:
https://prometheus.io/docs/prometheus/latest/querying/operators/#binary-operators
`Between two instant vectors, these operators behave as a filter by default, applied to matching entries. Vector elements for which the expression is not true or which do not find a match on the other side of the expression get dropped from the result,.`
So the second set from the original AND operation would be totally empty, and a labelset comparison would be like comparing an empty string to a non-existent/null value. They are not the same.
- Well, given the labels don't match, populate the result set with elements in second set (which is an empty set). So the result is just the original elements of the first set, {} 1.

The key issue here is interpreting the expected behavior of the AND operator. It is not doing AND on values with matching label sets on either side of the operand (which seems to be the assumption of thinking an empty set on right side causes the whole thing to evaluate as empty set). Rather, the documented rules state to explicitly use the value  in the first set and ignore the value in the second set when the labelsets match, and then supplementing with any different labelsets and values that appear on the right side. Any way you slice it, the elements from the first set are always included.

I welcome hearing a different viewpoint and learning more if I'm wrong.

**Comment by useredsa** [comment] 2024-08-28 21:17
@skeagy, I think your definition of `and` is wrong.

> Rather, the documented rules state to explicitly use the value in the first set and ignore the value in the second set when the labelsets match, and then populate the result set with any different labelsets and values that appear on the right side.

Where did you see this? I think you meant `or` instead of `and`.

> The key issue here is interpreting the expected behavior of the AND operator. It is not doing AND on values with matching label sets on either side of the operand (which seems to be the assumption of thinking an empty set on right side causes the whole thing to evaluate as empty set). 

This is literally what it should do. Only that the set is not empty.

> It boils down to whether you consider the second set to be completely empty, versus having a single element with empty string label space and null value.

But it is not empty, because that's not how binary operators work, it has an empty series (otherwise why would we have `drop_empty_series`?) that has no labels (and not an empty string label).

> So the labels don't match, populate the result set with elements in second set (which is an empty set). So the result is just the original elements of the first set, vector(1).

The documentation does not state that if a vector would end up without non-null values it is dropped. And if the right-hand-side is an empty set then the result is nothing, because `and` does not work as you described, non-matched elements do not appear. See [prometheus docs](https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators)) and experiment with other queries.

---

I think not enough attention was put to the fact that this works as expected if the scalars are all given the same label (with `label_set`). Which means that this error comes from handling the scalars in a specific way. @changshun-shi, will this be fixed?

**Comment by changshun-shi** [comment] 2024-08-29 07:46
@useredsa I can't agree with u more.  However, I'm so sorry I can't give you more help because I'm not the author or core member of developer. Maybe it's better to mention them. @jiekun , @valyala, @hagen1778.

**Comment by jiekun** [comment] 2024-08-29 07:48
Hello, after internal discussions, we have determined that this is a bug that should be fixed. It will be addressed in a future release.

**Comment by valyala** [comment] 2024-09-18 15:33
Re-opening the issue until it is propagated into the next release.

**Comment by valyala** [comment] 2024-09-18 15:41
The bug has been fixed in the commit b82e2cabc53220f963e99f594e50ead5a6418981 . This commit will be included in the next release. In the mean time it is possible to build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether the issue is fixed there. Thanks to @jiekun for the fix!

**Comment by hagen1778** [comment] 2024-10-03 07:38
The bugfix was included into [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040), [v1.102.3](https://docs.victoriametrics.com/changelog/#v11023) and [v1.97.8](https://docs.victoriametrics.com/changelog/#v1978).

**Closed by hagen1778** 2024-10-03 07:38 UTC
Labels: bug, metricsql, waiting for release
