### ISSUE TITLE
m1 mac has different behavior when convert float64 to uint64

### ISSUE THREAD

**Issue by flashmouse** [VictoriaMetrics/VictoriaMetrics#1653] opened 2021-09-26 10:01 UTC
**Describe the bug**
Hi, Recently I do work with m1 mac, then lots of vm unit test fails arise. I check the unit report, seems all of them failed with the same  reason.
The one fail test is ```f(1<<64, 18446744073709548, 3)``` in ```TestPositiveFloatToDecimal```,  I debug into the code, when execute ```positiveFloatToDecimal```, parameter f is 18446744073709552000, but uint64(f) is 18446744073709551615. 
on the another intel cpu mac, the uint64(f) is 9223372036854775808.
I do some search with this (https://github.com/golang/go/issues/29463), seems currently golang cut too large float64 18446744073709552000 to uint64(2^63) should be correct result. But seems when use m1 mac, it has different result.

**To Reproduce**
I believe this problem should reproduce in any m1 mac, and golang version shoudn't be the cause. because in both m1 & intel mac, I test this code with the same golang sdk version(1.16.4).

**Expected behavior**
m1 mac should execute the test with no fail.

**Logs**
go tool test2json -t /private/var/folders/5g/2njlptcx26j6knhfbg06q_hm0000gn/T/GoLand/___10TestPositiveFloatToDecimal_in_github_com_VictoriaMetrics_VictoriaMetrics_lib_decimal.test -test.v -test.paniconexit0 -test.run ^\QTestPositiveFloatToDecimal\E$
=== RUN   TestPositiveFloatToDecimal
    decimal_test.go:82: unexpected decimal for positiveFloatToDecimal(18446744073709551616.000000); got 18446744073709551; want 18446744073709548
--- FAIL: TestPositiveFloatToDecimal (0.00s)

FAIL

Process finished with the exit code 1

**Version**
1.37.1-cluster

Hope for any advice, thx!

**Comment by valyala** [comment] 2021-09-27 16:51
The issue is related to precision loss during hardware converting from `float64` to `int64`. It looks like [Apple M1](https://en.wikipedia.org/wiki/Apple_M1) has slightly different math unit, which is responsible for these conversions, so the end result is slightly different. See https://github.com/golang/go/issues/48458 .

I think these tests must be updated, so it work on both x86 and M1 processors. @flashmouse , it would be great if you could help with this, since I have no access to M1 at the moment.

**Comment by syepes** [comment] 2021-09-28 16:31
@valyala I can help if needed.
I have a M1 were we can do the tests, just poke me

**Comment by flashmouse** [comment] 2021-09-29 02:01
seems golang develop team doesn't have any plan handle the problem. They say 
>The result is implementation defined

I'm not quite sure how we fix these test?

**Comment by valyala** [comment] 2021-10-19 20:19
The tests can be adjusted in order to don't touch the edge case numbers, which give different results due to precision errors on M1 and x86 processors.

**Comment by valyala** [comment] 2021-11-08 15:09
The bugfix has been integrated into [v1.69.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Now VictoriaMetrics tests should pass on Apple M1. Closing the issue as fixed.

**Closed by valyala** 2021-11-08 15:09 UTC
Labels: bug
