### ISSUE TITLE
VictoriaLogs: Unexpected 'count_uniq' results

### ISSUE THREAD

**Issue by p5i** [VictoriaMetrics/VictoriaMetrics#7152] opened 2024-10-01 08:05 UTC
### Describe the bug

Hi.

When I do
`$ curl http://localhost:9428/select/logsql/query -d 'query= version:= unknown | stats count_uniq(version) ver'
{"ver":"2"}`

VictoriaLogs returns
`{"ver":"2"}`

I expect to receive
`{"ver":"1"}`

'uniq' returns correct number
`$ curl http://localhost:9428/select/logsql/query -d 'query= version:= unknown | uniq(version) | stats count() ver'
{"ver":"1"}`

I used version v0.31.0 before and had the same problem with 'uniq(version) | stats count() ver' too.
I suppose it is related to the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0c0f013a60c812f46df1b8fa2863d1038e0e0208 that fixed 'uniq' and that was discussed here https://github.com/VictoriaMetrics/victorialogs-datasource/issues/72 .

### To Reproduce

I reproduce this issue by ingesting logs with promtail with two different sets of static labels.
For querying I use Grafana datasource and then reproduce the same results with curl.

### Version

$ /opt/victoria-logs-prod --version
victoria-logs-20240930-123307-tags-v0.32.1-victorialogs-0-g82482fca4b

### Logs

There is no warnings or errors while ingesting and querying.

**Comment by valyala** [comment] 2024-10-01 11:38
@p5i , thanks for filing the bugreport! The issue should be fixed in the commit a350be48b68330ee1a487e1fb09b002d3be45163 . This commit will be included in the next release of VictoriaLogs. In the mean time you can build VictoriaLogs from this commit on yourself according to [these instructions](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code) and verify whether the issue is fixed.

**Comment by valyala** [comment] 2024-10-01 11:55
The bugfix has been included in [v0.33.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.33.0-victorialogs). Closing the issue as fixed.

**Closed by valyala** 2024-10-01 11:55 UTC
Labels: bug, victorialogs

**Comment by p5i** [comment] 2024-10-01 12:12
@valyala thanks for the quick fix.
