### ISSUE TITLE
vmselect return different result with different time range when a timeseries has no value

### ISSUE THREAD

**Issue by luhhujbb** [VictoriaMetrics/VictoriaMetrics#1522] opened 2021-08-05 09:44 UTC
**Describe the bug**
When querying for a large time range (90 days or more), result is different from the result a smaller time range (30 days).

**To Reproduce**
Create a time series with one point per month and others with one point per day on the same metric.

Adding `or on() vector(0)` does not change the result.

**Expected behavior**
Send the same result on all time range

**Logs**
No specific logs

**Screenshots**
* 30 days graph
![30days](https://user-images.githubusercontent.com/13641063/128327910-99d1b211-bc09-488b-8a87-3f0d8c65ac1a.png)
* 90 days graph
![90days](https://user-images.githubusercontent.com/13641063/128327948-61008c5c-25eb-41a7-ab15-9b006771a226.png)

Here the red time series on 90 days graph has normally only one point per month like in 30 days graph.

**Version**

- v1.63.0
- v1.64.1

**Used command-line flags**

Only retention and data path

**Comment by hagen1778** [comment] 2021-08-06 09:36
Hi @luhhujbb!
This might be a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1486
Could you please try following recommendations from https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1486#issuecomment-889771364 and don't forget to reset caches as proposed here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1486#issuecomment-886785301.

**Comment by luhhujbb** [comment] 2021-08-06 10:02
Hi @hagen1778,
I'm not using cluster version. I found the right commit on master. I've also try the latest version from master, I've cleared the cache and it's seems not fixed yet.

**Comment by luhhujbb** [comment] 2021-08-30 08:14
After more investigation, it seems that this problem occurs only where there is two non null points in the time window. ie, with the hypothesis of the issue (only one point per month) when selected a time windows between 30 and 50 days there is no issue, but as soon as a time window contains two points or more (one per month) the issue occurs.

**Comment by luhhujbb** [comment] 2021-09-02 13:15
@valyala Following your comment here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1509#issuecomment-900186521 in #1509 , I comment the adjustLastPoints function, and it solves this issue.

Hope it helps.

**Comment by luhhujbb** [comment] 2021-09-02 14:00
This issue seems to be fixed on v1.65.0

**Comment by luhhujbb** [comment] 2021-09-02 14:08
Actually, now it works for 30d, 60d, 6 months but still bug for one years ... :disappointed:

**Comment by Yuri1Kravets** [comment] 2022-07-27 15:58
@luhhujbb Hi, does this issue still persists for you?

**Comment by luhhujbb** [comment] 2022-08-09 16:23
@Yuri1Kravets unfortunately I've moved to another company so it's difficult for me to troubleshoot this issue anymore.

In such condition maybe it can be closed.

**Closed** 2022-08-09 17:27 UTC
Labels: bug
