### ISSUE TITLE
rollup func problems (such as avg_over_time)

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#636] opened 2020-07-17 02:39 UTC
**Describe the bug**
when i use sum(sum_over_time(credis.exceptions.count_sum))，everything is ok。

![image](https://user-images.githubusercontent.com/6347394/87741620-89355c00-c817-11ea-9257-0a2e3706d710.png)

when i use avg(avg_over_time(credis.exceptions.count_sum))，I found something strange.

![image](https://user-images.githubusercontent.com/6347394/87741993-63f51d80-c818-11ea-91d5-72df007f56b2.png)

I found the raw data matches sum_over_time, why avg_over_time  add so many none-exists datapoints ?

```
$ ./victoria-metrics-prod --version
victoria-metrics-v1.37.3
```

**Comment by valyala** [comment] 2020-07-23 19:30
@davidsome , thanks for the bug report!

The bug should be fixed in the following commits:
* Single-node version: b1f6843bd0834086d094e369e800c7cc94de46a9
* Cluster version: 88e8bed0c993fad274e74db860494b7b1d4f50e8

Could you build VictoriaMetrics from the commit b1f6843bd0834086d094e369e800c7cc94de46a9 according to [these docs](https://victoriametrics.github.io/#how-to-build-from-sources) and verify whether `avg_over_time` works as expected now?

**Comment by valyala** [comment] 2020-07-24 19:17
The bugfix has been included in [v1.39.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@davidsome , feel free re-opening the issue if `v1.39.0` doesn't work as expected for your case.

**Closed by valyala** 2020-07-24 19:18 UTC
Labels: bug

**Comment by davidsome** [comment] 2020-12-30 03:10
@valyala the newest version I found sum_over_time behaves strange，
![image](https://user-images.githubusercontent.com/6347394/103327457-9a091f80-4a8f-11eb-8033-ac64a29b823c.png)


when use sum_over_time,  null values becomes zero。avg_over_time is ok  .is this a bug？

**Comment by valyala** [comment] 2021-04-02 23:44
@davidsome , I cannot reproduce this issue on the [latest release of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) (v1.57.1) - both `sum_over_time()` and `count_over_time()` return empty values on time ranges without raw samples.

Try exporting raw samples for these time series on the selected time range via [/api/v1/export](https://victoriametrics.github.io/#how-to-export-time-series) and inspecting their contents - probably they contain some unusual values there.
