### ISSUE TITLE
vmselect gets timeout when request /api/v1/label/.../values

### ISSUE THREAD

**Issue by evkuzin** [VictoriaMetrics/VictoriaMetrics#6456] opened 2024-06-11 08:30 UTC
### Describe the bug

I'm running all nodes with v1.97.1 and this version got issues with autodiscovery. 1.101.0 got issues too. 1.98 seems to work so far.

 I can see this in the logs

**1.101.0:**
```
v1.101.0/vmselect-prod -dedup.minScrapeInterval 10s -httpListenAddr ':8080' -http.connTimeout 3m0s -replicationFactor 2 -search.maxConcurrentRequests 96 -search.maxQueryDuration 180s -search.maxQueueDuration 60s -search.maxSeries 125000000 -search.maxSamplesPerQuery 50000000000 -search.maxUniqueTimeseries 3000000 -search.logSlowQueryDuration 30s -clusternativeListenAddr ':8401' -clusternative.maxConcurrentRequests 64 -clusternative.maxQueueDuration 60s -storageNode=... -search.maxLabelsAPIDuration 30s
2024-06-11T08:14:10.005Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmselect-20240425-150402-tags-v1.101.0-cluster-0-g310d100ed
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxConcurrentRequests="64"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxQueueDuration="1m0s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternativeListenAddr=":8401"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="10s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -http.connTimeout="3m0s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":8080"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -replicationFactor="2"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.logSlowQueryDuration="30s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxConcurrentRequests="96"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxLabelsAPIDuration="30s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueryDuration="3m0s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueueDuration="1m0s"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSamplesPerQuery="50000000000"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSeries="125000000"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="3000000"
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageNode="..."
2024-06-11T08:14:10.006Z	info	VictoriaMetrics/app/vmselect/main.go:96	starting netstorage at storageNodes [...]
2024-06-11T08:14:10.020Z	info	VictoriaMetrics/app/vmselect/main.go:110	started netstorage in 0.014 seconds
2024-06-11T08:14:10.023Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 59008376832 bytes, leaving 39338917888 bytes to the OS according to -memory.allowedPercent=60
2024-06-11T08:14:10.027Z	info	VictoriaMetrics/app/vmselect/main.go:125	starting vmselectapi server at ":8401"
2024-06-11T08:14:10.028Z	info	VictoriaMetrics/app/vmselect/main.go:131	started vmselectapi server at ":8401"
2024-06-11T08:14:10.028Z	info	VictoriaMetrics/lib/vmselectapi/server.go:158	accepting vmselect conns at 0.0.0.0:8401
2024-06-11T08:14:10.029Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:119	starting server at http://127.0.0.1:8080/
2024-06-11T08:14:10.029Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:120	pprof handlers are exposed at http://127.0.0.1:8080/debug/pprof/
2024-06-11T08:15:15.005Z	warn	VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1968	20 out of 20 vmstorage nodes at group "" were unavailable during the query; a sample error: cannot get label values from vmstorage storage8:8401: cannot obtain connection from a pool: cannot dial storage8:8401: dial tcp4 10.40.193.165:8401: connect: connection refused
2024-06-11T08:15:15.005Z	warn	VictoriaMetrics/app/vmselect/main.go:309	error in "/select/0/prometheus/api/v1/label/__name__/values?match%5B%5D=%7B__name__%3D%7E%22.*node.*%22%7D&limit=1000&start=1718060400&end=1718146799.999": cannot obtain values for label "__name__": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage storage8:8401: cannot obtain connection from a pool: cannot dial storage8:8401: dial tcp4 10.40.193.165:8401: connect: connection refused
2024-06-11T08:15:15.005Z	warn	VictoriaMetrics/app/vmselect/main.go:245	slow query according to -search.logSlowQueryDuration=30s: remoteAddr="10.14.27.100:49819", duration=31.243 seconds; requestURI: "/select/0/prometheus/api/v1/label/__name__/values?match%5B%5D=%7B__name__%3D%7E%22.*node.*%22%7D&limit=1000&start=1718060400&end=1718146799.999"
```

even with -search.maxLabelsAPIDuration 30s it cannot finish the query (but on other version it will finish in 7s. 

**1.97.1**
```
v1.97.1/vmselect-prod -dedup.minScrapeInterval 10s -httpListenAddr ':8080' -http.connTimeout 3m0s -replicationFactor 2 -search.maxConcurrentRequests 96 -search.maxQueryDuration 180s -search.maxQueueDuration 60s -search.maxSeries 125000000 -search.maxSamplesPerQuery 50000000000 -search.maxUniqueTimeseries 3000000 -search.logSlowQueryDuration 30s -clusternativeListenAddr ':8401' -clusternative.maxConcurrentRequests 64 -clusternative.maxQueueDuration 60s -storageNode=...
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmselect-20240201-133717-tags-v1.97.1-cluster-0-g765917ae6
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxConcurrentRequests="64"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxQueueDuration="1m0s"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternativeListenAddr=":8401"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="10s"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -http.connTimeout="3m0s"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":8080"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -replicationFactor="2"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.logSlowQueryDuration="30s"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxConcurrentRequests="96"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueryDuration="3m0s"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueueDuration="1m0s"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSamplesPerQuery="50000000000"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSeries="125000000"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="3000000"
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageNode="..."
2024-06-11T08:19:48.986Z	info	VictoriaMetrics/app/vmselect/main.go:96	starting netstorage at storageNodes [...]
2024-06-11T08:19:49.003Z	info	VictoriaMetrics/app/vmselect/main.go:110	started netstorage in 0.016 seconds
2024-06-11T08:19:49.006Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 59008376832 bytes, leaving 39338917888 bytes to the OS according to -memory.allowedPercent=60
2024-06-11T08:19:49.010Z	info	VictoriaMetrics/app/vmselect/main.go:125	starting vmselectapi server at ":8401"
2024-06-11T08:19:49.012Z	info	VictoriaMetrics/app/vmselect/main.go:131	started vmselectapi server at ":8401"
2024-06-11T08:19:49.012Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:101	starting http server at http://127.0.0.1:8080/
2024-06-11T08:19:49.012Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:102	pprof handlers are exposed at http://127.0.0.1:8080/debug/pprof/
2024-06-11T08:19:49.012Z	info	VictoriaMetrics/lib/vmselectapi/server.go:158	accepting vmselect conns at 0.0.0.0:8401
```
No errors in the logs, query will finish in 7s, but web doent show a thing. So might be a js issue? 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16777863/2b3bac10-73b4-4ba3-9a8c-a065b62f82fb)

with 1.98.0 it works. labels will be shown on a web page after about 7s. 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16777863/4390f699-7352-4c76-8e76-80f7dddacce0)

### To Reproduce

storage nodes are running 1.97
and I tried select nodes with 1.97, 1.98,1.101

### Version

 v1.98.0/vmselect-prod --version
vmselect-20240214-142128-tags-v1.98.0-cluster-0-g06da06dac

v1.97.1/vmselect-prod --version
vmselect-20240201-133717-tags-v1.97.1-cluster-0-g765917ae6

v1.101.0/vmselect-prod --version
vmselect-20240425-150402-tags-v1.101.0-cluster-0-g310d100ed

**Comment by Haleygo** [comment] 2024-06-14 08:05
Hello!
Which way do you use to auto-discover vmstorage nodes here, using service, DNS or just enumerating nodes?
For the log of v1.97.1, the query was succeed. So vmselect is not the problem, just VMUI got stuck, do you exprience this autocomplete issue all the time? And it's mostly like to be fixed in the lastest version, check our playground with latest [VMUI](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.range_input=30m&g0.end_input=2024-06-14T08%3A03%3A12&g0.relative_time=last_30_minutes&g0.tab=0).

About the v1.101.0, the query failed because vmselect failed to connect all the vmstorage nodes(20/20). Can you test the connection between vmselect and vmstorage nodes using command like curl?
>2024-06-11T08:15:15.005Z	warn	VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1968	20 out of 20 vmstorage nodes at group "" were unavailable during the query; a sample error: cannot get label values from vmstorage storage8:8401: cannot obtain connection from a pool: cannot dial storage8:8401: dial tcp4 10.40.193.165:8401: connect: connection refused

**Comment by evkuzin** [comment] 2024-06-14 15:29
> Which way do you use to auto-discover vmstorage nodes here, using service, DNS or just enumerating nodes?
enumerating nodes

> Can you test the connection between vmselect and vmstorage pods using command like curl?
THis is a production storage, all I did is I spin one test node and run these binaries one at a time
v1.101.0/vmselect-prod
v1.97.1/vmselect-prod
v1.97.1/vmselect-prod

Besides, this indeed looks like odd error, mayeb there was some netwok issues at that time. 
So I tested 1.101 again for you (as upi can see below it is failing after 30s of timeout. And if you check examples above for previous version - the same query would be finished in 7s. Looks like a degradation to me. 

```
v1.101.0/vmselect-prod -dedup.minScrapeInterval 10s -httpListenAddr ':8080' -http.connTimeout 3m0s -replicationFactor 2 -search.maxConcurrentRequests 96 -search.maxQueryDuration 180s -search.maxQueueDuration 60s -search.maxSeries 125000000 -search.maxSamplesPerQuery 50000000000 -search.maxUniqueTimeseries 3000000 -search.logSlowQueryDuration 30s -clusternativeListenAddr ':8401' -clusternative.maxConcurrentRequests 64 -clusternative.maxQueueDuration 60s -storageNode=... -search.maxLabelsAPIDuration 30s
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmselect-20240425-150402-tags-v1.101.0-cluster-0-g310d100ed
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxConcurrentRequests="64"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxQueueDuration="1m0s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternativeListenAddr=":8401"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="10s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -http.connTimeout="3m0s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":8080"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -replicationFactor="2"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.logSlowQueryDuration="30s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxConcurrentRequests="96"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxLabelsAPIDuration="30s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueryDuration="3m0s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueueDuration="1m0s"
2024-06-14T15:17:50.486Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSamplesPerQuery="50000000000"
2024-06-14T15:17:50.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSeries="125000000"
2024-06-14T15:17:50.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="3000000"
2024-06-14T15:17:50.487Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageNode="..."
2024-06-14T15:17:50.487Z	info	VictoriaMetrics/app/vmselect/main.go:96	starting netstorage at storageNodes [...]
2024-06-14T15:17:50.504Z	info	VictoriaMetrics/app/vmselect/main.go:110	started netstorage in 0.017 seconds
2024-06-14T15:17:50.508Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 59008376832 bytes, leaving 39338917888 bytes to the OS according to -memory.allowedPercent=60
2024-06-14T15:17:50.511Z	info	VictoriaMetrics/app/vmselect/main.go:125	starting vmselectapi server at ":8401"
2024-06-14T15:17:50.512Z	info	VictoriaMetrics/app/vmselect/main.go:131	started vmselectapi server at ":8401"
2024-06-14T15:17:50.512Z	info	VictoriaMetrics/lib/vmselectapi/server.go:158	accepting vmselect conns at 0.0.0.0:8401
2024-06-14T15:17:50.512Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:119	starting server at http://127.0.0.1:8080/
2024-06-14T15:17:50.512Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:120	pprof handlers are exposed at http://127.0.0.1:8080/debug/pprof/
2024-06-14T15:19:02.911Z	warn	VictoriaMetrics/app/vmselect/main.go:309	error in "/select/0/prometheus/api/v1/label/__name__/values?match%5B%5D=%7B__name__%3D%7E%22.*node.*%22%7D&limit=1000&start=1718319600&end=1718405999.999": cannot obtain values for label "__name__": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage storage:8401: cannot execute funcName="labelValues_v5" on vmstorage "10.40.193.9:8401" with timeout 30.000 seconds (elapsed 31.911 seconds); the timeout can be adjusted with `-search.maxLabelsAPIDuration` command-line flag: the number of matching timeseries exceeds 1000000; either narrow down the search or increase -search.max* command-line flag values at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits
2024-06-14T15:19:02.911Z	warn	VictoriaMetrics/app/vmselect/main.go:245	slow query according to -search.logSlowQueryDuration=30s: remoteAddr="10.14.27.100:50926", duration=31.038 seconds; requestURI: "/select/0/prometheus/api/v1/label/__name__/values?match%5B%5D=%7B__name__%3D%7E%22.*node.*%22%7D&limit=1000&start=1718319600&end=1718405999.999"
```

And just in case you would want me to test rc1:

```
v1.102.0-rc1/vmselect-prod -dedup.minScrapeInterval 10s -httpListenAddr ':8080' -http.connTimeout 3m0s -replicationFactor 2 -search.maxConcurrentRequests 96 -search.maxQueryDuration 180s -search.maxQueueDuration 60s -search.maxSeries 125000000 -search.maxSamplesPerQuery 50000000000 -search.maxUniqueTimeseries 3000000 -search.logSlowQueryDuration 30s -clusternativeListenAddr ':8401' -clusternative.maxConcurrentRequests 64 -clusternative.maxQueueDuration 60s -storageNode=... -search.maxLabelsAPIDuration 30s
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmselect-20240607-151249-tags-v1.102.0-rc1-cluster-0-g3f883559e2
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxConcurrentRequests="64"
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternative.maxQueueDuration="1m0s"
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -clusternativeListenAddr=":8401"
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dedup.minScrapeInterval="10s"
2024-06-14T15:27:32.023Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -http.connTimeout="3m0s"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -httpListenAddr=":8080"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -replicationFactor="2"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.logSlowQueryDuration="30s"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxConcurrentRequests="96"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxLabelsAPIDuration="30s"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueryDuration="3m0s"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxQueueDuration="1m0s"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSamplesPerQuery="50000000000"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxSeries="125000000"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -search.maxUniqueTimeseries="3000000"
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -storageNode="..."
2024-06-14T15:27:32.024Z	info	VictoriaMetrics/app/vmselect/main.go:96	starting netstorage at storageNodes [...]
2024-06-14T15:27:32.037Z	info	VictoriaMetrics/app/vmselect/main.go:110	started netstorage in 0.013 seconds
2024-06-14T15:27:32.040Z	info	VictoriaMetrics/lib/memory/memory.go:42	limiting caches to 59008376832 bytes, leaving 39338917888 bytes to the OS according to -memory.allowedPercent=60
2024-06-14T15:27:32.043Z	info	VictoriaMetrics/app/vmselect/main.go:125	starting vmselectapi server at ":8401"
2024-06-14T15:27:32.044Z	info	VictoriaMetrics/app/vmselect/main.go:131	started vmselectapi server at ":8401"
2024-06-14T15:27:32.044Z	info	VictoriaMetrics/lib/vmselectapi/server.go:158	accepting vmselect conns at 0.0.0.0:8401
2024-06-14T15:27:32.044Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:119	starting server at http://127.0.0.1:8080/
2024-06-14T15:27:32.044Z	info	VictoriaMetrics/lib/httpserver/httpserver.go:120	pprof handlers are exposed at http://127.0.0.1:8080/debug/pprof/
2024-06-14T15:28:10.908Z	warn	VictoriaMetrics/app/vmselect/main.go:309	error in "/select/0/prometheus/api/v1/label/__name__/values?match%5B%5D=%7B__name__%3D%7E%22.*node.*%22%7D&limit=1000&start=1718319600&end=1718405999.999": cannot obtain values for label "__name__": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage storage8:8401: cannot execute funcName="labelValues_v5" on vmstorage "10.40.193.25:8401" with timeout 30.000 seconds (elapsed 31.908 seconds); the timeout can be adjusted with `-search.maxLabelsAPIDuration` command-line flag: the number of matching timeseries exceeds 1000000; either narrow down the search or increase -search.max* command-line flag values at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits
2024-06-14T15:28:10.908Z	warn	VictoriaMetrics/app/vmselect/main.go:245	slow query according to -search.logSlowQueryDuration=30s: remoteAddr="10.14.27.100:54618", duration=31.137 seconds; requestURI: "/select/0/prometheus/api/v1/label/__name__/values?match%5B%5D=%7B__name__%3D%7E%22.*node.*%22%7D&limit=1000&start=1718319600&end=1718405999.999"
```

**Comment by evkuzin** [comment] 2024-06-14 15:50
TL/DR

@Haleygo - as you can see, old version would run query and return result in 7s, new version will fail after 30s limit on the same dataset.

**Comment by evkuzin** [comment] 2024-06-15 21:07
And, just to be on the same page - I was running the same storage version in all tests.

**Comment by Haleygo** [comment] 2024-06-17 09:55
Okay, the error message on v1.101.0 has been changed. Before it says "connection refused" which indicates connection error between vmselect and vmstorage, now it gives error
>timeout 30.000 seconds (elapsed 31.908 seconds); the timeout can be adjusted with `-search.maxLabelsAPIDuration` command-line flag: the number of matching timeseries exceeds 1000000; either narrow down the search or increase -search.max* command-line flag values at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits

It's caused by `-search.maxLabelsAPISeries(default 1000000)` which is introduced from [v1.99.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.99.0), to limit CPU and RAM usage for [/api/v1/labels](https://docs.victoriametrics.com/url-examples/#apiv1labels), [/api/v1/label/.../values](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) and [/api/v1/series](https://docs.victoriametrics.com/url-examples/#apiv1series) APIs.
>-search.maxLabelsAPISeries int
   The maximum number of time series, which could be scanned when searching for the the matching time series at /api/v1/labels and /api/v1/label/.../values. This option allows limiting memory usage and CPU usage. See also -search.maxLabelsAPIDuration, -search.maxTagKeys, -search.maxTagValues and -search.ignoreExtraFiltersAtLabelsAPI (default 1000000)

Could you try increase the `-search.maxLabelsAPISeries` on vmselect side to higher value, check if the api works?

**Comment by evkuzin** [comment] 2024-06-17 11:39
Previous versions as I mentioned above did that in 7s. And we are changing only vmselect binary 🤔 What could be wrong?

**Comment by evkuzin** [comment] 2024-06-17 11:42
Hm... after I restarted it and run queries a few time it seems like populated some file cache and next queries run in 5s. Which is good. Let me ran a few more tests and see how it all goes.

**Closed** 2024-08-16 10:00 UTC
Labels: bug, question, need more info
