### ISSUE TITLE
Unicode handling issue in vmselect

### ISSUE THREAD

**Issue by zcavaliero** [VictoriaMetrics/VictoriaMetrics#613] opened 2020-07-08 20:21 UTC
I have an issue where prometheus has a label that has a unicode character in it and when grafana pulls the data from promtheus, promtheus handles the conversion. When I do the same query with the vmselect in grafana, the unicode character is not handled the same and returns and error in grafana.

Examples of json returned:

Prometheus result:
`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"cf_application_info","application_id":"foo_bar","application_name":"foo_bar","buildpack":"client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=\u001b[34mv4.25\u001b[0m-offline-https://github.com/cloudfoundry/java-buildpack.git#349e93b java-main java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk...","deployment":"cf","detected_buildpack":"client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=\u001b[34mv4.25\u001b[0m-offline-https://github.com/cloudfoundry/java-buildpack.git#349e93b java-main java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk...","env":"prod","environment":"foo_bar","instance":"foo_bar:443","job":"cf_exporter","organization_id":"foo_bar","organization_name":"foo_bar","space_id":"foo_bar","space_name":"instances","stack_id":"foo_bar,"state":"STARTED"},"value":[1,"1"]}]}}`

vmselect result:
`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"cf_application_info","application_id":"foo_bar","application_name":"foo_bar","buildpack":"client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=[34mv4.25[0m-offline-https://github.com/cloudfoundry/java-buildpack.git#349e93b java-main java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk...","deployment":"cf","detected_buildpack":"client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=[34mv4.25[0m-offline-https://github.com/cloudfoundry/java-buildpack.git#349e93b java-main java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk...","env":"prod","environment":"foo_bar","instance":"foo_bar:443","job":"cf_exporter","organization_id":"foo_bar","organization_name":"foo_bar","space_id":"foo_bar","space_name":"instances","stack_id":"foo_bar","state":"STARTED"},"value":[1,"1"]}]}}`

**Comment by valyala** [comment] 2020-07-10 10:08
The issue must be fixed in the following commits:

* For single-node version - e5b9f47623fe332fdbe7e525101d87d68a0515c6
* For cluster version - 5910207d6154dc69ad7f8943998ddb2179418bc2

@zcavaliero , could you build VictoriaMetrics from these commits according to the following docs and verify whether the issue is fixed there?

* [How to build single-node victoriametrics](https://victoriametrics.github.io/#how-to-build-from-sources)
* [How to build cluster version](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#building-from-sources)

**Comment by zcavaliero** [comment] 2020-07-10 14:00
@valyala Can I just build the vmselect or do I need to build all three?

**Comment by zcavaliero** [comment] 2020-07-10 14:35
@valyala Nevermind, I just tested vmselect and everything looks good!!

{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"cf_application_info","application_id":"foo_bar","application_name":"foo_bar","buildpack":"client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=\u001b[34mv4.25\u001b[0m-offline-https://github.com/cloudfoundry/java-buildpack.git#349e93b java-main java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk...","deployment":"cf","detected_buildpack":"client-certificate-mapper=1.11.0_RELEASE container-security-provider=1.16.0_RELEASE java-buildpack=\u001b[34mv4.25\u001b[0m-offline-https://github.com/cloudfoundry/java-buildpack.git#349e93b java-main java-opts java-security jvmkill-agent=1.16.0_RELEASE open-jdk...","env":"foo_bar","environment":"foo_bar","instance":"foo_bar:443","job":"foo_bar","organization_id":"foo_bar","organization_name":"foo_bar","space_id":"foo_bar","space_name":"instances","stack_id":"foo_bar","state":"STARTED"},"value":[1,"1"]}]}}

Will this get put into an official release?

**Comment by valyala** [comment] 2020-07-13 12:48
> Will this get put into an official release?

Yes, the bugfix will be included in the next release. Thanks for the testing!

**Closed** 2020-07-13 13:56 UTC
Labels: bug

**Comment by valyala** [comment] 2020-07-14 15:13
@zcavaliero , the bugfix has been included in [v1.38.1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) of VictoriaMetrics.
