### ISSUE TITLE
when query instant data, why response query old data

### ISSUE THREAD

**Issue by slm940208** [VictoriaMetrics/VictoriaMetrics#1724] opened 2021-10-19 09:09 UTC
use vm cluster version
first delete po, in 5 minutes， when query instant data, will response old data
![Snipaste_2021-10-19_17-00-30](https://user-images.githubusercontent.com/40267976/137879511-68546e0e-6ab5-46f0-b608-fbfbd2cfc548.png)

**Comment by slm940208** [comment] 2021-10-20 01:29
> The screenshot shows two time series with different `uid` label. It looks like the pod has been re-deployed in the time range between 16:56:00 and 16:56:30 and the restarted pod had the updated `uid` label, because the `uid` is updated with each deployment according to [kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids).

**Comment by slm940208** [comment] 2021-10-20 01:40
@valyala yes, the pod has re-deployed, so uid changed, so when query instant data, should only response new pod data, but now , the old and new data are returned. After 5 minutes, only new data will be returned.

In this case, when we use prometheus, only new data will be returned.

So now after the conversion from Prometheus to VM, I have this question

**Comment by valyala** [comment] 2024-02-13 01:05
Closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1025

**Closed by valyala** 2024-02-13 01:05 UTC
Labels: question, need more info
