### ISSUE TITLE
vmagent: endpointslice discovery missing role: service labels

### ISSUE THREAD

**Issue by Alexul** [VictoriaMetrics/VictoriaMetrics#2823] opened 2022-07-04 05:42 UTC
Reproducing on latest vmagent 1.78.0:
When trying to migrate from /endpoints to /endpointslices (missing metrics when number of targets is over 1000)
Encountered a problem, vmagent seems to behave not per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpointslice
specifically all the role: service labels are missing, so relabel_configs are failing

**To Reproduce**
Running with
> relabel_debug: true
>         kubernetes_sd_configs:
>         - role: endpoints
In the debug i see all the needed labels:
`{"ts":"2022-07-04T05:32:30.087Z","level":"info","caller":"VictoriaMetrics/lib/promrelabel/relabel.go:60","msg":"\nRelabel  In: {__address__=\"10.209.64.214:53\",__meta_kubernetes_namespace=\"kube-system\",__meta_kubernetes_pod_annotation_prometheus_io_port=\"9253\",__meta_kubernetes_pod_annotation_prometheus_io_scrape=\"true\",__meta_kubernetes_pod_annotationpresent_prometheus_io_port=\"true\",__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape=\"true\",__meta_kubernetes_pod_container_name=\"node-cache\",__meta_kubernetes_pod_container_port_name=\"dns-tcp\",__meta_kubernetes_pod_container_port_number=\"53\",__meta_kubernetes_pod_container_port_protocol=\"TCP\",__meta_kubernetes_pod_controller_kind=\"DaemonSet\",__meta_kubernetes_pod_controller_name=\"node-local-dns\",__meta_kubernetes_pod_host_ip=\"10.209.64.214\",__meta_kubernetes_pod_ip=\"10.209.64.214\",__meta_kubernetes_pod_label_controller_revision_hash=\"88fdb5f6c\",__meta_kubernetes_pod_label_k8s_app=\"node-local-dns\",__meta_kubernetes_pod_label_pod_template_generation=\"1\",__meta_kubernetes_pod_labelpresent_controller_revision_hash=\"true\",__meta_kubernetes_pod_labelpresent_k8s_app=\"true\",__meta_kubernetes_pod_labelpresent_pod_template_generation=\"true\",__meta_kubernetes_pod_name=\"node-local-dns-srpd6\",__meta_kubernetes_pod_node_name=\"i-05dce92bf5f893c56\",__meta_kubernetes_pod_phase=\"Running\",__meta_kubernetes_pod_ready=\"true\",__meta_kubernetes_pod_uid=\"f1d7fbfe-b71e-45a8-830e-5b7a4ee45ada\",__meta_kubernetes_service_annotation_kubectl_kubernetes_io_last_applied_configuration=\"{\\\"apiVersion\\\":\\\"v1\\\",\\\"kind\\\":\\\"Service\\\",\\\"metadata\\\":{\\\"annotations\\\":{\\\"prometheus.io/port\\\":\\\"9253\\\",\\\"prometheus.io/scrape\\\":\\\"true\\\"},\\\"labels\\\":{\\\"k8s-app\\\":\\\"node-local-dns\\\"},\\\"name\\\":\\\"node-local-dns\\\",\\\"namespace\\\":\\\"kube-system\\\"},\\\"spec\\\":{\\\"clusterIP\\\":\\\"None\\\",\\\"ports\\\":[{\\\"name\\\":\\\"metrics\\\",\\\"port\\\":9253,\\\"targetPort\\\":9253}],\\\"selector\\\":{\\\"k8s-app\\\":\\\"node-local-dns\\\"}}}\\n\",__meta_kubernetes_service_annotation_prometheus_io_port=\"9253\",__meta_kubernetes_service_annotation_prometheus_io_scrape=\"true\",__meta_kubernetes_service_annotationpresent_kubectl_kubernetes_io_last_applied_configuration=\"true\",__meta_kubernetes_service_annotationpresent_prometheus_io_port=\"true\",__meta_kubernetes_service_annotationpresent_prometheus_io_scrape=\"true\",__meta_kubernetes_service_cluster_ip=\"None\",__meta_kubernetes_service_label_k8s_app=\"node-local-dns\",__meta_kubernetes_service_labelpresent_k8s_app=\"true\",__meta_kubernetes_service_name=\"node-local-dns\",__meta_kubernetes_service_type=\"ClusterIP\",__metrics_path__=\"/metrics\",__scheme__=\"http\",__scrape_interval__=\"1m0s\",__scrape_timeout__=\"20s\",dc=\"208\",job=\"kubernetes-service-endpoints_208_kube\"}\nRelabel Out: DROPPED - all labels removed"}`

When running with:

> relabel_debug: true
>         kubernetes_sd_configs:
>         - role: endpointslice
missing labels in debug:
`{"ts":"2022-07-03T11:06:47.437Z","level":"info","caller":"VictoriaMetrics/lib/promrelabel/relabel.go:60","msg":"\nRelabel  In: {__address__=\"10.209.81.105:53\",__meta_kubernetes_namespace=\"kube-system\",__meta_kubernetes_pod_annotation_prometheus_io_port=\"9253\",__meta_kubernetes_pod_annotation_prometheus_io_scrape=\"true\",__meta_kubernetes_pod_annotationpresent_prometheus_io_port=\"true\",__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape=\"true\",__meta_kubernetes_pod_container_name=\"node-cache\",__meta_kubernetes_pod_container_port_name=\"dns-tcp\",__meta_kubernetes_pod_container_port_number=\"53\",__meta_kubernetes_pod_container_port_protocol=\"TCP\",__meta_kubernetes_pod_controller_kind=\"DaemonSet\",__meta_kubernetes_pod_controller_name=\"node-local-dns\",__meta_kubernetes_pod_host_ip=\"10.209.81.105\",__meta_kubernetes_pod_ip=\"10.209.81.105\",__meta_kubernetes_pod_label_controller_revision_hash=\"88fdb5f6c\",__meta_kubernetes_pod_label_k8s_app=\"node-local-dns\",__meta_kubernetes_pod_label_pod_template_generation=\"1\",__meta_kubernetes_pod_labelpresent_controller_revision_hash=\"true\",__meta_kubernetes_pod_labelpresent_k8s_app=\"true\",__meta_kubernetes_pod_labelpresent_pod_template_generation=\"true\",__meta_kubernetes_pod_name=\"node-local-dns-qlgvz\",__meta_kubernetes_pod_node_name=\"i-0c118f91cf243e040\",__meta_kubernetes_pod_phase=\"Running\",__meta_kubernetes_pod_ready=\"true\",__meta_kubernetes_pod_uid=\"e6f1ccf1-ab9f-4a29-a3d7-226a6d0e649f\",__metrics_path__=\"/metrics\",__scheme__=\"http\",__scrape_interval__=\"1m0s\",__scrape_timeout__=\"20s\",dc=\"208\",job=\"kubernetes-service-endpoints_208_kube\"}\nRelabel Out: DROPPED - all labels removed"}
`

**Expected behavior**
Should behave the same as /endpoints
If the endpoints belong to a service, all labels of the role: service discovery are attached.
For all targets backed by a pod, all labels of the role: pod discovery are attached.

**Comment by Alexul** [comment] 2022-07-10 08:38
Sorry, just checked with 1.78.1, still missing "_service_" labels:
```{
  "ts": "2022-07-10T08:29:57.635Z",
  "level": "info",
  "caller": "VictoriaMetrics/lib/promrelabel/relabel.go:60",
  "msg": "\nRelabel  In: {__address__=\"10.209.42.98:53\",__meta_kubernetes_endpointslice_address_target_kind=\"Pod\",__meta_kubernetes_endpointslice_address_target_name=\"coredns-56dd667f7c-djhsl\",__meta_kubernetes_endpointslice_address_type=\"IPv4\",__meta_kubernetes_endpointslice_annotation_endpoints_kubernetes_io_last_change_trigger_time=\"2022-07-08T20:37:36Z\",__meta_kubernetes_endpointslice_annotationpresent_endpoints_kubernetes_io_last_change_trigger_time=\"true\",__meta_kubernetes_endpointslice_endpoint_conditions_ready=\"true\",__meta_kubernetes_endpointslice_label_addon_kops_k8s_io_name=\"coredns.addons.k8s.io\",__meta_kubernetes_endpointslice_label_app_kubernetes_io_managed_by=\"kops\",__meta_kubernetes_endpointslice_label_endpointslice_kubernetes_io_managed_by=\"endpointslice-controller.k8s.io\",__meta_kubernetes_endpointslice_label_k8s_addon=\"coredns.addons.k8s.io\",__meta_kubernetes_endpointslice_label_k8s_app=\"kube-dns\",__meta_kubernetes_endpointslice_label_kubernetes_io_cluster_service=\"true\",__meta_kubernetes_endpointslice_label_kubernetes_io_name=\"CoreDNS\",__meta_kubernetes_endpointslice_label_kubernetes_io_service_name=\"kube-dns\",__meta_kubernetes_endpointslice_labelpresent_addon_kops_k8s_io_name=\"true\",__meta_kubernetes_endpointslice_labelpresent_app_kubernetes_io_managed_by=\"true\",__meta_kubernetes_endpointslice_labelpresent_endpointslice_kubernetes_io_managed_by=\"true\",__meta_kubernetes_endpointslice_labelpresent_k8s_addon=\"true\",__meta_kubernetes_endpointslice_labelpresent_k8s_app=\"true\",__meta_kubernetes_endpointslice_labelpresent_kubernetes_io_cluster_service=\"true\",__meta_kubernetes_endpointslice_labelpresent_kubernetes_io_name=\"true\",__meta_kubernetes_endpointslice_labelpresent_kubernetes_io_service_name=\"true\",__meta_kubernetes_endpointslice_name=\"kube-dns-dz9ts\",__meta_kubernetes_endpointslice_port=\"53\",__meta_kubernetes_endpointslice_port_name=\"dns-tcp\",__meta_kubernetes_endpointslice_port_protocol=\"TCP\",__meta_kubernetes_namespace=\"kube-system\",__meta_kubernetes_pod_container_name=\"coredns\",__meta_kubernetes_pod_container_port_name=\"dns\",__meta_kubernetes_pod_container_port_number=\"53\",__meta_kubernetes_pod_container_port_protocol=\"UDP\",__meta_kubernetes_pod_controller_kind=\"ReplicaSet\",__meta_kubernetes_pod_controller_name=\"coredns-56dd667f7c\",__meta_kubernetes_pod_host_ip=\"10.209.67.52\",__meta_kubernetes_pod_ip=\"10.209.42.98\",__meta_kubernetes_pod_label_k8s_app=\"kube-dns\",__meta_kubernetes_pod_label_kops_k8s_io_managed_by=\"kops\",__meta_kubernetes_pod_label_pod_template_hash=\"56dd667f7c\",__meta_kubernetes_pod_labelpresent_k8s_app=\"true\",__meta_kubernetes_pod_labelpresent_kops_k8s_io_managed_by=\"true\",__meta_kubernetes_pod_labelpresent_pod_template_hash=\"true\",__meta_kubernetes_pod_name=\"coredns-56dd667f7c-djhsl\",__meta_kubernetes_pod_node_name=\"i-02f3643f3c3613e57\",__meta_kubernetes_pod_phase=\"Running\",__meta_kubernetes_pod_ready=\"true\",__meta_kubernetes_pod_uid=\"94ef43a4-2891-439e-92df-fe9937e188d3\",__metrics_path__=\"/metrics\",__scheme__=\"http\",__scrape_interval__=\"1m0s\",__scrape_timeout__=\"20s\",dc=\"208\",job=\"kubernetes-service-endpoints_208_kube\"}\nRelabel Out: DROPPED - all labels removed"
}```

**Comment by Alexul** [comment] 2022-07-14 10:32
I see, thank you. Confirming i see the labels in debug with heads-master-0-gf9500abfe (and they are not DROPPING now)
Still somehow 0/0 up for that scraping job, but its probably on my side now. Will dig deeper
`{"ts":"2022-07-14T10:27:26.918Z","level":"info","caller":"VictoriaMetrics/lib/promrelabel/relabel.go:81","msg":"\nRelabel  In: {__address__=\"10.208.1.83:9100\",__meta_kubernetes_endpointslice_address_target_kind=\"Pod\",__meta_kubernetes_endpointslice_address_target_name=\"node-exporter-node-5vmdb\",__meta_kubernetes_endpointslice_address_type=\"IPv4\",__meta_kubernetes_endpointslice_endpoint_conditions_ready=\"true\",__meta_kubernetes_endpointslice_label_app=\"prometheus-node-exporter\",__meta_kubernetes_endpointslice_label_app_kubernetes_io_version=\"\",__meta_kubernetes_endpointslice_label_chart=\"prometheus-node-exporter-3.3.0\",__meta_kubernetes_endpointslice_label_endpointslice_kubernetes_io_managed_by=\"endpointslice-controller.k8s.io\",__meta_kubernetes_endpointslice_label_helm_sh_chart=\"\",__meta_kubernetes_endpointslice_label_heritage=\"Helm\",__meta_kubernetes_endpointslice_label_kubernetes_io_service_name=\"node-exporter-node\",__meta_kubernetes_endpointslice_label_release=\"node-exporter-node\",__meta_kubernetes_endpointslice_label_role=\"node\",__meta_kubernetes_endpointslice_labelpresent_app=\"true\",__meta_kubernetes_endpointslice_labelpresent_app_kubernetes_io_version=\"true\",__meta_kubernetes_endpointslice_labelpresent_chart=\"true\",__meta_kubernetes_endpointslice_labelpresent_endpointslice_kubernetes_io_managed_by=\"true\",__meta_kubernetes_endpointslice_labelpresent_helm_sh_chart=\"true\",__meta_kubernetes_endpointslice_labelpresent_heritage=\"true\",__meta_kubernetes_endpointslice_labelpresent_kubernetes_io_service_name=\"true\",__meta_kubernetes_endpointslice_labelpresent_release=\"true\",__meta_kubernetes_endpointslice_labelpresent_role=\"true\",__meta_kubernetes_endpointslice_name=\"node-exporter-node-wl29z\",__meta_kubernetes_endpointslice_port=\"9100\",__meta_kubernetes_endpointslice_port_name=\"metrics\",__meta_kubernetes_endpointslice_port_protocol=\"TCP\",__meta_kubernetes_namespace=\"monitoring\",__meta_kubernetes_pod_annotation_cluster_autoscaler_kubernetes_io_safe_to_evict=\"true\",__meta_kubernetes_pod_annotationpresent_cluster_autoscaler_kubernetes_io_safe_to_evict=\"true\",__meta_kubernetes_pod_container_name=\"node-exporter\",__meta_kubernetes_pod_container_port_name=\"metrics\",__meta_kubernetes_pod_container_port_number=\"9100\",__meta_kubernetes_pod_container_port_protocol=\"TCP\",__meta_kubernetes_pod_controller_kind=\"DaemonSet\",__meta_kubernetes_pod_controller_name=\"node-exporter-node\",__meta_kubernetes_pod_host_ip=\"10.208.1.83\",__meta_kubernetes_pod_ip=\"10.208.1.83\",__meta_kubernetes_pod_label_app=\"prometheus-node-exporter\",__meta_kubernetes_pod_label_chart=\"prometheus-node-exporter-3.3.0\",__meta_kubernetes_pod_label_controller_revision_hash=\"7f5d9c7957\",__meta_kubernetes_pod_label_heritage=\"Helm\",__meta_kubernetes_pod_label_pod_template_generation=\"2\",__meta_kubernetes_pod_label_release=\"node-exporter-node\",__meta_kubernetes_pod_label_role=\"node\",__meta_kubernetes_pod_labelpresent_app=\"true\",__meta_kubernetes_pod_labelpresent_chart=\"true\",__meta_kubernetes_pod_labelpresent_controller_revision_hash=\"true\",__meta_kubernetes_pod_labelpresent_heritage=\"true\",__meta_kubernetes_pod_labelpresent_pod_template_generation=\"true\",__meta_kubernetes_pod_labelpresent_release=\"true\",__meta_kubernetes_pod_labelpresent_role=\"true\",__meta_kubernetes_pod_name=\"node-exporter-node-5vmdb\",__meta_kubernetes_pod_node_name=\"i-00cba364a876b3d99\",__meta_kubernetes_pod_phase=\"Running\",__meta_kubernetes_pod_ready=\"true\",__meta_kubernetes_pod_uid=\"a945363d-12d8-481c-8303-a08982053320\",__meta_kubernetes_service_annotation_prometheus_io_scrape=\"true\",__meta_kubernetes_service_annotationpresent_prometheus_io_scrape=\"true\",__meta_kubernetes_service_cluster_ip=\"10.209.163.23\",__meta_kubernetes_service_label_app=\"prometheus-node-exporter\",__meta_kubernetes_service_label_app_kubernetes_io_version=\"\",__meta_kubernetes_service_label_chart=\"prometheus-node-exporter-3.3.0\",__meta_kubernetes_service_label_helm_sh_chart=\"\",__meta_kubernetes_service_label_heritage=\"Helm\",__meta_kubernetes_service_label_release=\"node-exporter-node\",__meta_kubernetes_service_label_role=\"node\",__meta_kubernetes_service_labelpresent_app=\"true\",__meta_kubernetes_service_labelpresent_app_kubernetes_io_version=\"true\",__meta_kubernetes_service_labelpresent_chart=\"true\",__meta_kubernetes_service_labelpresent_helm_sh_chart=\"true\",__meta_kubernetes_service_labelpresent_heritage=\"true\",__meta_kubernetes_service_labelpresent_release=\"true\",__meta_kubernetes_service_labelpresent_role=\"true\",__meta_kubernetes_service_name=\"node-exporter-node\",__meta_kubernetes_service_type=\"ClusterIP\",__metrics_path__=\"/metrics\",__scheme__=\"http\",__scrape_interval__=\"1m0s\",__scrape_timeout__=\"20s\",dc=\"208\",job=\"kubernetes-service-endpoints_208_kube\"}\nRelabel Out: {__address__=\"10.208.1.83:9100\",__meta_kubernetes_endpointslice_address_target_kind=\"Pod\",__meta_kubernetes_endpointslice_address_target_name=\"node-exporter-node-5vmdb\",__meta_kubernetes_endpointslice_address_type=\"IPv4\",__meta_kubernetes_endpointslice_endpoint_conditions_ready=\"true\",__meta_kubernetes_endpointslice_label_app=\"prometheus-node-exporter\",__meta_kubernetes_endpointslice_label_chart=\"prometheus-node-exporter-3.3.0\",__meta_kubernetes_endpointslice_label_endpointslice_kubernetes_io_managed_by=\"endpointslice-controller.k8s.io\",__meta_kubernetes_endpointslice_label_heritage=\"Helm\",__meta_kubernetes_endpointslice_label_kubernetes_io_service_name=\"node-exporter-node\",__meta_kubernetes_endpointslice_label_release=\"node-exporter-node\",__meta_kubernetes_endpointslice_label_role=\"node\",__meta_kubernetes_endpointslice_labelpresent_app=\"true\",__meta_kubernetes_endpointslice_labelpresent_app_kubernetes_io_version=\"true\",__meta_kubernetes_endpointslice_labelpresent_chart=\"true\",__meta_kubernetes_endpointslice_labelpresent_endpointslice_kubernetes_io_managed_by=\"true\",__meta_kubernetes_endpointslice_labelpresent_helm_sh_chart=\"true\",__meta_kubernetes_endpointslice_labelpresent_heritage=\"true\",__meta_kubernetes_endpointslice_labelpresent_kubernetes_io_service_name=\"true\",__meta_kubernetes_endpointslice_labelpresent_release=\"true\",__meta_kubernetes_endpointslice_labelpresent_role=\"true\",__meta_kubernetes_endpointslice_name=\"node-exporter-node-wl29z\",__meta_kubernetes_endpointslice_port=\"9100\",__meta_kubernetes_endpointslice_port_name=\"metrics\",__meta_kubernetes_endpointslice_port_protocol=\"TCP\",__meta_kubernetes_namespace=\"monitoring\",__meta_kubernetes_pod_annotation_cluster_autoscaler_kubernetes_io_safe_to_evict=\"true\",__meta_kubernetes_pod_annotationpresent_cluster_autoscaler_kubernetes_io_safe_to_evict=\"true\",__meta_kubernetes_pod_container_name=\"node-exporter\",__meta_kubernetes_pod_container_port_name=\"metrics\",__meta_kubernetes_pod_container_port_number=\"9100\",__meta_kubernetes_pod_container_port_protocol=\"TCP\",__meta_kubernetes_pod_controller_kind=\"DaemonSet\",__meta_kubernetes_pod_controller_name=\"node-exporter-node\",__meta_kubernetes_pod_host_ip=\"10.208.1.83\",__meta_kubernetes_pod_ip=\"10.208.1.83\",__meta_kubernetes_pod_label_app=\"prometheus-node-exporter\",__meta_kubernetes_pod_label_chart=\"prometheus-node-exporter-3.3.0\",__meta_kubernetes_pod_label_controller_revision_hash=\"7f5d9c7957\",__meta_kubernetes_pod_label_heritage=\"Helm\",__meta_kubernetes_pod_label_pod_template_generation=\"2\",__meta_kubernetes_pod_label_release=\"node-exporter-node\",__meta_kubernetes_pod_label_role=\"node\",__meta_kubernetes_pod_labelpresent_app=\"true\",__meta_kubernetes_pod_labelpresent_chart=\"true\",__meta_kubernetes_pod_labelpresent_controller_revision_hash=\"true\",__meta_kubernetes_pod_labelpresent_heritage=\"true\",__meta_kubernetes_pod_labelpresent_pod_template_generation=\"true\",__meta_kubernetes_pod_labelpresent_release=\"true\",__meta_kubernetes_pod_labelpresent_role=\"true\",__meta_kubernetes_pod_name=\"node-exporter-node-5vmdb\",__meta_kubernetes_pod_node_name=\"i-00cba364a876b3d99\",__meta_kubernetes_pod_phase=\"Running\",__meta_kubernetes_pod_ready=\"true\",__meta_kubernetes_pod_uid=\"a945363d-12d8-481c-8303-a08982053320\",__meta_kubernetes_service_annotation_prometheus_io_scrape=\"true\",__meta_kubernetes_service_annotationpresent_prometheus_io_scrape=\"true\",__meta_kubernetes_service_cluster_ip=\"10.209.163.23\",__meta_kubernetes_service_label_app=\"prometheus-node-exporter\",__meta_kubernetes_service_label_chart=\"prometheus-node-exporter-3.3.0\",__meta_kubernetes_service_label_heritage=\"Helm\",__meta_kubernetes_service_label_release=\"node-exporter-node\",__meta_kubernetes_service_label_role=\"node\",__meta_kubernetes_service_labelpresent_app=\"true\",__meta_kubernetes_service_labelpresent_app_kubernetes_io_version=\"true\",__meta_kubernetes_service_labelpresent_chart=\"true\",__meta_kubernetes_service_labelpresent_helm_sh_chart=\"true\",__meta_kubernetes_service_labelpresent_heritage=\"true\",__meta_kubernetes_service_labelpresent_release=\"true\",__meta_kubernetes_service_labelpresent_role=\"true\",__meta_kubernetes_service_name=\"node-exporter-node\",__meta_kubernetes_service_type=\"ClusterIP\",__metrics_path__=\"/metrics\",__scheme__=\"http\",__scrape_interval__=\"1m0s\",__scrape_timeout__=\"20s\",app=\"prometheus-node-exporter\",chart=\"prometheus-node-exporter-3.3.0\",dc=\"208\",heritage=\"Helm\",job=\"kubernetes-service-endpoints_208_kube\",kubernetes_name=\"node-exporter-node\",kubernetes_namespace=\"monitoring\",kubernetes_pod_node_name=\"i-00cba364a876b3d99\",release=\"node-exporter-node\",role=\"node\"}"}`

**Comment by valyala** [comment] 2022-07-14 20:56
@Alexul , thanks for the confirmation that the issue is fixed!

`vmagent` should properly set service-level labels for `role: endpointslice` targets starting from [v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue then.

**Closed by valyala** 2022-07-14 20:56 UTC
Labels: bug, vmagent

**Comment by Alexul** [comment] 2022-07-17 09:43
@valyala Thank you, works perfect in v1.79.0
What got me confused for some time and probably a bug:
Running with "relabel_debug: true" breaks metrics collection

Scenario: perfectly running job config just adding "relabel_debug: true" to the job and amount of "Active Targets" drops to 0/0
removing debug, metrics are back
Reproducing with both endpointslices and endpoints, for me
