### ISSUE TITLE
Add backoff time flag to vmAlert 

### ISSUE THREAD

**Issue by weenxin** [VictoriaMetrics/VictoriaMetrics#668] opened 2020-08-04 09:22 UTC
**Is your feature request related to a problem? Please describe.**

In Our usage, We use `vmAgent` as a scraper, It will scrape target metrics, and then push data to `vmstorage`, However , When The data is very huge , It will takes some time. 

And I do some `recording rule`  in `vmAlert`, Some time the recording rule calc less data than `vmagent` scrape because the latency write.

**Describe the solution you'd like**
And a flag like `--query.backoff` flag to wait the write end.

**Comment by weenxin** [comment] 2020-08-04 09:27
Or we can add `backoff` option on `recording rule` config file.

**Comment by valyala** [comment] 2020-09-21 12:59
FYI, the commit 5dffc7a553b35b3269c74b03239a3b5fef3f2eb3 adds `-datasource.lookback` command-line flag to `vmalert`, which allows setting the time shift for querying the data. See `vmalert -help` output for this flag below:
```
-datasource.lookback duration
       Lookback defines how far to look into past when evaluating queries. For example, if datasource.lookback=5m then param "time" with value now()-5m will be added to every query.
```

This commit will be included in the next release.

**Comment by valyala** [comment] 2020-09-23 09:08
FYI, the `-datasource.lookback` command-line flag has been added to `vmalert` starting from [v1.41.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Closed by valyala** 2020-09-23 09:08 UTC
Labels: enhancement, vmalert

**Comment by GerryYuan** [comment] 2021-08-03 10:34
![image](https://user-images.githubusercontent.com/11907624/128000956-7575b8d0-a0ce-4a10-ade3-cf1a24604fe9.png)

1、Data aggregated by vmalert's recording-rule, the last few points of the data queried are always completed by the VM, is this caused by the delay in the execution of the recording-rule?

```yml
groups:
 - name: xxx
   interval: 10s
   rules:
       - record: xxx
         expr: sum(rate(xxxxx)) by(job, instance,xxxx.....) 

--datasource.lookback=5s
```

**Comment by hagen1778** [comment] 2021-08-03 11:09
Hi @GerryYuan! Not sure I'm understand what exactly you did here. Is the annotation on the graph is the moment when you've added `--datasource.lookback=5s` param? Or it was always there?

**Comment by GerryYuan** [comment] 2021-08-03 12:14
> Hi @GerryYuan! Not sure I'm understand what exactly you did here. Is the annotation on the graph is the moment when you've added `--datasource.lookback=5s` param? Or it was always there?

Always there, always in the last 30s or so, the VM should not find the data after the recording-rule, and it is automatically filled.

**Comment by hagen1778** [comment] 2021-08-04 09:26
Could you please describe what you'd expect to see instead on the graph?
