### ISSUE TITLE
absent first point when do request to `query_range` (cluster version)

### ISSUE THREAD

**Issue by eking-go** [VictoriaMetrics/VictoriaMetrics#183] opened 2019-09-11 09:25 UTC
In previous release  - `vminsert-20190611-105736-heads-cluster-0-g3437c30`  first point present as expected.
Problem present after upgrade cluster version to release `vminsert-20190910-094200-heads-cluster-0-gdc6e415`

Summary: 

Data in VM:
```
# curl -G 'http://127.0.0.1/select/0/prometheus/api/v1/export' --data-urlencode 'match={__name__!=""}'

{"metric":{"__name__":"TestHost_test","test tag":"test tag value"},"values":[0,0,1,1,2,2,3,3,4,4,5,5],"timestamps":[1568181496953,1568181496953,1568181498185,1568181498185,1568181499379,1568181499379,1568181500616,1568181500616,1568181501791,1568181501791,1568181502970,1568181502970]}
```
(double points because of cluster structure it is not a bug or problem)

When I do query:
```
# curl -G 'http://127.0.0.1/select/0/prometheus/api/v1/query_range?query=TestHost_test&start=1568181496.952638&end=1568181502.96961&step=1.203000'

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"TestHost_test","test tag":"test tag value"},"values":[[1568181498.155,"0"],[1568181499.358,"1"],[1568181500.561,"2"],[1568181501.764,"3"],[1568181502.967,"4"]]}]}}
```

I am expecting getting first point in  `1568181496.952638` because I send `start=1568181496.952638` in query. And it point was presented in reply from previous release. But now first point  - `1568181498.155` looks like `start + step`. So, we lost first point

**Comment by valyala** [comment] 2019-09-11 12:47
This is expected behavior. VictoriaMetrics returns data points from `/api/v1/query_range` according to [Prometheus data model](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness):

> When queries are run, timestamps at which to sample data are selected independently of the actual present time series data. This is mainly to support cases like aggregation (sum, avg, and so on), where multiple aggregated time series do not exactly align in time. Because of their independence, Prometheus needs to assign a value at those timestamps for each relevant time series. **It does so by simply taking the newest sample before this timestamp.**

There is no real sample before `start=1568181496.952638`, since the first sample has `timestamp=1568181496.953`, so VictoriaMetrics skips the first data point in the `/api/v1/query_range` result. Try setting `start` to the value equal or greater than the timestamp for the first real data point stored in the db - `1568181496.953` in your case.

**Comment by valyala** [comment] 2019-09-13 14:49
Closing the issue as resolved

**Closed by valyala** 2019-09-13 14:49 UTC
Labels: question
