### ISSUE TITLE
Prometheus metadata endpoint support in VM

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#837] opened 2020-10-15 14:21 UTC
**Is your feature request related to a problem? Please describe.**
We need to know what is the type of a metric, if its a counter or a gauge etc..

**Describe the solution you'd like**
We have been using the prometheus api called metadata (https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata)
This way we can easily filter by specific metric and labels and in return we can get the type of the metric

**Describe alternatives you've considered**
The metrics are unknown for us in advanced so we need a dynamic way to get info about the metrics (a caching solution which stores for each metric its type will not work here)

**Additional context**
Is there another way to get this info about each metric in VM? Are there any plans to support the metadata api?

Thanks!

**Comment by f41gh7** [comment] 2020-10-16 10:54
Hello, 
it's duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/643

**Closed by f41gh7** 2020-10-16 10:54 UTC
