### ISSUE TITLE
Could not find binary release for victoria-metrics Windows 64, only vmutils

### ISSUE THREAD

**Issue by Arnaud-Nauwynck** [VictoriaMetrics/VictoriaMetrics#3821] opened 2023-02-15 07:52 UTC
### Is your feature request related to a problem? Please describe

I would like to test on windows, but I could not find binary release for victoria-metrics Windows 64, only vmutils
Is there any reason, or did I missed it ? 

### Describe the solution you'd like

complete cross-plateform builds for windows 64

### Describe alternatives you've considered

I did not find it

**Comment by denisgolius** [comment] 2023-02-15 14:35
Hi @Arnaud-Nauwynck !
There are no builds for VictoriaMetrics Single or Cluster because Windows OS use proprietary filesystems which are note POSIX compatible - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3236#issuecomment-1310516521 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/70. But as workaround you can use it via WSL/WSL2 or run it in docker containers on Windows OS.

**Comment by denisgolius** [comment] 2023-02-17 12:32
#3781

**Comment by valyala** [comment] 2023-03-20 07:11
Binary release of VictoriaMetrics for Windows will be available in the next release if the testing will go smooth. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/70#issuecomment-1475726886 .

Closing this issue as a duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/70

**Closed by valyala** 2023-03-20 07:11 UTC
Labels: enhancement, question, windows

**Comment by valyala** [comment] 2023-04-07 02:22
FYI, VictoriaMetrics for Windows is available starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
