### ISSUE TITLE
Limit memory usage per query

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3203] opened 2022-10-06 08:00 UTC
**Is your feature request related to a problem? Please describe.**
Proper memory capacity planning for vmselects. Queries served by vmselect aren't homogenous, and some can use plenty of memory while the rest only a small fraction. While there are a plenty of settings to limit the query complexity, they're not transparent enough for user to understand.

**Describe the solution you'd like**
Would be great to have a setting `search.maxMemoryPerQuery` to limit the maximum amount of memory used for query processing on vmselect. When the limit is reached, vmselect should return an error. Such limit is quite easy to understand for a user and plan capacity accordingly. For example, if `-search.maxMemoryPerQuery=1GB` and `-search.maxConcurrentRequests=10` then for queries processing vmselect will use at max 10GB of memory (plus additional memory for caches and process itself).

**Describe alternatives you've considered**
Carefully measure limits listed here https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#resource-usage-limits

**Comment by valyala** [comment] 2022-10-07 22:21
The `-search.maxMemoryPerQuery` command-line flag has been added into VictoriaMetrics in the following commits:

* single-node VictoriaMetrics - 5138eaeea0791caa34bcfab410e0ca9cd253cd8f
* cluster version of VictoriaMetrics - 938ff7bba66481be3ed8bdca7b1b2ea1b1accdee

These commits will be included in the next release. In the meantime it is possible to build single-node VictoriaMetrics or `vmselect` from these commits according to the following docs and verifying whether the per-query memory limit works as intended:

* [how to build single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-build-from-sources)
* [how to build cluster version of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources)

**Closed** 2022-10-29 01:48 UTC
Labels: enhancement
