### ISSUE TITLE
vmselect jitter handling logic lead to wrong result of irate calculation

### ISSUE THREAD

**Issue by eddietanshuo** [VictoriaMetrics/VictoriaMetrics#2787] opened 2022-06-25 05:55 UTC
**Describe the bug**
Hello @valyala, we get new problem and need you help.

We have a counter which represent quantity of network interface input packets, the counter was remote written by a per-node agent. For some reason it's counter occasionally reset to a lower value.

![WechatIMG142](https://user-images.githubusercontent.com/103412360/175759752-197cbe4b-1bfc-4ec9-8641-5b88745b14f8.jpeg)

We use irate to calculate the result, the result has a very wide time range with zero value.
![image](https://user-images.githubusercontent.com/103412360/175759927-3cf4a3fa-abe1-432f-947d-86f6010db708.png)

**What we expect**
In this case, if counter reset, our customer will find there is no packets input for one hour in their dashboard. We expect the vm
will handler the reset logic correctly.

**Cause**
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9bb35779d206a60ebc9d42acbbd15da82663042f/app/vmselect/promql/rollup.go#L696-L699

I find there is a jitter handling logic lead to this problem. After counter reset, If the abs delta value of the the sample before reset and samples after reset is less than 1/8 of the sample value before reset , the current value will continuously adjust to the sample value before reset until the delta is non-negative. So for the time range which starts at counter reset and end at the delta become 0 will have identical values after sample values preprocessed.

example: 
in current design, counter values:
[100 90 92 95 110 120 125 50] will become [100 100 100 100 110 120 125 175]

what we expected:
[100 90 92 95 110 120 125 50] will become [100 100 102 105 120 130 135 185]

**Comment by valyala** [comment] 2022-06-30 19:43
@eddietanshuo , thanks for the detailed bugreport and root cause analysis! The issue must be fixed in the commit 84e373e5c75b112dcad36c4d4b5f7e146599dec8 . Could you try building VictoriaMetrics cluster components - `vmselect`, `vminsert` and `vmstorage` - from this commit according to [these instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verifying whether the cluster built from these components properly handles partial counter resets when calculating `irate()`?

**Comment by eddietanshuo** [comment] 2022-07-01 02:05
I applied the change, it works! 
thanks a lot, best wish with your team. 🇺🇦

**Closed** 2022-07-04 06:56 UTC
Labels: bug

**Comment by valyala** [comment] 2022-07-14 20:51
@eddietanshuo , thanks for the confirmation that the bugfix works!

The bugfix has been included in [VictoriaMetrics v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
