### ISSUE TITLE
Netdata logs too much when using Victoria Metrics backend

### ISSUE THREAD

**Issue by agrimal** [VictoriaMetrics/VictoriaMetrics#205] opened 2019-10-09 07:25 UTC
Hello,

FYI i opened an issue on Netdata side : [https://github.com/netdata/netdata/issues/7034](https://github.com/netdata/netdata/issues/7034)

Too many logs, don't know  if the problem is with Netdata or Victoria Metrics.

**Comment by valyala** [comment] 2019-10-09 11:08
VictoriaMetrics returns http response with `204 No content` status code for each incoming `remote_write`. Netdata should silently accept such response instead of logging the warning.

**Comment by valyala** [comment] 2019-10-09 11:09
Closing it for now, since it is a duplicate of https://github.com/netdata/netdata/issues/7034

**Closed by valyala** 2019-10-09 11:09 UTC
