### ISSUE TITLE
vmctl: migrate data out of Promscale (TimescaleDB)

### ISSUE THREAD

**Issue by feld** [VictoriaMetrics/VictoriaMetrics#4655] opened 2023-07-17 17:58 UTC
### Describe the bug

Promscale has been deprecated and VictoriaMetrics seems like an appropriate replacement for many use cases.

vmctl can support migrating data from many Prometheus/Influx time series implementations.

Promscale does not store data in the normal Prometheus format so loading the data from snapshots is not possible.

Promscale does not implement the /api/v1/read API endpoint

### To Reproduce

try to use vmctl with prometheus remote read

### Version

git head

### Logs

2023/07/17 17:48:55 remote read error: request failed for: error while fetching data from remote storage: unexpected response code 404 for http://REDACTED:9201/api/v1/read. Response body "404 page not found\n"

**Comment by feld** [comment] 2023-07-17 19:22
sorry issue filed in wrong repo

**Comment by dmitryk-dk** [comment] 2023-07-18 10:17
Hi @feld ! I checked the Promscale code they have the `/api/v1/read` api. Please check this [link](https://github.com/timescale/promscale/blob/6ee8545bf30d3bd1ba778cba1736eb0ac21169fe/pkg/api/read.go#L22).

Can you share how you run your Promscale and vmctl?

**Comment by hagen1778** [comment] 2023-07-25 07:26
Hey @dmitryk-dk can we try migrating data from Promscale to see if issue exists?

**Comment by dmitryk-dk** [comment] 2023-07-25 07:28
> Hey @dmitryk-dk can we try migrating data from Promscale to see if issue exists?

Hi! Yes of course. I asked just to clarify how user run the Promscale and vmctl. But I will try to reproduce it by mysels

**Comment by hagen1778** [comment] 2023-07-31 09:03
Promscale exposes read API at non-standard path: `/read` instead of `/api/v1/read`. Since vmctl expects the standard API path, this difference of Promscale requires to change the expected path. @dmitryk-dk is addressing this here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4744

**Comment by valyala** [comment] 2023-08-12 14:39
[vmctl](https://docs.victoriametrics.com/vmctl.html) gains support for `--remote-read-disable-path-append` command-line flag starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). If this flag is set, then the `--remote-read-src-addr` may contain full address for the Prometheus read API. For example, the following command should read data from Promscale, which exposes the Prometheus read API at `/read` path:

```
./vmctl --remote-read-src-addr=http://promscale-host/read --remote-read-disable-path-append
```

Closing the feature request as done.

**Closed by valyala** 2023-08-12 14:39 UTC
Labels: enhancement, vmctl, TBD
