### ISSUE TITLE
[vmauth]: a lot of TLS handshake errors

### ISSUE THREAD

**Issue by zbindenren** [VictoriaMetrics/VictoriaMetrics#1699] opened 2021-10-12 14:32 UTC
**Describe the bug**
We have vmauth in front of vminsert. Now I observed that there are a lot of handshake errors like the following:

```

Oct 12 16:22:53 insert.example.com vmauth[3599771]: 2021-10-12T14:22:53.181Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48540: EOF
Oct 12 16:22:53 insert.example.com vmauth[3599771]: 2021-10-12T14:22:53.186Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48538: EOF
Oct 12 16:22:53 insert.example.com vmauth[3599771]: 2021-10-12T14:22:53.186Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48536: EOF
Oct 12 16:22:54 insert.example.com vmauth[3599771]: 2021-10-12T14:22:54.182Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48552: EOF
Oct 12 16:22:54 insert.example.com vmauth[3599771]: 2021-10-12T14:22:54.182Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48550: EOF
Oct 12 16:22:54 insert.example.com vmauth[3599771]: 2021-10-12T14:22:54.182Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48546: EOF
Oct 12 16:22:54 insert.example.com vmauth[3599771]: 2021-10-12T14:22:54.185Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48548: EOF
Oct 12 16:22:57 insert.example.com vmauth[3599771]: 2021-10-12T14:22:57.184Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48562: EOF
Oct 12 16:22:57 insert.example.com vmauth[3599771]: 2021-10-12T14:22:57.184Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48570: EOF
Oct 12 16:22:57 insert.example.com vmauth[3599771]: 2021-10-12T14:22:57.186Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48568: EOF
Oct 12 16:22:57 insert.example.com vmauth[3599771]: 2021-10-12T14:22:57.186Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48564: EOF
Oct 12 16:22:59 insert.example.com vmauth[3599771]: 2021-10-12T14:22:59.204Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48578: EOF
Oct 12 16:22:59 insert.example.com vmauth[3599771]: 2021-10-12T14:22:59.204Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48574: EOF
Oct 12 16:22:59 insert.example.com vmauth[3599771]: 2021-10-12T14:22:59.204Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48572: EOF
Oct 12 16:22:59 insert.example.com vmauth[3599771]: 2021-10-12T14:22:59.205Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48576: EOF
Oct 12 16:23:00 insert.example.com vmauth[3599771]: 2021-10-12T14:23:00.181Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48590: EOF
Oct 12 16:23:00 insert.example.com vmauth[3599771]: 2021-10-12T14:23:00.183Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48586: EOF
Oct 12 16:23:00 insert.example.com vmauth[3599771]: 2021-10-12T14:23:00.185Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48592: EOF
Oct 12 16:23:00 insert.example.com vmauth[3599771]: 2021-10-12T14:23:00.186Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48588: EOF
Oct 12 16:23:08 insert.example.com vmauth[3599771]: 2021-10-12T14:23:08.182Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48622: EOF
Oct 12 16:23:08 insert.example.com vmauth[3599771]: 2021-10-12T14:23:08.185Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48620: EOF
Oct 12 16:23:08 insert.example.com vmauth[3599771]: 2021-10-12T14:23:08.185Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48618: EOF
Oct 12 16:23:08 insert.example.com vmauth[3599771]: 2021-10-12T14:23:08.185Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48616: EOF
Oct 12 16:23:09 insert.example.com vmauth[3599771]: 2021-10-12T14:23:09.181Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48630: EOF
Oct 12 16:23:09 insert.example.com vmauth[3599771]: 2021-10-12T14:23:09.181Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48634: EOF
Oct 12 16:23:09 insert.example.com vmauth[3599771]: 2021-10-12T14:23:09.183Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48632: EOF
Oct 12 16:23:12 insert.example.com vmauth[3599771]: 2021-10-12T14:23:12.190Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48650: EOF
Oct 12 16:23:12 insert.example.com vmauth[3599771]: 2021-10-12T14:23:12.190Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48656: EOF
Oct 12 16:23:12 insert.example.com vmauth[3599771]: 2021-10-12T14:23:12.190Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48652: EOF
Oct 12 16:23:12 insert.example.com vmauth[3599771]: 2021-10-12T14:23:12.193Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48654: EOF
Oct 12 16:23:14 insert.example.com vmauth[3599771]: 2021-10-12T14:23:14.184Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48660: EOF
Oct 12 16:23:14 insert.example.com vmauth[3599771]: 2021-10-12T14:23:14.185Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48662: EOF
Oct 12 16:23:14 insert.example.com vmauth[3599771]: 2021-10-12T14:23:14.188Z        error        net/http/server.go:3157        http: TLS handshake error from 192.168.1.2:48664: EOF
```

The logs are coming from vmagent. Even if I set:

``` 
http_idleConnTimeout=700s
```
in vmauth nothing changes.

I also tried:
```
promscrape_disableKeepAlive=true
```

but nothing changed. Everything works fine and I see no errors in vmagent logs.

It is annoying because I would like to create an alert for `vm_log_messages_total{level!="info"}`  and in the vm-cluster grafana dashboard I have a large error log rate.

**Comment by azeroc** [comment] 2021-11-10 23:39
Hello,

I have exact same problem where victoria-metrics database instance is complaining about TLS handshake error from same IPv4 but hundred different ports. It seems to be happening during vmagent scrapes against it.

Both vmagent and the victoriametrics instances are running with TLS enabled. Here is my scrape config for vmagents.
```
global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "victoria-db-prd-1"
    scheme: https
    static_configs:
      - targets:
        - "myproject-victoria-db-prd-1.corp.mycorp.com:8428"
  - job_name: "victoria-db-prd-2"
    scheme: https
    static_configs:
      - targets:
        - "myproject-victoria-db-prd-2.corp.mycorp.com:8428"
```

Here is a sample vmagent run configuration:
```
/app/victoria/victoria-vmagent-prd-1/bin/victoria-vmagent 
--promscrape.suppressScrapeErrors=false 
--httpListenAddr=myproject-victoria-vmagent-prd-1.corp.mycorp.com:8429 
--remoteWrite.tmpDataPath=/app/victoria/victoria-vmagent-prd-1/storage 
--promscrape.config=/app/victoria/victoria-vmagent-prd-1/config/scrape.yml 
--promscrape.configCheckInterval=60s 
--tls 
--tlsCertFile=/app/victoria/victoria-vmagent-prd-1/tls/myproject-victoria.crt 
--tlsKeyFile=/app/victoria/victoria-vmagent-prd-1/tls/myproject-victoria.key 
--remoteWrite.showURL  
--remoteWrite.url=https://myproject-victoria-db-prd-1.corp.mycorp.com:8428/api/v1/write  
--remoteWrite.url=https://myproject-victoria-db-prd-2.corp.mycorp.com:8428/api/v1/write
```

Here is sample victoria-metrics db instance configuration:
```
/app/victoria/victoria-db-prd-1/bin/victoria-db 
--storageDataPath=/app/victoria/victoria-db-prd-1/storage 
--httpListenAddr=myproject-victoria-db-prd-1.corp.mycorp.com:8428 
--retentionPeriod=400d 
--dedup.minScrapeInterval=10s 
--tls 
--tlsCertFile=/app/victoria/victoria-db-prd-1/tls/myproject-victoria.crt 
--tlsKeyFile=/app/victoria/victoria-db-prd-1/tls/myproject-victoria.key
```

Here are sample errors:
```
Nov 11 00:17:30 server-15 victoria-db[42708]: 2021-11-10T23:17:30.673Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35950: EOF
Nov 11 00:17:30 server-15 victoria-db[42708]: 2021-11-10T23:17:30.673Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35948: EOF
Nov 11 00:17:31 server-15 victoria-db[42708]: 2021-11-10T23:17:31.633Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36566: read tcp4 123.123.123.90:8428->123.123.123.88:36566: read: connection reset by peer
Nov 11 00:17:31 server-15 victoria-db[42708]: 2021-11-10T23:17:31.633Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36570: EOF
Nov 11 00:17:32 server-15 victoria-db[42708]: 2021-11-10T23:17:32.672Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35964: EOF
Nov 11 00:17:32 server-15 victoria-db[42708]: 2021-11-10T23:17:32.672Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35966: EOF
Nov 11 00:17:32 server-15 victoria-db[42708]: 2021-11-10T23:17:32.672Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35968: EOF
Nov 11 00:17:32 server-15 victoria-db[42708]: 2021-11-10T23:17:32.672Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35970: EOF
Nov 11 00:17:33 server-15 victoria-db[42708]: 2021-11-10T23:17:33.633Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36584: EOF
Nov 11 00:17:33 server-15 victoria-db[42708]: 2021-11-10T23:17:33.633Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36586: EOF
Nov 11 00:17:33 server-15 victoria-db[42708]: 2021-11-10T23:17:33.633Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36588: EOF
Nov 11 00:17:34 server-15 victoria-db[42708]: 2021-11-10T23:17:34.673Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35987: EOF
Nov 11 00:17:34 server-15 victoria-db[42708]: 2021-11-10T23:17:34.673Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35986: EOF
Nov 11 00:17:34 server-15 victoria-db[42708]: 2021-11-10T23:17:34.673Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35990: EOF
Nov 11 00:17:34 server-15 victoria-db[42708]: 2021-11-10T23:17:34.674Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:35992: EOF
Nov 11 00:17:35 server-15 victoria-db[42708]: 2021-11-10T23:17:35.649Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36606: EOF
Nov 11 00:17:35 server-15 victoria-db[42708]: 2021-11-10T23:17:35.652Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36604: EOF
Nov 11 00:17:35 server-15 victoria-db[42708]: 2021-11-10T23:17:35.655Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36608: EOF
Nov 11 00:17:36 server-15 victoria-db[42708]: 2021-11-10T23:17:36.674Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:36008: EOF
Nov 11 00:17:36 server-15 victoria-db[42708]: 2021-11-10T23:17:36.674Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:36004: EOF
Nov 11 00:17:36 server-15 victoria-db[42708]: 2021-11-10T23:17:36.674Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:36006: EOF
Nov 11 00:17:36 server-15 victoria-db[42708]: 2021-11-10T23:17:36.675Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:36010: EOF
Nov 11 00:17:37 server-15 victoria-db[42708]: 2021-11-10T23:17:37.649Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36624: EOF
Nov 11 00:17:37 server-15 victoria-db[42708]: 2021-11-10T23:17:37.650Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36626: EOF
Nov 11 00:17:37 server-15 victoria-db[42708]: 2021-11-10T23:17:37.650Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.88:36622: EOF
Nov 11 00:17:38 server-15 victoria-db[42708]: 2021-11-10T23:17:38.672Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:36018: EOF
Nov 11 00:17:38 server-15 victoria-db[42708]: 2021-11-10T23:17:38.673Z        error        net/http/server.go:3157        http: TLS handshake error from 123.123.123.89:36016: EOF
```

It doesn't seem to affect anything critical, just spams logs.

**Comment by azeroc** [comment] 2021-11-14 01:27
Could this issue be similar to https://github.com/cockroachdb/cockroach/issues/32102 ?

Does vmagent make empty-TCP health checks against HTTPS/TLS listening server? Those could be triggering the errors against TLS-secured victoria-metrics database.

**Comment by azeroc** [comment] 2021-11-14 17:49
It appears vmagent_remotewrite_conn_read_errors_total and vmagent_remotewrite_conn_write_errors_total are incremented whenever I see those EOF errors from the db. They are incremented at vmagent, while the errors come from the database.

The counters are described here: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/remotewrite/statconn.go

I will clone the repo and add some error messaging on vmagent's side at statconn.go to see what the actual errors are that seem to coincide with the EOF errors from the database.

For reference, you can easily reproduce EOF error with telnet as well which is why it got me thinking that this could be result of initiating TCP conn to TLS listening server and then closing it right away:
telnet <your victoria-metrics service https URL> <db port>
(quit telnet right away)
(service should report TLS handshake EOF error)

**Comment by azeroc** [comment] 2021-11-15 15:22
So I added error logging to Read/Write for statConn as well as debug trace. The errors coincide with TLS handshake errors from remoteWrite targets (such as victoria-metrics db or vmauth targeted by vmagent). The errors simply complain about use of closed network connection but timestamps seem to indicate that remoteWrite target only triggers EOF log few milliseconds after vmagent error log.

I think something weird is going on with remotewrite code portion of vmagent on how it uses TLS connections. The scrape targets by vmagent, for example, don't report any TLS issues and they have HTTPS/TLS enabled as well.

Error logs from vmagent:
```
[victoria-metrics db]
2021-11-15T15:09:43.716Z	error	net/http/server.go:3157	http: TLS handshake error from 1.2.3.88:51894: EOF

[victoria-metrics vmagent]
2021-11-15T15:09:43.715Z	error	VictoriaMetrics/app/vmagent/remotewrite/statconn.go:59	statConn [1.2.3.88:51894 -> 1.2.3.90:8428] write error: write tcp4 1.2.3.88:51894->1.2.3.90:8428: use of closed network connection,
goroutine 468179 [running]:,
runtime/debug.Stack(),
	runtime/debug/stack.go:24 +0x65,
ntime/debug.PrintStack(),
	runtime/debug/stack.go:16 +0x19,
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*statConn).Write(0xc001e2a390, {0xc005af2c40, 0x20, 0x20}),
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/statconn.go:61 +0x1ae,
crypto/tls.(*Conn).flush(0xc003480380),
	crypto/tls/conn.go:922 +0x47,
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc001241d98),
	crypto/tls/handshake_client_tls13.go:99 +0x225,
crypto/tls.(*Conn).clientHandshake(0xc003480380, {0xaa7938, 0xc006f16780}),
	crypto/tls/handshake_client.go:219 +0x585,
crypto/tls.(*Conn).handshakeContext(0xc003480380, {0xaa79a8, 0xc003c7a660}),
	crypto/tls/conn.go:1445 +0x3d1,
crypto/tls.(*Conn).HandshakeContext(...),
	crypto/tls/conn.go:1395,
net/http.(*persistConn).addTLS.func2(),
	net/http/transport.go:1534 +0x71,
created by net/http.(*persistConn).addTLS,
	net/http/transport.go:1530 +0x345,


[victoria-metrics db]
2021-11-15T15:09:33.716Z	error	net/http/server.go:3157	http: TLS handshake error from 1.2.3.88:51884: EOF

[victoria-metrics vmagent]
2021-11-15T15:09:33.714Z	error	VictoriaMetrics/app/vmagent/remotewrite/statconn.go:46	statConn [1.2.3.88:51884 -> 1.2.3.90:8428] read error: read tcp4 1.2.3.88:51884->1.2.3.90:8428: use of closed network connection,
goroutine 468093 [running]:,
runtime/debug.Stack(),
	runtime/debug/stack.go:24 +0x65,
ntime/debug.PrintStack(),
	runtime/debug/stack.go:16 +0x19,
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*statConn).Read(0xc0030802a0, {0xc009748240, 0x12716f976966f5e6, 0x100008b03036a0b}),
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/statconn.go:48 +0x1ae,
crypto/tls.(*atLeastReader).Read(0xc0030802e8, {0xc009748240, 0x0, 0x40ad0d}),
	crypto/tls/conn.go:777 +0x3d,
bytes.(*Buffer).ReadFrom(0xc000812978, {0xa9d5a0, 0xc0030802e8}),
	bytes/buffer.go:204 +0x98,
crypto/tls.(*Conn).readFromUntil(0xc000812700, {0x7f0240dd5508, 0xc0030802a0}, 0x463f9b),
	crypto/tls/conn.go:799 +0xe5,
crypto/tls.(*Conn).readRecordOrCCS(0xc000812700, 0x0),
	crypto/tls/conn.go:606 +0x112,
crypto/tls.(*Conn).readRecord(...),
	crypto/tls/conn.go:574,
crypto/tls.(*Conn).readHandshake(0xc000812700),
	crypto/tls/conn.go:1009 +0x6d,
crypto/tls.(*Conn).clientHandshake(0xc000812700, {0xaa7938, 0xc00294a740}),
	crypto/tls/handshake_client.go:179 +0x266,
crypto/tls.(*Conn).handshakeContext(0xc000812700, {0xaa79a8, 0xc0066d4420}),
	crypto/tls/conn.go:1445 +0x3d1,
crypto/tls.(*Conn).HandshakeContext(...),
	crypto/tls/conn.go:1395,
net/http.(*persistConn).addTLS.func2(),
	net/http/transport.go:1534 +0x71,
created by net/http.(*persistConn).addTLS,
	net/http/transport.go:1530 +0x345,
```

Might try changing around some of the remoteWrite HTTP client settings defined in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/remotewrite/client.go#L94 to see if it fixes anything.

**Comment by azeroc** [comment] 2021-11-15 18:39
I narrowed down the generation of EOF error to TLS Handshake timeout functionality. VMagent is using default Golang's http transport TLS dialer.

In https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/remotewrite/client.go#L94  there is a custom dialer for normal unencrypted TCP connection. There is no DialTLS option specified, so as per http.Transport documentation:
```
// DialTLSContext specifies an optional dial function for creating
// TLS connections for non-proxied HTTPS requests.
//
// If DialTLSContext is nil (and the deprecated DialTLS below is also nil),
// DialContext and TLSClientConfig are used.
//
// If DialTLSContext is set, the Dial and DialContext hooks are not used for HTTPS
// requests and the TLSClientConfig and TLSHandshakeTimeout
// are ignored. The returned net.Conn is assumed to already be
// past the TLS handshake.
DialTLSContext func(ctx context.Context, network, addr string) (net.Conn, error)
```

By that they mean to use `addTLS` function: https://golang.org/src/net/http/transport.go#L1512 called in below `dialConn` function to get TLS-secured connection. Specifically to distinguish between custom TLS dialer and default one you can see the logic in https://golang.org/src/net/http/transport.go#L1578 and there if there is no custom TLS dialer defined then it will resort to using normal Dialer + `addTLS` function. Seems weird that they go with that route instead of initializing some default tls.Conn.

So what caused those EOF errors on remoteWrite target? Since my previously published read/write errors of vmagent coincided with EOF errors from the remoteWrite targets, as well as those error stack-traces originating from `addTLS`, then the best guess is that this specific section causes them: https://golang.org/src/net/http/transport.go#L1540 (TLS handshake timeout triggers abrupt connection closure in `addTLS`).

**Potential fix? Not sure.** @valyala 
I duplicated statConn as statConnTLS and made it internally use tls.Conn. The methods are the same as normal statConn, however, you must specify SetReadDeadline and SetWriteDeadline before calling tls.Conn.Read/Write respectively, they are used by tls.Conn's internal write/read methods that first check/initiate TLS handshake before writing/reading request data.

The `statConnTLS.statDialTLS` method is then set to transport's `DialTLS` field. One issue is that there doesn't seem to be an easy way to pass TLSConfig object, so very likely you may want to supply an additional wrapper object that supplies DialTLS function and the dial function uses TLSConfig from the wrapper object to initiate tls.Conn.

I quickly tried this with the following:
```
func statDialTLS(ctx context.Context, network string, addr string) (conn net.Conn, err error) {
	network = netutil.GetTCPNetwork()
	tlsConn, tlsConnErr := tls.Dial(network, addr, nil)
	dialsTotal.Inc()
	if tlsConnErr != nil {
		dialErrors.Inc()
		logger.Errorf("statDialTLS error: %s", tlsConnErr)
		return nil, tlsConnErr
	}
	scTLS := &statConnTLS{
		Conn: tlsConn,
	}
	return scTLS, nil
}
```

Even with nil TLS config, the EOF errors finally disappeared from remoteWrite target. If you log errors from statConnTLS write/read then I have noticed that there are occasional i/o timeouts but doesn't seem to affect anything, seems to be just part of usual connection churn noise.

Anyways, I am not sure if creating a custom TLS statConn dialer is the solution just to silence seemingly harmless EOF TLS errors from vmagent remoteWrite targets. I am still puzzled why these random TLS handshake timeouts happen in the first place.

**Comment by azeroc** [comment] 2021-11-18 13:29
I fixed the errors by tweaking `--remoteWrite.queues` parameter on vmagents, lowering amount of queues used for remote writes. Each queue will make a connection to the remoteWrite target so I guess too many of them saturate the target and your TLS handshakes start timing out, which in turn creates those EOF errors on the target.

I think creating TLS version of statDial would help hide the EOF log spam triggered by vmagents and instead log i/o timeouts to the metrics. Otherwise you simply need to tweak queue count settings to make vmagents less aggressive towards their targets.

**Comment by akaczm** [comment] 2022-03-18 12:27
Reducing `--remoteWrite.queues` to 2 has certainly reduced the amount of errors, however they still sporadically happen. Triggered by vmagent, most likely remoteWrite
However I fear such small queues can be problematic once more data gets pushed into the database via the vmagent.

**Comment by tomalacis** [comment] 2022-03-18 19:13
I think the main reason these TLS handshake errors happen is because vmagent oversaturates network with them, causing portion of them to regularly timeout but they are immediately recreated afterwards. It didn't cause any data loss or noticeable performance degradation (because any faulty queue connection is immediately retried and recreated), it really just spams logs.

At least on VictoriaMetrics side statDial object should be created/updated for TLS connections and instead of logging EOF errors they should just be made into metrics. If applications outside VictoriaMetrics domain are complaining about EOF errors (because vmagent spams them with a lot of TLS connections) then you should just continue to reduce queue count. This is because there are too many active queues each trying to push data past the network interface limits (my above issues were tested with 2Gbps links). Also remember that a single CPU core can easily go past 1Gbps data processing speed depending on how much processing each individual queue item requires (in case of vmagent data ingestion I am assuming majority of time is spent converting source data format into remoteWrite target format).

If you have a weak network interface (less than few Gbps) then having many vmagent remoteWrite queues will create this oversaturation and some of them will choke/block, therefore, creating a timeout before finishing initial TLS handshake. Alternatively, you can ratelimit data ingestion towards vmagents to stop the oversaturation.

**Comment by LibiKorol** [comment] 2022-03-27 15:14
We experienced the same issue as tomalacis described above. Currently it floods victoria metrics log and prevents us configuring alerts based on vm_log_messages_total metric. We reduced --remoteWrite.queues as akaczm suggested but it still sporadically happens.
Is there an ETA for a fix?

**Comment by tenmozes** [comment] 2022-04-03 19:21
@valyala @f41gh7 could you please take a look

**Comment by valyala** [comment] 2022-04-06 09:37
@tomalacis , thanks for deep analysis of the issue! Could you try whether `vmagent` built from 7da20a4b3fad761f6582fde6672c1a4138cd5e6d fixes the issue with `TLS handshake error` log messages when connecting to `vmauth`? See [build instructions for vmagent](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by LibiKorol** [comment] 2022-05-24 04:39
@valyala, we upgraded all components (victoria metrics, vmagent and vmalert to v1.76.0 and it atill happens
 Same error appears every few seconds in victoria metrics log.

**Comment by valyala** [comment] 2023-02-10 05:00
@LibiKorol , could you try `vmauth` [v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html)? It contains improved logging, which could help debugging the issue with LTS handshake errors.

**Comment by hagen1778** [comment] 2023-08-18 07:22
Closing the issue due to lack of activity.

**Comment by valyala** [comment] 2024-02-13 00:45
@tomalaci , the proposed fix at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1699#issuecomment-969204024 uses [`tls.Dial()`](https://pkg.go.dev/crypto/tls#Dial), which never times out:

```go
func statDialTLS(ctx context.Context, network string, addr string) (conn net.Conn, err error) {
	network = netutil.GetTCPNetwork()
	tlsConn, tlsConnErr := tls.Dial(network, addr, nil)
	dialsTotal.Inc()
	if tlsConnErr != nil {
		dialErrors.Inc()
		logger.Errorf("statDialTLS error: %s", tlsConnErr)
		return nil, tlsConnErr
	}
	scTLS := &statConnTLS{
		Conn: tlsConn,
	}
	return scTLS, nil
}
```

This fixes the issue on over-saturated networks, where the tls handshake cannot be performed in the hardcoded timeout of 10 seconds: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cafdc7e21acdabd348d903295b13f19007af2169/app/vmagent/remotewrite/client.go#L125

I added `-remoteWrite.tlsHandshakeTimeout` command-line flag in the commit 3a5b23fc18fa5a8a9d885d22abe1eb7232bddeca . This flag allows configuring the tls handshake timeout if needed in order to reduce the amounts of `http: TLS handshake error` error messages at the remote storage side under high load. This commit will be included in the next release.

In general, it is better to remove the bottleneck (network bandwidth or CPU limits) instead of tuning the `-remoteWrite.tlsHandshakeTimeout`, since, if TLS handshake cannot be performed in 10 seconds, then this clearly points to some bottleneck in the network or CPU either at `vmagent` side or at the remote storage side at `-remoteWrite.url`.

**Comment by valyala** [comment] 2024-02-14 15:36
The `-remoteWrite.tlsHandshakeTimeout` command-line flag is available in [vmagent](https://docs.victoriametrics.com/vmagent.html) starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the issue as addressed.

**Closed by valyala** 2024-02-14 15:36 UTC
Labels: bug, vmauth
