### ISSUE TITLE
Query logging

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2770] opened 2022-06-22 11:28 UTC
**Describe the solution you'd like**
Would be great to have an option to log all or just specific queries for all or specific users or entities in https://docs.victoriametrics.com/vmauth.html or https://docs.victoriametrics.com/vmgateway.html components. Such logs could be then collected by any logging system like loki, rsyslog, graylog for further analysis.
The main intention to have such a feature is to get opportunity to analyze usage pattern for each configured user. This would help to optimize and improve configuration or data collection settings.

**Comment by f41gh7** [comment] 2023-07-07 11:42
@valyala PTAL

**Comment by hartfordfive** [comment] 2024-02-07 15:33
Hi all.   Have there been any developments on this issue?   Is it currently possible at all to have some kind of query logging enabled in Victoriametrics?

**Comment by hagen1778** [comment] 2024-02-08 14:30
> Hi all. Have there been any developments on this issue? Is it currently possible at all to have some kind of query logging enabled in Victoriametrics?

Not yet. The workaround is to set `-search.logSlowQueryDuration=1ms` to small value, like 1ms. Then all queries that exceed the threshold will be logged by vmselect.

**Comment by valyala** [comment] 2024-11-13 09:20
Closing this feature request as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5936 .

**Closed by valyala** 2024-11-13 09:20 UTC
Labels: enhancement, enterprise, vmauth, vmgateway
