### ISSUE TITLE
[victoriametrics] Taking into account http.pathPrefix for the webui logo URL.

### ISSUE THREAD

**Issue by crocchietta** [VictoriaMetrics/VictoriaMetrics#5306] opened 2023-11-09 15:16 UTC
### Describe the bug

I don't know if this is a bug or a configuration problem for me.
When using -http.pathPrefix, it is not taken into account when clicking on the logo.
For example, if http.pathPrefix=victoria01, the logo URL is not https://@ip/victoria01 but https://@ip/.

### To Reproduce

configure -http.pathPrefix, go to the targets page then click on the VictoriaMetrics logo.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/63265649/e9740e0d-5d5c-40f2-bde1-41bf7e13f941)

### Version

victoria-metrics-20230602-095850-tags-v1.91.2-0-gde9481208

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/63265649/3b1c6a40-5594-4c5c-8441-0e743bf2003f)

**Comment by zekker6** [comment] 2023-11-09 15:55
Hello @crocchietta, thank you for the report!
The fix have been created here - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5307 .
Before this is released, you can build [VictoriaMetrics from sources](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-build-from-sources) and verify if the issue is fixed for you.

**Comment by valyala** [comment] 2023-11-13 19:59
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1858

**Comment by valyala** [comment] 2023-11-13 20:33
The issue should be fixed in the commit 8af56ea2edd68cabaf7c369741d7523571dfb1e5 . This commit replaces absolute links to the main page and to the `favicon.ico` with relative links, so they should work now for any path prefix (e.g. they are independent of `-http.pathPrefix` command-line flag). See [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5307#issuecomment-1808906971) for more details.

The commit 8af56ea2edd68cabaf7c369741d7523571dfb1e5 will be included in the next release. In the mean time it is possible to verify whether the commit fixes the issue by building VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by crocchietta** [comment] 2023-11-14 09:15
Good morning. Thank you both for your intervention.
I don't have the ability to test the commit at the moment.
Not being a blocking problem, I can wait for the next version to come out.

**Comment by valyala** [comment] 2023-11-15 23:18
The bugfix for this issue has been included in the [release v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing it as fixed then.

@crocchietta , feel free re-opening the issue if it still persists at `v1.95.0` release.

**Closed by valyala** 2023-11-15 23:18 UTC
Labels: bug

**Comment by crocchietta** [comment] 2023-11-23 14:02
I just deployed version 1.95.1 and the problem is well resolved. Thanks.
