### ISSUE TITLE
The endpoint /api/v1/import/prometheus/metrics does not support application/vnd.google.protobuf

### ISSUE THREAD

**Issue by akhenakh** [VictoriaMetrics/VictoriaMetrics#4672] opened 2023-07-19 19:45 UTC
### Describe the bug

While using the Go `github.com/prometheus/client_golang/prometheus/push` package, it's defaulting to send  `application/vnd.google.protobuf` content type.

VictoriaMetrics is returning a 200 but the data point will never show up. 

### To Reproduce

Simple code to reproduce:

```go
package main

import (
	"fmt"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/push"
	"github.com/prometheus/common/expfmt"
)

func main() {

	completionTime := prometheus.NewGauge(prometheus.GaugeOpts{
		Name: "db_backup_last_completion_timestamp_seconds",
		Help: "The timestamp of the last successful completion of a DB backup.",
	})

	prometheus.MustRegister(completionTime)

	completionTime.SetToCurrentTime()

	p := push.New("http://localhost:8428/api/v1/import/prometheus", "go_operation_aggregator")

	p.Grouping("instance", "stat_pusher")

	//p.Format(expfmt.FmtText)

	p = p.Collector(completionTime)
	if err := p.Push(); err != nil {
		fmt.Println("Could not push completion time to Pushgateway:", err)
	}
}
```

This code will trigger this HTTP request and response:

```
PUT /api/v1/import/prometheus/metrics/job/go_operation_aggregator/instance/stat_pusher HTTP/1.1
Host: localhost:8428
User-Agent: Go-http-client/1.1
Content-Length: 126
Content-Type: application/vnd.google.protobuf; proto=io.prometheus.client.MetricFamily; encoding=delimited
Accept-Encoding: gzip

 

}

+db_backup_last_completion_timestamp_seconds.?The timestamp of the last successful completion of a DB backup...".. N.h.

..AHTTP/1.1 200 OK
Vary: Accept-Encoding
X-Server-Hostname: victoriametrics-victoria-metrics-single-server-0
Date: Wed, 19 Jul 2023 19:20:24 GMT
Content-Length: 0
```

Uncomment `p.Format(expfmt.FmtText)` and the request is done in plain text and successfully insert data point.

```
PUT /api/v1/import/prometheus/metrics/job/go_operation_aggregator/instance/stat_pusher HTTP/1.1
Host: localhost:8428
User-Agent: Go-http-client/1.1
Content-Length: 238
Content-Type: text/plain; version=0.0.4; charset=utf-8
Accept-Encoding: gzip

 
# HELP db_backup_last_completion_timestamp_seconds The timestamp of the last successful completion of a DB backup.
# TYPE db_backup_last_completion_timestamp_seconds gauge
db_backup_last_completion_timestamp_seconds 1.689795062723326e+09

HTTP/1.1 200 OK

Vary: Accept-Encoding
X-Server-Hostname: victoriametrics-victoria-metrics-single-server-0
Date: Wed, 19 Jul 2023 19:31:01 GMT

Content-Length: 0
```

### Version

    tag: v1.89.1

### Additional information

VM should at least detect the `application/vnd.google.protobuf` encoding and reject the query.

**Comment by f41gh7** [comment] 2023-07-21 08:13
Hello, protobuf formatted prometheus metrics must be send into `/api/v1/write` endpoint.

 But it seems, that prometheus.Push library uses `push-gateway` url format to encode labels. And we have to end protobuf parsers for this case.

**Comment by hagen1778** [comment] 2023-07-26 07:24
duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3745

**Closed by hagen1778** 2023-07-26 07:24 UTC
Labels: enhancement, vmagent
