### ISSUE TITLE
VMAlert: {{ $labels.instance }} not working 1.50.1

### ISSUE THREAD

**Issue by BenB196** [VictoriaMetrics/VictoriaMetrics#974] opened 2020-12-18 00:44 UTC
**Describe the bug**
I recently upgraded to 1.50.1 and it appears that {{ $labels.instance }} is no longer being populated from VMAlert.

**To Reproduce**
- Create a rule that references: {{ $labels.instance }}

```
- alert: Router Down
      expr: probe_success{type=~".*router"} == 0
      for: 5m
      labels:
        severity: warning
        instance: '{{ $labels.instance }}'
      annotations:
        value: '{{ $value }}'
        description: "Router: {{ $labels.instance }} has been down for more than 5 minutes."
```

- Load rule with 1.50.1
- Get alert that contains {{$labels.instance}} instead of the instance value

**Expected behavior**
Based off of the Prometheus [docs](https://prometheus.io/docs/prometheus/latest/configuration/template_examples/), I expect {{$labels.instance}} to populate with the instance name.

**Screenshots**
![image](https://user-images.githubusercontent.com/8277432/102560176-99d84f80-409f-11eb-8eab-90daeef9a7ba.png)

**Version**
victoria-metrics: v1.50.1
vmalert: v1.50.1

**Comment by valyala** [comment] 2020-12-18 11:04
Confirmed the issue and working on a bugfix. Temporary workaround is to downgrade `vmalert` to v1.49.0

**Comment by f41gh7** [comment] 2020-12-18 11:28
It seems, that all vmalert versions is affected. Problem at re-declaring label `instance`. try to use following rule as workaround:  
```
- alert: Router Down
      expr: probe_success{type=~".*router"} == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        value: '{{ $value }}'
        description: "Router: {{ $labels.instance }} has been down for more than 5 minutes."
```

**Comment by BenB196** [comment] 2020-12-18 14:00
I don't believe this affects all versions of vmalert, I upgraded from v1.46.0 in which vmalert was working correctly.

**Comment by f41gh7** [comment] 2020-12-18 14:27
Sorry, i've checked recent releases and found the problem. Indeed, it works at v1.46.0. It causes by https://github.com/VictoriaMetrics/VictoriaMetrics/commit/3adf8c5a6f4a8eea5f2025dd53ba975d42f8b8d1

 Need to think, how to handle it better.

**Comment by valyala** [comment] 2020-12-19 12:17
The issue must be fixed in the commit 404cbd152252a9090bd6ca69bd43be470be0c94c . It will be included in the next release.

**Comment by valyala** [comment] 2020-12-19 14:41
@BenB196 , could you verify whether the issue is fixed in vmalert [v1.50.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by BenB196** [comment] 2020-12-20 02:47
@valyala I've upgraded vmalert to v1.50.2 and it is now working correctly. Thanks for the quick fix.

**Comment by valyala** [comment] 2020-12-21 09:14
@BenB196 , thanks for the update! Then closing the issue as fixed.

**Closed by valyala** 2020-12-21 09:14 UTC
Labels: bug, vmalert
