### ISSUE TITLE
vmui: change legend format

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3100] opened 2022-09-12 19:08 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to copy&paste label-value pairs from the time series in the graph's legend. This is needed for better experience of applying filters to the query.

**Describe the solution you'd like**
Would be nice if the following format:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/2902918/189735714-c3fbe198-4f9c-4f13-b505-d20e97385a88.png">

Would be changed to `metric{label="value",..}`, so I can copy&paste pairs I want right to the Query field. 
Or any other alternative solution which would help me to copy multiple label value pairs at once.

**Comment by Loori-R** [comment] 2022-11-18 10:20
Closed as duplicate of #3289

**Closed by Loori-R** 2022-11-18 10:20 UTC
Labels: enhancement, vmui
