### ISSUE TITLE
VictoriaMetrics Single Duplicate data

### ISSUE THREAD

**Issue by devadapter** [VictoriaMetrics/VictoriaMetrics#2083] opened 2022-01-20 05:50 UTC
**describe error**
In multi-cluster prometheus monitoring data sinks into VictoriaMetrics, grafana dashboard data is duplicated. vmui queries the same data.

**Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
grafana displays the data normally.

**Configuration**
Check if any warnings or errors are logged by the VictoriaMetrics component or components that communicate with VictoriaMetrics (e.g., VictoriaMetrics, Inc.).
or components that communicate with VictoriaMetrics (e.g. Prometheus, Grafana) log any warnings or errors.

**Screenshot**

I installed VictoriaMetrics Single via helm and this is part of its configuration
![image](https://user-images.githubusercontent.com/23102962/150280175-3d797abf-1c9c-4d5c-9529-f3f21de9fa29.png)

Duplicate data for grafana queries
![image](https://user-images.githubusercontent.com/23102962/150280134-53fab252-3bee-4e6f-94bd-3eaf43333335.png)

This is the data queried by vmui
![image](https://user-images.githubusercontent.com/23102962/150280308-3645fdf0-68ab-459a-b459-ee682c7eb188.png)

This is the configuration of kube-prometheus
![image](https://user-images.githubusercontent.com/23102962/150280648-3a18f97f-0ca6-494d-9bd5-669769dcef0b.png)

* **Version**
```
$ helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
vmsingle        default         1               2022-01-19 04:29:03.695915736 +0000 UTC deployed        victoria-metrics-single-0.8.14  1.71.0     
```

**Comment by denisgolius** [comment] 2022-01-21 09:28
Hi @devadapter !
You need to enable deduplication on the VictoriaMetrics side - see https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication . It will works after you will drop different labels from prometheus replicas with `relabelConfig` flag and set identical `external_labels` for  Prometheus instances section in their configs, so they write data to the same time series:
`
-relabelConfig string
    	Optional path to a file with relabeling rules, which are applied to all the ingested metrics. The path can point either to local file or to http url. See https://docs.victoriametrics.com/#relabeling for details. The config is reloaded on SIGHUP signal
`
(see [How to use relabeling in Prometheus and VictoriaMetrics](https://valyala.medium.com/how-to-use-relabeling-in-prometheus-and-victoriametrics-8b90fc22c4b2)) and set `-dedup.minScrapeInterval` to maximum value that you used.

**Comment by skeagy** [comment] 2024-01-24 09:04
(apologies for necro-post, but this seems most relevant thread for follow-up question).

I followed advice from @denisgolius and added -dedup.minScrapeInterval="60s" to my VictoriaMetrics single instance and restarted, and see the setting is accepted in the startup logs. I expected/hoped to get deduplication of historical raw data at query time. The docs for cluster VictoriaMetrics show deduplication at data ingestion or at query time depending on where it is applied. There is some ambiguity about behavior for a single instance: does the single instance support deduplication at query time (as seems like would be the case if applied on cluster vmselect instance)?

My actions above were not sufficient to make this work as I hoped/expected in VictoriaMetrics single.

About my setup and scenario:
* single VictoriaMetrics instance with lots of CPU/mem (planning to go cluster at some point)
* 3TB data, 7 trillion datapoints in ~20M data time series and ~10M series of "info" metrics for metadata
* no duplicate scraping or data pushing... but incidents over the last year have caused a small number of accidental duplicate timepoints in the historical data
* I have Grafana queries with a joining clause like `* on (my_var) group_left(my_metadata_var) info_metric`. These work most of the time.
* Some combinations of query variables and time ranges consistently fail with Message 422: cannot evaluate and "duplicate time series on the right side" error. This seems to happen when I hit the low frequency duplicate data points
* I was hoping that there is a mechanism to handle these at query-time in a single VictoriaMetrics instance without having to sift through all the historical data to clean it, or without being forced to cluster deployment to get my dashboards working more reliably and gracefully.

Thanks for your consideration.

**Comment by zekker6** [comment] 2024-02-02 09:07
Hello @skeagy 

>  There is some ambiguity about behavior for a single instance: does the single instance support deduplication at query time (as seems like would be the case if applied on cluster vmselect instance)?

Yes, single-node installation does support dedulication at query time as well. It applies value provided in `-dedup.minScrapeInterval` both at storage and query levels.

> Some combinations of query variables and time ranges consistently fail with Message 422: cannot evaluate and "duplicate time series on the right side" error. This seems to happen when I hit the low frequency duplicate data points (much more often when doing queries examining 1 year of data).

This error suggests that the problem is different from duplicated datapoint in the same series. An actual problem is that some of timeseries are likely to be missing labels used for "group by" clause. For example, if the series:
```
my_metric{label1="l1v1", label2="l2v1", label3="l3v1"}
my_metric{label1="l1v2", label2="l2v2", label3="l3v2"}
my_metric{label1="l1v3", label2="l2v3", label3="l3v3"}
my_metric{label1="l1v4", label3="l3v4"}
my_metric{label1="l1v5", label3="l3v5"}
```

In case response will be groupped by `label2` the result will be:
```
{label2="l2v1"}
{label2="l2v2"}
{label2="l2v3"}
{}
{}
```
So that two last series selectors are now duplicated even though they belong to different series.

**Comment by skeagy** [comment] 2024-02-02 17:30
Thank you @zekker6 for clarifying how dedup works with vm single, and for the other potential issue causing duplicates. I did discover a closely related problem for why deduplication wasn't happening in my case: the labels I was interested in were all present and matched, but there were a few more labels that I didn't expect to be different and they were! I didn't notice at first because it was a few like this speed="1000000000" and speed="10000000000" off by one repeated digit.

That led me to an excellent general case solution.... When I have a "metric1 * on() group_left() metric2" query, I wrap the metric2 clause in a "max by()" function that eliminates the other labels I don't need and should not be required to define a unique instance. That, combined with the deduplication behavior of Victoriametrics when unintended duplicates do have matching labels, completely solves my problem.

Also, thanks Victoriametrics gang for creating an awesome database! There are some types of technology and products that make me enjoy my job a lot more, and this is one of them.

**Comment by valyala** [comment] 2024-02-13 22:24
@skeagy , thanks for confirming that your question has been solved!

Closing the issue as answered then.

**Closed by valyala** 2024-02-13 22:24 UTC
Labels: need more info
