### ISSUE TITLE
query range result is missing

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#1496] opened 2021-07-27 05:15 UTC
**Describe the bug**
victoriametrics version: 1.51.0-cluster
hi, I store data more than 12 months in Victoriametrics cluster.

query1:  I query data last 6 months
api/v1/query_range?query=count(sum_over_time(sys.cpu.cores_num_value%7Borgid%3D%2737%27%7D))&start=1611705600&end=1627387200&step=43200
![image](https://user-images.githubusercontent.com/6347394/127099254-5f5d3290-a4b3-4961-96b6-66d4a10f4e27.png)
you can see the data early is missing.

query2: the same query data at early date, for example 2/15, the data is appear and exists.

![image](https://user-images.githubusercontent.com/6347394/127099333-eaab11b2-a280-44bb-b682-cbe04d109e62.png)

the first query hit huge timeseries.

@valyala ,  is it a bug?

**Comment by f41gh7** [comment] 2021-07-30 00:37
Its seems to be a bug, @valyala investigating it.

**Comment by davidsome** [comment] 2021-08-09 00:42
how does it go ？，thanks。  @valyala

**Comment by valyala** [comment] 2021-08-15 12:14
@davidsome , could you try building cluster components of VictoriaMetrics from the latest commit at `cluster` branch and verify whether the issue is fixed there?

The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1486 .
The related commit - c473d8ffe114051ba87e3a69cb047252af56a089

**Comment by valyala** [comment] 2021-08-15 12:17
@davidsome , did you ingest samples with timestamps from the past (aka backfilling)? Probably there is another issue with the inverted index related to ingesting historical data.

**Comment by sw0x2A** [comment] 2021-09-16 08:15
We are seeing a similar issue. Data is not displayed until you change the query range. Below is an example in VM UI (but also reproducible in Grafana). Just zooming in reveals more data that was zero before.

![image](https://user-images.githubusercontent.com/309352/133574694-ef9ab7ef-dc0b-40a0-bb18-c09802bd6d4f.png)
![image](https://user-images.githubusercontent.com/309352/133574775-d98cfc35-1206-48f4-af1f-e3e8ead10da3.png)
![image](https://user-images.githubusercontent.com/309352/133574873-ec49d09e-a02e-442a-86e5-e3e555ef0360.png)
![image](https://user-images.githubusercontent.com/309352/133574923-f00b8eed-d950-4c3c-a346-f89596181f72.png)

We are on 1.65.0 cluster. Usually update from version to version directly after it's been released. I tried the recommendations from #1486 (triggered resetRollupResultCache and removed metadata/minTimestampForCompositeIndex) but didn't help. We are not backfilling into cluster.

**Comment by sw0x2A** [comment] 2021-09-30 09:55
@valyala I build cluster components of VictoriaMetrics from the latest commit at cluster branch today (it had https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c473d8ffe114051ba87e3a69cb047252af56a089) but this didn't fix the issue.

**Comment by sw0x2A** [comment] 2022-08-01 16:18
The data in question has expired and I did not see another case like this again. I think it is safe to assume that this is fixed in a recent version. You can close this bug.

**Closed** 2022-08-01 17:08 UTC
Labels: bug
