### ISSUE TITLE
query_range seems to have a problem about rounding, wrong data fills the whole range

### ISSUE THREAD

**Issue by grinapo** [VictoriaMetrics/VictoriaMetrics#1055] opened 2021-02-05 15:50 UTC
**Describe the bug**

I have a time series containing alert state, it is either "1" or "undef". Alerts are rare, maybe one in a week and it takes about one minute. I request the data for a day and I get the data, 5-6 rows with "1", undef the others. (step=15 in grafana)
I start to zoom out. Step goes up and data gets aggregated by Vic. About step=110 (almost 2 days) I have only 2 rows "1". 
When I reach step=120 however it all falls apart: I get 1500 rows of "1" for almost the whole time range. I guess that was the point when there was less-than-one data for the result.
The query is a simple measument*5 (to make it higher as a bar chart).

```
$ curl -s "http://10.7.8.1:8428/api/v1/query_range?query=D_54*5&start=1610281440&end=1610407200&step=119" | jq '.data.result[].values | length'
3

$ curl -s "http://10.7.8.1:8428/api/v1/query_range?query=D_54*5&start=1610281440&end=1610407200&step=120" | jq '.data.result[].values | length'
1049
```

When the range has more alerts it may happen that it "gets filled" between two alerts.

**Version**
```
# victoria-metrics --version

```
That's my output. In reality it's the debian package `1.52.0+ds-1`.

But the problem is visible in `victoria-metrics-20210203-211435-tags-v1.53.1-0-g19986da16` too.

**Used command-line flags**
```
flag{name="bigMergeConcurrency", value="0"} 1
flag{name="csvTrimTimestamp", value="1ms"} 1
flag{name="dedup.minScrapeInterval", value="0s"} 1
flag{name="deleteAuthKey", value="secret"} 1
flag{name="denyQueriesOutsideRetention", value="false"} 1
flag{name="dryRun", value="false"} 1
flag{name="enableTCP6", value="false"} 1
flag{name="envflag.enable", value="false"} 1
flag{name="envflag.prefix", value=""} 1
flag{name="finalMergeDelay", value="0s"} 1
flag{name="forceFlushAuthKey", value="secret"} 1
flag{name="forceMergeAuthKey", value="secret"} 1
flag{name="fs.disableMmap", value="false"} 1
flag{name="graphiteListenAddr", value=":2003"} 1
flag{name="graphiteTrimTimestamp", value="1s"} 1
flag{name="http.connTimeout", value="2m0s"} 1
flag{name="http.disableResponseCompression", value="false"} 1
flag{name="http.idleConnTimeout", value="1m0s"} 1
flag{name="http.maxGracefulShutdownDuration", value="7s"} 1
flag{name="http.pathPrefix", value=""} 1
flag{name="http.shutdownDelay", value="0s"} 1
flag{name="httpAuth.password", value="secret"} 1
flag{name="httpAuth.username", value=""} 1
flag{name="httpListenAddr", value=":8428"} 1
flag{name="import.maxLineLen", value="104857600"} 1
flag{name="influx.maxLineSize", value="262144"} 1
flag{name="influxListenAddr", value=""} 1
flag{name="influxMeasurementFieldSeparator", value="_"} 1
flag{name="influxSkipMeasurement", value="false"} 1
flag{name="influxSkipSingleField", value="false"} 1
flag{name="influxTrimTimestamp", value="1ms"} 1
flag{name="insert.maxQueueDuration", value="1m0s"} 1
flag{name="loggerDisableTimestamps", value="false"} 1
flag{name="loggerErrorsPerSecondLimit", value="0"} 1
flag{name="loggerFormat", value="default"} 1
flag{name="loggerLevel", value="INFO"} 1
flag{name="loggerOutput", value="stdout"} 1
flag{name="loggerWarnsPerSecondLimit", value="0"} 1
flag{name="maxConcurrentInserts", value="72"} 1
flag{name="maxInsertRequestSize", value="33554432"} 1
flag{name="maxLabelsPerTimeseries", value="30"} 1
flag{name="memory.allowedBytes", value="0"} 1
flag{name="memory.allowedPercent", value="60"} 1
flag{name="metricsAuthKey", value="secret"} 1
flag{name="opentsdbHTTPListenAddr", value=""} 1
flag{name="opentsdbListenAddr", value=""} 1
flag{name="opentsdbTrimTimestamp", value="1s"} 1
flag{name="opentsdbhttp.maxInsertRequestSize", value="33554432"} 1
flag{name="opentsdbhttpTrimTimestamp", value="1ms"} 1
flag{name="pprofAuthKey", value="secret"} 1
flag{name="precisionBits", value="64"} 1
flag{name="promscrape.config", value=""} 1
flag{name="promscrape.config.dryRun", value="false"} 1
flag{name="promscrape.config.strictParse", value="false"} 1
flag{name="promscrape.configCheckInterval", value="0s"} 1
flag{name="promscrape.consulSDCheckInterval", value="30s"} 1
flag{name="promscrape.disableCompression", value="false"} 1
flag{name="promscrape.disableKeepAlive", value="false"} 1
flag{name="promscrape.discovery.concurrency", value="100"} 1
flag{name="promscrape.discovery.concurrentWaitTime", value="1m0s"} 1
flag{name="promscrape.dnsSDCheckInterval", value="30s"} 1
flag{name="promscrape.dockerswarmSDCheckInterval", value="30s"} 1
flag{name="promscrape.dropOriginalLabels", value="false"} 1
flag{name="promscrape.ec2SDCheckInterval", value="1m0s"} 1
flag{name="promscrape.eurekaSDCheckInterval", value="30s"} 1
flag{name="promscrape.fileSDCheckInterval", value="30s"} 1
flag{name="promscrape.gceSDCheckInterval", value="1m0s"} 1
flag{name="promscrape.kubernetesSDCheckInterval", value="30s"} 1
flag{name="promscrape.maxDroppedTargets", value="1000"} 1
flag{name="promscrape.maxScrapeSize", value="16777216"} 1
flag{name="promscrape.openstackSDCheckInterval", value="30s"} 1
flag{name="promscrape.streamParse", value="false"} 1
flag{name="promscrape.suppressDuplicateScrapeTargetErrors", value="false"} 1
flag{name="promscrape.suppressScrapeErrors", value="false"} 1
flag{name="relabelConfig", value=""} 1
flag{name="retentionPeriod", value="1200"} 1
flag{name="search.cacheTimestampOffset", value="5m0s"} 1
flag{name="search.disableCache", value="false"} 1
flag{name="search.latencyOffset", value="30s"} 1
flag{name="search.logSlowQueryDuration", value="5s"} 1
flag{name="search.maxConcurrentRequests", value="16"} 1
flag{name="search.maxExportDuration", value="720h0m0s"} 1
flag{name="search.maxLookback", value="0s"} 1
flag{name="search.maxPointsPerTimeseries", value="30000"} 1
flag{name="search.maxQueryDuration", value="30s"} 1
flag{name="search.maxQueryLen", value="16384"} 1
flag{name="search.maxQueueDuration", value="10s"} 1
flag{name="search.maxStalenessInterval", value="0s"} 1
flag{name="search.maxTagKeys", value="secret"} 1
flag{name="search.maxTagValueSuffixesPerSearch", value="100000"} 1
flag{name="search.maxTagValues", value="100000"} 1
flag{name="search.maxUniqueTimeseries", value="300000"} 1
flag{name="search.minStalenessInterval", value="0s"} 1
flag{name="search.queryStats.lastQueriesCount", value="20000"} 1
flag{name="search.queryStats.minQueryDuration", value="0s"} 1
flag{name="search.resetCacheAuthKey", value="secret"} 1
flag{name="search.treatDotsAsIsInRegexps", value="false"} 1
flag{name="selfScrapeInstance", value="self"} 1
flag{name="selfScrapeInterval", value="10s"} 1
flag{name="selfScrapeJob", value="victoria-metrics"} 1
flag{name="smallMergeConcurrency", value="0"} 1
flag{name="snapshotAuthKey", value="secret"} 1
flag{name="storageDataPath", value="/var/lib/victoria-metrics"} 1
flag{name="tls", value="false"} 1
flag{name="tlsCertFile", value=""} 1
flag{name="tlsKeyFile", value="secret"} 1
flag{name="version", value="false"} 1```
```

**Additional comments**
It is possibly not strictly related to #996 but shows some resemblance.

**Comment by valyala** [comment] 2021-02-06 15:10
It looks like the issue is related to automatic detection of the interval between datapoints. The /api/v1/qury_range handler expects to work with time series with a constant interval between datapoints. Such an interval is called scrape_interval in Prometheus ecosystem. The time series in your case contains datapoints with highly irregular interval between them if "undef" state isn't reported to VictoriaMetrics. So it improperly detects the scrape interval, which is then used for filling gaps in a time series during query execution if these gaps don't exceed 2x scrape interval. There are the following workarounds:
- To report "undef" state as 0 value to VictoriaMetrics at regular intervals. This shouldn't increase storage requirements too much, since VictoriaMaterics provides good compression for such data
- To specify -search.maxStalenessInterval command-line flag to small value in order to limit the maximum detected interval between datapoints with irregular interval.
- To query raw datapoints via /api/v1/export. See https://victoriametrics.github.io/#how-to-export-data-in-json-line-format

**Comment by grinapo** [comment] 2021-02-07 10:50
Yes, `maxStalenessInterval` "fixed" it, setting it to "60s" prevents the effect from happening. Thank you!

Is there a use case where the scrape interval could be over an hour or shall it be rather the exception and not vice versa?

This could be documented at `query_interval`, probably "alert" type measurements will have this problem.

**Comment by hagen1778** [comment] 2022-05-25 11:42
@valyala is this issue still relevant?

**Comment by valyala** [comment] 2024-02-08 15:35
VictoriaMetrics gained support for `-search.setLookbackToStep` command-line starting from [v1.79.0](https://docs.victoriametrics.com/CHANGELOG.html). This flag instructs VictoriaMetrics limiting the maximum detected staleness interval to the `step` query arg passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyconcepts/#range-query). This should help fixing the original issue described above.

See also https://docs.victoriametrics.com/guides/migrate-from-influx/ if you migrate from InfluxDB to VictoriaMetrics.

Closing the issue as resolved then.

**Closed by valyala** 2024-02-08 15:35 UTC
Labels: question
