### ISSUE TITLE
Can vmui automatically complete the labels in metrics like prometheus?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4054] opened 2023-04-03 13:00 UTC
### Is your question request related to a specific component?

vmui

### Describe the question in detail

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/52991866/229516739-99a2a52a-834b-440a-93c9-2628598272ae.png">

I use vmui to query metrics. The autocomplete here can automatically complete the name of the metrics, but it cannot automatically complete the label and the optional value of the label.

Is it because vmui doesn't have this function, or I haven't found the correct way to use it？

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment] 2023-04-03 14:03
@luzejia this feature is in our backlog.

Duplicate of #3006

**Closed by Amper** 2023-04-03 14:03 UTC
Labels: question

**Comment by luzejia** [comment] 2023-04-06 07:44
> @luzejia this feature is in our backlog.
> 
> Duplicate of #3006

Ok, I am very much looking forward to the day when it goes online
