### ISSUE TITLE
VmAgent Scrape kubernetes error because server close connection

### ISSUE THREAD

**Issue by weenxin** [VictoriaMetrics/VictoriaMetrics#580] opened 2020-06-22 13:31 UTC
**Describe the bug**
Use `vmagent` scrape `kubernetes` cluster.

got error 

```
2020-06-22T13:19:40.000Z	error	
VictoriaMetrics/lib/promscrape/scrapework.go:175
error when scraping "https://kcs.zl1.zw.internal:6443/api/v1/nodes/public-zl-kcs-node2665.idczw.hb1.kwaidc.com/proxy/metrics/cadvisor" from 
job "kcs-zl1-zw-cadvisor" with labels {KCS_BUFFER_POOLS="HOSTENVTYPE", RS="HOSTMODELTYPE", beta_kubernetes_io_arch="amd64", beta_kubernetes_io_os="linux", cluster="kcs-zl1-zw", component="cadvisor", instance="public-zl-kcs-node2665.idczw.hb1.kwaidc.com", job="kcs-zl1-zw-cadvisor", kubernetes_io_arch="amd64", kubernetes_io_hostname="public-zl-kcs-node2665.idczw.hb1.kwaidc.com", kubernetes_io_os="linux", pg_cluster_zl="USER_LABEL_VALUE", replica="B1"}: 
error when scraping "https://kcs.zl1.zw.internal:6443/api/v1/nodes/public-zl-kcs-node2665.idczw.hb1.kwaidc.com/proxy/metrics/cadvisor": the server closed connection before returning the first response byte. 
Make sure the server returns 'Connection: close' response header before closing the connection
```

**To Reproduce**
Like Above

**Expected behavior**
Success scrape targets.

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
vmagent-20200605-191103-tags-v1.37.0-0-g69a647b0d
```

**Used command-line flags**
```
/media/disk1/victoria/bin/vmagent-prod
 -httpListenAddr=:8429 
-memory.allowedPercent=10 
-maxInsertRequestSize=1024000000
 -promscrape.config=/media/disk1/victoria/agent/kcs/prometheus.yaml 
-promscrape.maxScrapeSize=10240000000 
-promscrape.configCheckInterval=1m -remoteWrite.tmpDataPath=/media/disk1/victoria/agent/kcs/data 
-remoteWrite.queues=50 
-remoteWrite.maxBlockSize=1024000000 
-promscrape.maxScrapeSize=1024000000 
-promscrape.disableCompression=true
 -remoteWrite.flushInterval=10s 
-remoteWrite.url=http://host4:8480/insert/1128/prometheus/api/v1/write 
-remoteWrite.url=http://host3:8480/insert/1128/prometheus/api/v1/write 
-remoteWrite.url=http://host2:8480/insert/1128/prometheus/api/v1/write 
-remoteWrite.url=http://host1:8480/insert/1128/prometheus/api/v1/write
```

**Comment by valyala** [comment] 2020-06-23 09:45
@weenxin , how frequently does this error appear in your setup? This error may appear when the scrape target becomes temporarily unavailable.

The commit 4c7f216dfe314be1f58fba77bc787b4750138bd5 should reduce the probabilty of this error by retrying multiple times if the scrape target closes keep-alive connections.

**Comment by weenxin** [comment] 2020-06-24 07:02
hi @valyala We have a `kubernetes` cluster  which contains about 10,000 nodes. In my situation it happens very frequently. Maybe the `kubernetes` apiserver close  connection every time ,  I did not scrape the target successfully in one time.

**Comment by weenxin** [comment] 2020-06-24 07:03
Another err message: 
```error when scraping "http://10.74.64.7:2379/metrics" from job "etcd_kcs_tx_mub1" with labels {instance="10.74.64.7:2379", job="etcd_kcs_tx_mub1"}: error when scraping "http://10.74.64.7:2379/metrics": error when reading response headers: cannot find whitespace in the first line of response "\x15\x03\x01\x00\x02\x02\n". Buffer size=7, contents: "\x15\x03\x01\x00\x02\x02\n"
```
When scrape our `etcd` cluster.

**Comment by weenxin** [comment] 2020-06-24 07:04
@valyala  Thanks for replying.

**Comment by valyala** [comment] 2020-06-24 09:58
> We have a kubernetes cluster which contains about 10,000 nodes. In my situation it happens very frequently. Maybe the kubernetes apiserver close connection every time , I did not scrape the target successfully in one time.

Could you try building `vmagent` from the latest commit in `master` branch (it includes the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/4c7f216dfe314be1f58fba77bc787b4750138bd5 mentioned above) and verify whether this fixes the error on closed connection? See [build instructions for vmagent](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources).

The last error message from `etcd_kcs_tx_mub1` job suggests that `vmagent` is trying to scrape non-http port. I.e. `10.74.64.7:2379` has no http server. It looks like this address contains other service than `etcd`. This usually means incorrectly configured service discovery.

BTW, the number of nodes in your k8s cluster looks impressive! Would you mind providing brief description with numbers from your setup, so we could post them at [Case studies](https://victoriametrics.github.io/CaseStudies.html) page?

**Comment by valyala** [comment] 2020-06-25 22:15
@weenxin , could you try `vmagent` from [v1.37.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)? It includes the commit mentioned above.

**Comment by weenxin** [comment] 2020-06-29 05:18
hi @valyala , We are testing `VictoriaMetrics` as our monitoring system, 
We have some difficulty when applying kubernetes ecosystem,  as you know,  we have a lot of targets need to be scraped.

We deployed four `prometheus` instance to scrape all targets (Shardding A, B C, D). All prometheus has `512G` Memory, but it happened OOM some times.

So we are trying to deploy `vmAgent` to scrape metrics, And send all metrics to `VictoriaMetrics` cluster. 

But we meed some error when we use `vmAgent`

#592 

And I have pushed A PR for it https://github.com/VictoriaMetrics/VictoriaMetrics/pull/593

I will do more test.

Thanks. I will push more information When we apply `vm` ecosystem.

**Comment by weenxin** [comment] 2020-06-29 05:27
And also  I have 

`
req.SetConnectionClose() // use http short connection
`

When scrape kubernetes, Maybe kubernetes apiserver does not accept  long term connection.

Thanks for replying.

**Comment by valyala** [comment] 2020-06-30 23:23
> And also I have Add this code to `lib/promscrape/client.go: ReadData`
> `req.SetConnectionClose() // use http short connection`
> When scrape kubernetes, Maybe kubernetes apiserver does not accept long term connection.

The commit 8da3f773ae76dee897c8f66973f6207a4c1c03c7 adds `-promscrape.disableKeepAlive` command-line flag for disabling HTTP keep-alive connections when scraping targets.

@weenxin , could you verify whether this solves the quoted issue?

**Comment by Allineer** [comment] 2020-07-02 06:47
I dream of being able to specify this flag for a specific job. Not for all exporters it makes sense to disable activity support.

**Comment by valyala** [comment] 2020-07-02 10:47
> I dream of being able to specify this flag for a specific job. Not for all exporters it makes sense to disable keep-alive connections support.

This will be done in the future versions :)

As for now, the `-promscrape.disableKeepAlive` command-line flag is available starting from [v1.37.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment] 2020-07-02 11:22
@Allineer , the commit 4dd3de9286768c83fada20b165acc16c719ccf2c adds ability to set `disable_keepalive: true` and `disable_compression: true` options inside `scrape_config` section on a per-job basis. Could you build vmagent from this commit according to [these docs](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources) and verify whether this works for your case?

**Comment by Allineer** [comment] 2020-07-02 11:30
@valyala, Yahooo!!!

**Comment by valyala** [comment] 2020-07-08 18:49
VictoriaMetrics supports `disable_keepalive` and `disable_compression` options under `scrape_configs` starting from [v1.38.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.

@weenxin , feel free re-opening it or creating new issue if you think the issue isn't resolved for your case.

**Closed by valyala** 2020-07-08 18:49 UTC
Labels: bug
