### ISSUE TITLE
VM not listening ipv6

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#245] opened 2019-11-29 13:17 UTC
**Describe the bug**
VM listen ipv4-only:
```tcp        0      0 0.0.0.0:8480            0.0.0.0:*               LISTEN      15206/vminsert```
So it is not working in ipv6-only infractructure.

**To Reproduce**
You can check it by command:
```netstat -nlp | grep 8480```

**Expected behavior**
Something like that:
```tcp6       0      0 :::8480                 :::*                    LISTEN      15206/vminsert```

**Version**
```# vmstorage --version
vmstorage-20191128-202352-tags-v1.30.1-cluster-0-g90f2530f

**Comment by valyala** [comment] 2019-11-29 15:54
Closing as duplicate of #244 .

**Closed by valyala** 2019-11-29 15:54 UTC
Labels: duplicate
